### ISSUE TITLE
Kolik CO2 emitují Sopky ve srovnání s lidmi nebo pořáry na sibiři?

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#104]
By stálo za zpracování do infografiky - viz: 
https://www.forbes.com/sites/startswithabang/2017/06/06/how-much-co2-does-a-single-volcano-emit/

Odborný Článek: American Geophysical Union: [Volcanic vs Anthropogenic Carbon Dioxide](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2011EO240001)

Data o požárech: 
https://graphics.reuters.com/WEATHER-WILDFIRES-ARCTIC/0100B26K13Y/index.html

Ondráš by měl data zkontrolovat z Global Carbon Cycle...

**Comment by ondraspribyla** [comment]
https://deepcarbon.net/scientists-quantify-global-volcanic-co2-venting-estimate-total-carbon-earth

**Comment by ondraspribyla** [comment]
Doplněn zdroj: https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2011EO240001

**Comment by mukrop** [comment]
Přesunuto do wiki.
