### ISSUE TITLE
Global Carbon Budget

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#110]
Co je třeba udělat: Přeložit resp. vytvořit ekvivalentní infografiku v češtině, ověřit data oproti dalším zdrojům (různé odhady Carbon budget, různé odhady množství fosilních paliv), doplnit komentáře.

Původní infografika: https://informationisbeautiful.net/visualizations/how-many-gigatons-of-co2/

Další dohledané zdroje: 
https://www.carbonbrief.org/analysis-how-much-carbon-budget-is-left-to-limit-global-warming-to-1-5c

**Comment by ondraspribyla** [comment]
![RETINA_IIB_gigatons_of_co2_Feb16](https://user-images.githubusercontent.com/17317136/63230425-c3177000-c20c-11e9-9a6c-9de5171a088b.png)

**Comment by mukrop** [comment]
Pokryto v #337.
