### ISSUE TITLE
Téma: proč se nic významného neděje, když máme fakt velký problém (pravda?), JAK mluvit o GCC?

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#126]
S přítelkyní jsme pojmenovali (ona) zásadní důležitou otázku (velmi volně/nepřesně parafrázuju):

> Proč se nic významného neděje, pokud je pravda to, že máme fakt velký problém, a pokud je na tom globální věděcký koncensus? Proč nestávkují vědci? Proč nejsou v televizi? Není to tak trochu nafouknuté teď ta hysterie? Přece pokud to říkají skoro všichni vědci, tak už by se něco významného dělo, ne?!!

**Comment by ondraspribyla** [comment]
Nevidím způsob, jak tohle issue "vyřešit". Pokud jsem schopni skrz interni diskusi nebo produkt na otázku odpovědět, udělej RE-OPEN a zkus naformulovat next steps.. (čistím starý issues, tohle visí dlouho a nevím co s tím, proto zavírám a nechávám na tobě, jestli ho nějak přeformuluješ).

**Comment by crysman** [comment]
Ahoj, no, zapojil bych ostatní. Přijde mi toto jako **critical issue**. Jakože bavit se s lidma o detailech v grafu je sice hezké, ale nemá to takový potenciál změnit politiku a aplikované kroky. Protože to jsou lidi, co už jsou nějak v tématu - buď jako supporters či jako odpůrci a kverulanti - to je fuk, ale jsou IN. Toto vlákno je o lidech, co nejsou nikde (a je jich podle mě většina) - protože to prostě pro ně není téma, a protože přece "_>>vědci říkali<<... nojo, to už tady bylo... nesmíš věřit všemu, co >>říkali vědci<<_"

Jak jsme na tom my s vědou a důvěrou ve vědu? Nebo je to víra? Jak odpovídat na tyto dotazy? A jaká je vůbec odpověď na tu položenou otázku?

Next steps:

1. zapojit sem víc lidí k názoru, diskusi...

1. napadá mě infografika typu
 - https://en.wikipedia.org/wiki/Climate_change_denial#/media/File:Cook_et_al._(2016)_Studies_consensus-en.svg
  - https://en.wikipedia.org/wiki/List_of_scientists_who_disagree_with_the_scientific_consensus_on_global_warming#/media/File:Climate_science_opinion_graph_3Path.svg
  - https://skepticalscience.com/images/poll_scientists.gif

atp

**Comment by ondraspribyla** [comment]
:-) Líbí se mi praktický produkt typu infograifka / článek shrnující
studie... intuitivně mi "vědecký konsenzus" přijde jako velmi slabý
argument, ale můžu se mýlit a stojí a to zjistit proč mi přijde slabý.
(a myslím že tuším... ale je to na delší zkoumání)

Zároveň mi tahle otázka dává smysl -> jako volání po jasnější strategii.
Což je věc, kterou můžeme/můžu představit ve středu.

Díky.
O.

**Comment by ondraspribyla** [comment]
Možná užitečný vstup? https://www.youtube.com/watch?v=YvsUHL9IQRs&fbclid=IwAR1JFjj1zaBS7eA22pDijpB4CoCA45SP6Pqfq3WnMk0-uo-m3LOHpBMfhTM

**Comment by crysman** [comment]
Díky za _I’ve learnt the most about climate change from those who deny it | George Marshall | TEDxEastEnd_ talk.

Odpovídá na mou otázku, kolik zhruba lidí ignoruje toto téma (psal jsem "většina"), pan Marshall říká, že 2/3 lidí se nikdy nebavili (neměli konverzace) o této existenciální krizi (!)(zdroj tvrzení jsem, nicméně, neověřoval). Aktivisti mluví, ano, víme, a ignorujeme je. Co tu máme dál - vědce...

Někteří vědci mluví, dokonce dobře, a dokonce i aktivisticky, a dokonce i na známých platformách: [TEDxNASA - Bruce Wielicki - Climate Change: Fact And Fiction](https://www.youtube.com/watch?v=_YNfA7mDri4)

A mluví o tom i filmoví producenti a politici ([The reality of climate change | David Puttnam | TEDxDublin](https://www.youtube.com/watch?v=SBjtO-0tbKU)) - ale, bohužel, zase jen na TEDu - čili zase jen pro lidi, co chtějí poslouchat a vzdělávat se...

Ale zřejmě nemluví v televizi (?) ani v denním tisku na prvních stránkách...

Rozhodně ale mluví na politických setkáních a v parlamentech, a my (lidstvo) se tu dost možná potýkáme opět s něčím takovýmto:
![image](https://user-images.githubusercontent.com/5269350/67273078-0963a680-f4be-11e9-98c2-cd632fbe5ada.png)
zdroj: video TEDx výše by D.Puttnam

"The impact of deniability" říká - a to je, myslím, důležitý point tady v tom všem. Ne uplně pro všechny z core týmu (což je dobře, že máme každý jiný background a pnutí), ale já to vnímám jako úzké místo tady v celé té klimatické krizi.

To celé mě vede k bodu 3:
Potřebuju se nutně dovzdělat v tom JAK mluvit s lidma o klimatické krizi, protože to je, zdá se, hlavní problém v této fázi. Zvlášť v moment, kdy dostanu (dostal jsem) zpětnou vazbu, že se se mnou na to téma nedá moc bavit, že jsem moc hluboko a vyvolávám pocit opozice a obrany :/

Mějme infografiky. Dělejme další infografiky a studie a texty. Ale podle mě potřebujeme interně se školit o tom, JAK o tom mluvit. Jak konkrétně... Co ne/pomáhá atp.

Pokud to nepatří sem, omlouvám se, nechce s emi přemýšlet, kam to vlastně patří... Díky všem, co to dočetli až sem.

**Comment by mukrop** [comment]
Přesunuto na wiki.
