### ISSUE TITLE
Doplnit vysvětleni CO2eq do emise-eu a emise-eu-srovnani (?)

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#132]
Zpětná vazba na infografiky emise-eu a emise-eu-srovani je, že v nich chybi vysvětleni CO2 eq. Chtělo by ho doplnit...

**Comment by mukrop** [comment]
Uz doplnene, zatvaram.

**Comment by kikinna** [comment]
Jste si jistí, že to je opravené?
Jakože má být v grafice to stejně, co je u rozdělení emisí ČR podle sektorů?

**Comment by ondraspribyla** [comment]
Doplněné v infografikách to není. Koukal jsem teď na to a přemýšlím, jestli je tam na to místo. 
Chce to jiný a kratší text něž v emise ČR.
Pokud je by se tam vlezlo, navrhoval bych: *Jednotka CO2 eq označuje emise CO2 + emise methanu, N20 a dalších skleníkových plynů přepočtené na ekvivalentní množství CO2*

Co si o tom myslíš @kikinna ?

**Comment by kikinna** [comment]
Za mě ta větička je okej. Podívám se na to, jak moc jednoduše se nám tam
vleze, hihi. :)

**Comment by kikinna** [comment]
Posílám upravené infografiky s doplněním vysvětlení CO2eq.
Tím by to snad měly být všechny, kterých se to týká.

**Comment by mukrop** [comment]
Bude zahrnute do aktualizacie spolu so zjednotenim na novy pomer stran.
