### ISSUE TITLE
Opravy infografiky "trend-teplot-cr"

### ISSUE THREAD

**Issue by Keramadohal** [faktaoklimatu/web#148]
-  [x] Změnit titulek infografiky na "Trendy nárůstu teploty v ČR v jednotlivých měsících"
-  [x] Doplnit hvězdičky k názvům statisticky významných měsíců (všechny kromě: únor, březen, září, říjen)
- [x] Doplnit popisek: "* ... trend je statisticky významný se spolehlivostí 95 %"

- [x] Přepsat popisky "... od 1961" na "mezi roky 1961–2018"

**Comment by mukrop** [comment]
* S druhym, tretim a stvrtym bodom suhlasim, do infografiky by som to doplnil presne tak, ako Marek navrhuje. (@kikinna ?)
* Zaroven by som navrhol dopisat to aj do sprievodneho textu (aj s kratkou zmienkou, ako sa to testovalo – ANOVA, t-test?) (@Keramadohal ?)

**Comment by Keramadohal** [comment]
@mukrop To mi přijde už jako fakt hodně velký detail pro max. pár statistických fajnšmejkrů ... Viz debata na fóru, jestli používat t-test nebo jinou testovou statistiku. Ale jako jestli bude shoda, že to tam máme mít, tak to tam klidně dopíšu :-)

**Comment by mukrop** [comment]
Nie som 100% presvedceny, ze to mame mat. Ale ak nie, toto issue prosim
zavriet (drzme poriadok).

**Comment by kikinna** [comment]
Jasně, souhlasím. Zapracuji

**Comment by kikinna** [comment]
Opravená verze grafiky

**Comment by mukrop** [comment]
Hotovo.
