### ISSUE TITLE
STUDIE: detection of climate signal in Europe

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#150]
https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019GL082062

Český text tady: 
https://ct24.ceskatelevize.cz/veda/2909360-evropa-se-otepluje-jeste-rychleji-nez-se-cekalo-prokazala-studie?fbclid=IwAR0ipQmd8fs6Jio1PF_bumQA7KFoZvLSEr0O9mH-nIlkzshRx1RcbKZnI4s

**Comment by mukrop** [comment]
Přesunuto na wiki.
