### ISSUE TITLE
Grafika: power generation by source (EU)

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#167]
https://blisty.cz/art/95914-cr-pali-uhli.html
dohledat data

**Comment by ondraspribyla** [comment]
Data nejspíš z 
 https://sandbag.org.uk/project/power-2018/ 
https://sandbag.org.uk/wp-content/uploads/2019/01/Final-excel-Sandbag-Agora-Power-2018.xlsx

**Comment by ondraspribyla** [comment]
Není mi ale jasné, jak data organizovat, aby se z nich dalo snadno vytovořit 28 čtverečků ukazujících energetický mix průbehu času  :-)

**Comment by mukrop** [comment]
Přesunuto na wiki.
