### ISSUE TITLE
Emise svět - vývoj v čase

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#172]
#111 zahrnuje statický pohled - chtěl bych to doplnit vývojem emisí různých zemí v čase (EDGAR obsahuje emise 1970-2012). Doufám, že v infografice by mohlo vyjít například:

- pokles emisí EU a zároveň ekonomický růst
- u Číny (a dalších regionů) se projeví prudký nárůst emisí v prvních fázích ekonomického růstu, později emise rostou pomaleji než ekonomika

**Comment by mukrop** [comment]
Přesunuto na wiki.
