### ISSUE TITLE
Knowledge base

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#174]
Zvazuji, zdali by melo smysl pouzivat neco vice *hypertextoveho* pro vytvareni knowledge base - spis otazka do plena nez nejaky konkretni navrh - zajimalo by me, jestli jeste nekdo vnimate tuto potrebu ci jste to pripadne uz diskutovali.

- Google Drive neni spatny, obcas mam radeji neco kde se da snadneji proklikavat a strukturovat obsah
- obcas pouzivam markdown soubory s odkazy mezi nimi jako takovou pseudowiki (akorat je skoda ze k souborum se nedaji pridavat tagy podobne jako k issues)
- v zasade mi asi nejvic chybi nejaky rozcestnik, kde zhruba mame jake informace

Proc o tom premyslim - chci se pustit do Carbon Tax a k tomu potrebuji dohledat hodne informaci, napriklad: cena elektriny v CR, mnozstvi uvolnenych emisi na vygenerovani urciteho mnozstvi energie z uhelne elektrarny / ze spaleni litru benzinu / pripadne energie z jinych zdroju. Dost mozna uz tyto informace nekde mame, ale momentalne je dost pracne je nekde najit v internich zdrojich. Muzu je samozrejme najit jinde, jen to je mozna duplicitni prace a pripadne to muze vest k mirne nekonzistenci v udajich.

**Comment by mukrop** [comment]
Povolit GH wiki nie je problem, ale nemyslim si, ze to bude pre nas
fungovat. Wiki je verejna a samotne data a dalsie dokumenty zostanu v
gDrive.

Bavili sme sa vcera osobne, ze gDrive je vlastne OK, len je tam aktualne
dost neporiadok. Ked to upraceme a vyrobime rozcestnik tam, mohlo by to
fungovat.

**Comment by protivinsky** [comment]
ok - premyslel jsem, jestli by to nevedlo k potizim typu cast verejna a cast privatni. souhlasim ze uklizeny GD a rozcestnik by mohl jako knowledge base stacit.

**Comment by ondraspribyla** [comment]
Uklízím projekty na GITu... spousta Issues jsou spíše nápady, nabo odkazy na zdroje. Nechci je zavírat, protože se k nim "možná" dostaneme... ale nemají prioritu a zahlcují prostor. Tedy nějaký "knowledge base" by se hodilo... ale vlastně momentálně nemám jasno ani v tom pro kolik lidí by měl tento knowledge base fungovat. V tom počtu, ve kterém jsme je možná jednodušší to mít v hlavách a v případě potřeby si zavolat. Pořádek momentálně neudržíme ani v GItu ani v Gdrivu...  (tohle je jen myšlenka, issue nechávám otevřené)

**Comment by ondraspribyla** [comment]
Zprovoznili jsme WIKI na githubu, kterou chci pouzivat jako knowledgebase + skladiste napadu.

Zatím tam přesouvám užitečné články, ktere jsem precetl, a píšu k nim anotace. Vetsina clanku neni potreba prekladat nebo psat jako studie, ale bylo by dobre je nekde mit aspon pro nas... s kratkyma ceskyma anotacema. 
Tohle issue nechavam otevrene na diskusi o tom, jak kowledgebase pouzivat, pripadne nechceme-li neco jineho.

**Comment by mukrop** [comment]
Aktuální závěr: Wiki na nápady, gDrive na rozpracovaná data, Issue tracker na probíhající práci a hlášené chyby.
