### ISSUE TITLE
Land Use - grafika k přebrání

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#177]
První obrázek - Land use je pro nás zzásadní. Ostatní zaztím moc řešit nemusíme. 
https://www.visualcapitalist.com/impact-on-climate-change-and-land-use/

**Comment by lilyjoe19** [comment]
grafika číslo 1 je ozdrojovaná tu:
https://www.ipcc.ch/site/assets/uploads/2019/08/4.-SPM_Approved_Microsite_FINAL.pdf
strana 6, figure C
(priemerné) čísla v IPCC reporte dávajú dokopy 100 % :)

**Comment by palcifer** [comment]
Ak by sa to niekomu zišlo, tak som vložil dáta z predchádzajúceho príspevku do malého csv na spracovanie.

Name,Percent,Category,,,,
Infrastructure,1,A,,,,
Irrigated Cropland,2,B,,,,
Non-irrigated cropland,10,B,,,,
Intensive pasture,2,C,,,,
Used savannahs,16,C,,,,
Extensive pasture,19,C,,,,
Plantation forrests,2,D,,,,
Forests for timber,20,D,,,,
Unforested ecosystem,7,E,,,,
Forests,9,E,,,,
Other land,12,E,,,,

**Comment by mukrop** [comment]
Přesunuto na wiki.
