### ISSUE TITLE
Přidat do dalších zdrojů další stránky

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#184]
Zoznam stranok na pridanie je k dispozicii v tabulke na gDrive:
https://docs.google.com/spreadsheets/d/1NC1OGrQcCpvUVbwOxAi9yjnDTudUUGeGApU6Em3hpsE/edit#gid=1753371023
(Vlozit len tie, ktore maju zaskrtnute "web-chceme" a nemaju "web-mame".)

**Comment by ondraspribyla** [comment]
- [ ] Copernicus: https://cds.climate.copernicus.eu/#!/home
podstránky: všelijaká data, týkající se zejména Evropy. historické i předpovědi. 
Příklady: 
- Heatwaves for european countries: https://cds.climate.copernicus.eu/cdsapp#!/software/app-health-heat-waves-projections?tab=app
- Predikce Temperature exposure: https://cds.climate.copernicus.eu/cdsapp#!/software/app-health-temperature-exposure-projections?tab=app pro evropské země podle scénáře. 
- Sea Ice extent (je ale divnej, ukazuje hodně velké zalednění i pro RCP 8.5 v 2090...

**Comment by ondraspribyla** [comment]
NEXT STEP: překlopit do jednotlivých issues, které se dají zavírat poté, co jsou napsané...

**Comment by ondraspribyla** [comment]
Proel jsem původní dokumet se seznamem zdrojů. Nic zásadního momentálně nechybí, proto bych toto souhrnné issue uzavřel a přešel na formu "Jeden nový zdroj = jedno issue"
