### ISSUE TITLE
Rozšíření slovníku

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#185]
@crysman, @ondraspribyla:
Mohli by ste sa prosim zamysliet, ci vam napadnu nejake konkretne pojmy, ktore by bolo treba v najblizsej dobre pridat do slovnicku? Nech tu mame zoznam veci na pridanie.

**Comment by ondraspribyla** [comment]
- [ ] Albedo

- [ ] SR15 (special report IPCC on global warming 1.5°C)

- [ ] SROCC (special report IPCC... )

**Comment by ondraspribyla** [comment]
- [ ]  Uhelný phase-out

**Comment by ondraspribyla** [comment]
Přecházíme na styl "Jedno heslo = Jedno issue" - bude to přehlednější. 
Tímto tohle issue zavírám.
