### ISSUE TITLE
Alpské ledovce

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#197]
Rešerše o úbytku alpských ledovců - přispěl Martin Veselý 

https://docs.google.com/document/d/1VkoKuyygpQ7YIQU0bREp7hznjOrFw2hctGfiiLgYRy8/edit?fbclid=IwAR0CcypKe5QotItbUqaWl09ozp7gI07ZfNAJQ7zAk9IxGwEs84Nwnqz4xwk

**Comment by mukrop** [comment]
Přesunuto na wiki.
