### ISSUE TITLE
Uhlikova bomba (permafrost)

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#202]
Na toto tema jsem ted nahodou narazil na FB - popravde o tomto jsem mel zatim dost letme povedomi a netusil jsem, jake mnozstvi uhliku v permafrostu skutecne je. Odkladam si to sem, pokud bychom to chteli zpracovat - bud jako studii [1] nebo mozna i nejakou grafiku?

![north-pole](https://user-images.githubusercontent.com/9573993/65729749-48692c80-e0b7-11e9-919b-a84bf36f53c9.jpg)
![north-pole2](https://user-images.githubusercontent.com/9573993/65729763-4ef7a400-e0b7-11e9-89e4-5d948bd37792.jpg)

Martin Utheraptor Duřt

Zahrajeme si takovou hru.
Kolik myslíte, že je asi momentálně uhlíku v atmosféře?
Kolem sedmi až osmi set miliard tun [1]
Kolik myslíte, že je asi uloženo uhlíku v permafrostu na Sibiři, v Kanadě a dalších regionech?
Něco přes jeden a půl bilionu tun. [1 a 2]
Jinak řečeno, permafrost momentálně uchovává asi dvakrát víc uhlíku, než kolik je v celém vzdušném obalu naší planety dohromady.
Tomuhle fenoménu se říká uhlíková bomba, protože má potenciál velmi rychle velmi zásadně zhoršit změnu klimatu. Je to typický sebeurychlující se cyklus, kdy zvýšená teplota vede k většímu tání permafrostu, a tudíž k většímu uvolňování uhlíku do atmosféry, což dále zvyšuje teplotu a uvolňování. Anglický odborný název pro tento proces zní 'carbon feedback'.
Naše modely prozatím nejsou tak úplně schopné předpovědět, kolik z tohoto v podstatě nepředstavitelného množství uhlíku se může reálně uvolnit, případně jak rychle, ale i poměrně zdrženlivé odhady jsou alarmující.
Odhaduje se, že do roku 2100 roztaje cokoliv mezi 30 a 85 % mělkého permafrostu při předpokladu třístupňového oteplení. To se ovšem stále více a více jeví jako podhodnocený odhad, nejmodernější modely začínají počítat s možností čtyřstupňového oteplení. [3]
Rozsáhlá studie [1] Programu OSN pro životní prostředí (UNEP) se domnívá, že do roku 2100 by se mohlo vyvázat asi 43 až 135 miliard tun ekvivalentu oxidu uhličitého, do roku 2200 něco mezi 246 a 415 miliardami tun. Toto vypouštění by pak mělo pokračovat po další staletí, těžko říct jakým tempem, přičemž jakmile pořádně začne (patrně během několika desítek let [1]), nebude jej podle UNEPu možné v lidském časovém horizontu zvrátit.
Důvod této nezvratnosti leží ve skutečnosti, že téměř není možné uložit uhlík uvolněný z permafrostu zpět do organické hmoty, ze které pochází - rostliny z něj sice stavějí svá těla, avšak jejich zvýšený růst, způsobený liskými snahami a vyššími teplotami, nebude podle UNEPu ani v nejmenším stačí ke kompenzaci permafrostového uhlíku. [1] Malou naději podle všeho představuje jen zvyšování rozlohy rašelinišť, které také slouží jako vydatná skladiště uhlíku. [1]
Experimenty s odebranými vzorky permafrostu, zahřátými v laboratoři na teploty těsně nad nulou, hovoří o velkém vlivu vlhkosti - pokud půda zůstane mokrá, vypustí jen asi dvě procenta svého obsahu uhlíku ročně. Pokud by ovšem pořádně proschla, mohlo by jít až o devastačních dvacet procent. [2] Pokud by opravdu došlo k tak masivnímu vyvázání skleníkových plynů, byli bychom patrně nuceni zcela přehodnotit všechny svoje stávající modely klimatické změny a ohřátí o čtyři stupně celsia do roku 2100 by se ještě mohlo jevit jako zoufalý sen.
Velký problém je, že podle všeho asi polovina organického materiálu (obsahujícího uhlík) leží v hloubce do tří metrů. [1] Různé modely se liší v předpokládaném rozšíření aktivní vrstvy (tedy vrstvy vypouštějící uhlík). Některé hovoří o hloubce méně než metr, jiné až o třech metrech, což by bylo katastrofální. [1] Tyto odhady ovšem hovoří o průměrných hodnotách, v úvahu je nutné vzít skutečnost, že jižněji položené plochy permafrostu patrně zcela roztají - odhad je znázorněn na mapce přiložené níže. [1 a 4] Jak ovšem ukazuje druhá mapka, naštěstí se zdá, že největší obsah uhlíku mají severněji položená ložiska permafrostu. [5]
Situaci navíc dále komplikuje eroze, ke které je bohužel permafrost, po stránce strukturální integrity do značné míry spoléhající na led, velmi náchylný. [1]
Co je horší, všem dobře známý oxid uhličitý není to jediné, co tající permafrost vypouští. Kromě něj se do atmosféry dostává metan, skleníkový plyn také založený na uhlíku, jenž má podle odhadů asi třicetkrát silnější skleníkové efekty. [7] Zvýšený růst rostlin momentálně odstraňuje asi čtvrtinu lidmi vytvořeného oxidu uhličitého. [1] Podle UNEPu by mohly skleníkové efekty permafrostového metanu tento pozitivní efekt částečně - podle nejčernějších modelů zcela - vyrušit. [1]
I pokud by se úplně podařilo zastavit vypouštění uhlíku do atmosféry lidmi, permafrost tající v důsledku již nezvratného zahřátí planety jej bude společně s metanem vypouštět po další stovky let. [1]
Divíte se, že jste o tomto podle všeho extrémně závažném dopadu klimatické změny nikdy neslyšeli?
Ani já o něm až donedávna v podstatě nevěděl.
Bohužel mu není věnována příliš velká pozornost. IPCC Assessment Reporty [8], nejvýznamější a nejrozsáhlejší metastudie této problematiky vůbec, na nichž jsou z velké míry postavená opatření přijímaná mezinárodním společenstvím, jej až do roku 2007 vůbec nezahrnovaly. [1] Pátý report z roku 2014 jej již částečně zmiňuje (naneštěstí bez konceptu sebeurychlujícího se vypouštění, popsaného výše) [6], avšak desetiletí nedostatečné pozornosti napáchala velké škody.
Jelikož současná politická reprezentace s tímto vypouštěním skleníkových plynů v podstatě nepočítá, není řádně započítáno do strategií pro zpomalování klimatické změny. Ty vesměs kalkulují jen s lidmi přímo vytvářeným uhlíkem, takže by se mohlo stát, že ačkoliv (pravděpodobnosti navzdory) splníme předepsané limity a cíle, stejně se nám nepodaří oteplení udržet pod cílovými dvěma stupni celsia, protože do hry vstoupí permafrost. [1]
Jak můžete vidět, situace opravdu není dobrá.

[1] https://epic.awi.de/id/eprint/33086/1/permafrost.pdf
[2] https://aprender.ead.unb.br/…/conte…/1/permafrost_C_bomb.pdf
[3] https://www.ipcc.ch/…/assets/…/2018/02/AR5_SYR_FINAL_SPM.pdf
[4] https://www.tandfonline.com/…/10.1…/j.1600-0889.2010.00527.x - bohužel se mi nepodařilo najít otevřenou verzi, ale bystrý čtenář jistě ví, jak používat sci-hub.
[5] https://agupubs.onlinelibrary.wiley.com/…/10.1…/2008GB003327
[6] https://www.ipcc.ch/…/uploads/2018/02/SYR_AR5_FINAL_full.pdf
[7] https://www.ipcc.ch/…/uploa…/2018/02/ar4_syr_full_report.pdf
[8] https://www.ipcc.ch/

**Comment by ondraspribyla** [comment]
Souhlas, je to další téma, které stojí za zpracování.
IPCC SR15 dává nějaké odhady pro uvolňování methanu z permafrostu, které
jsou velké, ale ne tak katastrofální... zkoušel jsem se dívat do zdroje [1]
- nenašel jsem jeho datum vydání, což je pro aktuálnost zásadní.

O.

**Comment by mukrop** [comment]
Přesunuto na wiki.
