### ISSUE TITLE
Cena za uhlik II: Rozsireni ve svete

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#205]
Pro lepsi trackovani rozdeluji #141 na tri issues:

2. Neni to nic obskurniho, je to overena metoda zavadena v mnoha zemich
vcetne Ciny (tedy neni to ze Cina emituje a nic nedela, jen my na to
kasleme; osobne mam skutecne dobry dojem z velkeho narustu opatreni v
poslednich letech, je to dobry lek na environmentalni zal).

---
_Zpracováváme překlopení grafiky ze zprávy WB do češtiny a našeho formátu.
Aktuální verze grafiky je v komentářích._

Garant obsahu: _doplnit_
Garant grafiky: @kikinna 
Graficky zpracovává: Kubo Novák

**Úkoly**
- [x] třeba přeložit z angličtiny do češtiny @tomaspsorn 
- [x] přiřadit garanta obsahu @protivinsky @ondraspribyla (Tome, možná zrovna ty?)

_Aktuální verze grafiky_
![cena-uhliku-lI-v1 0-01-01](https://user-images.githubusercontent.com/11555522/74597463-28370b80-5060-11ea-9745-d2204aea131f.png)

**Comment by protivinsky** [comment]
Osobne se mi libi ta mapa podle zpravy WB; rovnez mi prijde zajimavy i narust pokrytych emisi nekterym ze systemu (dan nebo ETS) v poslednich letech, viz nize. Nejsnadnejsi zpracovani infografiky tedy muze pouze zkombinovat tyto dva grafy.
- WB ma celou zpravu pod licenci CC BY 3.0 IGO, muzeme ji tedy prelozit i adaptovat jak chceme, pouze s uvedenim jejich disclaimeru. 
- grafy jsou ve zprave v krivkach, je tedy mozne je odtud vytahnout primo do illustratoru a upravit

@ondraspribyla souhlasis s takovym zpracovanim? Nebo bys to chtel nejak upravit / doplnit? Pokud by to takto bylo ok, v podstate se to da rovnou zadat grafikum. Nevim jestli by melo smysl ta data vytahat i do spreadsheetu nebo jestli staci odkazovat na tu studii.

![image](https://user-images.githubusercontent.com/9573993/65917418-38ab5a00-e3cf-11e9-9b15-6ede5d4a262a.png)

![image](https://user-images.githubusercontent.com/9573993/65917490-5b3d7300-e3cf-11e9-9274-420bf9db8846.png)

**Comment by ondraspribyla** [comment]
https://docs.google.com/spreadsheets/d/1-d7C0hMGS-KI7bs6Ad_cFBubFCaj7IMroN0KW1-HmEo/edit?usp=sharing

**Comment by protivinsky** [comment]
https://ekonom.ihned.cz/c7-66651430-gidm1-56a8b8ae97805c7?fbclid=IwAR2DXFuH6KfXE0ZRpfAMnyGeFoQZlzH252vKvPLlsRPbxs5pmYl6RCT8ZUE

_"Má se podle vás průmysl podílet na boji proti globálnímu oteplování?"
"Evropa přece sama svět nezachrání. Je nutné tlačit ekonomicky a politicky na Spojené státy, Čínu, Indii, Rusko či Brazílii."_

Zbytek clanku neni tolik relevantni, ale tento argument mi prijde jako klasicky narativ - a prave tato infografika by ho mela uvadet na pravou miru, ze to zdaleka neni sama Evropa (a navic Cesko se na tom podili jen velmi vlazne, bez EU by se mozna nepodilelo vubec - ze splnujeme cile Parizske dohody je jen diky padu environmentalne katastrofalnimu predchozimu rezimu...).

**Comment by ondraspribyla** [comment]
NEXT STEP: přeložení infografiky Figure 5. (viz výše) -> zkusíme zadat na nejbližším hackatonu. 
@protivinsky - mohl bys ověřit licenci? Případně sehnad vektorový formát?

**Comment by protivinsky** [comment]
**Vektorovy format** - studii jsem dal na nas GD jako pdf - https://drive.google.com/open?id=1_7BhuNanErJUKQ8xg144W1QAeU7d_Huu , pripadne je ke stazeni i na strankach WB - https://openknowledge.worldbank.org/handle/10986/31755
U sebe muzu v Illustratoru normalne otevrit to PDF a prislusnou stranu a mam to jako vektorovou grafiku (i kdyz ne zrovna v nejvic privetivem formatu, nejsou tam zadne vrstvy apod. - nicmene upravit to do pouzitelnejsiho stavu je celkem rychle).

Pokud by grafici chteli, muzu pripadne napsat WB a zeptat se jestli to nemuzou poslat v nejakem jinem formatu. Tezko rict, jestli by na to byla nejaka odezva, mne osobne by to PDF stacilo.

**Licence** - pocitam ze bychom meli uvest attribution a disclaimer ktery je uvedeny u translation:

**Rights and Permissions**
This work is available under the Creative Commons Attribution 3.0 IGO license (CC BY 3.0 IGO) http://creativecommons.org/licenses/by/3.0/igo. Under the Creative Commons Attribution license, you are free to copy, distribute, transmit, and adapt this work, including for commercial purposes, under the following conditions: 

**Attribution**—Please cite the work as follows: “State and Trends of Carbon Pricing 2019” State and Trends of Carbon Pricing (June), World Bank, Washington, DC. 
Doi: 10.1596/978-1-4648-1435-8.
License: Creative Commons Attribution CC BY 3.0 IGO

**Translations**—If you create a translation of this work, please add the following disclaimer along with the attribution: _This translation was not created by The World Bank and should not be considered an official World Bank translation. The World Bank shall not be liable for any content or error in this translation._

**Adaptations**—If you create an adaptation of this work, please add the following disclaimer along with the attribution: _This is an adaptation of an original work by The World Bank. Responsibility for the views and opinions expressed in the adaptation rests solely with the author or authors of the adaptation and are not endorsed by The World Bank._

**Comment by ondraspribyla** [comment]
@protivinsky Kika připravila grafiku do našeho templatu - NEXT STEP: 

- [ ] Přeložit texty v infografice

![CARBON-PRICING_03-1-1 5_2019-11-11-03](https://user-images.githubusercontent.com/17317136/68802599-8538b500-065e-11ea-874d-4cec1f8c6953.png)

**Comment by kikinna** [comment]
Nikoliv já, ale Kubo. Já jen přeposlala ;)

**Comment by kikinna** [comment]
> Pro lepsi trackovani rozdeluji #141 na tri issues:
> 
> 1. Neni to nic obskurniho, je to overena metoda zavadena v mnoha zemich
>    vcetne Ciny (tedy neni to ze Cina emituje a nic nedela, jen my na to
>    kasleme; osobne mam skutecne dobry dojem z velkeho narustu opatreni v
>    poslednich letech, je to dobry lek na environmentalni zal).

**Comment by kikinna** [comment]
Wow, ranní překlik, moc se omlouvám.

**Comment by protivinsky** [comment]
Nenapadne naznaceni ze bych to konecne mohl dodelat? :)
Pardon, trochu mi to zapadlo - pustim se do toho.

**Comment by kikinna** [comment]
No, já si vlastně nejsem jistá, jaké jsou přesně záměry )) Co máš v plánu
dodělávat? (Na překlad jsem to dala kamarádovi, co chtěl pomoct a neměli
jsme pro něj práci) a přemýšlím, co s tím budeme dělat potom dále )

**Comment by protivinsky** [comment]
Jo, myslel jsem ten preklad. Ale pokud uz na tom nekdo dela, skvele!

**Comment by tomas-psorn** [comment]
Ahoj, tady je první verze překladu.

https://docs.google.com/document/d/10CbCiR3vp7WiXGl99HP_Iyn2cdtRnvm6U214zt75TWY/edit

**Comment by ondraspribyla** [comment]
Díky moc, předpokládám, že během ledna to dál posunem :-)

O.

**Comment by tomas-psorn** [comment]
@palcifer

**Comment by palcifer** [comment]
![ceny-uhliku-ll-v1 0-01](https://user-images.githubusercontent.com/5993966/73223481-798d6280-4166-11ea-8cf7-28ec7cbedf85.png)
Prvy nastrel, aby bolo jasne, ze ten text v obrazku byt fakt nemoze.

**Comment by kikinna** [comment]
Ahojte )) Díky Palko, to je super) Hh, tvé tvrzení o nemožnosti dát text do
obrázku je nezpochybnitelné :D ( Teda nevím, jaká debata probíhala kolem
infografiky -- jestli někdo lobbuje za to, aby text v grafice byl.) Nicméně
od toho máme doprovodné texty a ty hvězdičky jsou imho přesně takovej druh
popisku. Tu grafiku by chtělo trochu provzdušnit (hlavně ty ikonky a názvy
států) a pak začátek dlouhé poznámky by se podle mě mohl dát pěkně převést
do legendy, hm? ;)

Palči, víš, co s tím dál ?

**Comment by protivinsky** [comment]
Ano, diky! Za text nikdo nelobuje, ja jsem taky presvedceny :) Takto je text opravdu velmi rusivy. 

Puvodne jsem si rikal, ze kdyby se text vydal nejakym ultramalym fontem a pripadne klidne nejakou nevyraznou sedou, tak by to bylo jednodussi, protoze by to bylo self-contained. Je tam toho ale moc.

Osobne navrhuji:
- hvezdickove texty ponechat v grafice, pouze hvezdicku * zkratit na:
  - "Pokrytí zahrnuje čínský národní ETS a osm pilotních ETS systémů. Rozsah pokrytí udává předběžné neoficiální odhady."
- jako legendu bych nekde v grafice ponechal:
  - "Velikost kruhů znázorňuje objem emisí v dané jurisdikci. Symboly označují odvětví průmyslu, a/nebo paliva zahrnutá v příslušných opatřeních pro zpoplatnění emisí uhlíku. Velikost největšího z kruhů (Čína) odpovídá množství 12,4 Gt CO2eq a velikost nejmenšího kruhu (Švýcarsko) množství 0,05 Gt CO2eq." (prvni dve vety, ale pozor, opravil jsem chybku u jednotek - obecne pouzivame tento format)
- zbytek poznamky a dovysvetleni cinskeho ETS se da snadno presunout do pruvodniho textu

Dalsi komentare:
- nazev ma byt: "Zpoplatnění emisí: Rozšíření ve světě" (promin Palko, nekde nam to z toho prekladu vypadlo). Podle toho i URL ma byt zpoplatneni-emisi-rozsireni
- krome toho do grafiky potrebujeme atribuci a disclaimer. Popravde, nejsem si prilis jisty, jak to funguje, kdyz prejimame pouze jeden graf z cele zpravy, jestli k tomu mame referovat jako k adaptaci nebo jako k prekladu. Navrhuji:
  - State and Trends of Carbon Pricing 2019, World Bank, Washington, DC. Doi: 10.1596/978-1-4648-1435-8. Licence: CC BY 3.0 IGO.
  - Tento překlad nebyl vytvořený Světovou bankou a neměl by být považovaný za oficiální překlad. Světová banka nepřebírá odpovědnost za obsah ani za případné chyby v tomto překladu.

A souhlasim, trochu provzdusneni by prospelo. Kdyby bylo jeste neco potreba, dejte vedet - a diky :)

**Comment by palcifer** [comment]
![ceny-uhliku-ll-v1 0-01](https://user-images.githubusercontent.com/5993966/73769210-91727100-477a-11ea-9efb-411ad0bf4880.png)
tak som sa pokusil to trochu prevzdusnit. Ak tomu rozumiem spravne, tak tam este ma byt:

- atribuce
- disclamer
- legenda (aj vizualna)
- sest hviezdickovych viet

nevravim, ze to tam nemoze byt, ale stoji za zamyslenie, co tam naozaj ma byt, co staci udrzat v texte a co napriklad musi byt v grafike, pretoze sa to priamo viaze na vizualne premenne.

**Comment by protivinsky** [comment]
Diky za dalsi verzi, vypada to vyrazne lepe!

- atribuce a disclaimer v grafice byt musi, ale mohou byt velice male / svetle nekde na kraji - neni to ani tolik pro ctenare, jako pro splneni povinnosti vuci zdroji (co treba dat "hlavni zdroj dat o malicko vyse, namisto NASA... napsat "World Bank" a pod to nejakym malym svetlym fontem plnou atribuci a disclaimer? ono to s tim zdrojem dat souvisi)
- textova legenda je podle me tez uzitecna (vizualni uz k tomu podle me byt dalsi nemusi, nad ramec toho co uz tam mame?)
- pokud se hvezdickove texty nevydaji, dame je do pruvodniho textu. Grafika by s nimi byla ucelenejsi, ale rozhodne nema smysl ji mit prehustenou.

Jeste bude taky potreba prelozit nazvy statu, zvladnes to? Nebo jestli chces, klidne ti napisu ceske preklady. Take mi zatim ty texty kolem mapy - popisy dole a vpravo - prijdou hodne vyrazne, az to budeme finalizovat, byl by fajn nejaky lehci rez, at z toho tolik netrci.

**Comment by kikinna** [comment]
Díky Palči za grafiku a Tome za feedback))

Jen quick note obecně ke grafikám. Je třeba být opatrný s přemisťováním
zdroje dat a když to není nezbytně nutné, tak to nedělat. Je podle toho
třeba nastaven ořez grafiky na webu a mohlo by se to tak jednoduše rozbít.

Ad legenda a popisky - ano, zatím je to dost výrazné. Myslím ale, že když
se vyjde z konvencí, které používáme v ostatních grafikách, tak to bude ok.

Můžem na to, Palči, kouknout spolu a prokonzultovat)

Mějte se,
Kristi ))

**Comment by protivinsky** [comment]
Aha, orez me nenapadl - good point. Ponechavam tedy na vas, kam schovat attribution + disclaimer :)

**Comment by kikinna** [comment]
@ondraspribyla Nahoře je hozená aktuální verze grafiky. Prosím koukni na ty texty, jestli tam něco chceš upravit. 
@protivinsky Tome, myslíš, že bych tě mohla poprosit, jestli by jsi nezkontroloval věci jako názvy států, jejich procenta a jestli je danej stát vybarevenej správně? (Dost jsem s tím bojovala, protože tam byl děsnej bordel s těma šrafováníma a doufám, že se i nic nerozpadlo)

**Comment by protivinsky** [comment]
Grafiku jsem zkontroloval, vytvoril PR #414 a zaviram issue.

**Comment by jankrcal** [comment]
Skvělá práce!

Dívám se na grafiku a vidím dva drobné překlepy:
 - Odhadovan**é** podíl emisí
 - regionů pokrytých daným **opatření**

Mám na to založit další issue nebo to opravíme v rámci tohoto?

**Comment by kikinna** [comment]
Fixed. New version here
<https://www.dropbox.com/sh/4wwopqeb0ccofu4/AADggQUskkt5YsDbBudNwVyma?dl=0>

**Comment by jankrcal** [comment]
Super, dík, postarám se o PR.

**Comment by ondraspribyla** [comment]
Je součástí posledního PR  #425 na opravu grafik. Zavírám

**Comment by jankrcal** [comment]
Dík.
