### ISSUE TITLE
Teplotní anomálie -> Teplotní odchylka

### ISSUE THREAD

**Issue by Keramadohal** [faktaoklimatu/web#208]
Tolasz: Nelíbí se mi spojení "teplotní anomálie", zaužívaná je "teplotní odchylka" s jasným uvedením, od kterého období je odchylka vypočtena.

**Comment by kikinna** [comment]
@Keramadohal @jankrcal Kluci, co s tady tím. Mám to předělat nebo to issue zavřeme?

**Comment by ondraspribyla** [comment]
Zavřeme. Podle mě to je jen preference RT.

Dne po 3. 2. 2020 19:19 uživatel kikinna <notifications@github.com> napsal:

**Comment by Keramadohal** [comment]
Ok, já nakonec taky souhlasím. Je to tak i v [Meteorologickém slovníku](http://slovnik.cmes.cz/fulltext/anom%C3%A1lie). Takže zavírám.
