### ISSUE TITLE
Změna grafu "Srovnání průměrné teploty v ČR v jednotlivých měsících" ?

### ISSUE THREAD

**Issue by Keramadohal** [faktaoklimatu/web#209]
Tolasz:  Graf "Srovnání průměrné teploty v ČR v jednotlivých měsících" považuji za neúplný a napadnutelný. Je to vlastně prvních a posledních 5 let v řadě, vhodnější by bylo dát nad sebe 10leté průměry všechny od r.2018 zpětně (2009-2018, 1999-2008, 1989-1998, 1979-1988 a 1969-1978)

**Comment by lilyjoe19** [comment]
ten Tolaszov návrh sa mi páči... tiež voči tomu grafu mám výhrady (a tuším aj Jirka Kalina?).
@ondraspribyla, čo ty na to - myslíš, že môžeme tú infografiku prepracovať?

**Comment by Keramadohal** [comment]
S Ondrášem jsme to už předminule řešili a došli jsme k tomu, že ano, bylo by to lepší a šlo to udělat pomocí horizontálních linek místo puntíků. Ale pokud vím, tak grafici teď mají už dost úkolů a toto aktuálně není priorita. Data k tomu ale nachystat můžeš/můžeme ;-)

**Comment by ondraspribyla** [comment]
Graf předělán pro článek z iRozhlas. Update o rok 2019, změna pětiletky na desetiletí. 
Všechny ostatní dekády jsme se rozhodli nedoplňovat, protože to hrozně zašumí grafiku.(doporučuju udělat si výpočet nad daty...)

Tímto issue zavírám.
