### ISSUE TITLE
Studie: State and Trends of Carbon Pricing 2019

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#220]
Sepisu z toho nejake shrnuti. Jedna se o tu studii World Bank: https://openknowledge.worldbank.org/handle/10986/31755
Chci tlacit Carbon Pricing dopredu co nejvice, potrebujeme ho dostat do povedomi.

Proc: https://www.facebook.com/notes/martin-křivánek/klimatická-změna/10156872665543090/

Je to samozrejme skvele shrnuti a Set je velice inteligentni a dobre analyticky premysli, zaroven:
- tam nebyla ani zminka o zpoplatneni emisi - pritom ja to povazuji za nejefektivnejsi prostredek pro reseni klimatickych zmen, ktery mame
- nebylo tam zmineno vubec nic pozitivniho, co se v oblasti na mezinarodni rovine deje (ackoli ty pozitivni krucky jsou zatim velmi male)

Pokud toto Set nezaregistroval, pak to zjevne v CR nevi temer nikdo. O to dulezitejsi mi prijde tema Carbon Pricing, vcetne toho svetoveho porovnani (#204, #205, #206).

**Comment by protivinsky** [comment]
souvisejici - Fiscal Monitor od IMF: https://www.imf.org/en/Publications/FM/Issues/2019/09/12/fiscal-monitor-october-2019

**Comment by ondraspribyla** [comment]
Myslím, že můžeme zavřít. Studie MMF bude, dál posuneme téma skrz issue z trilogie Cena Uhlíku I, II a III... 
Pokud nesouhlasíš, tak to znovu otevři...
