### ISSUE TITLE
Studie: 80% snizeni emisi v CR

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#221]
Na toto jsem narazil, ekonomicka analyza snizeni emisi zamerena na CR. Muzeme zvazit zdali ji take chceme na web do studii. 

https://idea.cerge-ei.cz/files/IDEA_Studie_21_2016_Snizeni_emisi_sklenikovych_plynu/mobile/index.html#p=1

**Comment by mukrop** [comment]
Přesunuto na wiki.
