### ISSUE TITLE
Srovnání emisí Production / Consumption

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#222]
https://ourworldindata.org/consumption-based-co2?fbclid=IwAR3i5gD2BpJUB4eZjcC-8gWuc-PbloJsSSUi1Oo7IGd7lRr2amrDTz4kTtw

TODO:
- [ ] přidat nějakou odrážku k emisním infografikám

**Comment by crysman** [comment]
hele, co jsem našel:
![image](https://user-images.githubusercontent.com/5269350/68804755-c59a3200-0662-11ea-9874-f5348637187d.png)

podle mě je to důkazní linka toho, že "Čínské emise" jsou z velké části vlastně "naše" emise (západního světa) - lebo Čínský "export CO2" podle mě reprezentuje masové nákupy tamního zboží. Jsem v tom správně? @protivinsky

**Comment by protivinsky** [comment]
@crysman castecne: ano, cinske emise jsou z casti "nase" emise, avsak ta cast neni az tak velka. v grafu to vychazi ze Cina vyvazi zbozi s emisemi cca 1.4 Gt, pritom celkove emise Ciny pro 2012 byly 12.2 Gt CO2eq, samotne CO2 neco pres 10 Gt. Cili zapadni svet je zodpovedny cca za 13 % cinskych emisi. Tedy za vyraznou vetsinu svych emisi je Cina zodpovedna sama.

Tech cca 13 % ukazuji i dalsi grafy na tom odkazu od Ondrase - a zaroven Ceska republika ma obecne obchodni bilanci vicemene na nule, takze my za cinske emise v zasade zodpovedni nejsme. Zaroven to pomaha vysvetlit, proc ma CR temer nejvyssi emise na hlavu v EU - cast nasich emisi je vyvazena do ostatnich zemi (v podobe elektriny).

**Comment by mukrop** [comment]
Přesunuto na wiki.
