### ISSUE TITLE
Projít ročenku CENIA

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#230]
CENIA = česká informační agentura životního prostředí je příspěvkovou organizací, příspěvkovka MŽP
má ročenku, v ní je spousta ajímavých informací. Hodilo by se ji projít a případně některé informace vypsat. 

[Statisticka_Rocenka_ZP_CR_2017-1.pdf](https://github.com/mukrop/faktaoklimatu/files/3740795/Statisticka_Rocenka_ZP_CR_2017-1.pdf)

**Comment by Keramadohal** [comment]
Zaměřit se na vodní zdroje?

Viz https://groups.google.com/forum/#!topic/klimaton-brno-all/u8853P7a770

**Comment by LenkaSedlackova** [comment]
ja si myslím, že v tej ročenke je oveľa viac zaujímavých info :) napr o využití fosílnych palív, o veku vozového parku, o počte hospodárskych zvierat apod (a to je iba výcuc z prvých cca 100 strán, čo som prešla). ale ak sa tomu chceš venovať, môžeme si to nejak rozdeliť

**Comment by ondraspribyla** [comment]
Asi by pomohlo, kdybyste ty témata zkusili snižovat, abychom my ostatní
nemuseli tu ročenku procházet sami. Třeba jako:

Téma: průtok vody v řekách
Data: množství vody ve Vltavě v letech x-y
Co je z dát vidět: Vltava má konzistentní pokles průtoku
Jak to zobrazit: asi sloupcový graf
Ref: strana CD

Co vy na to? Vlastně stačí jen ty věci, které vás zaujaly...

Dne út 28. 1. 2020 11:56 uživatel LenkaSedlackova <notifications@github.com>
napsal:

**Comment by LenkaSedlackova** [comment]
ja som zatiaľ pracovala takým spôsobom, ako hovoríš - vypisovala som si info, ktoré ma zaujali. výstup zatiaľ je:
13 Tab. 2.1.1.2 Hospodářská zvířata, 2006–2018
kráv stabilne, menej prasiat

15 Tab. 2.1.1.4 Spotřeba průmyslových hnojiv NPK, 1995–2017
nárast NPK hnojív

23 Tab. 2.2.1 Těžba energetických, nerudních a stavebních surovin, 2006–2017
útlm ťažby uhlia - hlavne čierneho, mierne aj hnedého + ropy, zemný plyn cca stabilný (max 207, min 148)

24 Tab. 2.2.2 Podíl vývozu vybraných surovin na jejich celkové těžbě, 2007–2017cca 50 % čierneho uhlia sa vyváža, zatiaľčo takmer všetko (cca 97 %) hnedé uhlie je určené na domácu spotrebu

32 Tab. 2.4.1.1 Celková energetická bilance, 2010–2016
domáce zdroje: podiel OZE stabilný, jadro a tuhé palivá pokles
dovoz: stúpol dovoz tuhých palív aj OZE
vývoz: pokles vývozu tuhých palív
pozrieť a doplniť
spotreba energie +- stabilná

41 Tab. 2.4.1.14 Spotřeba paliv a energie v domácnostech, 2010–2016
čierne uhlie stabilné, hnedé uhlie mierny pokles; biomasa hore, zemný plyn pokles

43 Tab. 2.4.2.3 Podíl spotřeby energie vyrobené z OZE na spotřebě elektřiny, energie v dopravě, na vytápění a chlazení a na konečné spotřebě energie, 2004–2016
podiel OZE stúpol

47 Tab. 2.5.3 Počet motorových vozidel, 2005–2017
počet osobných áut medziročne rastie a pribúda áut starších akoi 10 rokov 
(49 Tab. 2.5.6 Osobní automobily registrované v ČR podle věkových kategorií, 2005–2017)

112 Tab. 3.2.1.4 Kvantifikace dílčích indikátorů Národního programu snižování emisí ČR dle jednotlivých opatření relevantních pro aktuální rok
veľa starých áut

---------------------
chcela som to poslať, keď to dokončím, ale možno aj takáto čiastočná práca môže byť užitočná

**Comment by protivinsky** [comment]
Jsem za **zpracovani vody**.

**Motivace / prostor pro osobni vylev:**
Dnes tomu bylo ve zpravach CT venovano aspon 10 minut. Poukazali na mnoho vesnic, ktere maji velke problemy s nedostatkem pitne vody, na chovatele krokodylu, ktery bude muset za vodu zaplatit ctvrt milionu rocne a na vyrobce zmrzliny, ktery kvuli zdrazeni vody bude platit 12 Kc denne za myti stroju na vyrobu zmrzliny. A nasledne navrhli, ze resenim bude postavit vice vodovodu. Ani slovo o klimaticke zmene nebo o zpusobu vyuzivani krajiny.

Je to tema a je o nem mizerne informovano, navic se to skutecne dotyka mnoho lidi a resi to. Navic to tusim bylo take vysoke riziko podle Davosu.

**K tematu - zajimave indikatory** (pozor, je to z novejsi rocenky pro rok 2018 - https://www.mzp.cz/cz/statisticka_rocenka_zivotniho_prostredi_publikace):
- rocni srazky, odtok vody, zdroje povrchove vody a vyuzitelne zdroje podzemni vody (tab 3.3.1.1, casove rady 2001-2018, vsechno dramaticky klesa) - toto mi prijde nejnosnejsi, ukazuje to vyvoj lepe nez srovnani roku 2018 vs dlouhodobych ukazatelu
- srovnani odtokovych vysek jednotlivych rek (2018 vs dlouhodoby prumer), viz mapka nize (obr 3.3.1.3)
- hladiny podzemnich vod a vydatnost pramenu, rok 2018 vs dlouhodobe statistiky (obr 3.3.1.6 a 3.3.1.7)
- zajimave jeste muze byt kdo kolik vody spotrebovava - prumysl, zemedelstvi, energetika, domacnosti - u podzemni jsou domacnosti, tedy pokud nebude, pak neni prilis kde setrit. U povrchovych spotrebovava hodne energetika (tab 3.3.3.1-4)

**Jak bych to uchopil:**
- @ondraspribyla : dal bych do kontrastu ty casove rady (mnozstvi povrchove i spodni vody pokleslo na mene nez polovinu) s tim, kolik vody a na co skutecne vyuzivame (pres 30 % zbyvajici povrchove vody, necelych 50 % podzemni vody; u podzemni je drtiva vetsina pitna voda pro domacnosti). Zaroven to ilustruje, ze pokud bude tento pokles pokracovat, hrozi skutecny problem pro vsechny obyvatele.

![image](https://user-images.githubusercontent.com/9573993/73401277-c0a06280-42e2-11ea-80e3-109b48dda02b.png)

![image](https://user-images.githubusercontent.com/9573993/73401245-af575600-42e2-11ea-880e-3ec6234cf675.png)

**Comment by Keramadohal** [comment]
Jsem taky za prioritní zpracování vody.

Všechna ta ostatní čísla jsou samozřejmě taky zajímavá a někdy v budoucnu můžeme udělat infografiku i o prasátkách :-), ale naprosto se ztotožňuju s tím, co píše Tom. Nedostatek pitné vody je jeden z přímých dopadů změn klimatu (a špatného hospodaření v krajině), který je u nás už dnes jasně viditelný (společně s degradací lesů), ale informuje se o tom špatně, málo nebo vůbec, takže lidé si to nespojují.

Jinak excely jsou ke stažení na webu CENIA: https://www.cenia.cz/publikace/statisticka-rocenka-zivotniho-prostredi-cr/statisticka-rocenka-zivotniho-prostredi-cr-2018/

Tu Vodu jsem nahrál na Disk: https://drive.google.com/drive/folders/1m0zrxdILOxTyhOa_-b1NlEBosra9aqLv

**Comment by Keramadohal** [comment]
Hodil jsem to do náhledových grafů

![image](https://user-images.githubusercontent.com/41745152/73533198-8936d080-441e-11ea-9b22-3ba5328e6231.png)

**Comment by kikinna** [comment]
Ahojte, jsem taky za zpracování vody. Je to  důležité a aktuální téma.
Zkusím nad tím přemýšlet.

**Comment by ondraspribyla** [comment]
Na vodu zalozeno vlastni issue. Jen pripominam, ze jeden pokus o nejake
zpracovani dat vody byl v #192, ktere jsme zavreli, protoze to nikam
nevedlo. Tak bych chtel, abychom si dali pozor a neopakovali nikam
nevedouci praci...

O.
