### ISSUE TITLE
Zalesňování - potenciál pro mitigaci klimatických změn

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#235]
**Bylo by dobre na toto tema mit nejakou grafiku nebo studii.**

Nedavno byla v Science studie o potencialu zalesnovani pro snizeni sklenikovych plynu (odstraneni az 2/3 antropogennich emisi CO2 z atmosfery), ktera nasledne proletela ruznymi medii vcetne ceskych (a vcetne ruznych chyb, napriklad Aktualne zamenuje GtC za GtCO2):

https://zpravy.aktualne.cz/zahranici/klima-by-mohlo-zachranit-sazeni-stromu-tvrdi-svycarska-studi/r~064bcd249e9c11e9b7740cc47ab5f122/
https://www.vox.com/2019/7/4/20681331/climate-change-solutions-trees-deforestation-reforestation

Odkaz na studii: http://www.fieraboster.it/docs/BOSTER%202019/The-global-tree-restoration-potential.pdf
V leccems je zjevne zjednodusujici, napriklad zde jsou tvrzeni dost opravena: https://twitter.com/hausfath/status/1147190442145898496

Nicmene zalesnovani je dulezite tema (upozornuje na ne i Stern), uchopitelne pro bezne lidi a zaroven neni jednoduche - zalezi hodne na tom jake stromy, kde apod; rovnez skutecny potencial je pravdepodobne vyrazne nizsi nez naznacuje ta studie. Prislo by mi skvele, kdybychom k tomu meli neco, co by pomohlo se v te diskuzi zorientovat a zodpovedet nejake zakladni otazky.

**Comment by mukrop** [comment]
Přesunuto na wiki.
