### ISSUE TITLE
Korektura finálního datasetu: teplota ČR

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#237]
https://drive.google.com/open?id=14eph67uGIQJgEBSmvWAufdRY49sI3JFq9G9_lH8G7h4

**Comment by jankrcal** [comment]
Nový datasheet je tu: https://docs.google.com/spreadsheets/d/1kd3BvkzVTNUV799pldht9YLGGHImREl70LuIX2koYS8/edit#gid=979818322

Je to skoro hotovo, ke zveřejnění chybí: 
 - doplnit hodnoty p-values a způsob jejich výpočtu (např. skript pro R)
 - upravit grafiku (byla tam chyba v průměrné teplotě roku 1961, proto se mění graf teplot i trend, rozdíl teplot za sledované období je jen 1,9 a ne 2,0)
 - možná se vším počkat, až budou komplet data za rok 2019 (tedy do ledna 2020), aby se rovnou aktualizovala data o rok 2019

**Comment by jankrcal** [comment]
Přidávám Marka na doplnění podkladů k p-values, nejlépe sem, já to doplním do data sheetu.

**Comment by Keramadohal** [comment]
> * doplnit hodnoty p-values a způsob jejich výpočtu (např. skript pro R)
Vytvořil jsem složku na GDrive a nahrál tam R skript včetně dat a výsledků + i worksheet a screenshot z programu Statistica: https://drive.google.com/drive/folders/1U2N73RzfSu-rDUUsJPuSUtWrCUgUHuYI

Vychází to stejně :-)

Jinak, info k výpočtům:
- Statistica help: https://documentation.statsoft.com/STATISTICAHelp.aspx?path=Glossary/GlossaryTwo/P/PearsonCorrelation
- Rko: https://www.rdocumentation.org/packages/stats/versions/3.6.1/topics/cor.test
- obecně, detailně a hlavně česky: https://portal.matematickabiologie.cz/index.php?pg=aplikovana-analyza-klinickych-a-biologickych-dat--biostatistika-pro-matematickou-biologii--zaklady-korelacni-analyzy--pearsonuv-korelacni-koeficient

**Comment by setcz** [comment]
Ha, sám si odpovím - ony už ty měsíční teploty na tom webu jsou zaokrouhlené na jedno desetinné místo - což pak může způsobit, že se jejich průměr liší od "správného průměru". Tak bych věřil webu. Jako bych nic nenapsal:).

**Comment by jankrcal** [comment]
Co se tyce chyby, v grafice: zrovna grafiky z tohoto datasetu jsou pouzite na ceske Wikipedii i na dalsich mistech.

Z tohoto pohledu jsem pro zarazeni opravy na seznam ukolu grafiku a zverejneni opravy ASAP (tedy necekat na uplna data za rok 2019) a transparentni komunikaci toho, ze jsme tam meli (drobnou) chybu skrz https://faktaoklimatu.cz/aktuality.

Snadno se muze stat, ze ASAP stejne znamena leden 2020 a tudiz tam budeme mit i kompletni data za 2019, to ale nic nemeni na tom, ze bych tu aktualizaci chtel transparentne komunikovat.

Prosim @ondraspribyla o nazor.

**Comment by jankrcal** [comment]
(pro uplnost, je to https://cs.wikipedia.org/wiki/Globální_oteplování_v_Česku)

**Comment by jankrcal** [comment]
@Keramadohal Tak jsem konečně do tabulky doplnil výpočet v R:
https://docs.google.com/spreadsheets/d/1kd3BvkzVTNUV799pldht9YLGGHImREl70LuIX2koYS8/edit#gid=161963639

Přijde Ti to tak ok?

V hlavní tabulce jsem označil šedým textem řádky, kde p-hodnota je příliš velká. Je nějaký standardní způsob, jak toto označovat?

**Comment by Keramadohal** [comment]
Za mě supr :-) Po domluvě jsme doplnili poznámku ke statistické významnosti. Díky!

Pozn.: Po aktualizaci dat za rok 2019 bude potřeba přepočítat p-hodnoty a zkontrolovat statistické významnosti, jestli se některý měsíc náhodou nezmění.

**Comment by jankrcal** [comment]
Pořád nejsou data za prosinec, takže tohle issue bohužel o víkendu neposuneme.

**Comment by jankrcal** [comment]
Dvě dobré zprávy: 
 - Doplnil jsem do dat teploty ČR za prosinec a průměr za celý rok 2019.
 - Když se do lineárního trendu přidal rok 2019, vyšlo oteplení od roku 1961 opět 2 stupně :) Přesněji 1,98.
https://docs.google.com/spreadsheets/d/1kd3BvkzVTNUV799pldht9YLGGHImREl70LuIX2koYS8/edit#gid=2143879769

Přijde mi nutné opravit hlavní grafiku nárůst teploty o 2.0 C. Moc bych si přál otevřeně komunikovat, že jsme tam měli chybu v teplotě roku 1961, ale že z vyznění se nic nemění.

Otázka na priority: 
 - chceme aktualizovat i všechny další grafiky z tohoto datasetu?
 - Přidal jsem do datasetu sheet Shrnuti 2019, kde je aktualizovaná i sekce B.4, ze které se tahají ty další grafiky. Zaráží mě, jak nestabilní jsou tato data (vlastně pochopitelně, průměr z posledních 5 let i lineární trend nad měsíčními průměry bude nutně hodně skákat). 
 - I z tohoto důvodu navrhuju ty další grafiky neaktualizovat. (naším cílem u těchto grafik koneckonců není dodat bulletproof data jako spíš na datech ukázat nějaký trend)
 -> @Keramadohal Máš na to prosím názor?

**Comment by jankrcal** [comment]
Ještě komentář, podle dat ČHMÚ byl rok 2019 druhý nejteplejší rok od roku 1961, hned po roce 2018.

Toto by se dalo prodat do newsletteru, twitteru, apod.
(některá média už to probírala, ale v mainstreamu spíš málo)

**Comment by Keramadohal** [comment]
@jankrcal Probrali jsme to teď s @ondraspribyla a @kikinna a shodli se přesně na tom, co píšeš. Ty další infografiky jsou jen ilustrační pro detail, takže je teď není třeba aktualizovat.

@kikinna Aktualizuje https://faktaoklimatu.cz/infografiky/teplota-cr
[] Doplnit rok 2019
[] Opravit hodnotu roku 1961

@jankrcal Je to všechno? Jestli jo, tak tady tento řádek pls smaž ;-)

**Comment by kikinna** [comment]
@jankrcal @Keramadohal @ondraspribyla Prosím o kontrolu. 

![Průměrné roční teploty v ČR 1961-2019 v2 0_teplota-cr](https://user-images.githubusercontent.com/11555522/73678932-b8b53980-46b9-11ea-90a8-9e9c6028bae3.png)

Pokud je vše v pořádku, tak [tady ](https://www.dropbox.com/sh/ee6yu8evygtrfwe/AACwy0sQat4rC5KKuPWsj0g-a?dl=0)je odkaz na updatované grafiky (trochu jsem teď vypadla z organizace grafik na gitu, tak pokud nevadí, nechám to na někom z vás)

**Comment by ondraspribyla** [comment]
Za mě je to v pořádku. Dneska potřebuju ještě řešit další maily, ale zítra
bych to mohl zkusit nasadit...

O.

**Comment by jankrcal** [comment]
Za mě taky v pořádku, díky!

Ondráši, připravil jsem ten nový spreadsheet ke zveřejnění (smazal Rozpracováno z názvu a zamknul jednotlivé listy). Pokud se k tomu nedostaneš, klidně to zítra / pozítří nasadím. Stačí napsat.

**Comment by Keramadohal** [comment]
@jankrcal, @ondraspribyla : V tom novém datasetu (včetně 2019) máme pořád u měsíčních charakteristik napsáno jen do 2018. A v té složce vidím několik souborů Teplota ČR. Můžete to prosím nějak uklidit, kdo víte, který je který?

https://docs.google.com/spreadsheets/d/1pNBmfQbz6QKAl9nLc5RnoLrJMFrCSxzk_KOY4Ns7xTY/edit#gid=979818322

https://docs.google.com/spreadsheets/d/1kd3BvkzVTNUV799pldht9YLGGHImREl70LuIX2koYS8/edit#gid=979818322

https://docs.google.com/spreadsheets/d/14eph67uGIQJgEBSmvWAufdRY49sI3JFq9G9_lH8G7h4/edit#gid=0

**Comment by Keramadohal** [comment]
Jo a tento dataset se ještě nějak používá nebo se může někam uklidit?

https://docs.google.com/spreadsheets/d/14eph67uGIQJgEBSmvWAufdRY49sI3JFq9G9_lH8G7h4/edit#gid=0

**Comment by ondraspribyla** [comment]
Opraveno, vyčištěno. Udělal jsem Pull Request, který předělává link na aktuání dataset.
