### ISSUE TITLE
Korektura finálního datasetu: teplotní anomálie svět

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#238]
https://drive.google.com/open?id=1dIK4lqpfGxr0Ea_KT_WmR6GpB2nc2Y9ylYf_3TBu95M

**Comment by jankrcal** [comment]
Upravený dataset https://docs.google.com/spreadsheets/d/1mYBzne9T_tVpjNFmBuv1e6tNlUAVtADoQNGRJjuiyE4/edit#gid=979818322

Prosím Ondráše o rychlou korekturu, abych to mohl zveřejnit.

**Comment by ondraspribyla** [comment]
Za mě dobrý - jen v tabulce vstupních dat jsem si všiml chybějícího políčka
únor 1901. To je přepodokládám omyl, ale chybí i v současných finálních
datech.
Mohl bys zkontrolovat, zzda chybí i v původním datasetu?

Přehodíš tabulku do finální verze?
Pak hotovo a můžem zavřít issue..

**Comment by jankrcal** [comment]
V původních datech únor 1901 nechybí. Ale těžko se to ověřuje, protože ta data na uvedeném linku (https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.txt) se změnila.

Nejen, že (pochopitelně) přibývají další měsíce, ale všechny údaje jsou maličko jiné (řádově o setinu stupně různými směry). V updates mají nedávnou změnu na nový dataset (ale ty linkuješ už ten nový), nic jiného podezřelého tam nevidím.

**Otázka**:
Chceme
 a) aktuální data (a tím pádem předělat grafiku)?
 b) nechat původní data (kde chybí únor 1901?
 c) nechat původní data a doplnit únor 1901 z aktuálních dat?

Možnost c) mi přijde metodicky nejmíň čístá (byť nijak neovlivní vyznění dat). Nejčistší mi přijde možnost a), ale neodhadnu kolik je to práce pro grafiky (navíc dělat opravu, které si nikdo nevšimne je trochu úmorné). Navíc nemáme garanci, že se nám data opět nezmění pod rukama, takže ta čistota je trochu efemérní. Možnost b) mi přijde pragmatická volba :)

V novém dataset jsem pracovně aktualizoval data na aktuální (možnost a), abych viděl rozdíl v grafu (když to dost zkoumáš, jde to vidět). Není problém se vrátit v historii úprav k předchozímu stavu (varianta b)).

**Comment by ondraspribyla** [comment]
...jen pro úplnost, doplňuju, co jsme si s Jeňou řekli osobně:
Teplotní data ponecháme zatím bez zásahů. Někdy koncem ledna nebo v únoru
2020 budeme mít doplněná data za rok 2019, tak je použijeme a rovnou
aktualizzujeme všechny grafiky a datasety.
