### ISSUE TITLE
Korektura finálního datasetu: koncentrace CO2

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#239]
https://drive.google.com/open?id=1fV9lD8vdVRpijeswxnuqDnbRQOXayiP_mTLZvDOflmQ

**Comment by jankrcal** [comment]
Koukám na studii EPICA a na konci README davaji:

NOTE:  These data have been revised for an analytical bias as described
by Bereiter et al. 2015.  Please see the revised EDC and Antarctic
composite CO2 records at:  http://www.ncdc.noaa.gov/paleo/study/17975

Je důvod, proč nepoužíváme ta upravená data, např. zde?
https://www1.ncdc.noaa.gov/pub/data/paleo/icecore/antarctica/antarctica2015co2composite.txt

**Comment by ondraspribyla** [comment]
@jankrcal Nevím proč jsem si toho NOTE nevšiml... 
Správně bychom tedy měli použít ty revisited data. Bude to nutně znamenat korekce v datasetu, možná korekce grafiky (ale nevím, jak velký je ten bias, tedy zda bude zřetelně viditelný ten posun dat...)

Mám si to vzít jako práci na vánoce, nebo ti mám tyhle korekce dat nechat?

**Comment by jankrcal** [comment]
Ten dataset muzu v novem formatu pripravit s revisited daty sam, to pro me neni moc prace navic.

Pak muzem kouknout na rozdil v grafech a probrat, jestli to potrebuje novou grafiku. Pokud ano, ocenim, kdyz to zkoordinujes s grafiky.

**Comment by jankrcal** [comment]
Poznámky na osobní debatu:
 - Hotový upravený dataset: https://docs.google.com/spreadsheets/d/10Ku7uOPfDmbvrzWFtvlqvZ-ImWbS6QDHrxKtRIyO4r4/edit#gid=979818322
 - Myslím si, že rozdíl člověk okem nepozná, ale to by se ta grafika musela udělat, aby to bylo vidět :)
 - Jen nerozumím tomu, proč je v současné grafice rozsah ledových a meziledových dob 170 - 280 ppm, když maximum do roku 1750 je 299ppm.

**Comment by jankrcal** [comment]
Shoda na dalších krocích:
 - jsem garant zveřejnění, domluvím se sám s grafiky na úpravách příp. navrhnu drobné úpravy průvodního textu;
 - v grafice upravme maximum na 300 ppm a v doprovodném textu vysvětleme, proč je zajímavá hodnota 280 ppm (preindustriální hodnota) a proč je zajímavé, že je to relativně blízko historickému maximu.

**Comment by jankrcal** [comment]
Kiko, můžeš prosím v grafice upravit horní hodnotu na 300 ppm? (ze současných 280 ppm)

**Comment by jankrcal** [comment]
Ještě prosím u úpravu současné hodnoty na 411 ppm.

**Comment by kikinna** [comment]
@jankrcal Jéni, jak moc se změnil dataset? Ptám se kvůli verzování grafik. Při změně vstupních dat měníme verzi z verze 1.x na 2.x. Já to považuji teda za byť malou, ale datovou změnu, tak zvyšuji verzi. Je to ok?

**Comment by jankrcal** [comment]
Ano, zvýšení verze na 2.x je za mě ok.

Zapomněl jsem doplnit, co jsem Ti říkal těsně před odjezdem: prosím o smazáni datového bodu roku 2019. Poslední hodnota tedy bude rok 2018, který by měl mít (zaokrouhlenou) hodnotu 406 ppm.

Ještě jedna věc, celý dataset se maličko změnil v části rok -800 000 -- rok 0.
Pokud je to netriviální práce, můžeš to nechat být, změny by měly být zanedbatelné.
Pokud je to málo práce, můžeš ta data znovu natáhnout z nové tabulky https://docs.google.com/spreadsheets/d/10Ku7uOPfDmbvrzWFtvlqvZ-ImWbS6QDHrxKtRIyO4r4/edit#gid=979818322?

 - data -800 000 až 0 jsou na listu EPICA, 
 - data 0 až 2018 jsou na listu SCRIPPS (neměněno kromě smazání údaje 2019, údaj 2018 se změnil na druhém desetinném místě)

**Comment by kikinna** [comment]
@jankrcal Je to takhle ok? (Pokud v datech -800 000 až 0 nejsou žádné výraznější změny, tak odkládám úpravu. Pak se podívám na ty data. Otázka je, jestli by se to vůbec projevilo vizuálně.)

![Koncentrace CO2 v2 0_koncentrace-co2](https://user-images.githubusercontent.com/11555522/72731401-f54e4480-3b93-11ea-9dfe-9af9deb51d84.png)

**Comment by jankrcal** [comment]
Je to tak super, díky moc!

Souhlasím s odkladem zbytku, nemá to vysokou prioritu.

Kde najdu výsledné PDF, abych to mohl nasaditna web?

**Comment by kikinna** [comment]
Opravené to má už @mukrop a bude to nasazovat na net společně s ostatníma
grafikami a fixem červených okrajů)

**Comment by jankrcal** [comment]
Aha, @mukrop, potřebuju s tím současně provést commit, který je ve větvi
https://github.com/faktaoklimatu/web/tree/koncentrace-co2-vycisteny-dataset.

Můžeš mi prosím nějak předat to upravné pdf k co2 koncentraci, že bych ho přidal do té své větve, ať to zůstane atomické a přehlednější?

**Comment by kikinna** [comment]
Najdeš ty soubory u issue #339

**Comment by mukrop** [comment]
Dnes sa k tomu nahadzovaniu nedostanem. PDF su linkovane z posledneho komentara tu: https://github.com/faktaoklimatu/web/issues/339

Ak by si mal cas, mozes nahodit aj tie ostatne do vetvy `fix-rozmery-infografik` a urobit pull request.

**Comment by jankrcal** [comment]
Super, děkuju, práce hotova, jen chybí merge PRs.

**Comment by ondraspribyla** [comment]
PR aprooved. Zavírám. Díky za preciznost :-)
