### ISSUE TITLE
Body zlomu: zapracovat Jeňovy připomínky ke struktuře

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#242]
První krok: sepsat připomínky :)

**Comment by jankrcal** [comment]
Návrhy ke struktuře hlavních textů na grafikách:
https://docs.google.com/document/d/1MHvTtiDhjWNltTLnUPZzt3lioCZIUQArnjyj4epAk0I/edit

**Comment by jankrcal** [comment]
Ondráši, můžeš se na to prosím podívat, jestli s tím takto souhlasíš, příp. kterékoliv úpravy a komentáře zavrhnout?

**Comment by jankrcal** [comment]
Ondráš s návrhem souhlasí (diskutovali jsme offline).

Prosím o zapracování do grafiky.

**Comment by jankrcal** [comment]
Upravil jsem příslušným způsobem dataset: https://docs.google.com/spreadsheets/d/1zTZ74HuIG1_5labOaoKs-07WOl7YfUEWaOEjvl3bvLQ/edit#gid=0

Ondráši, můžeš na to prosím kouknout?

 - Nechal jsem tam všechny texty. Některé z nich nemají zdroje (vždy v úvodu grafiky). Vyřešil jsem to tak, že jsem dal více odstavců do jedné buňky a tak to tak není vidět :) Přijde mi to lepší v současné struktuře tam mít kompletní text. Pokud nesouhlasíš, klidně promaž odstavce, které nemají zdroje.
 - Je to výrazně méně barevné, pokusil jsem se přiblížit co nejvíce jednotnému vizuálnímu stylu ostatních datasetů.

**Comment by ondraspribyla** [comment]
Zavírám. Hotovo.
