### ISSUE TITLE
Body zlomu: rozepsat názvy článků v datasheetu

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#243]
Datasheeet obsahuje hrubé zdroje (IPCC, Nature, Wikipedia) + odkazy na konkrétní články / dokumenty.

Bylo by skvělé, aby v tabulce byl další sloupec "Dokument", kde bude přímo vidět názvy článků / dokumentů, na které odkazujeme (ideálně v nějaké odlehčené formě, jak se citují vědecké články).

**Comment by jankrcal** [comment]
Přiřazuju Ondrášovi, aby našel někoho kdo to udělá nebo zavřel, pokud to nebudeme dělat.

**Comment by lilyjoe19** [comment]
Ahoj @jankrcal , prečo si myslíš, že to je dôležité urobiť? Včera sme sa na to s Ondrášom pozerali a linky odkazujú na konkrétne zdroje informácií, tak nám to prišlo celkom self-explanatory. Ale to samozrejme neznamená, že to tak majú všetci, preto ma zaujíma, aká je tvoja motivácia k tejto zmene :)

**Comment by jankrcal** [comment]
Tohle za mě byla spíš drobnost, takže se nehodlám vysilovat velkým přesvědčováním :)

Jen me prislo skoda, ze clovek musi link otevrit, aby videl, co je to za stranku. Nejvic mi to vadilo u zdroju "EN Wikipedia", kde na prvni pohled nevidim, k jakemu pojmu na wikipedii to odkazuje.

Tolik na vysvetleni. Klidne to zavrete.

**Comment by VladaSedlacek** [comment]
Přidal jsem sloupec Heslo/Upřesnění, kde je detailnější lokace citace. Je to v kopii finálního dokumentu: https://docs.google.com/spreadsheets/d/1J9CQ1Sni_1zIUJn6iaXFxtKFVRqS-89jPONuq-Zw1c0 .

**Comment by ondraspribyla** [comment]
@VladaSedlacek zkus prosim jeste doplnit tyhle odkazy do zalozek kryosfera a atmo /oceanska proudeni

**Comment by VladaSedlacek** [comment]
> @VladaSedlacek zkus prosim jeste doplnit tyhle odkazy do zalozek kryosfera a atmo /oceanska proudeni

Hotovo (opět na https://docs.google.com/spreadsheets/d/1J9CQ1Sni_1zIUJn6iaXFxtKFVRqS-89jPONuq-Zw1c0/).

**Comment by ondraspribyla** [comment]
hotoov
