### ISSUE TITLE
Body zlomu: rozdělit datasheet na jednotlivá tvrzení

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#244]
Současná struktura datasheetu je: pro každý odstavec textu ukazujeme seznam citací a jejich zdrojů.

Mnohem čitelnější pro konzumaci mi přijde: pro každé tvrzení dodáme jednu citaci a zdroj. Tedy rozdělit odstavce na jednotlivá tvrzení, pro která odkazujeme zdroje. Někdy je tvrzení přímo věta z textu na grafice, někdy by bylo dobré uvést zvlášť větu a zvlášť tvrzení, které je mírně odlišné.

*Příklady:*
věta: Hodnoty oteplení jsou uváděny vzhledem k předindustriální době. 
tvrzení: Předindustriální dobou rozumíme období 1850 - 1900.
odkaz: IPCC, ...

věta = tvrzení: Současná hodnota globálního oteplení je přibližně 1 °C.
odkaz: IPCC, ...

**Comment by jankrcal** [comment]
Přiřazuju Ondrášovi, aby našel někoho kdo to udělá nebo zavřel, pokud to nebudeme dělat.

**Comment by ondraspribyla** [comment]
Příliš velká práce, která není prioritní. zavírám
