### ISSUE TITLE
ořezaná atribuce u infografik

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#264]
u některých infografik chybí, že jsou naše, např. zde: https://faktaoklimatu.cz/infografiky/teplota-cr - ale týká se to vícero. při té příležitosti by zároveň měla být všude verze.

TODO:
- [ ] odsouhlasit, že to tak chceme @mukrop @ondraspribyla 
- [ ] upravit všechny infografiky, kde není faktaoklimatu.cz, aby to tam bylo @kikinna (možno předat dalším grafikům, neznám jejich loginy :/ - jak verze, tak atribuce

související: #254

**Comment by mukrop** [comment]
Nechyba, je to tam. Ale na webe je to zamerne orezane pri zobrazovani (po rozkliku a pri stahovani to mas v plnom formate aj s okrajmi a patickami). Verzie tiez vsade uz su.

**Comment by crysman** [comment]
brr, ne tak rychle

1. aha, OK, záměrného ořezu jsem si nevšiml, pardon
1. ten ořez se mi nelíbí - zobrazujeme něco jiného, než to je - při použití PrntScr apod. to zanikne, navrhuju neořezávat
1. na české Wiki jsou tedy špatné verze, a je třeba to vyměnit

**Comment by mukrop** [comment]
Orez sme diskutovali celkom dost uz davnejsie tak na prelome jula a augusta (#71, #80). Mozme to znova prediskutovat, ale osobne mi pride, ze aktualne mozme travit cas aj uzitocnejsie.

Infografiky na Wiki sa mozu vymenit, bude to k dobru. Ak sa ti chce, mozes to dohodnut (ak sa nemylim, tak aktualizaciu medialnych suborov musi robit majitel).

Kazdopadne by som tym padom toto issue rozdelil na dve -- maju rozny proces riesenia a su to veci, ktore sa daju uzavriet nezavisle na sebe.

**Comment by crysman** [comment]
issue rozděleno, čisté wikiupdate issue je zde https://github.com/mukrop/faktaoklimatu/issues/280

**Comment by mukrop** [comment]
Odstraňovat ořezy je aktuálně zbytečně složité – web i grafici s tím už počítají, řeší se tím duplikace nadpisů i zdrojů, ...
Předci je zavírám.
