### ISSUE TITLE
Zjednotit rozměry a okraje grafik

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#272]
Body zlomu maju iny rozmer, Kika chcela menit spatne aj ostatne (a bude podls toho potom treba mierne upravit web). Aktualny stav je, ze body zlomu maju urezane podnadpisy a paticky.

**Comment by protivinsky** [comment]
@mukrop stare infografiky jsou nekde cachovane a zobrazuji se stale stare verze se spatnym orezanim. Napriklad https://faktaoklimatu.cz/infografiky/teplota-cr je spatne orezana (a v podstate vsechny ostatni teplotni grafiky tez). Vsimli jsme si toho predevcirem s @ondraspribyla 

Stale se mi na webu zobrazuje verze 1.0, zatimco pri lokalnim checkoutu vidim opravenou verzi 1.1. Protoze orez je nastaveny pro nove verze, vidim na webu uriznutou polovinu nadpisu z infografiky. Puvodne jsem si myslel, ze mam akorat stare verze nacachovane v prohlizeci, ale nepomohlo ani smazani dat prohlizece, rovnez pres jiny pocitac se mi to nacita rozbite. Proto predpokladam, ze nekde musi byt neaktualizovana cache nekde na strane serveru? Muzes to prosim zkontrolovat?

Mimochodem, v nove verzi obcas vyleza diakritika na spodni strane orezu infografiky. Napriklad u infografiky/teplota-cr vidim zretelne na prave strane hacek a carku z ČHMÚ, obcas je cast diakritiky patrna i na leve strane. Je mozne orez malinko zvetsit, abychom se te diakritiky zbavili? Diky.

**Comment by mukrop** [comment]
Uff, moja chyba. Neskontroloval som dosledne zostavnie webu. Premazal som cache a nechal zostavit znova, aby sa to vycistilo. Cache prehliadaca by zostavat nemala, ale vyskusaj.

Co sa tyka diakritiky – na to sa pozriem, ale az niekedy neskor (samotne obrazky som riesil urgentne hned).

**Comment by protivinsky** [comment]
Diky, uz je to ok. Diakritika je relativne nepodstatny detail, rozhodne to nech na pozdeji.
Hezke svatky!

**Comment by mukrop** [comment]
Vyřešeno, čeká v pull requeste.
