### ISSUE TITLE
Koncentrace CO2 - různá místa

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#275]
Idea: převzít graf, který zobrazuje roční průběh koncentrace CO2 na růzzných měřících místech planety. 
Je to důležitý graf? Data a související graf mohou umožnit učitelům učit podrobněji o průbehu ročním CO2, zzároveň ukazují přesnost/rozptyl hodnot, který dostáváme.  
https://www.esrl.noaa.gov/gmd/ccgg/trends/gl_trend.html

**Comment by ondraspribyla** [comment]
![global_trend](https://user-images.githubusercontent.com/17317136/70849879-9c98d700-1e84-11ea-99c8-297ee0153329.png)

**Comment by mukrop** [comment]
Přesunuto na wiki.
