### ISSUE TITLE
Body zlomu: zlepšení čitelnosti

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#276]
u https://faktaoklimatu.cz/#/sekce/budoucnost vypadá úvodní odstavec "co jsou body zlomu" furt stejně, takže ho jako čtenář u další grafiky už nečtu, a tím míjím i info v tom dalším odstavci "body zlomu v...."

Návrh:
**prohození pořadí - obecné info co to je až na druhém místě**

**Comment by lilyjoe19** [comment]
mne sa zase ten jednotný začiatok páči, pretože je to taký spájací motív tých infografík :)

sa ale do tejto issue přicmrdnem so svojimi návrhmi, čo by sa v textoch infografík dalo (hodilo) zmeniť. prosím @jankrcal , aby sa mrkol sem: https://drive.google.com/open?id=1Otd-ixjfs3hvxHljwiEwWBk2oIDSj7Al a nejak sa k tomu kvalifikovane vyjadril

**Comment by jankrcal** [comment]
ad crysman: Rozumím problému :) Mně přijde, že když prohodím pořadí, tak to zase zlehka nedává smysl, mluvit prvně o konkrétních bodech zlomu a pak obecně definovat, co to je. Nepomohlo by, kdyby mezi ty dva odstavce grafici vykouzlili trochu větší mezeru? Nebo ten druhý odstavec jakkoliv jinak vizuálně zvýraznili?

ad lilyjoe19: Omlouvám se za neaktivitu. Kouknu na to.

K oběma bodům si potřebuju ale prvně vyjasnit, @ondraspribyla, je vůle (a energie grafiků) teď v nejbližší době dělat doladěnou verzi těchto grafik?

**Comment by ondraspribyla** [comment]
po diskusi s Kikou o kapacitách grafiků a s vědomím, že úpravy jsou sice dobré ale atím NICE-TO -HAVE (četl jsem poznámky od Lenky) bych issue teď na něějakou dobu odložil,... nové verze grafik se asi časem budou hodit.

**Comment by ondraspribyla** [comment]
Priority projektu jsou sřetelně jinde. zavírám.
