### ISSUE TITLE
nefunkční odkazy

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#278]
%%MSG: trying to find something...
Found 2 broken links.

https://energynautics.com/content/uploads/2016/11/CV_Martensen_english.pdf
https://energynautics.com/content/uploads/2016/11/Publications_Ackermann.pdf

FINISHED --2019-11-13 13:16:22--
Total wall clock time: 3m 22s
Downloaded: 172 files, 12M in 16s (739 KB/s)
%%MSG: looking for FIXMEs...
%%-
faktaoklimatu.cz/slovnik:        
%%-

%%--
%%Wed, 13 Nov 2019 13:13:01 +0100
%%watchdog.sh v.1.0 by crysman(e)2019

**Comment by crysman** [comment]
update: po pěti dnech stále nefunguje

**Comment by mukrop** [comment]
Dival si sa, cim to je? Problem so servrom? Preskladali stranky? Odstranili obsah?

**Comment by crysman** [comment]
tentokrát ne (narozdíl od minula, kde jsem to celé zařídil) - nebudu to teď řešit, nemám kapacitu, dávám to sem, aby to někdo někdy opravil

**Comment by mukrop** [comment]
Jasne, v pohode. Prave som zistoval, ci to je len report, alebo si to uz aj trochu skumal.

**Comment by crysman** [comment]
nové rozbitosti:

> %%MSG: trying to find something...
> Found 1 broken link.
> 
> https://www.mzp.cz/C1257458002F0DC7/cz/parizska_dohoda/$FILE/OEOK-Cesky_preklad_dohody-20160419.pdf
> 
> FINISHED --2019-11-26 13:16:27--
> Total wall clock time: 3m 27s
> Downloaded: 177 files, 12M in 18s (669 KB/s)
> %%MSG: looking for FIXMEs...
> %%-
> faktaoklimatu.cz/slovnik:        
> %%-
> 
> %%--
> %%Tue, 26 Nov 2019 13:13:01 +0100
> %%watchdog.sh v.1.0 by crysman(e)2019

**Comment by mukrop** [comment]
Napisal som na MZP.

**Comment by lilyjoe19** [comment]
ďalšie nefunkčnosti našiel Jeňa, viď https://github.com/mukrop/faktaoklimatu/issues/314

**Comment by mukrop** [comment]
Len doplnam: Z odkazov, co reportoval Jena (ako pise Lenka) je vsetko funkcne okrem prekladu Parizskej dohody na strankach MZP, a ta tu uz je (a je v rieseni).

**Comment by crysman** [comment]
znovu nefunkční věci:

http://glopolis.org/wp-content/uploads/Infolist-sit-bez-uhli.pdf
http://glopolis.org/wp-content/uploads/Czech-Grid-Without-Coal-By-2030_fin.pdf

(hlásí watchdog už vícero dnů)

**Comment by SklenarOldrich** [comment]
Tímto prosím o náhradu za tyto (funkční) odkazy:

https://frankbold.org/sites/default/files/publikace/infolist-sit_bez_uhli.pdf
https://frankbold.org/sites/default/files/publikace/czech_grid_without_coal_by_2030_fin_0.pdf


> znovu nefunkční věci:
> 
> http://glopolis.org/wp-content/uploads/Infolist-sit-bez-uhli.pdf
> http://glopolis.org/wp-content/uploads/Czech-Grid-Without-Coal-By-2030_fin.pdf
> 
> (hlásí watchdog už vícero dnů)

**Comment by SklenarOldrich** [comment]
Opět prosím o náhradu za tyto funkční linky:

https://energynautics.com/content/uploads/CV_Martensen_english.pdf
https://energynautics.com/content/uploads/Publications_Ackermann.pdf

Díky!

> %%MSG: trying to find something...
> Found 2 broken links.
> 
> https://energynautics.com/content/uploads/2016/11/CV_Martensen_english.pdf
> https://energynautics.com/content/uploads/2016/11/Publications_Ackermann.pdf
>

**Comment by mukrop** [comment]
Aktualne vsetko OK.
