### ISSUE TITLE
Aktualizovat infografiky na Wikipedii

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#280]
TODO:
- [ ] Na všech Wikistránkách, kde jsou naše infografiky vyměnit za nejnovější verze. POZOR, grafici dělají updates většího množství infografik, dokončí nejpozději do 20.11.2019

vysvětlení: např. zde (a asi i jinde na Wiki) https://cs.wikipedia.org/wiki/Glob%C3%A1ln%C3%AD_oteplov%C3%A1n%C3%AD_v_%C4%8Cesku jsou staré verze našich infografik

PS: kontakt [na Wikipedistu](https://cs.wikipedia.org/wiki/Wikipedista:Jirka_Dl) je mail jiri.dlouhy@czp.cuni.cz

**Comment by lilyjoe19** [comment]
@kikinna , sú prosím ťa už všetky infografiky updatované alebo sa bude ešte niečo upravovať? môžem sa ozvať pánovi Wikipedistovi? :)

**Comment by mukrop** [comment]
Este cakat, bude sa menit pomer stran (to caka na mna).

**Comment by ondraspribyla** [comment]
@LenkaSedlackova Updatovali jsme tri grafiky ktere souvisi s teplotami v CR: graf rustu teplot, trendy mesicu a mesicni teploty. Můžeš napsat prislušným wikipedistům?

**Comment by LenkaSedlackova** [comment]
@ondraspribyla pokúsim sa v najbližších dňoch

**Comment by LenkaSedlackova** [comment]
napísala som Wikipedistom https://cs.wikipedia.org/wiki/Wikipedista:Pavouk (do jeho diskusie) a https://cs.wikipedia.org/wiki/Wikipedista:Jirka_Dl (mail)

**Comment by LenkaSedlackova** [comment]
Dobrý den,
asi bychom mohli dát nějakou kategorii pro infografiky z Fakta o klimatu, aby se jednoduše daly najít při aktualizaci. Kouknu na to.

Jirka Dl

**Comment by crysman** [comment]
aktualizace se zjevně už děje:
https://commons.wikimedia.org/wiki/File:Srovn%C3%A1n%C3%AD_pr%C5%AFm%C4%9Brn%C3%A9_teploty_v_%C4%8CR_v_jednotliv%C3%BDch_m%C4%9Bs%C3%ADc%C3%ADch.svg

každopádně, nelíbí se mi, že tam ořezávají ty verze, napsal jsem proto uživateli _Pavouk_:
https://commons.wikimedia.org/wiki/User_talk:Pavouk

**Comment by LenkaSedlackova** [comment]
čaute,
FYI, Wikipedisti dnes začali riešiť kontrast infografík:
https://cs.wikipedia.org/wiki/Diskuse_s_wikipedistou:Jirka_Dl#GO_a_graf_CO2_za_650_000_let_na_%C3%BAvod
uvidíme, k akému záveru prídu a čo z toho bude pre nás vyplývať

**Comment by ondraspribyla** [comment]
Díky za echo, ozvu se jim

O.

**Comment by crysman** [comment]
Tak já nevím, já mám prostě totálně bad karmu na Wiki - už je z toho zase konflikt:

https://commons.wikimedia.org/wiki/User_talk:Pavouk#ne/o%C5%99ez%C3%A1vat_infografiky_faktaoklimatu.cz

já to nechápu, asi dělám něco blbě v komunikaci (co??)

Jsem totálně otrávený a mám chuť celé slavné Wikipedisty nakopat dořiti. To je přesně to, co oni dělají - chytají se nepodstatností a dlouhosáhle argumentují metapostupy a subpahýly pahýlů a odvádějí pozornost na zcestí... OMG...

[Odepsal jsem mu stručně a pouze k věci](https://commons.wikimedia.org/wiki/User_talk:Pavouk#crysman_#2), bez emocí a zbytečností, tak uvidíme.

Na Wikipedii nic přispívat a upravovat nemůžu - a tedy nebudu, nestojí mi to za ten emoční masakr, který to ve mě vyvolává - stala se z toho příliš VIP věc, pro mě nedostupná, škoda, bývalo to jiné, svobodnější, přístupnější. Škoda - obojího - jednak změny Wiki (za mě k horšímu), druhak toho, že to nezvládám. Mrzí mě to. [Zde historie, proč](https://cs.wikipedia.org/wiki/Wikipedie:%C5%BD%C3%A1dost_o_koment%C3%A1%C5%99/Destruktivn%C3%AD_z%C3%A1sahy_editor%C5%AF,_sm%C4%9B%C5%99ov%C3%A1n%C3%AD_a_filosofie_Wikipedie_jako%C5%BEto_otev%C5%99en%C3%A9_encyklopedie,_nadu%C5%BE%C3%ADv%C3%A1n%C3%AD_subpah%C3%BDlizace) (jen pro zájemce o detaily - velmi bonusové jenom).

**Comment by jankrcal** [comment]
FYI, tato diskuse issue je veřejná, crysmane :)

Podle mě jsi crysmane v oné diskusi trochu agresivní v požadování něčeho, na co v principu nemáš "právo", např:
> Píšeš tam "nadbytečné údaje" - já s tím nesouhlasím, že jsou "nadbytečné", a žádám tímto o re/upload originálů. 

A tak uživatel Pavouk reaguje defenzivně. Tento člověk do toho asi vkládá dost času a má oko pro detaily (např. ručně fixnul typografii u https://commons.wikimedia.org/wiki/File:Pr%C5%AFm%C4%9Brn%C3%A1_ro%C4%8Dn%C3%AD_teplota_v_%C4%8CR_1960-2019.svg). A z pohledu uživatele wikipedie je verze infografiky podle mě vskutku dost irelevantní.

Nedalo by se ta verze vyplnit někam do metadat toho souboru, aby to bylo vidět po rozkliknutí?

**Comment by crysman** [comment]
Ano, vím, že je veřejná, jsem si toho vědom, přesto jsem si dovolil trochu exprese, jako sám za sebe, trochu ukázat, že jsou věci, co mě štvou.

Díky, Jeňo, za ZV. Trochu jsem to tam zjemnil ještě - nyní jsem se zněním spokojen.

Buď jak buď, vypadá to, že brzo to tu bude na zavření issue konečně :)
