### ISSUE TITLE
schůzka k vyřešení ticketů "k diskuzi"

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#281]
z debaty s @ondraspribyla vyplynulo, že zorganizuje nějakou schůzku na toto téma - čili protřízení a projítí [věcí "k diskuzi"](https://github.com/mukrop/faktaoklimatu/issues?q=is%3Aopen+is%3Aissue+label%3A%22na+diskuzi%22), kterých přibývá a zůstavají bez rozhřešení.

**Comment by mukrop** [comment]
Vyriesime pri cisteni issues v priebehu dneska.
