### ISSUE TITLE
námět na nový druh infografiky: TEN WORDS

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#282]
Takto nějak by mohl vypadat nový druh infografiky:
![image](https://user-images.githubusercontent.com/5269350/68797702-5c5ff200-0655-11ea-9e5a-36ed52dd06be.png)

Námět zde na straně 3: https://www.climatechangecommunication.org/wp-content/uploads/2019/10/America_Misled.pdf

Ještě jsem to celé nečetl, ale vypadá to na zajímavé a přínosné čtení.

Tato studie částečně odpovídá na toto: https://github.com/mukrop/faktaoklimatu/issues/126

**Comment by kikinna** [comment]
Není to už ten aktivismus, který mi nechceme dělat?

**Comment by crysman** [comment]
no, možná že je, nevím, nejde o to udělat to stejně, je to inspirace na něco takového

proč to já osobně považuju za zajímavé a užitečné:

1. je to velmi  dobře čitelné na první pohled
1. je to stručné, jasné a výstižné
1. ve všech bodech to stojí na vědě, o kterou se tak jako tak opíráme
1. není tam žádný kontroverzní bod
1. je to aktivizační a obsahuje to naději

**Comment by mukrop** [comment]
Přesunuto do nápadů na wiki.
