### ISSUE TITLE
Studie/Grafika: EXXON 

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#291]
STUDIE: Interní zpráva Exxonu o dopadech spalování fosilních paliv na klima - https://insideclimatenews.org/sites/default/files/documents/1982%20Exxon%20Primer%20on%20CO2%20Greenhouse%20Effect.pdf

Zpráva hodnotící aktivity fosilního průmyslu v rámci dezinformačních kampaní - http://www.bristol.ac.uk/news/2019/october/america-misled.html

GRAFIKA K PŘEBRANI Vědecká analýza interních a externích dokumentů Exxonu (peer reviewed) - https://iopscience.iop.org/article/10.1088/1748-9326/aa815f

**Comment by ondraspribyla** [comment]
@setcz tohle by mohla být prácička pro tebe... prostudování a napsání výtahu z  https://insideclimatenews.org/sites/default/files/documents/1982%20Exxon%20Primer%20on%20CO2%20Greenhouse%20Effect.pdf

nemyslím to jako vyloženě zadání práce - jestli chceš, mrkni na to a kdyžtak se přidej k Assignees.

**Comment by ondraspribyla** [comment]
Článek z huffington postu o tom, že uhlený průmysl věděl o klimatické změně už v roce 1966
https://m.huffpost.com/us/entry/us_5dd6bbebe4b0e29d7280984f?guce_referrer=aHR0cHM6Ly90LmNvL00yaGlqeXBWZWM&guce_referrer_sig=AQAAAKTs699fyKXfbqYXH1I3Paqd5lX7Mn7AhUuf81gkgFizENPUDPZqZiwyWxvot7NGREGoPoWiQL9saPWwVNQ7w6lpNDQxYGrPVp8okVsABufPVpd5-rGhx2mCVjHb4_uA3SjdTVLy83w6Q93lU2YCSYEBIJW19e4ZmNfZaOvyUGB8

**Comment by mukrop** [comment]
Přesunuto na wiki.
