### ISSUE TITLE
slovnicek - sklonovani hesel v textu

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#311]
Slovnikove heslo je v textu stranek, kde je pouzito, zobrazeno primo jako "name-short", tedy v prvnim padu a zpravidla s velkym pismenem. Nelze do toho volani hesla {% include glossary.html id='mitigace' %} vlozit i zpusob zobrazeni ve strance? Abych mohl snadno pouzit heslo uprostred vety v jinem padu?

**Comment by JarekParal** [comment]
Podívám se na to.

**Comment by mukrop** [comment]
Vlada za mnou prisiel, ze vraj "nejaky kamarat v zahranici". Mohol rovno povedat, ze ty :D.

**Comment by mukrop** [comment]
@JarekParal Keby si mal dotaz k chcenej funkcionalite, napis.

**Comment by mukrop** [comment]
@JarekParal: @Tasssadar dnes robil vyraznejsie zmeny v chovani slovnika (#401 a #181). Mohli by ste sa dohodnut, ako do toho zapada riesenie tohto issue?

**Comment by JarekParal** [comment]
Ok, proberu to s @Tasssadar. Dostal jsem se do fáze, že jsem schopen vybírat pády, ale není to pěkné řešení. Třeba najdeme s Vojtou (@Tasssadar) lepší řešení.

**Comment by mukrop** [comment]
Nebolo by cistejsie, keby autor v pripade sklonovania pri volani vlozil string, ktory sa ma pouzit a inak by sa by default pouzil ten z definicie? Zda sa mi to mensi overhead ako definovanie jednotlivych padov v slovniku.
(Ale neviem, ako sa to bude zlucovat s novym tagom `<glos>` od @Tasssadar.)

**Comment by Tasssadar** [comment]
S tím `<glos>` tagem se naskytuje docela jednoduché řešení: místo řešení nějakých pádů globálně by se na takovém místě, kde `name-short` z *glossary.yml* neodpovídá, použil extra atribut, něco jako `<glos text="Nekonformní slovíčko">super-slovo</glos>` a místo `name-short` by se vyrenderovalo cokoliv je v `text` attributu.

Bylo by to takhle v pohodě?

**Comment by mukrop** [comment]
Ano, to je presne typ riesenia, ktore som si predstavoval.
@JarekParal: Ako to vidis? (Trochu ma mrzi, ze sa tvoja praca bude musiet prerabat, to je moje maslo na hlave, ze som vas nezosynchronizoval zu v priebehu.)

**Comment by JarekParal** [comment]
Souhlasim, bude to urcite lepší řešení. Asi jsem se s tebou o tom měl pobavit hned na začátku :). Tak tim pádem moje PR neřešme a Vojta to může zapracovat do jeho `<glos>` tagu? @Tasssadar 

Já jsem si alespoň vyzkoušel práci s Jekyllem.
