### ISSUE TITLE
Uhelná komise - obsazení 

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#318]
Grafika by měla přehledně ukazovat obsazení uhelné komise http://www.zelenykruh.cz/na-cem-pracujeme/uhelna-komise

Podklady rozpracovan zde: https://docs.google.com/spreadsheets/d/1wnN4DmlGwKS0c5QgrQOHElbfrPs7hiEWsg1brHvF074/edit?usp=sharing

Další info zde: 
https://www.hnutiduha.cz/aktualne/z-jakych-scenaru-konce-uhli-se-bude-vybirat-uhelna-komise-rozhodne-v-pondeli

Dále článek na Irozhlasu zde: 
https://www.irozhlas.cz/zpravy-domov/uhelna-komise-uhli-clenove-klimaticka-zmena_1909030702_jab

---
Garant obsahu: @ondraspribyla 
Garant grafiky: @kikinna
Graficky zpracovává: @kikinna 

- [x] Dokážeme získat porovnání na uhelnou komisi v Německu? @Keramadohal @jankrcal 
- [x] U všech pracovních skupin (na drive) chybí třetí člen -> jedná se pouze o vizuální oddělené předsedů PS od zbytku členů?
- [x] Podívat se, jestli jsou členové, kteří jsou součástí více PS a přitom nejsou členy komise (to jsem ještě neudělala) @kikinna 
- [x] Zkrácené popisky jednotlivých pracovních skupin @ondraspribyla 
- [ ] Popis hlavního mandátu uhelné komise, co můžeme očekávat a kdy @ondraspribyla 

_Aktuálně rozpracovaná verze infografiky -- mega hrubej draft, kterej spíš sloužil k rozkreslení toho, co máme v datech, abychom na to mohli kouknout vizuálně. Šedé čáry znázorňují, že člen komise je současně členem nějaké PS. Tato verze je vizuálně absolutně neřešná a je tam hodně věcí, které jsou špatně, haha._
![Slozeni uhelne komise-01-01-01-01](https://user-images.githubusercontent.com/11555522/72203840-6fcee400-3471-11ea-9b73-279ad821e01e.png)

**Comment by ondraspribyla** [comment]
Dnes jsem diskutoval grafiku s Jiřím Koželuhem - s rozdělením do kategorií (níže) souhlasil.

Nadkategorie "politici" 
- Vládní politik nebo poslanec PČR
- Krajský politik
- Pracovník ministerstva nebo jiný vysoký úředník

Nadkategorie "Uhelný byznys"
- Majitel nebo předstabitel těžařské či elektrárenské společnosti
- Představitel sdružení průmyslových podniků, nebo jejich odborů

Nadkategorie "Zelení"
- Enviromentalista
- Představitel sdružení firem zabývajících se Obnovitelnými zdroji energie  

- Akademici (

**Comment by Keramadohal** [comment]
Porovnání s Německem řešil @jankrcal, protože víc info je jen v němčině. Je to už zpracované v té tabulce, jen nevím, jestli je to dodělané.

**Comment by jankrcal** [comment]
Pokud jsou kategorie vyse finalni a pokud mate pocit, ze se to muze dostat do grafiky (nebo do doplnujiciho textu), muzu tu tabulku nemecke komise jeste jednou projit a prekategorizovat.

Asi bych to mel zkontrolovat, jak to slozeni analyzoval Nemecky internet, jestli nekde neulitavam.

Jaky je deadline? ;)

**Comment by ondraspribyla** [comment]
@jankrcal porovnání s Německem zatím neřešme. My s @kikinna nejdřív dotáhnem grafický draft a message a vyjasní se, jaká další práce na datech je dál užitečná. Schůzku s Kikou máme v neděli.

**Comment by ondraspribyla** [comment]
Doplněny zkrácené texty k pracovním skupinám i celé komisi (v GSheetu). Pro přehlednost kopíruju i sem: 

**Uhelná kmise je poradní orgán vlády. Hlavním cílem je poskytnout vládě ČR objektivní a v maxímální možné míře konsenuální výstupy ohledně budoucího využití hnědého uhlí v ČR.**

** Pracovní skupina 1. - popis činnosti:** 
* Analýza současného energetického mixu a odhad budoucího vývoje energetiky. 
* Analýza možných scénářů uzavírání uhelných zdrojů a jejich dopadů. 
* Stanovení harmonogramu útlumu využití uhlí. 

Pracovní skupina 2. - popis činnosti: 
* Stanovení kritérií a pravidel pro útlum jednotlivých paliv  a energetických zdrojů se zohledněním jejich charakteru (elektrárny, teplárny, výtopny). 
* Analýza nutných úprav legislativy a vypracování harmonogramu legislativních změn. 

Pracovní skupina 3. - popis činnosti: 
* Analýza socioekonomických dopadů různých scénářů útlumu uhlí na regiony.
* Analýza možností následného rozvoje dotčených regionů.

**Comment by ondraspribyla** [comment]
https://www.irozhlas.cz/zpravy-domov/uhelna-komise-uhli-clenove-klimaticka-zmena_1909030702_jab

**Comment by kikinna** [comment]
@ondraspribyla Máš v prvním komentáři nahranou novou verzi infografiky.
Koukni na ni pls, jestli je za tebe reprezentace atd. v pohodě. Pokud ano, tak pak můžu dořešit detaily a můžem udělat nějaké kontroly.

**Comment by kikinna** [comment]
@ondraspribyla Přidána informace o předsedech

**Comment by protivinsky** [comment]
Love the naming convention! :)

![image](https://user-images.githubusercontent.com/9573993/72292237-e3771980-3648-11ea-9cda-8a3d907500dc.png)

**Comment by kikinna** [comment]
Ahaha, nedošlo mi, že to uvidíte :D

**Comment by crysman** [comment]
Aktuální stav: čekáme na vyjasnění a řádné ozdrojování kvůli výpadku primárního zdroje. Sekundární zdroj je nedostatečný/v konfliktu s aktuální verzí. Konkrétní bottleneck viz zde https://docs.google.com/spreadsheets/d/1wnN4DmlGwKS0c5QgrQOHElbfrPs7hiEWsg1brHvF074/edit?disco=AAAAEGuO22Y

**Comment by kikinna** [comment]
@crysman @ondraspribyla Je nějaký update?

**Comment by crysman** [comment]
pourgoval jsem teď před chvílí MŽP #McZ

**Comment by crysman** [comment]
ministerský rada Ing. Lukáš Minařík mi to dnes poslal v PDF mailem - požádal jsem ho, zda mi nemůže poskytnout online odkaz na web kvůli korektní citaci, tak uvidíme...

**Comment by crysman** [comment]
takže, nikde to nemají, na můj dotaz na koho se mám tedy obrátit, mě odkázal na pana Hřebíka, kterému teď píšu

**Comment by crysman** [comment]
pan Hřebík píše neuspokojující odpověď:

> ...složení institucí a organizací zastoupených v Uhelné komisi vychází z jejího Statutu, který je schválen usnesením vlády ze dne 30. července 2019 č. 565 (na webových stránkách MPO). K odkazům či citaci zdrojů je potenciálně možné se odvolat na schválený Statut...

Tedy se ho ptám:

> ...Bohužel ale, k tomu datu tam není aktuální složení - vím nejméně o dvou jménech, co jsou jinak (Koželouh, Farkač). Potřebujeme pro náš projekt důvěryhodný citovatelný zdroj online, kde bude aktuální složení jak uhelné komise, tak pracovních skupin. Z Vaší odpovědi, i kolegů, to vypadá, že nic takového na webu ani jednoho ministerstva není. Ptám se tímto, co můžeme udělat pro to, aby to tam bylo? Popř. pokud tomu něco brání, co?...

(pod oním "náš projekt" není nic uvedeno, v podpisu FoK nejsou, celé to je jen na moje osobní jméno)

**Comment by crysman** [comment]
Nic se nedělo, poslal jsem urgenci, odpověď zde:

> ...
> na webových stránkách MPO, mohou být k Uhelné komisi umístěny pouze informace, které jsou schválené usnesením vlády, obdobně jako u jiných poradních orgánů vlády.
> Dle Statutu se tedy jedná o instituce či organizace zastoupené v Uhelné komisi, nikoli o konkrétní osoby, které je zastupují.
> V rámci své pokračující činnosti Uhelná komise využívá dílčí výstupy a výstupy Pracovních skupin Uhelné komise průběžně, po pracovní linii, bez uveřejňování.
> Souhrnné a závěrečné výstupy Uhelné komise, jako poradního orgánu vlády ČR, budou vládě předloženy prostřednictvím ministra průmyslu a obchodu a ministra životního prostředí, formou komplexního materiálu s doporučeními.
>...

Takže oficiální zdroj typu ministerstvo prostě nebude. Varianty řešení @ondraspribyla :

a. využít [web Zeleného Kruhu](http://www.zelenykruh.cz/na-cem-pracujeme/uhelna-komise).
b. datasety a grafiku a texty uzpůsobit, aby tam konkrétní jména nebyla

**Comment by mgrabovsky** [comment]
Jestli chápu aktuální problém správně, tak za žádost podle 106 by měl povinný subjekt informaci zveřejnit i online (způsobem umožňujícím "dálkový přístup"). Možná by to stálo za to, pokud chceme co nejoficiálnější zdroj.

**Comment by Keramadohal** [comment]
> Jestli chápu aktuální problém správně, tak za žádost podle 106 by měl povinný subjekt informaci zveřejnit i online (způsobem umožňujícím "dálkový přístup"). Možná by to stálo za to, pokud chceme co nejoficiálnější zdroj.

Je to tak. Mustr na 106 můžu dodat, je to snadný jak facka.

**Comment by crysman** [comment]
Tyotoje cominapsal na konci mailu:
"""
Pro Vaší případnou další emailovou komunikaci využijte prosím oficiální 
webový kontakt MPO (www.mpo.cz), určený veřejnosti. Po zaevidování Vašeho 
dotazu Vám bude v zákonné lhůtě do 30 dní odeslána elektronicky odpověď.
"""

Nevím zda tím myslí 106 ci ne, explicitně to tam není.

Ale mužem asi požádat skrz 106 proč ne.

Mczzmobilu

---------- Původní zpráva ----------
Od: Marek Lahoda 
Datum: 15. 2. 2020 v 21:18:45
Předmět: Re: [faktaoklimatu/web] Uhelná komise - obsazení (#318)

"


Jestli chápu aktuální problém správně, tak za žádost podle 106 by měl 
povinný subjekt informaci zveřejnit i online (způsobem umožňujícím "dálkový 
přístup"). Možná by to stálo za to, pokud chceme co nejoficiálnější zdroj.


"


Je to tak. Mustr na 106 můžu dodat, je to snadný jak facka.





—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
(https://github.com/faktaoklimatu/web/issues/318?email_source=notifications&email_token=ABIGOZQQYENL5TXXQW5RTO3RDBE2BA5CNFSM4JULG4WKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL3WDDY#issuecomment-586637711)
, or unsubscribe

**Comment by mgrabovsky** [comment]
Lhůta pro poskytnutí informace podle 106 je 15 dní (s možným prodloužením o 10 dní), takže to bude asi ještě něco jiného.

**Comment by Keramadohal** [comment]
106 na ně! Ať si v tom udělají pořádek ....

**Comment by crysman** [comment]
@ondraspribyla říkal na poslendím hackathonu, že se zeptá Koželouha, co dál, aby se to někam posunulo - prosím o info o progresu

**Comment by ondraspribyla** [comment]
stále v procesu. Mám slib od Koželuha i od Zuzky Vodrákové, že to ve svých
pracovních skupinách potlačí...byl bych asi raději, abychom měli link z
nějakého oficialniho zdroje...

Budou mít ted zasedani komise zacatkem brezna, tak pockejme
