### ISSUE TITLE
Strategické a vizionářské materiály k projektu

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#321]
* **Zeitgeist:** teď, v roce 2019 je časové okno, kdy se utváří v myslích lidí obraz (brand) toho, co znamená klimatická změna. **Strategický cíl:** tento branding je potřeba "dobře" dokončit.

* ...mimo centra (Praha, Brno) není změna klimatu téma - lidé o tom neví a nediskutují to. V centrech se diskuse posouvá dál (už se neřeší, zda klima změna přichází nebo ne) - ale mimo centra ta diskuse neproběhla. A tedy tam je potřeba tuto diskusi vést. **Stratgický cíl:** dostat diskusi do lokálních center. Pro lidi mimo centra jsou Greenpeace, IPCC nebo Shell prostě korporát, ke kterému nemají důvěru - tzn nemají dosah.  

Tady je prostor pro ukládání materiálů a myšlenek k strategii a směřování...
[Lidé-potřebují-emoce.-Když-jim-je-nenabídnou-seriózní-politici-odejdou-za-populisty-varuje-expertka-Deník-N.pdf](https://github.com/mukrop/faktaoklimatu/files/3922409/Lide-potrebuji-emoce.-Kdyz-jim-je-nenabidnou-seriozni-politici-odejdou-za-populisty-varuje-expertka-Denik-N.pdf)

**Comment by repli2dev** [comment]
@ondraspribyla @mukrop btw. GitHub má vlastní konfigurovatelné kan-ban (meta) boardy přes více projektů, tohle je ideální materiál pro jejich založení.

**Comment by mukrop** [comment]
@repli2dev vieme – na urovni projektov pouzivame (napr. https://github.com/mukrop/faktaoklimatu/projects/2). Ked budeme mat GH organizaciu, budu sa dat robit projekty aj skrz repozitare.

**Comment by ondraspribyla** [comment]
//část commentu přehozena jako update prvního příspěvku. 

* lidé, kteří zažili komunismus mají tendenci nepovažovat oficiální zdroje za důvěryhodné - protože tehdy to byla propaganda. Důvěryhodnější pro ně je etězový email než ČT.

**Comment by ondraspribyla** [comment]
Převedeno na Wiki
