### ISSUE TITLE
Studie: Dobrodružství fotovoltaiky

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#324]
**Zdroj:** https://www.irozhlas.cz/zpravy-domov/fotovoltaika-energetika-obnovitelne-zdroje_1912040600_jab

**Comment by protivinsky** [comment]
Rozhodne zajimavy text, informacne hutny. Nejsem si prilis jisty, jestli ma smysl to davat do studii - je to spis mnoho dilcich informaci a pohledu nez male mnozstvi konkretnich zaveru. Pokud bychom to prece jen chteli, musime vymyslet, z jakeho pohledu to nejlepe uchopit.

**Comment by mukrop** [comment]
Přesunuto na wiki.
