### ISSUE TITLE
tip nová infografika lesy a odlesňování

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#326]
inspirace na jednoduchou ale údernou infografiku:
![image](https://user-images.githubusercontent.com/5269350/70175207-92cde180-16d6-11ea-8ad8-923753e8c57d.png)

zdroj: kniha _Nové pohledy_ od _A.Bonnetta_

zároveň je k tomu otázka: je víc lesa dobře? kolik lesa je akorát? ...

TODO:
- [ ] chceme to?

**Comment by kikinna** [comment]
(nejspíš Future work / topic to discuss)
Also klidně bychom mohli udělat edici "úderných infografik", kde budeme
prezentovat jen vybrané fakta, které mohou připoutat pozornost a potom pod
nich odkazovat na naše detailnější / související infografiky?
