### ISSUE TITLE
Slovníčkové heslo: Citlivost klimatu

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#329]
Climate sensitivity.

- [x] zařadit odkaz na článek [Uploading knutti08natgeo.pdf…]()  (a ideálně ten článek pořádně přečíst, možná z něj vytáhnout infografiku??)

- [x] projít anglickou wiki a vytáhnout relevantní informaci.

**Comment by lilyjoe19** [comment]
tu je funkčný link na článok:
https://ethz.ch/content/dam/ethz/special-interest/usys/iac/iac-dam/documents/group/climphys/knutti/publications/knutti08natgeo.pdf
ak by prestal fungovať, https://doi.org/10.1038/ngeo337 je istota :)

ja to skúsim prečítať cez Vianoce, ale ako na to zbežne pozerám, asi tomu nebudem veľmi rozumieť :) možno @Keramadohal by sa na to mohol časom pozrieť, hm?

**Comment by Keramadohal** [comment]
Jo, těch pár stránek bych o svátcích mohl zvládnout. Samotného mě to zajímá :-)

**Comment by Keramadohal** [comment]
Článek jsem přečetl a sepsal slovníkové heslo - viz pull request #357.

S @ondraspribyla jsme se domluvili, že by bylo dobré to vzhledem k důležitosti tohoto konceptu zpracovat šířeji do formy článku/studie. Založil jsem na to novou issue #359.

**Comment by mukrop** [comment]
Hotovo.
