### ISSUE TITLE
Infografika emise-eu-podrobně

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web#334]
Stylově stejná grafika jako emise-svet-podrobne #296, tentokrát pouze pro státy EU

Garant obsahu: @ondraspribyla 
Garant grafiky: @kikinna
Graficky zpracovává: @kikinna 

**Úkoly**
- [ ] Nachystat podkladová data pro grafiku @ondraspribyla 
- [ ] Nachystat nadpis a podnadpis @ondraspribyla

**Comment by protivinsky** [comment]
@kikinna 
Kristi, do spreadsheetu EU jsem pridal informaci o populaci (emise na obyvatele jiz obsahuje): https://docs.google.com/spreadsheets/d/1KNL5d1CwLsLc8INquN7z5ABdr52APEsDjEsUcYGh_Mk/edit#gid=979818322
Sekce B - 4, Emise sklenikovych plynu v EU. Jsou tam i staty mimo EU, ale ty nas pro infografiku nezajimaji (predpokladam).

Staci to jako podklady takto nebo potrebujes jeste neco dalsiho? Svetovy dataset byl akorat serazeny sestupne podle emisi na obyvatele a mel dopocitane kumulativni populace - nicmene vy jste to nakonec stejne rozdelily do jednotlivych kontinentu, tak nevim jestli to vlastne potrebuje. Pokud ano, dej vedet, muzu to samozrejme taky doplnit (akorat bych pak musel prekopirovat tu tabulku, abych neserazoval tu existujici).

**Comment by protivinsky** [comment]
Doplňující podklady pro infografiku: 
- **nadpis:** Emise států EU přepočtené na osobu
- **podnadpis:** Srovnání států Evropské unie podle ročních emisí skleníkových plynů na obyvatele za rok 2016 měřené v tunách CO2eq, doplněné o velikost populace a celkové emise.
- **url:** emise-eu-na-osobu
- **zdroj dat:** Evropská agentura pro životní prostředí
- **vysvětlující box:** Indonésie má populaci 248 milionů a roční emise na osobu 3,42 tun. Celkové roční emise státu jsou součinem těchto hodnot, který je vyjádřený plochou obdélníku, v tomto případě přibližně 850 milionů tun.

Layout podle stejné infografiky pro celý svět, tedy popisky os, vzhled a vysvětlující box podobně jako zde:

![image](https://user-images.githubusercontent.com/9573993/72668088-f3ad4100-3a1a-11ea-8e08-113bebba323b.png)

**Comment by palcifer** [comment]
![image](https://user-images.githubusercontent.com/5993966/72678205-06b82380-3aa4-11ea-8972-6b7f867ad86f.png)

nastrel prvej verzie grafiky, aj na druhy den to vyzera celkom schopne

**Comment by palcifer** [comment]
![image](https://user-images.githubusercontent.com/5993966/72678238-71695f00-3aa4-11ea-961a-a74105176cad.png)
Prva verzia grafiky

**Comment by protivinsky** [comment]
Hotovo, PR #334, zaviram.
