### ISSUE TITLE
divná PDFka - červené okraje, chybí obsah

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#339]
poslední dvě infografiky (energ bilance a mitigace) jsou nějaká divná PDF - nemůžu to vytisknout, jedno má červené okraje, druhé dokonce v rámci červených okrajů ani žádný obsah :/

chyba vypadá nějak takto:
![image](https://user-images.githubusercontent.com/5269350/72263311-e78b4300-3618-11ea-8f15-8c99576c7705.png)

projevuje se jak v prohlížeči Brave, tak ve Firefoxu, tak v Chromiu

tisk z mého desktopového programu na PDFka nefunguje

nezaznamenal jsem podobný problém u žádných jiných PDF tady z faktů...

**Comment by mukrop** [comment]
To vyzera na testovacie PDF na okraje. Ale na webe si myslim, ze aktualne nie je, u mna funguju mitigacne opatrenia MMF aj energetika spravne. Skus iny prehliadac alebo premazat cache, odhadoval by som problem skor u teba lokalne.

**Comment by kikinna** [comment]
Jojo, to jsou testovací okraje, které by neměly být součástí PDF (je to
skrytá vrstva), tak pokud ti to bude blbnout i po promazání cache, tak dej
vědět a já to přeexportuju a vymažu tu vrstvu úplně.
Ale taky se mi nepodařilo ten problém reprodukovat.

**Comment by crysman** [comment]
zkusil jsem tři prohlížeče, čtvrtý kvůli tomu instalovat nebudu, cache sice vymazat můžu, ale pochybuju, že jsem kdy ve Firefoxu otevíral faktaoklimatu, ten prohlížeč normálně nepoužívám

co se snažím říct je, že i když si JÁ vymažu cache, tak dost pravděpodobně to může blbnout lidem tam venku - z důvodů uvedených výše - použití tří prohlížečů z nichž jeden standardně ani nepoužívám

takže to spíš vypadá na nějaký problém s tím, že mám GNU/Linux Xubuntu (a vy zřejmě Win ?)

nicméně, OK, vymazal jsem všecko ve Firefoxu, otevřel pro jistotu anonymní okno, nezabralo

Závěry:
- promazání cache nepomáhá problém vyřešit
- jiný prohlížeč taky ne
- anonymní okno taky
- problém dělá dokonce i jiný graf, který jsem dřív úspěšně tisk (vývoj teplot) - takže zřejmě nějaké nové verze těch věcí (?)
- na firemním počítači s Windows Server 2012R2 to taky dělá červené okraje a u mitigačních bez obsahu (prohlížeč Chrome) - stejná chyba jako u mě na Xubuntu

@ondraspribyla ty máš taky nějaký klon Ubuntu - zkusíš prosím i ty?

**Comment by jankrcal** [comment]
Zaujat problémem jsem to otevřel na firemním počítači s linuxem (Debian) a obě PDF vypadají v pořádku...

Ty dva počítače, co zkoušíš, jsou oba u Tebe doma?
Přemýšlím, co můžou mít společného (co naše počítače nemají)...

**Comment by mukrop** [comment]
Podla symptomov to nebude cache, ale PDF prehliadacom. Z toho, co viem od @kikinna si myslim, ze to PDF ma skrytu vrstvu kvoli kalibracii okrajov, ale crysmanov prehliadac mozno nerespektuje to, ze je skryta a zobrazuje ju (for the record, u mna je to Fedora, nie Win).
@crysman: Skus to PDF stiahnut (neotvarat v print dialogu) a otvorit v PDF prehliadacoch, ktore mas nainstalovane. Ale aj tak to vidim na to, ze budeme ostru verziu musiet cistit a tieto vrstvy tam vobec nedavat.

**Comment by protivinsky** [comment]
Postup reprodukce:
- stahl jsem PDF
- otevrel jsem je v prohlizeci a dal tisknout do PDF
- bylo to takto rozbite jak v tiskovem nahledu, tak ve "vytistenem" PDF - podezrivam, ze pri tisku na papir by to bylo totez
- pokud stahnute PDF otevru v Adobe Reader a dam tisknout, nahled vypada v poradku - pravdepodobne je to zpusobeno nejakou interakci mezi nasimi PDF a tiskem v prohlizecich (mam Vivaldi, coz je taky na chromim jadre)

@mukrop - volne souvisejici otazka - pri uzkem zobrazeni se stranka preskupi a nasledne jiz tlacitko ke stazeni jako PDF / SVG / PNG neni dostupne (napriklad jsem marne hledal PDF ke stazeni pres telefon...). Je to zamer?

![image](https://user-images.githubusercontent.com/9573993/72292592-98a9d180-3649-11ea-8de9-2e0648c6f5f2.png)

**Comment by kikinna** [comment]
Ok, vyexportuji nanovo.
Nicméně, dlěá to teda jen u oněch dvou pdf nebo u všech? Přijde mi totiž
zvláštní, že by to dělalo jen u dvou.

**Comment by crysman** [comment]
spíš mi přijde zvláštní, že chybu nereprodukujete - fakt dáváte tisk a náhledové okno? a zkoušeli jste to vytisknout?

já to právě proto zkoušel i na uplně jiném computeru a OS - se stejným výsledkem... a @protivinsky  nyní potvrzuje.

Díky všem za nasazení a aktivitu.

Závěry za mě:

1. chyba nezávisí na použitém OS
1. ano, budeme/te muset vše přeexportovat, aby to bylo failsafe @kikinna

**Comment by repli2dev** [comment]
OS X a Preview je OK, ale Chrome s vestavěným PDF.js má stejný problém.  V nějakém smyslu vadná budou nejpravděpodobněji ty PDFka.

**Comment by jankrcal** [comment]
Omlouvám se, nezvládl jsem přečíst popis, skutečně jsem neotevřel náhled tisku. Můžu potvrdit, že jsem na linuxu otevřel asi 7 náhodně zvolených grafik a všechny mají stejný problém, který popisuje crysman.

**Comment by mukrop** [comment]
@kikinna: Prosim opravene PDFka mi bud poslat, alebo nahrat do vetvy "fix-rozmery-infografik".

**Comment by kikinna** [comment]
Upraveno. 
Až se to nahodí, bylo by super, kdyby to @crysman zase zkontroloval. 

Všechny pdfka [zde](https://www.dropbox.com/sh/7ht2mzmh4nnt358/AADWw-UfD5W-ebslkF36z7Npa?dl=0)

**Comment by jankrcal** [comment]
PDF jsem nahrál do větve fix-rozmery-infografik.
