### ISSUE TITLE
Štítkování (obsahová část)

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#346]
Je potřeba přiřadit štítky všem infografikám a zprávám (upravit položku `tags`).
* Promyslet, co jsou vhodné štítky a co ne (aby jich nebylo příliš moc, ale ani nebyly příliš obecné).
* Max 5–6 štítků na grafiku/studii.
* Nedělat štítek s typem (studie/infografika/data) – toto bude řešeno jinak.
* Štítky psát s diakritikou, začínající malým písmenem (mimo případů jako "ČR").
* Na pořadí štítků ve zdrojáku nezáleží (budou se zobrazovat v abecedním pořadí).

**Comment by ondraspribyla** [comment]
...zkoušel jsem si udělat "velkou tabulku": https://docs.google.com/spreadsheets/d/1Z1uEaWHrziIrIS2DBql13TrwSd5LMGh1ocBrI_1OCmI/edit?usp=sharing

...je potřeba myslet dopředu a ptát se: jaké otázky si budou pokládat naši uživatelé? Na to by měly být štítky/tagy optimalizované...

...jak velké by měly být štítky? Kolik slov? Asi dává smysl, aby byly 1-2 slovné... ?

... zápasím se souhrnným štítkem "fyzikální charakteristiky" - dá se rozdělit na teploty, koncentrace (a pak další jako kryosféra, oceány, ...??) Budu potřebovat s pár lidma diskutovat tohle koncepční rozhodnutí...

**Comment by mukrop** [comment]
Tabulka vyzera fajn. Ale navrhovane tagy mas podla mna stale prilis dlhe. Za mna dve slova max (a silne preferovane jedno). Tj. namiesto 'emise skleníkových plynů' by som fakt dal len 'emise'. Podobne namiesto 'souvislosti s ekonomikou' len 'ekonomika'. Ano, je to zjednodusujuce, ale podla mna to nevadi.

Ak chces, moze mat kazdy stitok vysvetlujuci odstavec, ktory sa zobrazi na stranke s prehladom objektov s danym stitkom.

Navhujem v piatok na klimatone nechat niekoho preklepat tvoj aktualny draft stitkov do gitu a potom uvidime, ako to bude vyzerat.
