### ISSUE TITLE
Štítkování (technická část)

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#347]
* Vytvořit layout stránky se štítkem (přehled infografik, studií a datových sad s daným štítkem).
* Generovat takovouto stránku pro každý štítek.
* Přidat zobrazování proklikávatelných štítků k infografikám a studiím (do pravého panelu, souvisí s #340).
* Integrace do produkce čeká na #346.

**Comment by kikinna** [comment]
Až to bude aktuální, dáš mi @mukrop prosím vědět? Ráda bych se pobavila o
tom, jak budeme se štítky pracovat (hlavně mi jde o to, že momentálně
chcete vytvářet stránku pro každý štítek, což si myslím, že může fungovat
při malém množství štítků, ale nepřijde mi to moc dobře rozšířetelné a
zapadající do konvencí dnešního webu -- ale jsem si vědoma, že na to, aby
to zapadalo, museli bychom udělat web v2).
Děkuji ))

**Comment by mukrop** [comment]
Technicka poznamka: Nepouzivat ani `jekyll-archives` ani `jekyll-tagging`, pretoze nepodporuju custom collections. Mozno nejaku variaciu (tj. skopirovat zdrojat a upravit).

**Comment by mukrop** [comment]
From @mgrabovsky: `jekyll-archives` vyzera trochu lepsie na adaptaciu.

**Comment by mukrop** [comment]
Zbývá:
* [ ] Dodělat texty (copywriting) stránky s tagem.

**Comment by mukrop** [comment]
@Tasssadar: Vies prosim z hlavy, ci je mozne niekde vlozit zoznam vsetkych tagov? Tj. ci je dostupna nejaka premenna typu `site.tags`, kde su vsetky?

**Comment by Tasssadar** [comment]
@mukrop obávám se, že ne. jekyll-archives nevypadá, že by něco přidával do site, a s původníma `@site.tags` je ten stejný problém - nepodporují collections. Asi je to fakt něco, co se musí vyřešit v core Jekyllu https://github.com/jekyll/jekyll/issues/8107

Nicméně je možné dostat všechny tagy stejným způsobem, jako jsem to dělal v jekyll-archive: https://github.com/faktaoklimatu/web/blob/a921b6d022f91feb681dba40e2480a152c935ebb/_plugins/jekyll-archives.rb#L63-L68
