### ISSUE TITLE
Založit Twitter

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#348]
* [x] Obrazek, popis, background, ...
* [ ] Naplanovat par prispevku

**Comment by mukrop** [comment]
Potom prosim:
* [ ] Doplnit Twitter handle [do prehladu](https://docs.google.com/spreadsheets/d/1awR7r6ePT7HcYtbm-MDC6YPYL_I_vUlT5oSck-VBdRU/edit#gid=0)
* [ ] Spisat kratky popis s "politikou a planom", tj. ako casto postovat, co asi retweetovat a co nie, ... do [zlozky s navodmi k zdrojom a sluzbam]{https://drive.google.com/drive/folders/13u60TTLTFnlPLSXeK-UL_cMtTm1fZSfb}

**Comment by Keramadohal** [comment]
Přístup Kice zařízen.
"Politiku a plán" asi budeme muset ještě probrat osobně v jádru týmu, hned druhý den provozu nám vyvstaly drobné rozpory :-)))

**Comment by mukrop** [comment]
@Keramadohal Ako to vyzera? Mate tusim zajtra nejaky meeting k Twittru?
Ak to bude strucne, tak to potom prosim spiste a toto issue zatvorte (je totiz sucastou milestonu vikendoveho klimatonu, takze visi ako nedokoncena vec).

**Comment by ondraspribyla** [comment]
Zitra se jeste k Twitteru sejdeme a doplánujeme. Zavírám, není potřeba mít jako issue.
