### ISSUE TITLE
Napsat newsletter a aktualitu z víkendu

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#349]
- [x] napsat DRAFT
- [x] nechat udělat review Ondráše
- [x] zkontrolovat hyperlinky
- [x] review by @kikinna 
- [x] přidat kolážní obrázek
- [x] udělat podle toho aktualitu na webu

! POZOR nutné to dělat přímo na https://app.tinyletter.com/ - kvůli správnému formátování

**Comment by mukrop** [comment]
Kika uz dodala, cezo mna uz to preslo, cakam na schvalenie Ondrasa.

**Comment by mukrop** [comment]
Infografika verejne dostupna.
Len upozornujem @crysman a @ondraspribyla, ze link na zdrojove data EDGAR trochu zlobi (u mna v Chrome dostavam 403, ale vo Firefoxe funguje OK).

**Comment by crysman** [comment]
makám na tom... dnes večer to pošlu na review, zítra chci poslat, pokud Ondráš @ondraspribyla stihne během zítřka review (?) - jsem schopen odeslat po review obratem

**Comment by crysman** [comment]
prosím @ondraspribyla o review mého [draftu 1.0](https://docs.google.com/document/d/1KRaWiXlg2fVj6YeKPjrcn4KHS951J9UEy7SaTueT-1A/edit#), dodělával jsem to teď ve spěchu, takže tam může být chyba, hyperlinky ještě zkontroluju dodatečně kdyby něco volej po 21:00h teď musím valit na kole...

klidně může review dělat i někdo jiný, ale není to nutné podle mě

**Comment by crysman** [comment]
řeším technické trable s tinyletter s @mukrop jakmile fixnu doplním kolážpicture a pošlu

**Comment by kikinna** [comment]
(Just a quick note -- byla bych opatrná s koláž picture. Pokud není nutný,
tak bych se tomu vyhla nebo prosím pošli na schválení. Ať si držíme jeden
vizál i napříč komunikačními kanály)

**Comment by kikinna** [comment]
Paráda. Tak to je koláž nekoláž, to je úplně v pohodě ))
Jinak jsem tam dohodila jen odmezerování jednotlivejch bodů, aby tam byl
nějakej negativní prostor a ne jen shluk textu. Je to ok

**Comment by crysman** [comment]
dokončili jsme společné review s Kikinnou - jak grafika tak obsah

**Comment by crysman** [comment]
konečně se mi to povedlo vyladit, aby to vypadalo, závěr je jasný - je nutné to dělat přímo na https://app.tinyletter.com/ - jakýkoli můj pokus o poslání přímo mailem zkolaboval - jak z klienta, tak ze dvou nezávislých webmailů... plánované odeslání: 17:00 CEST

**Comment by kikinna** [comment]
Na to se těším. ))
Ale asi se mi pletou zóny. :D Podle mě je aktuálně CEST 18.35, tak pokud
jsi před hodinou nastavil odeslání, tak by to znamenalo, že jsi to nastavil
v 17.35 odeslání na 17.00 CEST. Nebo?
Asi na tom nesejde a jsem unavená z práce :D Jsem zvědavá, kdy mi to přijde
:D

Díky moc, že jsi to napsal! ))

**Comment by crysman** [comment]
už čeká jen na schválení PR https://github.com/faktaoklimatu/web/pull/371 zavírám
