### ISSUE TITLE
Chyba: Neaktuální odkazy v infografice Emise skleníkových plynů EU

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#354]
Odkazy na data v průvodním textu míří na různé části souboru https://docs.google.com/spreadsheets/d/1ldy3l-W0HDG1cHK393_rQC5pGXIWbVw94Dh3ie4aEI8/edit#gid=525565541 s názvem DELETE v názvu. Pravděpodobně to má mířit na finální verzi https://docs.google.com/spreadsheets/d/1KNL5d1CwLsLc8INquN7z5ABdr52APEsDjEsUcYGh_Mk/edit#gid=979818322 (tato rovněž obsahuje změny pro nový graf, následně přejmenuji a nahradím tím původní), čili je potřeba zkontrolovat, že obsahuje i ta doplňující data, najít kam odkazy směřují a přesměrovat.

**Comment by protivinsky** [comment]
A nefunguje ani odkaz na zdrojový dataset Eurostatu - zobrazuje prázdnou stránka a Unexptected Error.

http://appsso.eurostat.ec.europa.eu/nui/show.do?query=BOOKMARK_DS-089165_QID_20FB36E9_UID_-3F171EB0&layout=GEO,L,X,0;AIREMSECT,B,Y,0;UNIT,L,Z,0;AIRPOL,L,Z,1;TIME,C,Z,2;INDICATORS,C,Z,3;&zSelection=DS-089165INDICATORS,OBS_FLAG;DS-089165TIME,2016;DS-089165UNIT,MIO_T;DS-089165AIRPOL,GHG;&rankName1=UNIT_1_2_-1_2&rankName2=AIRPOL_1_2_-1_2&rankName3=INDICATORS_1_2_-1_2&rankName4=TIME_1_0_0_0&rankName5=GEO_1_2_0_0&rankName6=AIREMSECT_1_2_0_1&rStp=&cStp=&rDCh=&cDCh=&rDM=true&cDM=true&footnes=false&empty=false&wai=false&time_mode=NONE&time_most_recent=false&lang=EN&cfo=%23%23%23.%23%23%23%2C%23%23%23

**Comment by ondraspribyla** [comment]
Odkaz teď přesměruje na ddatové rozhraní https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=env_air_gge&lang=en

Kde si člověk musí vyklikat jaká data chce zobrazit... asi to není ideální, ale jde aspoň o správny odkaz. Možná by stálo za zmínku do textu pod grafikou napsat jednu větičku o tom, že si na datovém rozhraní EUROSTATU musí člověk sám vyklikat jaká data chce... co si to tom myslíš @jankrcal ?

**Comment by ondraspribyla** [comment]
Issue neni podstatna chyba - hlavni cast byla jiz opravena a odkaz funguje. Visi to tu zbytecne tak zaviram.
