### ISSUE TITLE
Seřazovat slovník dle plného názvnu, ne dle ID

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#355]
Staci upravit filter tag v `_stranky/slovnik.html`.

**Comment by mukrop** [comment]
Toto je zlozitejsie, Jekyll nema by default usporiadavanie podla ceskej abecedy. Tj. je treba implementovat vlastny liquid filter ([napoveda](https://jekyllrb.com/docs/plugins/filters/)) s nazvom `sort_czech`, ktory bude fungovat podobne ako [toto riesenie](https://github.com/moskyt/sort_by_alphabet).

**Comment by mukrop** [comment]
@mgrabovsky: Dostal si sa k tomu? @Tasssadar robil dnes vyraznejsie zmeny slovnika a idealne by som to chcel vsetko zobrat pod PR #402.

**Comment by mgrabovsky** [comment]
Nedostal jsem se k tomu. Všechen čas mi sežral Docker a nějaké drobnosti.
