### ISSUE TITLE
Vybrat pár čísel z analytiky návštěvnosti webu

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#356]

**Comment by mukrop** [comment]
Este poznamka, ktoru som nestihol osobne: V tom GA profile je vytvoreny custom dashboard, kde mam  naklikane nejake zakladne prehlady, mohlo by to pomoct pri vyberani cisel.

**Comment by jankrcal** [comment]
Zadne custom dashboard tam nevidim. Myslis Customization > Dashboards?
 - Neni to vazane na uzivatele (Tvuj Google ucet)?
 - Nemuzes to nejak explicitne sdilet se vsemi uzivateli toho GA profilu?

**Comment by mukrop** [comment]
Mas pravdu, bola oznacena ako "private". Nastavenie zdielania som uplne nenasiel, ale skusil som ju prestavit ako "shared", mozno ju uz uvidis.
Ak nie, tak asi sa ti bude dat importovat cez https://analytics.google.com/analytics/web/template?uid=JlIUcvYrSPC4TobInruMfg

**Comment by jankrcal** [comment]
Supr, uz to tam vidim, diky!

po 20. 1. 2020 v 14:27 odesílatel Martin Ukrop <notifications@github.com>
napsal:

**Comment by jankrcal** [comment]
První úvaha: líbilo by se mi definovat událost i pro rozkliknutí grafiky na celou obrazovku. To mi totiž přijde jako metrika toho, že si to někdo chce pořádně přečíst.

**Comment by mukrop** [comment]
Dobra uvaha. Zalozis prosim issue na upavy Google analytics a zacnes to tam pisat ako checklist do prveho prispevku? Ten dashboard by sa dal tiez asi vylepsit.

**Comment by jankrcal** [comment]
Ano, založeno #376

**Comment by mukrop** [comment]
Toto issue mozem zavriet?
Jeho cielom bolo par cisel na stakeholder's meeting, ktory uz prebehol (navyse je to issue v milestone vikendoveho klimatonu).

**Comment by ondraspribyla** [comment]
Zavírám, není relevantní... metriky hledat budem dál :-)
