### ISSUE TITLE
Systém pro stránky k datasetům

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#358]
Checklist potřebných úprav (větev `datove-sady`):
* [x] Konvence pojmenování: Našim zpracovaným datům se ŕíká "dataset", přebíraná data voláme "vstupní data" nebo zkráceně jenom "data". Tj. každá infografika staví na právě jednom našem datasetu, který vznikl agregací několika vstupních dat (z jiných zdrojů).
* [x] Navrhnout a implementovat metadatovou tabulku k vstupním datům.
* [x] Vytvořit sekci na titulní stránce a v navigační liště.
* [x] <del>Navrhnout a implementovat veřejné infomace o verzování ("changelog" pro dataset). In progress</del> @mukrop.
* [x] Udělat mapováníaktuálních infografik na datasety. Ideální výsledek: V každém `.md` souboru infografiky je nová položka v hlavičce `dataset: <slug-datasetu>`. Příklad viz infografika `emise-eu`. (Tj. pro každý dataset bude nutno formalizovat slug.)
* [x] Vytvořit `.md` soubor pro každý dataset a vložit textový obsah, který zatím máme. @jankrcal (Už jen chybí koncentrace co2, ke kterému je draft textu, jen ho potřebuju přestrukturovat; zbývající 3 datové sady ještě texty nemají.)
* [x] <del>Dohodnout se, jak verzivat data a jak infografiky: Aktuální draft: Verze datasetu ako přirozené číslo a verze infografiky jako "verze-datasetu.iterace-infografiky"?</del>
* [x] <del>Přejmenovat existující datasety dle nových názvů a slugů a verzovací schémy.</del>
* [x] Dohodnout se, jak odkazovat datasety z původních infografik. (Co linkovat: Stránku datasetu, dataset přímo, vstupní data přímo)
* [x] Upravit odkazování z infografik.
* [x] Upravit náhledové obrázky na titulce.
* [x] Napsat intro text do sekce na titulní stránku.
* [x] Doplnit texty a metadata k jednotlivým datasetům.
* [ ] Upravit řazení datasetů (upravit váhu v `.md` souboru).

**Verzování přesuto do samostatné iterace.**
---
(původní obsah komentáře)
Chceme dělat stránky k datasetům, z dnešní domluvy:

Vlevo:
 - velký screenshot datasetu
 - jeden odstavec shrnutí
Vpravo:
 - link na dataset
 - seznam linků na originální data
 - copyright? (asi potřebujeme říct zkontrolujte si copyrighty původních dat)
Dole:
 - volný text
 - seznam grafik, které dataset používají.

**Comment by jankrcal** [comment]
Dnes jsem nad tím přemýšlel na kole a došlo mi, že zveřejnit datasety zvlášť klade o něco vyšší nároky na transparentnost, aby uživatelé datasetu rozuměli, co se jim změnilo pod rukama a proč.
(Vlastně to za mě trochu vychází z frustrace, že člověk po půl roce znovu stáhne nějaký vědecký dataset a maličko se mu změní všechna čísla pod rukama a nerozumí tomu proč.)

Tedy bychom za mě měli:
 - začit datasety verzovat (asi nezávisle na grafikách, protože jinak bychom se z toho zbláznili),
 - každá verze datasetu v novém GSheet souboru (takový je zdá se mi momentálně workflow),
 - na stránce k datasetu mít stručný changelog popisující, co se změnilo ve které verzi.
 - staré datasety neodkazovat z webu, ale nemazat je, držet je ve složce na Disku "staré verze datasetů".

Posledním bodem si nejsem jistý, ještě transparentnější je odkazovat všechny verze.

@mukrop Co myslíš?

**Comment by mukrop** [comment]
@jankrcal: V podstate suhlasim so vsetkym, co si napisal. Datasety bude tiez teba verzovat. Zvazoval by som pisat "changelog" aj priamo do toho dataset google sheetu.

**Comment by jankrcal** [comment]
Za mě changelog do souboru spíše ne. Snažil bych se minimalizovat informace, které musíme manuálně udržovat konzistentní. Error-prone. Může trochu nahradit backreference na stránku datasetu, který explicitně zmíní, že tam je i changelog.

**Comment by jankrcal** [comment]
Technický komentář k tomu jak generovat screenshoty z CLI:
firefox --screenshot [path_souboru.png] --window-size=1200,800 [URL_of_data]

Otestováno na crysmanově linuxu, funguje, je to pěkný. Možná to ještě bude potřeba prohnat imagemagick a uříznout horní řádek s nadpisem, atd., nechat tam jenom samotnou tabulku.

**Comment by mukrop** [comment]
@jankrcal, @ondraspribyla: Vo vetve `datove-sady` je aktualny stav prace na strankach datasetov. Do prveho komentara tohto issue som urobil celkom podrobny checklist dalsej prace, ako nam vyplynul zo zmien vcera.

@jankrcal: Nevrhnes sa na vytvorenie mapovania, slugov a nazvov jednotlivych datasetov? Viz 5. a 6. bod v checkliste. Dalo by nam to prehlad, kolko toho je a kolko textov sa ide pisat a ci realita sedi s nasou predstavou.

PS: Stare datasety (gSheety) prosim nemazat, premenujeme ich a budeme ich drzat ako stare verzie.

**Comment by jankrcal** [comment]
@mukrop Ano, udělám. Jen jsem pořád nemocnej, tak nevím, kdy na to budu mít dost soustředěné energie. Snad příští čtvrtek.

Ještě přemýšlím, když už se tímto snažíme nastavit systém a udržet pořádek v našich datasetech:
 - Byl bych pro založit na zveřejněné datasety druhý týmový disk, kam bude mít právo zápisu jen pár z nás.
 - Udělat přesun nové rozpracované verze do finálního disku součástí review procesu (tedy technický recenzent ten soubor musí vzít, zkontrolovat a přesunout / zkopírovat).
 
Výhody:
 - Zmizí nutnost zamykat jednotlivé listy, což je voser.
 - Možná se dá taky nastavit default právo čtení pro všechny, tedy by zmizel jeden krok při zveřejňování datasetu (nastavení veřejného sdílení odkazem) a tedy by zmizela jedna možnost něco opomenout.   
 - Oddělíme tím tvůrčí chaos hlavního týmového disku od jasnosti a struktury publikovaných datsetů.

Co myslíte?

**Comment by mukrop** [comment]
Uz som nad tym presunutim na samostatny disk tiez par krat rozmyslal. Vyrobil som.
Default sharing settings v timovych diskoch neexistuju. Vyrobil som to zatial ako interny disk pre CORE, casom uvidime. Mozes to pouzivat na robenie poriadku (tj. poriadkovat to kopirovanim tam).

**Comment by jankrcal** [comment]
Díky. Na pořádek na discích jsem se ještě nedostal, ale třeba na to časem dojde :)
Otázka, jestli jsme spokojení s tím, že by k finálním datovým sadám měli právo zápisu všichni členové core-týmu. Za mě je to hraničně OK, zajímal by mě názor @ondraspribyla, který možná zaváděl současný režim zamykání listů.  

Zpět k původní issue: 
 - Udělal jsem commit k mapování slugů. Doplnil jsem text jedné datové sady.
 - Pořád chybí přepsat text k koncentraci co2. Udělám.
 - Pořád nám chybí text k teplotám ČR. Budu se snažit dodat.
 - Dále jsem identifikoval 2 netriviální datové sady, které by za mě bylo fajn pokrýt: světová teplotní anomálie (vývoj a ta nová mapa). Nemusí být součástí první verze, pokud na to nebude energie a bude chuť s tímto jít ASAP ven. Zjistím.
 - Všechny ostatní datové sady jsou spíš triviální (nemají moc data), takže tam bych zůstal u původních odkazů přímo na Google Sheet.

Můj názor na odkazování z infografik:
 - Pokud máme stránku datasetu, tak bych odkazoval jen a jen tu.
 - Pokud nemáme stránku datasetu (např. u triviálních dat), tak bych odkazoval stejně jako dnes: původní data + naši tabulku.

**Comment by mukrop** [comment]
Cau. Dik za postup!
* Moj nazor je netlacit to, urobit to poriadne a az potom pustit von. Menime tym viacero veci vo workflow projektu, tak to premyslime poriadne, nech sa to nemusi obratom menit.
* Vaham, ci je vhodne rozdelovat infografiky, ktore "maju" dataset a tie, ktore linkuju povodny. Ale zase je pravda, ze niektore (napriklad tie, ktore preberame) fakt nema zmysel, aby mali vlastu stranku datasetu. Zase odkazovat data v dvoch roznych formatoch (cez nasu stranku a priamo) sa mi zda nekoncepcne, takze zvazujem aj mat tam nasu tabulku aj original vzdy a ked dataset ma dalsie poznamky, tak odkazovat aj stranku datasetu (to ale zase triesti pozornost, to je fakt). @ondraspribyla, ako to vidis?

**Comment by ondraspribyla** [comment]
Přemýšlím o tom už pár dní... chce to diskusi. Mohli bychom zkusit
konferenční hovor? Třeba někdy dnes odpoledne/večer?

O.

**Comment by ondraspribyla** [comment]
Hlavní závěry z konferenčního hovoru: 
1. Postup práce: musíme rozhodnout koncepční věci typu verzování... pak můžeme vydávat jednotlivé datasety postupně. 
2. Pro ukládání hodotvých datasetů použijeme speciální googledrive, na který budou mít přístup jen Ondráš, Jeňa a Martin. 
3. Rozlišujeme texty ke grafice, které mají hlavně pomoct se v grafice zorientovat a zasadit ji do kontextu a texty k datasetu, které spíše vyjasňují původ a kozistenci dat. Text ke grafice bude číst pravděpodobně kdokoliv, koho zazujal grafika. Text k datasetu budou číst pouze lid, kteří se budou do hloubky zajímat o ta data. (nicméně pro účely kredibility je důležité, aby text k datasetu byl k dispozici i pro všechny ostatní). Informace se na obou stránkách mohou a pravděpodobně budou překrývat, budou ale nejspíš psány trochu jiným stylem. 

4. Otázka jak moc agregovat a zda nespojit data např k emise EU a emise ČR... odpověď je že zatím spíše ne, budeme chtít ponechat dva různé googlesheety, které jsou přehledně zpracované vzhledem k těm infografikám. Dataset jako produkt staví na tom google sheetu - informace v různých textech k datasetům se tedy mohou překrývat (např. v obou těchto datasetech budou průvodní informace k vstupním datům z EUROSTATU)

5. Z hlediska pojmenování rozlišujeme DATASET= náš agregovaný googlesheet a VSTUPNÍ DATA=to, co jsme použili pro vytvoření datasetu

6. Verzování infografik a datasetů: ujasnili jsme si, že verzování infografik a datasetů je hlavně pro nás, uživatelé jej asi moc chápat nepotřebují. Pojďme ho tedy udělat tak, aby dobře odpovídalo našemu workflow. 

7. Jako dataasety budeme dělat pouze naše složitější agregovaná data (tedy ne pouze překlady tabulky, nebo body zlomu)

8. Verzování datasetů: Staré verze datasetů asi budeme chtít ukládat, Nečekáme ale, že bychom měli na staré datasety nechávat odkaz, určitě ne ze stránky grafiky.

**Comment by ondraspribyla** [comment]
Metadata k datasetum: 
https://docs.google.com/spreadsheets/d/1NEoQW3HVYbFUHvS5mRjz9FWhK9LiWHDfBPG4NOCT77w/edit?usp=sharing

**Comment by jankrcal** [comment]
Otevřené koncepční otázky pro minimum-viable-product:
 1. Jak odkazujeme na datasety (a) z grafik, které mají dataset s vlastní stránkou, (b) z grafik, které mají dataset jen jako Google tabulku.
 2. Jak / jestli zobrazit staleness-warning.

**Comment by ondraspribyla** [comment]
Za mě:
- Staleness warning ano, zejména když bude vhodně napsaný tak dodá
credibilitu (skrze lidskost formulace)
- grafiky,ktere maji vlastni dataset: odkazat na dataset jedním tlačítkem
(v "podkladová data" tlačítko "DATASET")
- grafiky, které mají pouze podkladovou googletabulku bych
odkazoval stejne, jako to deláme dosud.

**Comment by mukrop** [comment]
Diskutovane v PR #475, zatvaram.
