### ISSUE TITLE
Vytvořit pozadí pro Twitter

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#364]
* [ ] Pozadí v rozlišení 1500 x 500 px.
* [ ] Nahrat na gDrive do gDrive > PR, přednášky, fotky, rozhovory
* [ ] Poslat pozadí Martkovi Lahodovi, nech ho vymeni.
* [ ] Vyrobit nove logo: aby malo biele pozadie (aktualne ma priehladne, co robi problem v ciernej verzii Twittru) a mat dobry anti-aliasing (aktualne vidno rozpixelovane okraje).
* [ ] Zvážit menší height hlavičkového obrázku, pokud možno - viz druhý comment.

**Comment by crysman** [comment]
aktuální pozadí je fakt ošklivé:
![image](https://user-images.githubusercontent.com/5269350/72803169-b1b81100-3c4d-11ea-90a8-b97f6ae40f1e.png)

chce to něco zašedlého ala styl "30% trasp. gray"

zároveň je ošklivé logo - de vidět rozpixelovaný okraj
a v poslední řadě mi přijde extrémně vysoká ta hlavičková část - jakože vidět vlastní obsah až ZA polovinou mé obrazovky mi přijde extrémní

**Comment by mukrop** [comment]
@kikinna Ako je to s tym pozadim? Toto issue mame v milestone k vikendovemu klimatonu, tak by som to rad zavrel.
Plus prosim pri prilezitosti pozadia vyrobit aj noveho avatara – ten aktualny okrem rozpixelizovanych karajov ma aj transparentne pozadie, co v ciernej verzii Twittru uplne nefunguje.

**Comment by kikinna** [comment]
@crysman A máš prosímtě nějaký návrh, jak nemít extrémně ošklivé pozadí? Nebo to za tebe stačí zešedět?
Totiž, já moc nevím, jak si naložit s kritikou "je to extrémně ošklivé". Vlastně mi z toho nezůstává nic moc víc než milé pohlazení :D

**Comment by crysman** [comment]
@kikinna mno, on to zjevně někdo už dost potunil, oproti minule se mi to teď vykresluje takto:
![image](https://user-images.githubusercontent.com/5269350/73138981-09e57d80-4069-11ea-935f-4dbf06c6d62d.png)

- obrázek sahá už jen do třetiny obrazovky (ou jé!)
- a není tedy tak výrazný (ou jé!)

co s rozpixelovaným okrajem teďka nevím, nebudu zkoumat

díky za hezké vybruslení z té negativní zpětné vazby podané nepřívětivým způsobem, to se mi líbí, [posílám pohlazení](https://res.cloudinary.com/twenty20/private_images/t_watermark-criss-cross-10/v1564382954000/photosp/0399242f-f8b0-48fc-bb0e-ebbd3a34f4c0/stock-photo-pet-0399242f-f8b0-48fc-bb0e-ebbd3a34f4c0.jpg).

**Comment by kikinna** [comment]
Hh, no ono to bylo nejspíš daný rozdílným rozlišením zařízení / okna. Nevím, jak jinak si to vysvětlit. Obrázek je tam totiž stále stejnej a nečekala bych, že si jako uživatel twitteru můžeš nastavit jejich layout. Kdo ví. 
Nicméně jsem ráda, že takhle je to za tebe víc ok. Ještě to stále trochu zešedím, to je dobrej návrh ;) 
Rozpixelování loga zítra vyřešíme s Markem.
