### ISSUE TITLE
Přejmenovat sekci "Ostatní stránky"?

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web#366]
IMHO, název **Ostatní stránky** mi evokuje ostatní webové stránky, které nejsou naše. 
Co takhle pojmenovat na styl "Doplňující informace" nebo ... ? Teď mě nic moc lepšího nenapadá, ale za mě to je aktuálně matoucí název.

**Comment by mukrop** [comment]
"Doplňující informace" je strasne dlhe (a podla mna nie o vela lepsie ako aktualna verzia). Zamyslim sa. Mozno len jednoduche "Dalsi"? Alebo "Vice"?
(A mimochodom, aktualne "Ostatni" mi pride o dost lepsie ako "Ostatni stranky", co si napisala ty, ze tam je. Prave to slovo "stranky" sa tam zamerne nikde nezmienuje :-) ).

**Comment by mukrop** [comment]
@kikinna Nezareagovala si, co si myslis o tych mojich navrhoch. Pride mi to ako detail, zbytocne nam to tu visi. Bud nieco vymyslime a zmenme to, alebo to ako issue zavrime.

**Comment by kikinna** [comment]
@mukrop Marti, promiň!
Ostatní samo o sobě zní fajn, ale působí to, že jde o věci méně důležité, odsunuté na druhou kolej.
Pokud ti "doplňující informace" nevyhovuje, pak bych hlasovala za "Další".

**Comment by ondraspribyla** [comment]
Obě varianty "Další" a "Více" se mi líbí - preferoval bych je ve variantě s třemi tečkami "Další..." nebo "Více..."

Nevidím důvod nějak dlouho váhat a rozmýšlet to, tedy prosím nějak rozhodněte a udělejte úpravu...
