### ISSUE TITLE
Nadpisy infografik na stránce nesouhlasí s obrázkem

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#367]
nadpisy preview nesouhlasí

nevím kde všude, ale příklad zde:
![image](https://user-images.githubusercontent.com/5269350/72750803-1cba0700-3bbe-11ea-8691-a3f75aa0a020.png)

po rozkliknutí:
![image](https://user-images.githubusercontent.com/5269350/72750829-2fccd700-3bbe-11ea-9239-6b496d045c37.png)

chápu, že má vliv cache prohlížeče, ale nemůžeme po našich čtenářích chtít, aby si manuálně čistili cache pořád... chce to nějak systémově fixnout ( @mukrop ?)

**Comment by mukrop** [comment]
To nema s cache nic spolocne, to autori nahodili iny nadpis ako nazov v infografike :-P.
Snazim sa to pri review kontroloval, ale tu som na to zjavne zabudol.

Kludne to fixni (urob pull request). A idealne pri hlaseni drobnosti tohto typu to idealne hlas systematicky, tj. ked si to vsimnes, tak to skontroluj vsetko a nareportuj, co vsetko nefunguje :-).

**Comment by ondraspribyla** [comment]
@crysman Jaký je status? Můžeš udělat opravu, nebok tomu potřebuješ něí součinnout?

**Comment by crysman** [comment]
udělám, stačí mi říct, co je master - jestli:

A) text v nadpisu infografiky jako takové, čili toto
http://localhost:4000/assets/infographics/vyvoj-teplotni-anomalie_1920.png
(a tedy i minináhledu na homepage)
![image](https://user-images.githubusercontent.com/5269350/73980655-f96ab800-4930-11ea-9afb-d0300177cd33.png)


anebo


B) HTML texty k infografikám, čili toto:
http://localhost:4000/infografiky/vyvoj-teplotni-anomalie
![image](https://user-images.githubusercontent.com/5269350/73980635-f079e680-4930-11ea-854e-15a29ce196a3.png)


Osobně si myslím, že **A) je správně** - a to nejen v tomto konkrétním případě.

Prosím jen o potvrzení/vyvrácení @ondraspribyla   #McZ

**Comment by ondraspribyla** [comment]
podle toho,co je v grafice. Konkretne tady to ma byt vyvoj svetove teplotni
anomalie

**Comment by crysman** [comment]
OK, za mě hotovo, nicméně, jsou tu dva ToDo body:

I)
Bylo nutno upravit celkem 9 souborů - to mi přijde hodně. Zjevně potřebujeme jedno z následujícího:

1. upravit workflow všech grafiků (i nových) tak, aby při změně názvu povinně změnili i `title` atribut (to bude dost pain a není to blbuvzdorné)
1. napsat skript/hook/check/f() tak, aby se bral strojově aktuální text z infografiky - která je v SVG, takže by to mohlo jít

silný názor nemám, dávám do pléna: @ondraspribyla @mukrop @kikinna 

II)
dále je třeba opravit infografiky ( @kikinna ? ):
1. "za rok 2016" v http://localhost:4000/assets/infographics/emise-eu-poradi_600.png sjednotit s ostatníma infografikama, čili konkrétně dát tento údaj doleva pod hlavní nadpis, jako to je všude jinde - abychom byli koherentní
1. přidat "`(detail)`" v http://localhost:4000/assets/infographics/emise-cr-detail_600.png - protože jinak máme dvě různé infografiky se stejným nadpisem, což je podle mě nežádoucí

(pokud se upraví, je třeba změnit minor verzi - což beru jako samozřejmost, ale pro jistotu...)

za chvíli hodím PR #McZ

**Comment by crysman** [comment]
@kikinna ad II)-2 navrhuji:

> Celkové roční emise jednotlivých států EU a jejich přepočet na obyvatele za rok 2016

**Comment by kikinna** [comment]
Pořadí
https://www.dropbox.com/sh/u13da5vts4vwtbt/AABaBCIfFPzYtIIRMgQIfaXpa?dl=0
Emise detail
https://www.dropbox.com/sh/6lbhdn8xzope7rt/AADhPLmBQSuopRwxcsXfmllja?dl=0

**Comment by crysman** [comment]
za mě hotovo, tj. výměna dvou PDF a úprava podnadpisu

pushnuto, PR zde https://github.com/faktaoklimatu/web/pull/422

TODO: @kikinna zařídí změnu workflow infografiků tak, aby při změně infografiky nezapomněli i změnit .MD soubor - popř. aby založili issue na někoho, aby to udělal
