### ISSUE TITLE
Překlep

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#368]
namátkou nalezeno:
![image](https://user-images.githubusercontent.com/5269350/72751247-6d7e2f80-3bbf-11ea-8be7-044e40a1d72f.png)

"Švědsku"

- nemám teď kapacitu to opravovat, priorita je newsletter, sem dávám, aby nezapadlo

**Comment by mukrop** [comment]
Robit issue na takuto drobnost mi pride trochu overkill, ale je pravda, je to sposob poznamky :D.
Idealne to potom rovno oprav (kludne s tym druhym issue, co si pred chvilou hlasil).
