### ISSUE TITLE
Popisování změn infografik v aktualitách

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#372]
dělám teď na PR https://github.com/faktaoklimatu/web/pull/345/files

a někde vidím na první pohled změny (od toho, co jsem nám kdysi vytiskl do práce na nástěnku) - velmi bych si přál, abychom změny infografik logovali v aktualitách - aby i člověk neznalý gitu se snadno dopátral toho, že je nová verze infografiky, a od kdy vlastně

hodí se pro kohokoliv, kdo používá naše infografiky

udělat jeden minizáznam v aktualitě není na dlouho...

co vy na to? @kikinna @ondraspribyla @mukrop

**Comment by mukrop** [comment]
Suhlasim s tym pisat tam aktualitu, ked sa menia data (tj. meni sa major version). Zda sa mi zbytocne robit to pre zmenu minor version (typicky mensia vizualna zmena, uprava paticky a pod).

**Comment by kikinna** [comment]
Souhlasím s Marťou.

**Comment by ondraspribyla** [comment]
V poslední aktualitě byly aktualizace grafik uvedeny, IMHO docela dobře. 
Zároveň vznikne díky zpracování datových sad trochu více pořádek jak v datech, tak v infografikách. Jinak řečeno, budeme to podrobněji řešit i v rámci této větší změny, takže issue zavírám.
