### ISSUE TITLE
Chybějící členy core teamu na stránkách

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#373]
v [oficiálním výčtu core týmu](https://faktaoklimatu.cz/#creators) chybí lidi

chybí tam např. Tom Protivínský - vzhledem k množství času, který v projektu tráví... což? možná ještě někdo další, nemám uplný přehled, proto zatím reportuju sem

**Comment by mukrop** [comment]
Ano, Tom tam ma urcite byt. Idealne to prejdi a nareportuj, koho treba pridat (alebo rovno urob pull request :-) ).

**Comment by ondraspribyla** [comment]
Zaviram skrze #377
