### ISSUE TITLE
Nefunkční odkazy

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#375]
tak zase nás to pronásleduje:

```
%%MSG: trying to find something...
Found 4 broken links.

https://pbs.twimg.com/
https://www.warningstripes.com/
https://abs.twimg.com/a/1576611360/icons/favicon.svg
http://zelenykruh.cz/xmlrpc.php

FINISHED --2020-01-21 13:18:33--
Total wall clock time: 5m 33s
Downloaded: 333 files, 37M in 30s (1.23 MB/s)
%%MSG: looking for FIXMEs...
%%-
faktaoklimatu.cz/slovnik:        <!-- FIXME dodělat markdownify filtr a&nbsp;upravit glossary.yml --#McZ_2019-10-02 -->
%%-

%%--
%%Tue, 21 Jan 2020 13:13:01 +0100
%%watchdog.sh v.1.0 by crysman(e)2019
```

je tam jeden false positive u stripes, ale ostatní 3 fakt nejedou, dnes už končím, 7.5h pro Fakta, už mám dost :) čabs všem a mám dobrý pocit z projektu, je to mazec

**Comment by mukrop** [comment]
Stojim si za politikou, ze nefuncknost pod tyzden je blbost riesit, to sa proste webom stava.

Mimochodom, odkial odkazujeme https://pbs.twimg.com/ a https://abs.twimg.com/a/1576611360/icons/favicon.svg? Neviem to v celom projekte dohladat.

**Comment by crysman** [comment]
OK, to beru, tedy nefunkčnost <7d vynechám.

Ty false-positives checknu, na první dobrou (`grep -iRI "abs.twimg.com" ./`) taky nic nevidím, prověřím.

**Comment by ondraspribyla** [comment]
Warningstripes maji web v prestavbe.
, je to tam korektne napsany.  Isuue tu IMHO visi zbytecne a neni jasna akce co s nim udelat ani to neni podstatna chyba. Zaviram.
