### ISSUE TITLE
Text k datové sadě: Emise Svět

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#378]
viz původně #111 
Co myslím, že by text měl obsahovat? 

- [ ] odkud jsou data, vysvětlení charakteristiky a důvěryhodnosti zdroje

- [ ] odkazy na jiné možné zdroje a proč jsme je nevybrali a nechali 2012

- [ ] komentář k datům a jejich struktuře, komentář k rozdělení států do kategorií

...můžeš vyjít z textu ,který u  grafik EMISE svět už je...

**Comment by protivinsky** [comment]
V listopadu JRC konecne zverejnila novou verzi, EDGAR v5.0, s daty CO2 az do 2018 a CH4 a N2O az do 2015. Ke zvazeni, jestli budeme chtit nekdy updatovat. Zatim bych to neresil, pridam do wiki.

**Comment by protivinsky** [comment]
Prvni verze:
https://docs.google.com/document/d/1rWsGxba2qlRM79_EA1rkYYDEkROZCs4CNqOWM-__xrg/edit

**Comment by ondraspribyla** [comment]
Mě se tvůj text líbí, považoval bych ho za hotový... co na to @jankrcal a @tomas-psorn ??

**Comment by tomas-psorn** [comment]
Dal jsem tam pár poznámek, ale v zásadě je to v pořádku.

**Comment by protivinsky** [comment]
Diky za komentare, dobre postrehy! Vetsinu jsem rovnou prijal, dve mi zbyvaji na doreseni, nejspis to dotahnu o vikendu s cistou hlavou. Predpokladam, ze potom to stejne bude viset na vymysleni a zpracovani, jak vlastne ty datasety zakomponujeme do stranek.

**Comment by ondraspribyla** [comment]
Integrujeme do #391 a zavírám jako hotovo.

**Comment by jankrcal** [comment]
Přidal jsem pár komentářů, za mě je to skvělé!
