### ISSUE TITLE
Text k datové sadě: Koncentrace CO2

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#379]
Aktuální stav textu: https://docs.google.com/document/d/1Nn4-E5Rw6Csa-acJ6xs5lAAQcK92DQmSNCPLU21LbeU/edit?usp=sharing

- [ ]  popsat způsob měření

- [ ] popsat databazi SCRIPPS 

- [ ]  přeložit relevantní části doprovodného textu k datovým sadám

**Comment by ondraspribyla** [comment]
K napojení Keelingových měření na Ice core data: 
https://scripps.ucsd.edu/programs/keelingcurve/2014/03/20/how-are-ice-core-data-and-mauna-loa-atmospheric-data-made-comparable/

K processingu dat: 
https://scripps.ucsd.edu/programs/keelingcurve/2014/07/28/how-is-co2-data-processed/
 
Video zachycující metodu měření:
https://scripps.ucsd.edu/programs/keelingcurve/2018/04/12/video/

**Comment by ondraspribyla** [comment]
Původní Keelingův článek z roku 1960 uvádí jak metodu měření, tak přesnost +- 0.1ppm
https://scrippsco2.ucsd.edu/assets/publications/keeling_tellus_1960.pdf

**Comment by ondraspribyla** [comment]
Text z Bureau International des Poids et Measures podrobněji popisuje metodu a zmiňuje také přesnost +-0.1ppm
https://www.bipm.org/utils/common/pdf/chemistry/GAS2015_poster_CO2.pdf

**Comment by ondraspribyla** [comment]
Doplněn odkaz na aktuální verzi textu: https://docs.google.com/document/d/1Nn4-E5Rw6Csa-acJ6xs5lAAQcK92DQmSNCPLU21LbeU/edit?usp=sharing

**Comment by ondraspribyla** [comment]
Přišlo by mi navíc dobrý dataset a grafy z něj jednou ročně updatovat o poslední hodnoty podle https://scripps.ucsd.edu/programs/keelingcurve/
Což je teď v lednu 414ppm, roční průměr za 2019 bude kolem 411ppm

**Comment by jankrcal** [comment]
Přidal jsem pár komentářů k dokumentu, přijde mi to fajn (minimálně jako první verze).

**Comment by mukrop** [comment]
@jankrcal Je toto uz zapracovane a moze sa zatvorit?

**Comment by jankrcal** [comment]
Ano!
