### ISSUE TITLE
GA: IP anonymizace, do-not-track

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#383]
* Overit, ze mame pouze kod GTM a ne i GA.
* Nastavit IP anonymizaci pres GTM.  
https://www.optimizesmart.com/how-to-turn-on-ip-anonymization-in-google-analytics-and-google-tag-manager/
* Nastavit dodrzovani DNT.  
https://www.analyticsmania.com/post/respect-do-not-track-parameter-google-tag-manager/

**Comment by mukrop** [comment]
Dodrzovanie DNT nefunguje, treba odladit.

**Comment by Tasssadar** [comment]
U `Do Not Track request` triggeru nebylo zaškrtnuto `Use regex matching` (viz verze #17 v tag manageru), takže to kontrolovalo jméno eventu vůči stringu `.*`, opraveno.
