### ISSUE TITLE
Obecné issue: legislativa a strategické dokumenty ČR/EU/Svět

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#387]
cílem je vytvořit grafiku / list, která shrnuje hlavní legislativní prvky v ČR v ochraně klimatu. 

NEXT STEP: @Keramadohal se potka s Romanou Brezzovskou a poprosi ji o vytah / texty...

**Comment by ondraspribyla** [comment]
https://www.mzp.cz/cz/politika_ochrany_klimatu_2017 - ale tato strategie je hezká, zastaralá, neúčinná a nikdo se podle ní neřídí.

Hned předpoklady se týkají tvého návrhu:
str. 14:
"Odhad krátkodobého vývoje klimatu v ČR (2010–2039) V krátkodobém  časovém horizontu (k roku 2030) se průměrná roční teplota vzduchu na území  ČR podle modelu ALADIN‐CLIMATE/CZ zvýší cca o 1 °C v porovnání s průměrem let 1961‐1990 (tab. 2) a patrné je systematické zvýšení teplot (obr. 5). "

No a celá strategie směřuje maximálně na 80 % snížení emisí do roku 2050 a s její aktualizací se počítá tak v roce 2022.

Jirka Dlouhý

**Comment by ondraspribyla** [comment]
Atraktivní formou vizuálně přiblížit strategické materiály a jejich obsah

* **Globální úroveň** – Rámcová úmluva OSN o změně klimatu + Pařížská dohoda
* **EU úroveň**  – European Green Deal, [Adaptační strategie EU](https://www.mzp.cz/cz/adaptacni_strategie_eu), [klimaticko-energetické balíčky pro 2020 a 2030](https://ec.europa.eu/clima/policies/strategies/2020_en) 
* **ČR** -  Politika ochrany klimatu v ČR (https://www.mzp.cz/cz/politika_ochrany_klimatu_2017), Strategie přizpůsobení se změně klimatu v podmínkách ČR (https://www.mzp.cz/cz/adaptace_na_zmenu_klimatu), Komplexní studie dopadů, zranitelnosti a zdrojů rizik souvisejících se změnou klimatu v ČR (https://www.mzp.cz/cz/studie_dopadu_zmena_klimatu, bude nová aktualizovaná verze, dána na web cca do měsíce).
dále např. Národní energeticko-klimatický plán (až bude zveřejněn), Státní energetická koncepce

**Comment by ondraspribyla** [comment]
@kikinna tady je issue se strategickymi dokumenty ke klimatu  - viz výše

**Comment by ondraspribyla** [comment]
Romana Brezzovska Pise: 

Jinak co se týče Adaptační strategie, tak je to dokument schválený vládou, což mj. znamená, že by měl být závazný pro resorty, především pro ty, pro které z AS vyplývá nějaký úkol. Jednotlivé úkoly jsou popsány v Národním akčním plánu, to je implementační dokument Strategie. Bližší info s odkazy: https://www.mzp.cz/cz/adaptace_na_zmenu_klimatu.

V těchto chvílích se zrovna dokončuje hodnocení plnění Strategie a tento úkol provádí CENIA (https://www.cenia.cz/#aktuality_). Hodnocení by mělo být hotové cca do měsíce a finální verze bude uveřejněna na stránkách
Samotná strategie byla vypracovaná MŽP, na začátku dokumentu se uvádí, že:
Zpracovalo Ministerstvo životního prostředí v meziresortní spolupráci svyužitím klimatologických podkladů Českého hydrometeorologického ústavu.Na přípravě materiálu se podílely zejména resorty životního prostředí, zemědělství, průmyslu a obchodu, pro místní rozvoj, zdravotnictví a vnitra.Návrh strategie byl revidován Centrem pro otázky životního prostředí Univerzity Karlovy v Praze a konzultován s Centrem výzkumu globální změny AV ČR.

**Comment by ondraspribyla** [comment]
@tomas-psorn ...adaptacni strategie je dokument schvaleny vladou... https://www.mzp.cz/C1257458002F0DC7/cz/zmena_klimatu_adaptacni_strategie/$FILE/OEOK-Adaptacni_strategie-20151029.pdf

zkusis to dostat do myslenkove mapy?

**Comment by ondraspribyla** [comment]
Rozpracovaný dokument je tady: 
https://docs.google.com/document/d/1H9KoxhtPh9ueabNH4GuGC0lI9xTfMiQr_tJTIv_qb8Y/edit?usp=sharing

**Comment by crysman** [comment]
dodělány všechny 3.x sekce, zatím ponecháno více než méně informací
obahaceno o tučné věty vytažené z _Příloha č. 5: Souhrn hlavních doporučení pro přizpůsobení se změně klimatu v ČR_. a _Příloha č. 4: Souhrn adaptačních opatření_ (kromě sekce Vodní režim v krajině a vodní hospodářství Opatření pro zajištění stability vodního režimu )

**Comment by ondraspribyla** [comment]
přeneseno do notionu, obecné issue, které pouze obsahuje knowledge base nemá smysl držet.
