### ISSUE TITLE
Zkompletovat stránky k datasetům

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#391]
Integrační issue k #358 , #360 k de budeme integrovat vystupy z #378, #379, #380, #381.

Text k Emise sveta: https://docs.google.com/document/d/1rWsGxba2qlRM79_EA1rkYYDEkROZCs4CNqOWM-__xrg/edit

Text k Koncentrace CO2:
https://docs.google.com/document/d/1Nn4-E5Rw6Csa-acJ6xs5lAAQcK92DQmSNCPLU21LbeU/edit

Text k Teploty CR:
https://docs.google.com/document/d/1LEOzIATi4SoyVkrYiMqWnzESnvAU5zx2JDheZqE2Kf4/edit#heading=h.ybmu8lmlmnl4
(zatím pahýl, Marek to slíbil doplnit)

Text k Emise CR/EU: 
https://docs.google.com/document/d/16CVqAvURT7LvwvU8eJp9Affm7Igg0vnIuh3z0kYcLio/edit?ts=5e46cd3c#

**Comment by mukrop** [comment]
Ak chceme byt zodpovedni a dosledni (a podla mna chceme :-P), bolo by vhodne popisat aj licenciu povodnych dat (a idealne to doplnit aj do toho gDocu na listy, ktore tie data maju skopirovane). Co myslis @jankrcal?

**Comment by jankrcal** [comment]
Ano, plně souhlasím. Sám jsem ty licence začal nezávisle dohledávat :)

**Comment by mukrop** [comment]
Toto issue navehujem zavriet. Vsetko je v PR #475, texty, ktore su neurobene maju svoj vlastny issue (napr. #380).
