### ISSUE TITLE
Další zdroje a odkazy: knihy

### ISSUE THREAD

**Issue by tomas-psorn** [faktaoklimatu/web#398]
Je treba upravit stranu so zdrojmi:
* Pridat kazdemu zdroju do `data/resources.yml` novu polozku `type` s hodnotou `online-cs`, `online-en` alebo `book`.
* Pridat datovu polozku pre _There is no planet B_ (text nizsie, obrazok a URL dohladat).
* Prerobit stranku `_stranky/zdroje.html` tak, aby mala 3 sekcie (knihy, ceske weby, anglicke weby) v samostatnych `<div class="section">` a s nadpismi (a kratkym uvodnym textom?).

---
EDIT: Původní popis issue:

Chtěli bychom rozčlenit na stránku "Další zdroje a odkazy", na které jsou nyní odkazy na weby, na sekce. Kromě existující sekce o webech, by mohla vzniknout další o knihách, do budoucna třeba sekce o dokumentech, nebo podcastech. Odkazy by doprovázely podobné texty, jako ty, které tam jsou teď k těm odkazovaným webům. Shrnutí obsahu, motivace proč si to přečíst.

Můžu poprosit @mukrop jestli bys nezvážil, jakým způsobem by bylo možné tam tu sekci přidat?

První kniha, které se to týká je There is no planet B (autor: Mike Berners-Lee), o té teď píšu. Pokud by chtěl někdo doporučit nějakou relevantní knihu, napište prosím odstavec a přidejte ho k této issue.

**Comment by tomas-psorn** [comment]
Text k There is no planet B:

Kniha There is no planet B je koncipovaná jako série každodenních otázek, která nás postupně provádí různými tématy souvisejícími se změnou klimatu. Jaká je uhlíková stopa jednotlivých potravin? Může nás spasit jaderná fůze? Mám si koupit elektromobil? Autor odpovídá za pomocí čísel podložených vyčerpávajícím výzkumem. Čtenář tak získá představu o tom, jak může každý den malým dílem přispět k záchraně planety A. Z knihy je navíc patrné, ve kterých oblastech je možné dosáhnout výrazného systémového zlepšení (např. ve které fázi produkce potravin lze zásadním způsobem omezit ztráty) a jaké snahy přinášejí naopak spíše marginální výsledky.

**Comment by tomas-psorn** [comment]
@protivinsky navrhoval [A Bright Future](https://www.goodreads.com/book/show/40223272-a-bright-future?ac=1&from_search=true&qid=q5sRXjCOMQ&rank=1). Je tu někdo kdo ji četl?

**Comment by mukrop** [comment]
@tomas-psorn prepac, nejako som si tu ziadost o vyjadrenie nevsimol dlhsie. Upravil som issue tak, aby to bola zapracovatelna IT praca. Po pridani There is no planet B sa uzavrie. Napady na dalsie knihy prosim do wiki, ked budu na rozpracovanie, tak do issues.
