### ISSUE TITLE
Teplotni a emisni data pro Slovensko (+Hu +Pl??)

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#400]
Najít teplotní data pro Slovensko, zpracovat je a udělat ekvivallentní graf nárůstu teplot

Z dat emisí, které máme vytáhnout data pro slovensko, najít data emisních povolenek pro slovensko a rozředit k největším emitentům... zpracovat a udělat ekvivalent ke grafu emise-cr-detail

**Comment by VladaSedlacek** [comment]
Relevantní odkazy:

Climate Explorer - nejobsáhlejší zdroj, obsahuje teploty přímo pro jednotlivé státy, a umožňuje stahovat data (i vzhledem k několika různým zdrojům a modelům) ale je potřeba je správně interpretovat (příklad v příloze)
https://climexp.knmi.nl/plot_atlas_form.py

[time_noaa_temp_Slovakia_mon1_ave12_dump0.txt](https://github.com/faktaoklimatu/web/files/4205984/time_noaa_temp_Slovakia_mon1_ave12_dump0.txt)

SHMÚ - teploty vzduchu i půdy, ale jen od roku 2009 (i když normálové období je od 1961)
http://www.shmu.sk/sk/?page=1&id=klimat_operativneudaje1

Fyzická geografie - málo dat, jen přehled
https://geography.upol.cz/soubory/lide/smolova/RGSR/ucebnice/fg/klima.html#teplota

Meteoblue - měsíční údaje za poslední dva roky (detailní data jsou dost draze zpoplatněna)
https://www.meteoblue.com/cs/po%C4%8Das%C3%AD/historyclimate/weatherarchive/slovensk%c3%bd-raj_slovensko_723572?fcstlength=1m&year=2019&month=1

**Comment by ondraspribyla** [comment]
Tato práce pro nás momentálně nemá priotitu - zdroje přehazuju do WIKI a zaviram
