### ISSUE TITLE
Aktualizovat grafiku koncentrace-co2 s rekordní hodnotou pro rok 2020

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#406]
Dataset SCRIPPS zatím obsahuje jen rok 2018, jiné datové sety (jako např. přímá měření na Mauna Loa) se liší řádově o 1-2 ppm, tak to není korektní přímo slepit.

Bylo by dobré postupně kontrolovat, kdy se objeví údaj za rok 2019 a dataset aktualizovat.

Náš data set: https://docs.google.com/spreadsheets/d/10Ku7uOPfDmbvrzWFtvlqvZ-ImWbS6QDHrxKtRIyO4r4/edit
Next Action: 04/01/2020 - zkonotrolovat zdrojová data

**Comment by jankrcal** [comment]
Pořád v datasetu nemají rok 2019.

Next Action: 06/01/2020 - zkontrolovat data
(link merged_ice_core_yearly.csv na https://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products.html)

**Comment by jankrcal** [comment]
Až se to bude dělat, tak je samozřejmě taky potřeba aktualizovat data ke Keelingovi (https://scripps.ucsd.edu/programs/keelingcurve/ nebo ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt) a aktualizovat graf.

**Comment by jankrcal** [comment]
Pořád tam nemají hodnotu za 2019. Pokud to nebude za další půlrok, tak je to za mě na zvážení, jestli tu grafiku nepostavíme na jiných datech (nespojíme si ice core a současná měření nějak sami).

Next Action: 01/01/2021 - zkontrolovat data
(link merged_ice_core_yearly.csv na https://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products.html)

**Comment by jankrcal** [comment]
Teď jsme se s @ondraspribyla shodli, že v grafice zobrazíme místo hodnoty 406 dosavadní rekordní hodnotu. Konkrétní wording TBD.

**Comment by jankrcal** [comment]
Shrnutí pro grafiky: protože dataset SCRIPPS končí rokem 2018 a stále se ne a ne aktualizovat, navrhujeme (s Ondrášem):
 - nechat graf v grafice CO2 stejný (protože nemáme novější data),
 - místo hodnoty 406 vpravo nahoře uvést hodnotu 417 (klidně úměrně posunout nahoru)
 - k této hodnotě udělat hvězdičku s komentářem dole nebo šipku s komentářem:
    "dosavadní maximum z května 2020"
  kdyby to bylo moc dlouhý, tak stačí asi i jen "květen 2020" nebo "dosavadní maximum"
 - horní svorku možná aktualizovat na "2020 let"

Tohle je v podstatě jen pro kompatibilitu s novou (sezónní) grafikou co2+o2.

@kikinna Budeš tu grafiky přebarvovat (a můžeš to udělat) nebo mám poprosit Katku, jestli by na to našla čas?

**Comment by katkolouchova** [comment]
@jankrcal @ondraspribyla Grafiku jsem zaktualizovala, nicméně mám otázku, zda nepřidat i hodnotu pro rok 2019, protože je tam takhle velký skok a čtenáře by mohlo zajímat, proč daný rok chybí. Případně mě napadlo uvést to, že pro rok 2019 nemáme data k poznámce s *, ale to by asi nedávalo moc smysl, když máme data prok 2020 :)
![Koncentrace CO2 v3 0_koncentrace-co2](https://user-images.githubusercontent.com/49321752/89210291-2803db80-d5c0-11ea-9b0e-a517895ebf83.png)

**Comment by ondraspribyla** [comment]
Data mame, akorát to není ten stejný "homogenizovány" dataset, ve kterém se zobrazují středové hodnoty za každý rok a nikoliv rekordní...

Koukal jsem se na grafiku, raději bych, aby byl rekord za 2020 plynule napojen na zobrazenou řadu, vysvětlení, že jde o rekord za 2020 nechme (je to korektní) a pokud by někdo řešil podkladová data, bude možné takto vysvětlit nesrovnalosti v dataestech

**Comment by kikinna** [comment]
Ahojte, nemám z toho úplně dobrý pocit. Možná něco nechápu, takže prvně
napíšu své předpoklady:
1. Data končí rokem 2018, pak je přeskočen rok 2019 a uvedena hodnota z
května 2020
2. Data do roku 2018 jsou jiného charakteru (možná ty středové hodnoty?
Tady se můžu snadno mýlit) zatímco hodnota za rok 2020 je rekordní hodnota
(aneb aktuálně peak).

Pokud nemám správné předpoklady, tak se omlouvám.

Pokud mám správné předpoklady,
pak na mě tato grafika působí dost nedůvěryhodně. Opravdu vizuálně to
sděluje, že je mega skok za poslední rok, protože se přeskakuje rok 2019 (a
holt, sděluješ primárně a okamžitě vizuálně, sekundárně si to možná někdo
sem tam přečte, nicméně ten rok 2019 není ani zmíněn v hvězdičce a teda
hvězdička za rekordní hodnotu z roku 2020 je vlastně stejně dost "schovaná"
v celé grafice.
Takže bych navrhla, že pokud všechna data nejsou stejného charakteru, pak
je třeba je jednak jednoznačně odlišit (nejspíš barevně) a taky ukončit tu
původní řadu s rokem 2018 - nechat tam ten popisek, jak byl. To znamená
vzít tu grafiku tak, jak byla + přidat třeba modrý bod a udělat k němu
popisek, že to je aktuálně rekord za květen 2020 a říct, že víc info u nás
na webu.

**Comment by ondraspribyla** [comment]
Katko, zavoláme si a vyřešíme nutnou úpravu.
---
Kristy, prosím o trochu perspektivy: tohle má být korekce grafiky na
problém který řešíme (že aktuální rekord, o kterém potřebujeme mluvit je ve
zjevnem rozporu s tím co grafika ukazuje)

Nemůžeme předělávat barvy různých typů dát - moc práce (ani sama nevíš
kolik typu dát v té jedné care je) a byla by to další matoucí signál pro
čtenáře.

Prosím důvěřuj že vědeckou správnost (v rámci možností zobrazení) si
ohlidam.

Dne po 3. 8. 2020 23:54 uživatel kikinna <notifications@github.com> napsal:

**Comment by katkolouchova** [comment]
@ondraspribyla Jasně, zavolejme si.

@kikinna Kristi, díky za zpětnou vazbu. Souhlasím s tím, že by extrém z roku 2020 mohl být barevně odlišen, aby bylo jasné, že se nejedná o středovou hodnotu, jako u předchozích dat. To není zase taková práce navíc.

Předpokládám, že ta hodnota bude doplněna i s vysvětlením do datasetu?

**Comment by ondraspribyla** [comment]
...takže po třech hodinách studia datových sad z Mauna Loa, Jižního pólu a Aljašky, zjištění způsobu výpočtu hodnot pro agregovanou řadu, kterou od scripps institutu přebíráme, prohledávání novinových článků které vyšly a řeší koncentrace co2 (většina vychází k příležitosti rekordu a uvádějí jeho hodnotu), přemýšlení nad několika variantami zobrazení a jejich nedokonalostmi docházím k následující prosbě o dokončení grafiky: 

---
**- datové body pro zobrazení: 
rok 2019 hodnota 408.53 ppm
rok 2020 hodnota 411.15 ppm
Tyto hodnoty odpovídají způsobu výpočtu chybějících hodnot v datové sadě, která agreguje data z ledovců a měření, tedy až bude datová sada aktualizovaná bude aktualizovaná těmito hodnotami. (možné korekce v řádu setin ppm)

- datový bod pro "rekord"  nezobrazujme.

- text 417 ppm prosím nechat, včetně hvězdičky a textu "Dosavadní maximum z května 2020"**
---
Ano, vím, že zobrazená "tečka" za rok 2020 je v poloze 411.15 ppm, což není 417ppm. Je to nejlepší z možných kompromisů toho co zobrazit, aby to bylo široce použitelné a nestahovalo to pozornost k nerelevantním detailům. Všechny ostatní varianty vytvářejí v mysli čtenáže nebo posluchače přednášku otázky, které odvádějí pozornost od hlavního sdělení...

Podrobnější zdůvodnění nebo diskusi prosím osobně nebo telefonem + po tom, kdo bude diskutovat budu chtít, aby si nejdřív sám prošel (a vykreslil) data z Aljašky, Jižního pólu a Mauna Loa a udělal základní rešerši o tom, jak o koncentracích co2 reportují světové deníky

**Comment by katkolouchova** [comment]
@ondraspribyla [Zde](https://www.dropbox.com/sh/j0vp07ntc36jjmm/AAB5ZyqxJjBFmZJW6X_iUSA8a?dl=0) najdeš export upravené grafiky.

**Comment by ondraspribyla** [comment]
closed via #621
