### ISSUE TITLE
Slovníček - uhlíková neutralita, unabated coal use

### ISSUE THREAD

**Issue by VladaSedlacek** [faktaoklimatu/web#413]
Nové pojmy na přidání do slovníčku:

**Uhlíková neutralita**
Stavu, kdy se vypouštěné emise rovnají množství emisí skleníkových plynů, které jsou z atmosféry přírodními či technologickými procesy absorbovány.

**Unabated coal use**
Nevím, jak správně přeložit do češtiny; mám za to, že to má technický význam. (Tento pojem se vyskytuje např. v IPCC SR15, viz Issue #254.)

**Comment by protivinsky** [comment]
Pridal bych take heslo pro ETS - Emissions Trading Systems.

**Comment by ondraspribyla** [comment]
Uhlíková neutralita přidána (budoucí PR). Zavírám
