### ISSUE TITLE
Vytvořit stránku "Pro média"

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#416]
Dospeli sme s Kikou k tomu, ze potrebujeme stranku "Pro media"/"Pro novinare". Obsahom by bolo nase velktorove logo na stiahnutie, kratky odstavcovy popis projektu, ktory sa da prebrat, kratky popis o time a doporucenie, ze ak chcu ukazkovo vlozit obrazok nejakej inforgafiky, ktore preferujeme (a vo vseobecnosti, ako nas citovat). Asi pripomenut kontakt, ze nam mozu napisat.

(Dospeli sme k tomu, ked sme videli kratky clanok v EM, ktory prebral jednu trochu nevhodnu infografiku a pri popise timu pouzival nase formulacie – ktore neboli idealne.)

**Comment by setcz** [comment]
Odkládám sem myšlenky pro sebe. Koukal jsem na https://ourworldindata.org/how-to-use-our-world-in-data  - myšlenky, co si z toho beru a nápady, co mě napadly:
- Přidat na titulku webu za větu "Shromažďujeme data o klimatu a klimatické změně, která poskytují vědecké instituce (ČHMÚ, NASA, Eurostat a jiné) a zpracováváme z nich grafy a infografiky pro další použití." odkaz "(jak je použít)", který povede na infostránku. 
- dát tento odkaz i ke každé infografice, do sekce "SDÍLENÍ A LICENCE"
- volitelně: napsat přímo do všech obrázků licenci (teď je jen vedle obrázku)

Na té info stránce "Jak použít naše infografiky":
- říct, jak použít infografiky, co znamená licence CC-BY
- přidat doporučení jak citovat Fakta o klimatu a jak na to odkazovat
- dát kontaktní mail na dotazy či pro podněty 
- dát odkaz na krátké shrnutí o projektu a o týmu za ním stojícím

**Comment by jankrcal** [comment]
Mne prijde, ze by tam mel byt i velmi snadny kontakt na konkretniho cloveka / konkretni lidi v tymu, co resi kontakt s novinari. Tedy fotka, telefon, email.

V teto fazi asi nejspis @ondraspribyla, tedy to, co pisu, samozrejme visi na jeho souhlasu :)

**Comment by ondraspribyla** [comment]
ano, souhlasím a počítám s tím, že budu kontaktní osoba...
Jen nemám jasno, jestli si kvůli tomu pořizovat drhy "pracovní" mobil :-)
asi ne.

O.

**Comment by setcz** [comment]
Výstup dnešní práce společně s Markem (Krčálem) - a připomínkama od @jankrcal a @protivinsky - https://docs.google.com/document/d/1Az2Ye3McsP2VVxlpa_gDdhsyYNV5wDCal_-VNyxvxEc/edit

Je to ve stavu téměř hotového návrhu textu stránky (plus kam na ni přidat odkazy).

Další kroky:
1. dostat další připomínky od dalších lidí (kdokoliv, kdo chce)
2. upravit text do finální podoby (@setcz)
3. překlopit to do webu (???)

**Comment by mukrop** [comment]
@setcz: Ak chces, mozme ti ukazat ako a nejaky zaklad si nahodis sam. (Zalezi, ci mas chut sa to ucit a skusat nove veci.)

**Comment by setcz** [comment]
Tohle je hotové. https://faktaoklimatu.cz/jak-pouzivat

**Comment by mukrop** [comment]
OK, asi v tomto stave na teraz staci :-).
