### ISSUE TITLE
Doplnit datový soubor k Zpoplatnění Emisí

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#417]
nové grafice Zpoplatnění Emisí chybí soubor naše zpracovaná data. Je potřeba jej vytvořit, v poddstatě jde o to přepsat čísla z grafiky do Gsheetu

**Comment by JarekParal** [comment]
@mukrop Klidně se toho mohu ujmout, jak řešíte správu Google Dokumentů? Je nějaký společný GDrive?

**Comment by mukrop** [comment]
Podrobnejsie instrukcie cez IM.

**Comment by JarekParal** [comment]
Tabulka by měla být připravena na GDrivu pod názvem `Rozpracováno-Zpoplatnění emisí: Rozšíření ve světě (faktaoklimatu.cz)` (složka `img / draft / Emise skleníkových plynů v ČR podle sektorů` - umístěním jsem si nebyl moc jistý). 

@protivinsky říkal, že ještě poladíte finální podobu. Kdyby bylo ještě potřeba s něčím pomoct, dejte vědět.

**Comment by JarekParal** [comment]
Připravil jsem PR #442 s upraveným odkazem na tabulku. U tabulky jsem zatím ponechal prefix `Rozpracované-`, protože čeká ještě na finální kontrolu.
