### ISSUE TITLE
Zobrazování souvisejících infografik

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#427]
* [ ] Omezit související infografiky na 4 (aktuálně se zobrazují všechny).
* [ ] Zorazovat náhodný výběr (aktuálně se zobrazují dle atributu `weight`).

**Comment by JarekParal** [comment]
PR #438 řeší oba požadavky, ale náhodný výběr je proveden jen při generování stránek (úpravě obsahu na GitHubu). Pokud by se měla zobrazovat návštěvníkovy po každém načtení jiný výběr, bylo by potřeba implementovat úplně jiné řešení asi v kombinaci s JavaScriptem.

**Comment by mukrop** [comment]
To mas pravdu, to som si neuvedomil. Lepsie by to bolo pri refreshi, ale je to drobnost, aj takto je to pouzitelne. Navyse riesenie cez `sample` je kratke a elegantne.
