### ISSUE TITLE
Nezobrazování tlačítka dat

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#428]
Aktuálně se tlačítka nezobrazují, není-li atribut `data-our` nebo `data-orig` vůbec definován. Je potřeba upravit, aby se nezobrazovali ani když je definován, ale je to prázdný řetězec nebo prázdný seznam.

**Comment by JarekParal** [comment]
@mukrop Zkusím se na to podívat.

**Comment by JarekParal** [comment]
Mám fix pro prázdný řetězec v `data-our`. Testoval jsem prázdný seznam v `data-orig`:
```
data-orig: []
```
A zdá se, že už v aktuálním kódu je o to postaráno.
Nebo je požadavek na `data-orig`, aby v něm mohl být prázdný element:
```
data-orig: [["", ""]]
```
@mukrop ?

**Comment by mukrop** [comment]
Ja som to netestoval ani s `[]`, takze je mozne, ze to fungovalo. Dik za drobnu upravu a otestovanie :-).

**Comment by mukrop** [comment]
Hotovo.
