### ISSUE TITLE
Poslat newsletter + update aktualit

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#431]
standardni poslani newsletteru (tinyletter) + update aktualit.
Stačí update za věci, tkeré se staly dosud ( od posledniho newsletteru tzn od ledna? byly jen dvě grafiky?)

**Comment by mukrop** [comment]
Len dodavam, ze v niektorych pripadoch sa menili data (napr. opravy pre emisie, mozno aj nieco ine). Chceme mat politiku, ze toto a v aktualitach objavuje (a do buducna by sa to malo objavit rovno v tom PR).

**Comment by crysman** [comment]
draft zde https://docs.google.com/document/d/1W3nrVuz-wkj-kHuaoaCWUnSh3mh8eBYPEOpO3kK1Rco/edit# dodělám o víkendu a pošlu Ondrášovi k autorizaci před odesláním

**Comment by crysman** [comment]
weboaktuality ready https://github.com/faktaoklimatu/web/pull/444

**Comment by crysman** [comment]
newsletter verze crysman-1.0 ready ke korektuře @ondraspribyla https://docs.google.com/document/d/1W3nrVuz-wkj-kHuaoaCWUnSh3mh8eBYPEOpO3kK1Rco/edit?disco=AAAAGR1zCHc

**Comment by crysman** [comment]
newsletter odeslán na 100 subscriberů, zavírám
