### ISSUE TITLE
Doplnit text o měření koncentrací CO2

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#447]
Text stránky https://faktaoklimatu.cz/infografiky/koncentrace-co2 je zatím celkem neúplný. Dal by se krásně doplnit o dva odstavěčky o následujících článcích:  

Historie měření, použité aparáty apod:
https://pubs.acs.org/doi/full/10.1021/ac1001492

Další historické poznámky, zejm. podrobnosti o isotopové stopě
https://www.acs.org/content/acs/en/education/whatischemistry/landmarks/keeling-curve.html

---
Úkol: přečíst články, sepsat z nich krátký výtah (několik nejzajímavějších odstavců z každého článku) a pak zkusit napsat jednoodstavečkovou anotaci na každý z článků, která pak bude vložena do hlavní stránky  o koncentracích CO2

**Comment by mukrop** [comment]
NEpatri to skor do novovznikajucich stranok o datovych sadach? Ako to bude
s prekryvanim textov?
Patria informacia o zbere dat k datovym sadam, alebo k infografikam?

>

**Comment by ondraspribyla** [comment]
Issue je primárně o vytvoření toho textového výtahu. Jestli to nakonec dáme
k datové sadě, textu iiinfografiky nebo k obojímu rozzhodneme až to bude
trochu hotový...

**Comment by ondraspribyla** [comment]
souvisi s #476

**Comment by ondraspribyla** [comment]
Odkazy jsem dal do Pull requestu #594 - myslím, že to zatím takto stačí. 
Na podzim budeme dělat koncepční update textů a implementovat zpět co jsem se naučili při dělání textů v Atlasu - pak možná texty zakomponujeme koncepčněji. Tedˇnavrhuju zavřít...
