### ISSUE TITLE
Grafický výtah: Národní adaptační strategie

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#448]
Zpracovávaný dokument: https://www.mzp.cz/cz/zmena_klimatu_adaptacni_strategie

Tabulka pro grafický výtah
https://docs.google.com/spreadsheets/d/18YAJuU9SLfiAuFPqBjXR7d39-k_0kCJ6DZattEgyURQ/edit?usp=sharing

Výpisky z oficiálního dokumentu
https://docs.google.com/document/d/1H9KoxhtPh9ueabNH4GuGC0lI9xTfMiQr_tJTIv_qb8Y/edit?usp=sharing

![Adaptační strategie-21-21](https://user-images.githubusercontent.com/11555522/76706692-d5498600-66e9-11ea-8455-27de21b5df3f.png)

**Comment by ondraspribyla** [comment]
Romana Brezovska nam k tomu drive napsala: 

Jinak co se týče Adaptační strategie, tak je to dokument schválený vládou, což mj. znamená, že by měl být závazný pro resorty, především pro ty, pro které z AS vyplývá nějaký úkol. Jednotlivé úkoly jsou popsány v Národním akčním plánu, to je implementační dokument Strategie. Bližší info s odkazy: https://www.mzp.cz/cz/adaptace_na_zmenu_klimatu.

V těchto chvílích se zrovna dokončuje hodnocení plnění Strategie a tento úkol provádí CENIA (https://www.cenia.cz/#aktuality_). Hodnocení by mělo být hotové cca do měsíce a finální verze bude uveřejněna na stránkách MŽP.

Samotná strategie byla vypracovaná MŽP, na začátku dokumentu se uvádí, že:
Zpracovalo Ministerstvo životního prostředí v meziresortní spolupráci svyužitím klimatologických podkladů Českého hydrometeorologického ústavu.Na přípravě materiálu se podílely zejména resorty životního prostředí, zemědělství, průmyslu a obchodu, pro místní rozvoj, zdravotnictví a vnitra.Návrh strategie byl revidován Centrem pro otázky životního prostředí Univerzity Karlovy v Praze a konzultován s Centrem výzkumu globální změny AV ČR.

**Comment by tomas-psorn** [comment]
Nová verze tabulky po zapracování zpětné vazby od Romany a Jarka (v tabu v2):

https://docs.google.com/spreadsheets/d/18YAJuU9SLfiAuFPqBjXR7d39-k_0kCJ6DZattEgyURQ/edit#gid=1080422027

Dodělali jsme kategorizaci projevů klimatu, které se týkají jednotlivých oblastí, nově používáme jen tyto kategorie:
- sucho
- teplé zimy
- eroze půdy
- extrémní srážky a povodně
- extrémní teploty

Romana navrhuje zmínit v doprovodném textu i další dokumenty MZP, konkrétně:
- Národní akční plán adaptace na změnu klimatu (https://www.mzp.cz/cz/narodni_akcni_plan_zmena_klimatu), ve kterém jsou také uvedeny projevy/oblasti/dopady (mj. také konkrétní úkoly pro jednotlivé aktéry, jedná se o implementační dokument strategie)
- vyhodnocení akčního plánu z roku 2019 (https://www.mzp.cz/C1257458002F0DC7/cz/adaptace_na_zmenu_klimatu/$FILE/OEOK-vyhodnoceni_NAP_AZK-20200221.002.pdf)
- aktualizová komplexní studie dopadů (https://www.mzp.cz/cz/studie_dopadu_zmena_klimatu)

Jak vyhodnocení, tak i Aktualizovaná komplexní studie slouží jako podklady pro aktualizaci Adaptační strategie a akčního plánu.

Jarek navrhuje zaměřit nějaké další infografiky na konkrétní adaptační opatření.

**Comment by kikinna** [comment]
@ondraspribyla Ahoj, nahrála jsem nahorů nejaktuálnější rozpracovanou verzi tabulky. 
Jsou tam zatím ty dlouhé popisky tak, jak byly. Asi dva jsme s Tomem o kousek zkrátili (ještě než jsem se ti stěžovala, hh) a teď je otázka jestli je to za nás takhle hutné textem a informacemi okej. Hlavně to chce vyzkoušet vytisknout, jestli to je čitelné (a to teď moc nemám možnost, tak zkusím přes týden). 

Jak to na tebe prosím působí takhle?

**Comment by kikinna** [comment]
Test tisku vyšel dobře. Písmo je čitelné, tak nejspíš není třeba zkracovat texty. Yay ))

**Comment by ondraspribyla** [comment]
Náhodou jsem našel, že CENIA zpracovala v roce 2020 zprávu... @tomas-psorn je relevantní na ni dát odkaz do textu NAS? 
https://www.cenia.cz/wp-content/uploads/2020/07/Indikatory_Zranitelnosti_2017_opr.pdf

**Comment by ondraspribyla** [comment]
Hotovo - uzavírám.
