### ISSUE TITLE
označení nových infografik ala "NOVÉ" v rožku thumbnailů

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#449]
toto je kosmetický návrh - že bysme začali označovat nové infografiky, prostě nějak takto:
![image](https://user-images.githubusercontent.com/5269350/76256489-53bca880-6250-11ea-9c82-5255dfb078da.png)

ten flag "NOVÉ" by tam byl ideálně s nějakým auto-timeoutem, ale vzhledem k pravidelným hackathonům to není nutné

zároveň chápu, že to řadě lidem přijde kontroverzní či nevkusné - nemám silnou vůli to prosazovat ;)

**Comment by mukrop** [comment]
Znie to zaujimavo.

**Comment by ondraspribyla** [comment]
Nápadu rozumím, ale v mém dněšním rozpoložení mám chuť ho rovnou zavřít.

Drobnosti tohoto typu nepřinášejí zásadní přidanou hodnotu pro uživatele
(novináře), přidávají komplexitu pro mě na koordinaci a sledování všech
tasků a rozmělňují fokus lidí, kteří na projektu pracují.

Klíčové projekty z hlediska funkcionality jsou DATASETY JAKO PRODUKT (a
související uklizení a systém datových sad) a VYHLEDÁVÁNÍ PODLE TAGU (a
související systém tagování)
Klíčové projekty z hlediska dat a textů jsou nová(stará) témata: delší
teplotní řady, počty tropických dnů, emisní intenzity, voda, scénáře
budoucího vývoje... a výtahy ze zpráv IPCC.
Klíčové projekty z hlediska PR jsou kontakty a networking, zejména s
novináři, v budoucnu s učiteli a politiky.
Klíčový projekt z heldiska struktury je založení ústavu.

Flag "Nové" mi přijde jako ladění nálepek na karoserii v situaci, kdy
potřebujeme, aby auto mělo výrazně vyšší výkon a stabilnější řízení.

Pokud je flag "Nové" tvůj love-project, tak ho zkus naprogramovat a předat
tak, aby se tím ostatní nemuseli zabývat.
Pokud máš sílu vzít si nějaký z klíčových projektů, budu moc rád.

O.

**Comment by crysman** [comment]
Rozumím, že vnímáš priority jinde - a říkáš přesně, kde. Zároveň nabízíš možnost realizace, pokud je to moje citovka, což vítám.

Navrhuju to speciálně otagovat jako "tuning" či tak něco, a schovávat tyto nápady bokem - bude se nám to určitě dít častěji - někdo přijde s nekritickým nápadem.

Rád bych, aby tyto věci nemizely, ale měly specifické místo - s rozšiřující se základnou spolupracovníků roste šance, že se někdo bude mít chuť realizovat v některé z těchto věcí.

Může být?

**Comment by ondraspribyla** [comment]
Na nápady máme wiki. V IT oblasti je jen hrubá, ale dá se to vylepšit
používáním:
https://github.com/faktaoklimatu/web/wiki/N%C3%A1pady-na-funkcionalitu-webu

Pokud to nemáš jako issue na kterém chceš aktuálně dělat, tak bych
preferoval, abys to přesunul do wiki.

S "rozšiřující se základnou" komunikuju momentálně hlavně já a Martin a
moje (nevím jak jeho) zkušenost je, že je mnohem lepší mít issues méně a
přehledné...
Pro mě je tedy tohle issue balast, který komplikuje možnost soustředit síly
(moje i druhých)

O.

**Comment by crysman** [comment]
Tak to vypadá, že github nám neumožňuje shromažďovat nápady jako issues, resp. možná jen nevíme jak na to, protože **github to v principu umí** - takto si zobrazím všecky issues, co **ne**jsou `fine-tuning`:
![image](https://user-images.githubusercontent.com/5269350/76468045-4ee02c00-63eb-11ea-985c-362d9d4b39af.png)
https://github.com/faktaoklimatu/web/issues?q=is%3Aissue+is%3Aopen+-label%3Afine-tuning

V současné době github po kliknutí na `Issues` otevírá toto:
https://github.com/faktaoklimatu/web/issues

Dokážu si ale představit, že někde v nastavení projektu to de změnit právě na
https://github.com/faktaoklimatu/web/issues?q=is%3Aissue+is%3Aopen+-label%3Afine-tuning

což? @mukrop ?

Tím bychom se mohli zbavit nepřehledných WIKI - ano, vím, že to není dávno, co jsme to dělali právě naopak, ale udržovat to v issues je obecně mnohem výhodnější...

Pokud to, čeho jsme se snažili dosáhnout přesunem do WIKI, je **přehlednost** a **nezahlcenost**, tak to můj nápad řeší, a navíc má všechny benefity issues, které WIKI postrádá...

(A ano, toto je metaproblém, a neposunuje nikam data, což Ondráše teď zrovna možná štve nebo mrzí. Nicméně, kdybych nevěřil v jeho užitečnost, nediskutuju to tady)

Takže... Martine? Má nápad šanci? (nemám žádný soukr. github projekt, abych se mohl podívat)

**Comment by jankrcal** [comment]
Morálně podporuji crysmana (taky by se mi moc líbilo vést úkoly nižší priority jako issues, jen nějak chytře schované, aby nám netříštily pozornost).

Bohužel se nezdá, že by to bylo na githubu možné, viz tako diskuse
https://github.community/t5/How-to-use-Git-and-GitHub/Can-you-change-the-default-issue-filter-options-for-a-project/td-p/10424

Nalézt nějaké řešení by tedy vyžadovalo víc diskuse s Ondrášem a v týmu o workflow a to za to (za mě) momentálně nestojí.

**Comment by crysman** [comment]
díky, hodil jsem tam 
![image](https://user-images.githubusercontent.com/5269350/76504981-f770a900-6448-11ea-8cf8-48cbede16567.png)

- třeba, když nás to tam dá hodně, tak to vývojáři dodělají - mám s tím dobrou zkušenost na launchpadu např. Podpoříte to tam taky?

než se to dořeší, převedu tuto konkrétnost do Wiki, ať mají O a M klid

**Comment by crysman** [comment]
hlavní téma přesunuto do wiki: https://github.com/faktaoklimatu/web/wiki/N%C3%A1pady-na-funkcionalitu-webu

možnost mít nápady přímo v issues založeno zde: https://github.com/faktaoklimatu/web/issues/462

tento thread tedy zavírám
