### ISSUE TITLE
Špatné vykreslování odkazů do slovníku

### ISSUE THREAD

**Issue by mgrabovsky** [faktaoklimatu/web#450]
Pokud se odkaz do slovníku `<glossary>` vyskytne jako první věc v Markdownovém odstavci, způsobí to jeho odsazení od zbytku textu, viz sekce emisí a sekce opatření na hlavní stránce.

![Screenshot_2020-03-09 Fakta o klimatu](https://user-images.githubusercontent.com/134321/76262864-ce3ff500-625d-11ea-89fb-02761697dc9e.png)

Technické detaily: Zdá se, že problém nastává někde v konverzi Markdownu do HTML – odkaz do slovníku se ještě v Markdownu nahradí odkazem `<a>` (hook `:site, :post_render` v `_plugins/glossary-tag.rb`), přičemž po konverzi zůstane v HTML odkaz osamocený a následuje za ním blokový odstavec `<p>`. Hlouběji jsem se v tom nevrtal. Pokud to jde, bylo by asi lepší nahrazovat tagy až po konverzi.

Jako hotfix mě napadlo obalit odstavec v `_sekce/*.md` do `<p>…</p>`, ale to zase způsobí nevyrenderování odkazu na uhelnou komisi v sekci mitigačních opatření 🤯

**Comment by mukrop** [comment]
Dik za nahlasenie. Lepsi hotfix je aktualne preformulovat vetu. Ak si
najdes chvilku, kludne to urob.

**Comment by protivinsky** [comment]
Pardon, dival jsem se letmo na issues, ale duplicitu jsem prehledl.

Navrhuji jako hotfix obalit slovnickove heslo + kus textu za tim do <span>...</span> - neni potreba balit cely odstavec, takze by to nemelo mit negativni side efekty. To odradkovani na uvodni strane je prece jen trochu hloupe.

**Comment by mgrabovsky** [comment]
Tak jsem se do toho zakousl a opravil to, a ač trochu nepěkně, o moc hezčeji to asi nepůjde.

Problém tkví v tom, že Kramdown (asi) pokládá neznámý tag `<glossary>` na začátku odstavce za něco jako block-level element a následující text od něj při renderování oddělí pomocí `<p>`. Vyřešil jsem to tak, že nahrazování odkazu provádím těsně před posláním Markdownu, příp. HTML do dalších fází konverze, třeba právě do Kramdown.

Ještě pro úplnost: Původně jsem nesprávně uvedl, že se odkaz nahradí ještě v Markdownu. Ve skutečnosti je tomu naopak, nahrazování probíhalo až po vykreslení všeho HTML v hooku `post_render`.

**Comment by ondraspribyla** [comment]
Sice tomu nerozumím, ale díky, že se o to staráte
:-)

O.
