### ISSUE TITLE
Rešerše: Média a jejich dosah

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#452]
Zjistit čtenost médií (aktuálně.cz - hospodářky, respekt...)
jejich specifické cílovky 
a jejich "nakloněnost" enviro-tématům a klimatu

Dlouhodobý záměr:  na základě těchto podkladů vytvořit "mapu", která nám pomůže orientovat se v mediálním prostoru ČR (třeba abychom uměli odhadnout, kolik lidí zasáhneme, když vyjde článek v irozhlas nebo když vyjde článek na aktuálně.cz)

**Comment by setcz** [comment]
Docela dobrá data jsou tady:

-  typologie českých konzumentů zpravodajství s nejčastěji konzumovanými médií každou skupinou (z výzkumu Medianu) - http://www.mapamedii.cz/segmenty/index.php
- čtenost zpravodajských webů - http://www.mapamedii.cz/mapa/navstevnosti/index.php

(stojí za to projít i zbytek webu)

**Comment by ondraspribyla** [comment]
Díky, Sete, za zdroje. Doplním, aby to nemusle nekdo dohledávat po mě:
Typologie českých konzumentů vychází z dat z roku 2016. Čtenost
zpravodajských webů je zz ledna 2019.

**Comment by setcz** [comment]
Zpracovaná tabulka (přípravená společně s @JarekParal ) je zde - https://docs.google.com/spreadsheets/d/1x3LQDNiARx3Ek-7kjFpTHnoX62DiTpkb-Ru1Cql6Fs0/edit#gid=0 

Je třeba dodělat:

- doplnit majitele jednotlivých médií - @JarekParal nebo @setcz 
- doplnit enviromentální náklonnost jednotlivých médií - napsat někomu z katedry Enviromentálních studií na MU-  @ondraspribyla 

(a poznámka pro @setcz - pokud to někdy nějak rozumně sepíšeme, poslat to Marii Heřmanové, autorce tohoto článku, se kterou jsem si o tom psal - https://a2larm.cz/2019/08/ceska-media-a-klimaticka-zmena-pohadka-o-naivni-grete/ - říkala, že ona o žádných rozumných datech taky neví, že článek psala na základě svých dojmů)

**Comment by mukrop** [comment]
@setcz: Podotykam, ze si dnes pracoval s @jcechak (https://github.com/jcechak), nie @JarekParal.

**Comment by setcz** [comment]
> @setcz: Podotykam, ze si dnes pracoval s @jcechak (https://github.com/jcechak), nie @JarekParal.

Děkuju, opraveno.

**Comment by ondraspribyla** [comment]
Poslal jsem prosbu o doplnění Milanu Vítkovi z Greenpeace, který by o tom
mohl mít dobrý přehled...

**Comment by mukrop** [comment]
@ondraspribyla, znamena to, ze toto issue sa moze zavriet? Co je este treba?

**Comment by ondraspribyla** [comment]
stačí v té podobě, jakou kluci udělali. Zavírám.
