### ISSUE TITLE
IPCC Special reports do slovníčku

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#453]
Vytvořit souhrnné heslo pro "special reports" - SR15, SROCC, SRCCL a další, ve kterému bude:
- vysvětleny zkratky nejdůležitějších SR
- vysvětlen vztah SR k annual reports

**Comment by mukrop** [comment]
In progress by Dan Farkac

**Comment by ondraspribyla** [comment]
closed via #490
