### ISSUE TITLE
"Albedo" do slovníku

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#454]
Vysvětlení pojmu albedo, v kontextu klimatu. https://en.wikipedia.org/wiki/Albedo
Nejspíše i krátce naznačit Ice-albedo effect + dát numerické hodnoty albeda pro některé povrchy. 

(text předat Ondrášovi)

**Comment by mukrop** [comment]
In progress by Filip Kessner.

**Comment by ondraspribyla** [comment]
Hotovo.
