### ISSUE TITLE
Lepší 404 page

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#456]
Na stránce 404 zobrazovat náhodný výběr infografik či studií (aktuálně je tam zbytečně dlouhý textový seznam).
* Presnejsie zadanie: Namiesto odrazkoveho zoznamu zobrazovat 6 alebo 9 nahodne vybranych grafik podobne, ako sa zobrazuju "related" na strankach infografik (tj. pouzit include `preview-blocks`).
* Po uprave sa rovno pridaj do [Contributors](https://github.com/faktaoklimatu/web/blob/master/CONTRIBUTORS.md).

**Comment by kikinna** [comment]
Je to nice to have, ale bylo by milé udělat něco vtipného nebo něco v návaznosti na naší tématiku (buď něco s rozbitým klimatem nebo chybějícími daty?)
Jen kdyby vás něco napadlo (anytime in the future).

**Comment by Filip-Kessner** [comment]
vytvořil jsem novou větěv a tam to upravil. Věděl by @mukrop jak potlačit formátování, keré vzniká v {% if} bloku? Jestli ne, nechám text mimo if a vytvořím pull request.

**Comment by mukrop** [comment]
Vyzera to dobre, dik. Ten text sa ti zobrazuje vo formatovani kodu, pretoze riadok s textom zacina tabom. Cely dokument ma pripomu `.md`. takze predpoklada, ze vsetko je markdown. Tj. staci zmazat ten tab (ani nemusis davat `<p>`, to sa pri prevode z MD prida automaticky).
Po tejto malej uprave urob PR a oznac na review mna a @mgrabovsky.
