### ISSUE TITLE
Umístění štítků infografik a datasetů

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#457]
Je treba vymytsliet, kde budu stitky k danej infografike a ako budu vyzerat.
* Predpokladam, ze budu mat vizual ako tlacitka, ale budu trochu mensie?
* Farba nejaka svetlejsia modra? Alebo pouzit tu tmavu modru, co mame vsade?
* Umiestnene kde? Pod nadpisom zarovnane vlavo? V paneli metadat na vrchu? (Aky nadpis?)

Suvisi s #346 a #347.

**Comment by mukrop** [comment]
@kikinna, napises mi nazor na tieto veci?

**Comment by kikinna** [comment]
Marti, co mě k tomu napadá:
- ano, vizuál jako menší tlačítka nebo pilulky mi přijde dobrý :)
- barvu určitě odlišnou od tlačítek, takže buď světle modrou nebo, kdybychom měli štítků omezené množství, tak klidně barvy kategorické - co štítek, to barva (nebo klidně mít třeba jen omezené množství barev/odstínů barvy a to točit?)
- umístění mi přijde trochu tricky - nejvíc jsem asi pro to dát pod nadpis (pomůže to člověku se i zorientovat rychle v tématu) + to podle bude lépe fungovat na telefonech, nemusíme řešit nadpis, atd.
- ještě ne napadá, jestli by nedávalo smysl štítky dávat i k náhledům infografik na hlavních stránkách - mohlo by to taky pomocí v rychle orientaci a návštěvník by hned věděl, že se štítky může nějak pracovat. Co myslíš?

**Comment by mukrop** [comment]
Vyriesene pred nejakou dobou po telefone. Zaver:
* Pilulky pod nadpisom.
* Na titulke na spodnej strane nahladoveho obrazku z bielym gradientom.
*  Stranku tagu nerozkladat na sekcie, ale rozdelit najdene objekty podla typu.
