### ISSUE TITLE
Bug v implementaci slovníčkových hesel

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#458]
Pokud je slovníčkové heslo na začátku textu, zobrazí se na samostatném řádku a navazující text pokračuje na dalším řádku (z nějakého důvodu je v html mimo <p> tag s textem).

Viz například na titulní straně (ovšem narážím na totéž i u jednoho nově připravovaného textu):

![image](https://user-images.githubusercontent.com/9573993/77831198-a7226800-7125-11ea-9267-1dfd07e205d6.png)

(@mukrop - assignul jsem tebe, samozrejme to klidne prehod na nekoho dalsiho, pokud nekdo takovy je po ruce)

**Comment by mgrabovsky** [comment]
Víme o tom. Bohužel jsem ještě neměl čas se na to podívat do hloubky ://

Duplicate of #450.
