### ISSUE TITLE
Grafika: Emisní intenzita II

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#460]
Pokracovani k emisnim intenzitam po vytvoreni prvni grafiky, emise svetovych regionu prepoctene na HDP.

**V tuto chvili vidim dve dalsi moznosti:**
- historicky vyvoj - data jsou k dispozici od roku 1990 (resp. emise od 1970, ale HDP pro vsechny zeme je az od 1990)
- emise na HDP v relativnim, per capita vyjadreni (viz diskuze u #459 )

Historicky vyvoj navrhuje i AMO:
_Historicky vyvoj by byl nejvic. Mozna teda ale dve ruzne grafiky - a) emisni intenzita k poslednimu dostupnemu roku celosvetove, b) vyvoj ve vybranych zemich. Prime srovnani myslim pro tento ucel staci. Pokud jit o krok dal, tak zkusit ziskat data k emisim "na spotrebe", tj pricitatelnost nikoliv dle statu, kde byly vypusteny pri vyrobe zbozi/poskytnuti sluzby, ale tam, kde se realne konzumuje_

**Historicky vyvoj:**
- [CO2eq do roku 2015](http://q.prott.cz/ghg_15/)
- [CO2 do roku 2018](http://q.prott.cz/co2_18/)
- nic finalniho, spis jen zobrazeni vseho dohromady, abych se v tom mohl zorientovat a snad nalezt nejaky ramec, jak to uchopit a pojmout

Co by bylo zajimave doplnit:
- energeticka intenzita ekonomik a emise vzhledem k energii. Podivam se po datech.
- podil emisi v mezinarodnim obchodu. Ackoli emisni intenzita ekonomik dava smysl i bez toho, ne? Vyvoz je take soucasti GDP?

**Emise na HDP v relativnim vyjadreni** - zde pythonem generovany nahled grafiky pro relativni vyjadreni emisi na HDP:

![image](https://user-images.githubusercontent.com/9573993/77847094-5c9afd00-71b2-11ea-99a5-e91fa4b846c3.png)

- na x-ove ose jsou emisni intenzity ekonomik, cim sirsi sloupecek, tim vice produkuji emisi na dolar HDP
- na y-ove ose je HDP na osobu - cim vyssi sloupecek, tim vyssi ~zivotni uroven obyvatel. HDP na osobu je dulezitejsi i proto, ze casto souvisi se strukturou ekonomicke produkce (podil zemedelstvi / prumyslu / sluzeb), tedy je to takto interpretacne cistsi
- plocha obdelniku tedy znamena emise CO2eq na osobu, coz je take zajimavy ukazatel!
- v grafu tak nejsou videt rozdily ve velikostech jednotlivych zemi (at uz mereno jako populace nebo HDP), nicmene prave proto je prime srovnavani zemi zde vyrazne jednodussi
- je snadnejsi se zde zorientovat, ze idealni je uzky a vysoky sloupecek

Pokud by to opet vypadalo podobne, uz by se to nejspis pletlo. Zamyslet se, co s tim, pripadne jestli mame nejake jine smysluplne zpusoby zobrazeni pro tyto vztahy.

Graf je zalozeny na https://docs.google.com/spreadsheets/d/1A1DJVqQEbvs8PfQDrav1i56cfFUIzSL5CAg2jqmXALQ/edit#gid=0

__Notes to self__ k datasetu:
- agregace podle zemi nezahrnuje mezinarodni namorni a leteckou dopravu - dohromady jsou zodpovedne za 1.23 Gt CO2eq v roce 2015 (namorni je mirne vetsi polovina). Pokud budeme nekdy aktualizovat treemapu emise sveta, mozna by stalo za to je zahrnout take - je to temer dvojnasobek Australie a Noveho Zelandu.
- vysvetleni toho, jake emise jsou zahrnute - mozna by stalo za to to doplnit k popisu dataset, aby bylo jasne, proc vynechavame short-cycle: _"All human activities leading to climate relevant emissions are included, except biomass/biofuel combustion (short-cycle carbon) in the power, industry, buildings, transport and agricultural sectors, large-scale biomass burning and land use, land-use change and forestry (LULUCF)."_ (Crippa et al, 2019)

**Comment by ondraspribyla** [comment]
Tome, pro tebe by to mohlo být celkem snadné vygenervat: Jak by vypadal
obrázek, kdyby jsme nechali osy GDP per Capita a GHG per GDP? Jednotlivé
země jako body...

(čáry, které propojují země se stejným GHG per capita by pak byly
hyperboly... ty by pak šlo taky naznačit...) Barevné kodovani kontinentu
bych nechal - bude pak vidět clustery
Zkusíš vygenerovat?

O

**Comment by protivinsky** [comment]
Zajimavy napad!

![image](https://user-images.githubusercontent.com/9573993/77847941-a4248780-71b8-11ea-8c89-cf686c951ca7.png)

**Comment by jankrcal** [comment]
+1

Tohle je za mě výrazně srozumitelnější než předchozí návrh!
(pořád to může být dost složité na porozumění, ale nemám s tím problém)

Že bude Francie vítěz v tomto srovnání, to bych neuhodl :) Jaderné elektrárny holt dělají rozdíl :)

**Comment by kikinna** [comment]
Já jsem nadšená. Ten graf je skvělej! 
(víc se ozvu zítra)

**Comment by protivinsky** [comment]
Byl to výborný nápad, naprosto souhlasím. Ještě bych přidal jednu proměnnou, ať už je tam máme úplně všechny :)

![emise-hdp-per-capita-hyper-pop](https://user-images.githubusercontent.com/9573993/78300584-a0ce2a80-752f-11ea-917e-9989ef3216aa.png)

**Comment by kikinna** [comment]
@ondraspribyla @protivinsky Znamená to, že ten graf můžeme zpracovávat graficky?

**Comment by protivinsky** [comment]
Chci to jeste behem vikendu poslat Tomasi Jungwirthovi, spis informativne. Potom bych urcite smeroval ke grafickemu zpracovani.

**Comment by kikinna** [comment]
@protivinsky Ok, tak mi pak dej vědět. 
Jinak nevím proč, ale ještě nejsem přesvědčená tou velikosti koleček podle populace. Jakoby mi to nepomohlo předat tak moc informací a přitom to odlákávalo pozornost od toho ostatního. 
Zatím to říkám jen v rovině myšlenek.

**Comment by ondraspribyla** [comment]
Ano, graf mi přijde natolik dobrý, že ho stojí az to zpracovat i graficky

O.

**Comment by protivinsky** [comment]
Tusim, ze v patek mame hackaton - zatim ohledne grafu neni zcela jasne, jestli chceme odlisne velikosti bublin, a pokud ano, co by mely kodovat. Pro srovnani jsem vygeneroval velikosti bublin kodujici:

- nic, stejne velke bublinky
- velikost populace
- velikost celkovych emisi
- emise na osobu (tedy duplikujici informaci v hyperbolach)

Tomasi Jungwirthovi se graf libi a je pro, nema prilis nazor ohledne velikosti bublin (klidne mu staci stejne velke). Ja osobne mirne preferuji velikost bublin podle populace, prijde mi to nejcastejsi, snadno srozumitelne a poskytujici nejakou informaci navic.

![stejne-velke](https://user-images.githubusercontent.com/9573993/79386498-23a8a980-7f62-11ea-8a7f-f0f359ee0e70.png)

![velikost-dle-populace](https://user-images.githubusercontent.com/9573993/79386509-2905f400-7f62-11ea-8e51-3fa5565dba0c.png)

![velikost-dle-emisi](https://user-images.githubusercontent.com/9573993/79386522-2c997b00-7f62-11ea-8e60-2202f84ee7bf.png)

![velikost-dle-emisi-na-osobu](https://user-images.githubusercontent.com/9573993/79386534-302d0200-7f62-11ea-8213-6c995ef65ca4.png)

**Comment by ondraspribyla** [comment]
@protivinsky Navrhuju zavrit toto issue, nebot grafiku vyprodukovalo. Zaroven pokud ti z toho porad vypdavaji myslenky na napr. casove prubehy uhlikove intenzity, nebo celou KAYA identity, tak na to zalozme nove issue.

**Comment by ondraspribyla** [comment]
Grafika je hotova, tak zaviram. Vyrvotim nove issue na historicke prubehy emisi / KAYA
