### ISSUE TITLE
podpořit možnost mít nápady v issues umožněním změny defaultního filtru issues

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#462]
DONE by (checklist):
- [x] crysman
- [x] Yeňa
- [x] Matěj
- [ ] ...

TODO:
1. login to github
1. hlasuj +1 zde https://github.community/t5/How-to-use-Git-and-GitHub/Can-you-change-the-default-issue-filter-options-for-a-project/td-p/10424/page/2 + dej tomu _Kudo_ ("thumb up")
1. dodělej si sem ticknutý checkbox, žes provedl/a

GOAL:
až nás tam bude aspoň polovina týmu, crysman zavře

DETAILS (optional):
detaily a historie zde, kdyby někdo potřeboval vědět proč:  https://github.com/faktaoklimatu/web/issues/449#issuecomment-597901267

**Comment by mukrop** [comment]
@crysman: Trochu vaham, kedy je toto issue "zatvoritelne". Aky je tvoj pohlad – kedy ho budes povazovat za splnene?

**Comment by crysman** [comment]
zatvoritelne je za mě v momentu kdy aspoň polovina z nás podpořila +1/Kudem to issue na github community

**Comment by mukrop** [comment]
Ack, to je fajn kriterium. Tym padom si to prosim zober na starost, aby sa tak stalo.

**Comment by ondraspribyla** [comment]
S @mukrop jsme predelali system stitkovani a projektu tak, aby napady mohly byt jasne zarazeny - do projektu Diskuse. Tento projekt bude za ukol bud preklopit do doable issue, nebo zavrit. (nebo neco jineho) - s timto issue zaviram
