### ISSUE TITLE
opravit názvy měsíců na malé v souladu s aktuálním českým pravopisem

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#463]
problém:
V grafech máme názvy měsíců začínající velkým písmenem ("Leden"). Správně je ale "leden", viz např:
- https://www.mojecestina.cz/article/2014111701-psani-velkych-pismen-dny-v-tydnu-a-mesice
- https://prirucka.ujc.cas.cz/?id=180

názor:
Jsem sice purista (jak si Martin všiml, třeba mi hafo vadí nesprávné užívání "_linux_" místo [správného "_GNU/Linux_"](https://www.fsf.org/bulletin/2008/spring/wikipedia)), ale protože český pravopis považuju za nedobře udělaný (hlavně nekohorentní, nekonzistentní, nelogický), tak bych do tohoto konkrétně vůbec nevrtal. Nicméně, pokud chceme vypadat profi (a to my chceme, + credibilita...) tak to asi budeme muset opravit :(

řešení:
Přespsat měsíce na malá počáteční. Pokud vím, týká se jen dvou grafů zde https://faktaoklimatu.cz/#/sekce/teploty

**Comment by jankrcal** [comment]
Mně tam ta velká písmena přijdou konzistentní s tím, jak obecně píšeme labely na grafech.

Např. energetika a zemědělství se také nepíší s velkým písmenem, ale na grafu to tak máme:
https://faktaoklimatu.cz/infografiky/emise-cr

Jestli dobře čtu ty odkázané texty, tak jen argumentují, že ve větě je březen s malým. Ale neříkají nic o tom, jak kapitalizovat v grafech.

**Comment by kikinna** [comment]
Souhlasím s Jéňou (i Crysmanem v tom, že se měsíce nepíšou velkým), ale v
labelech to tak používáme a tam to nepovažuji za nějaký prohřešek, spíš to
dělám pro lepší čitelnost (ukotvení zraku) při přeskakování mezi pojmy.

Možná to můžeme v budoucnosti přehodnotit, ale teď to je podle mě hodně
nedůležité a imho nenarušujeme úroveň grafik.

**Comment by mukrop** [comment]
Suhlasim samozrejme s tym, ze chceme byt korektni podla gramatiky. Ale v aktualnej veci preferujem velke pismena presne kvoli tomu, co pise Jena a Kristy. Keby sme mali male, pride mi, ze napriklad aj v [grafe emisii](http://localhost:4000/infografiky/emise-cr-detail) by sme mali polozky zacinat malym pismenom (pretoze konzistencia oznacovania osi v grafoch).

@crysman, prosim bud navrhni dalsi postup alebo issue zatvor (nemyslim to v zlom, len nechcem, aby to tu zostalo visiet este 2 mesiace nerozhodnute).

**Comment by crysman** [comment]
@jankrcal je to jednoznačné:
![image](https://user-images.githubusercontent.com/5269350/77915111-31d6a480-7297-11ea-9389-8ef60e7b2805.png)

Pokud to budeme mít s malým, je to proti pravidlům českého pravopisu.
Dal jsem to sem proto, že na to poukazoval jeden Wikipedista - a další se určitě najdou. Nevidím důvod, proč zbytečně "nabíjet"... Malá písmena na začátku graf nijak neučiní méně přehledným. Jediná nevýhoda je práce s předěláváním, jinou nevidím.

**Comment by jankrcal** [comment]
Přijde mi, že si pořád nerozumíme.

Podle mě jsou dva důvody, proč se v češtině používají velká písmena:
 a) protože to vyžaduje dané slovo / sousloví (to je ted dokument, co odkazuješ)
 b) protože to vyžaduje kontext (např. začátek věty, začátek nadpisu v dokumentu).

Důvod našeho použití spadá do případu b). A tedy argumentovat, že se podle a) píše malé písmeno se podle mě nedotýká meritu věci.

Samozřejmě není z pravidel typografie zřejmé, že by se mělo v takové situaci (label na ose) používat velké písmeno. Ale je to za mě na jinou diskusi, protože se to dotýká velké většiny našich grafů. Pokud by se kvůli měly předělávat, tak bych byl pro udělat kompletní audit našich typografických zvyklostí (např. úvodní věta grafu většinou nemá na konci tečku, ale někdy má.)

Celkově mi to přijde nice-to-have, které teď nemá prioritu. Ale to je hlavně na @kikinna, aby posoudila, jestli to z grafického hlediska je potřeba.

**Comment by crysman** [comment]
Aha, OK, už rozumím, díky za doobjasnění.

Nesouhlasím, že to je na Kikině, je to typografická věc, nikoliv grafická..
Souhlasím: je to minor issue, kterou teď netřeba řešit.

A zároveň vidím, že takových bude přibývat, a že se nám to začíná dít - protože bobtnáme, a čím dál víc se budou objevovat minor issues "na pozdějc".

Klidně bych to celé všude opravil a zkonzistentněl a systematizoval, protože jednak to vidím (odjakživa mám přísné oko a taky jsem typografii několikrát nastudovával, protože jsem dělával korektury) a druhak umím být systematický, což je podle mě to, v čem jsem v rámci projektu potenciálně užitečný konkrétně zrovna já. Taky jsem dělal grafiku v Corelu i Photoshopu, takže kompetence nechybí. Potíž je, že nemám přístup, a udělat to nemůžu, ani kdybych chtěl.

Zároveň vnímám, že na tom není konsenzus, takže ani nevíme, jestli je co opravovat.

Závěry:

1. Ano, je to minor issue.
1. Minor issues začínají být z mého pohledu problém.
1. Nechci prudit a vrtat se v minor issues a rozbředávat pozornost a koncentraci na high-priority issues. "fine-tuning" label ponechávám, "chyba" odstraněn.
1. Mohl bych fine-tuning věci řešit, kdyby byl konsenzus, že můžu.
1. Ohledně pravopisu/stylistiky/typografie jsem kontaktoval _ujc.cas.cz_ - takže budeme mít odborné stanovisko. I když z toho vyplyne, že malá, nebudu to silou protlačovat.

**Comment by jankrcal** [comment]
Za mě:
 - Typografická revize grafik (a textů) a sepsání jednoduchých typografických guidelines pro další grafiky dává smysl.
 - Je to leštění dost malých detailů, zato na klíčovém produktu, který se dostává k uživatelům mnoha kanály (wiki, twitter, média). Tedy ho mít vyleštěný mi dává smysl.
 - Podle mě to má smysl jen pokud to nebude odebírat kapacitu grafikům, snad kromě diskuse kolem guidelines.

Pokud by jediná změna měla být změnit labely na malá písmena, tak to podle mě nemá smysl, už proto, že to není zjevný problém. Pokud najdeš víc zjevně problematických věcí, které by se současně sjednotily, tak to může mít dobrý smysl.

Byl bych ale konzervativní ohledně změn v našem zavedeném úzu a měnil jen pokud je pro ty silný typografický / gramatický důvod (že se to někomu z wikipedie nelíbí, mi nepřijde dost silné). Konzervativnost podle mě také sníží čas strávený diskusí :)

Tedy pokud do toho máš osobně chuť a pokud se podaří nastavit práci tak, abys mohl grafiky upravovat (po dosažení konsensu) sám, za mě to má zelenou.

Pořád to záleží na názoru @kikinna, protože to vyžaduje jisté její zapojení (minimálně Ti vysvětlit, jak na to technicky).

**Comment by kikinna** [comment]
Ahojte :)
nebudu se vyjadřovat úplně ke všemu, protože bych nepřidala žádný nový názor.

@crysman Těší mě, že si všímáš detailů a je to velice užitečná věc. Prosím dělej ji i dál :) Až se uzvou UCJ, tak dej vědět, jak to dopadlo a jestli to máme opravdu špatně.

Ad úpravy grafik - těch chyb se tam postupně nachází spoustu a často jsou drobňučké a souhlasím, že je třeba je upravit. Ale nemyslím si, že je třeba je upravovat hnedka, když se najde a to ze dvou důvodů: (1) zabírá to čas to dělat vždy po jedný chybě (2) hodně to mate pak verzování, protože s každým updateme grafik upravujeme verzi a když dojde na důvěryhodnost, tak pokud srovnám grafiku, která má verzi 1.2 a špatně velké písmeno versus grafiku, která má verzi 1.15 a je bezchybná, tak méně věřím té druhé, protože se na patnáckrát předělávala, takže můžu očekávat, že se ještě předělávat bude -- to jsem trochu přimrštila za vlasy tu 15ku, ale trochu se nám to začalo už dít u některých grafik. 

Takže podle mě to je třeba systematizovat.
Navrhuji následující postup:
- Pokud jsme v grafice našli drobnou chybu, která není kritická a hodně nás neponižuje, tak ji zařadit na seznam chyb v grafikách (jak to udělat chce ještě promyslet -- jestli mít jedno issue "drobné chyby v grafikách" a tam to sepisovat všechno) a buď se upraví při další větší opravě grafiky nebo se jednou za čas udělají batchové úpravy všech chyb -- buď když těch chyb bude už hodně nebo když tam budou ležet moc dlouho.
- Pokud v grafice najdeme velkou chybu, tak je třeba ji upravit relativně brzo. Velká chyba typicky znamená, že máme hrubku ve slově, špatně význam, atd. Prostě buď to znamená, že předáváme špatnou informace nebo jsme nezvládli gramatiku základní a střední školy.

@crysman Budu moc ráda, pokud budeš chtít pomáhat s těmi batchovými opravami chyb nebo i velkých chyb. Co to obnáší je to, že bysme se museli vždycky synchronizovat (momentálně já mám v hlavě aktuální stav všech grafik a ráda bych, aby to tak zatím zůstalo a neměnily se grafiky bez mého vědomí, aby se v tom nestal guláš). Pracuji ale teda v illustratoru a nevím, jestli k němu máš přístup. To je něco, co bych nerada měnila jen kvůli výpomoci s opravami chyb. Pokud to problém není, tak si můžeme někdy v budoucnu udělat synchronizační schůzku.

A ad kritika -- chápu, že dokáže být frustrující, ale nikdy nebudeme dokonalí. Holt takovému wikipedistovi můžeš říct "Ano, nejsem dokonalí, děláme to po večerech. Díky za upozornění, v budoucnu upravíme.". Je podle mě důležitý si uvědomit, že se nám nikdy nepodaří být bezchybní, a tak je to třeba brát víc v klidu. Protože jinak se může stát, že pak bez povšimnutí budeme místo tvorby relevantních věcí a předávání důležitých informací nahánět grafiky po dokonalosti a bude to mít menší dopad. 
Před pár dny mi Tom Protivinský poslal úryvek z knížky Factfulness, který se mi sem hodí.
![Hans Rosling](https://user-images.githubusercontent.com/11555522/78002998-4d45bc00-7338-11ea-80c8-76abb54bed07.jpeg)

Co na to říkáte? Souhlasili byste takhle s tím?

**Comment by crysman** [comment]
Ahoj oběma @kikinna a @jankrcal, vážím si vašich důkladných odpovědí. Zkusím odpovědět koncentrátem:

1. Díky, že spoluvnímáte, že záleží i na detailech, a že mi nemizí jedna z rolí v týmu. Zároveň, když zmizí, tak zmizí, netřeba držet neprospěšné.
1. Ano, dovolme si nedokonalost. Zároveň, jak píše Jeňa, pokud jsme schopni procesně to nastavit tak, že polishing nebere práci core grafika, tak je to za mě žádoucí stav - a odpovídá kartičce škálování + umožňuje potenciálně relativně snadné zapojení někoho, kdo zrovna hledá práci.
1. Guidelines ano - i když by to bylo jen 5 simple bodů - tím líp, aspoň si to každý přečte rychle a snadno. Obecně, líbí se mi idea, že máme k procesům guidelines - viz bod výše.
1. Úpravy infografik - ano, zcela souzním s konceptem méně častých "bulk" aktualizací u malých chyb a promptních update jen hrubých.
1. Díky za úryvek, padne.
1. Odpověď z ujc.cas.cz:
    > jazykové příručky se úpravě tabulek a grafů nevěnují, jde o záležitost typografickou. Doporučení pro úpravu tabulek je možné najít v normě ČSN 01 6910 Úprava dokumentů zpracovaných textovými procesory v oddílu "Tabulky". Vedle řady jiných zásad (nadpisy, měřicí jednotky, používání linek a barev, záhlaví, sloupce, řádky, vyznačení...) je zde uvedeno, že text v řádcích začíná velkým nebo malým písmenem, pro položky na stejné úrovni se používá jednotná úprava. Z toho vyplývá, že pro orientaci v tabulce a to, jak ji čtenář vnímá, je důležitá jednotnost řešení. Např. pokud budou všechny názvy měsíců jednotně s velkým/malým písmenem, je v pořádku, pokud bude polovina s malým a polovina s velkým, v pořádku není. Bližší podrobnosti najdete v normě.
    
    plyne z toho, že **je OK to mít s velkým prvním, pokud jsme v rámci celého projektu jednotní**.
1. Založím separate minor issue na konsolidaci názvosloví (hned namátkou během 5 sec jsem našel inkonzistenci)
1. K Illustratoru přístup mám, v práci, takže sync() schůzku si rád dám. Zatím mě baví role _universal pawn_ a mé bavení nevnímám v rozporu s vizí projektu, pokud někdo ano, zavolejte mi.

Díky, zavírám.

**Comment by crysman** [comment]
související: https://github.com/faktaoklimatu/web/issues/140
