### ISSUE TITLE
Globální opravy v grafikách - přechod na nové verzování, přidání licence, oprava typografie a chyb

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#464]
TODO:

Do všech grafik
- [x] ověřit, že máme zapracovány všechny překlepy z [korektury Atlasu](link-to-somewhere) (dodá Ondráš)
- [x] přidat licenci CC-BY-4.0 (#485) 
- [x] změnit verzování na nový systém (#478) u všech, co neměly checkbox níže
- [x] V infografice Výroba elektřiny ve světových regionech https://faktaoklimatu.cz/infografiky/elektrina-svet chybí v levém dolním rohu označení verze. 
- [x] zkontrolovat nezávislým okem, že vše OK (aspoň rámcově)
- [x] pushnout vše do mastera (resp. "mainu" či co to bude OMG)

DONE:
- [x] https://faktaoklimatu.cz/infografiky/koncentrace-co2
    - [x] chybí tečka v podnadpisu
    - [x] chybí tečka za "Koncentrace 400" pod podnadpisem
    - [x] u labels u eventů jedno začíná s velkým ("Izotopová"), zbytek malým
    - [x] Homo Sapiens -> Homo sapiens
- [x] https://faktaoklimatu.cz/infografiky/teplota-cr
    - [x] popisek k lineárnímu fitu je 1961-2018 ale správně má být 2019.
    - [x] přidat tečku do podnadpisu
- [x] https://faktaoklimatu.cz/infografiky/vyvoj-teplotni-anomalie
    - [x] chybí tečka v podpadpisu
    - [x] je tam spojovník (-) místo pomlčky (–) v rozmezí (2x nahradit)
- [x] https://faktaoklimatu.cz/infografiky/mapa-zmeny-teploty
    - [x] capitalize(2x "oblast")
    - [x] capitalize("severní")
- [x] https://faktaoklimatu.cz/infografiky/trend-teplot-cr
    - [x] capitalize("změna", "trend")
- [x] https://faktaoklimatu.cz/infografiky/teplota-cr-mesice
    - [x] nahradit v rozmezích spojovníky za pomlčky
- [x] https://faktaoklimatu.cz/infografiky/emise-svet-na-osobu
    - [x] capitalize("ostatní","kritérium")
    - [x] odstaveček s kritérium je věta - přidat tečku na konec
- [x] https://faktaoklimatu.cz/infografiky/elektrina-cr
    - [x] doplnit tečku v podpadpisu
- [x] https://faktaoklimatu.cz/infografiky/emise-svet
    - [x] <del>doplnit tečku v podpadpisu</del> (nebude, není to věta)
    - [x] doplnit tečku odstavec vpravo dole Jednotka...
- [x] https://faktaoklimatu.cz/infografiky/emise-eu
    - [x] doplnit tečku ve větě pod podnadpisem "Jednotka..."
- [x] https://faktaoklimatu.cz/infografiky/emise-vybrane-staty
    - [x] doplnit tečku v podpadpisu + větě pod tím "Jednotka..."
- [x] https://faktaoklimatu.cz/infografiky/emise-eu-poradi
    - [x] capitalize("sytější") + tečka na konec
    - [x] + tečka na konec Jednotka...
- [x] https://faktaoklimatu.cz/infografiky/body-zlomu-1
    - [x] biodiversity -> z (https://prirucka.ujc.cas.cz/?slovo=biodiversita)
    - [x] capitalize("velkého") u bariérového útesu (název)
    - [x] neobyvatelné - "neobyvatelnými"
- [x] https://faktaoklimatu.cz/infografiky/body-zlomu-2
    - [x] doplnit mezeru mezi Gt a CO₂eq
    - [x] 2 -> ₂ u CO2eq
- [x] https://faktaoklimatu.cz/infografiky/body-zlomu-3
    - [x] "EL NINO" -> "EL NIÑO" (_U+00D1_)
    - [x] na konci odstavce taky n -> "ñ" (mimochodem, pro nešpaněláky, čte se to [nyňo] - kdysi jsem slyšel [niňo] :)
- [x] https://faktaoklimatu.cz/infografiky/uhelny-phaseout-eu
    - [x] portugalsko se nám posunulo z 2023 na 2021
- [x] https://faktaoklimatu.cz/infografiky/zpoplatneni-emisi-svet
    - [x] přidat tečku do podnadpisu
- [x] https://faktaoklimatu.cz/infografiky/zpoplatneni-emisi-svet
    - [x] capitalize("detailnější")
- [x] https://faktaoklimatu.cz/infografiky/mitigacni-opatreni-mmf
    - [x] přidat tečku do podnadpisu
    - [x] i do věty pod ním
    - [x] "efektivní opatření" -> "efektivními opatřeními"
    - [x] vpravo dole legenda capitalize(poz, neut, negat)
 - [x] https://faktaoklimatu.cz/infografiky/tropicke-dny-praha a https://faktaoklimatu.cz/infografiky/tropicke-dny-brno
    - [x] opravit "teplota vystoupila" na "teplota vystoupala"

**Comment by mukrop** [comment]
Dotaz: Naozaj chceme bodky v podnadpisoch? 1) Podnadpisy (typograficky) typicky bodku nemavaju a 2) v nasom pripade to myslim nie je vzdy veta.

**Comment by crysman** [comment]
No - jak to píšu... mám to tam taky s otazníkem na některých místech, když se podíváš.

Obecně, pokud to je věta (obsahuje přísudek), dal bych tam tečku.
Pokud není, nedával bych.

**Comment by mukrop** [comment]
Plus nit-pick: Mozem poprosit kratsi nazov issue? (Plus idealne s velkym pismenom, skoro vsetky ostatne su s velkym v cestine s diakritikou, ty davas casto male :-P)

**Comment by mgrabovsky** [comment]
Když už jsme u mikrotypografie, existuje i mínusítko (U+2212 MINUS SIGN), které by se tu a tam hodilo místo spojovníku/pomlčky, pokud ho naše písmo má.

K druhému bodu COMMENTS výše, U+2013 je půlčtverčíková pomlčka, nikoliv spojovník.

**Comment by jankrcal** [comment]
Skvělá práce, díky, crysmane!

Souhlasím s tím nekončit tečkou podnadpisy bez přísudku.

Nestojí za to mít jedno výsostné issue stále otevřené, kde se prostě budou vždy shromažďovat drobnosti na opravu v grafikách? Třeba se do takového issue může přetransformovat toto, až budou koncepční věci (guidelines) hotové.

**Comment by crysman** [comment]
@mgrabovsky upraveno, samozřejmě jsem to tak myslel, ale napsal jsem to naopak, nějak se to celé nafouklo to vlákno a obědval jsem mezitím a tak, tak jsem udělal chybu ;)

Používal bych je standardní spojovník a standardní pomlčku (U+2013), ať to nekomplikujeme zbytečně moc.

@jankrcal Já osobně nemám problém s výsostným permaissue - v momentě, kdy je tam TODO checklist, tak je přehledně vidět, zda něco ne/třeba přímo z přehledu issues, takže člověk nemusí zalézat dovnitř:
![image](https://user-images.githubusercontent.com/5269350/78044327-cebb3f80-7374-11ea-9a57-e2db19011a19.png) a nijak to tedy za mě nebrání přehlednosti a nepřehlcuje.

**Comment by mukrop** [comment]
Len pre uplnost: Hoci som vo vseobecnosti proti issues, ktore sa nezatvaraju, v tomto pripade mi to pride v pohode.

**Comment by crysman** [comment]
@kikinna uděláme toto na příštím hackathonu? mám obavu, že jinak to zapadne... popř. to můžeme spojit s tou "grafickou schůzkou"... díky

**Comment by kikinna** [comment]
@crysman Jsem za to se na budoucím hackathonu pobavit o tom, jak teda pracovat s grafikama, jak pracovat s těmato úpravami atd. a ještě dohodnout osobně systém kolem grafik, se kterým budou všichni obeznámení (já, ostatní grafici a pár dalších) a pak to klidně můžeme udělat (i mimo hackathon).

Totiž. Nápad je to super, jen se teď trošku ztrácím v nastavení různých prací (pardon), tak bych ráda, abychom se všichni synchronizovali. A raději bych to měla systematičtěji.

Navíc, já bych potřebovala upravit možná zrovna nějaké barvy v grafikách, tak bych to ideálně ráda spojila s těmito úpravami, ať se to nedělá všechno na dvakrát. 

Takže ano. Adresujem to na příštím hackathonu. 
Díky, že to řešíš!

**Comment by jankrcal** [comment]
Předvídaje, že se z tohoto stane perma-issue jsem sem přihodil jazykovou drobnost z jiného issue, která nesouvisí s typografií (teplota vystoupila -> teplota vystoupala).

@crysman Jak jsi na tom s guidelines? Rád bych to oddělil od tohoto (budoucího) perma-issue a nejlepší způsob, jak to oddělit, je jednu část dodělat :)

**Comment by crysman** [comment]
za mě je guideliness hotovo (resp.... jakože, to nebude nikdy "hotovo" - ale je to ve stavu, podle kterého by měl kdokoliv cokoliv psát ideálně) - prostě si to dycky otevřít a psát podle aktuální verze

**Comment by jankrcal** [comment]
Přejmenoval jsem issue a smazal z prvního komentáře, co nesouvisí s jeho podstatou. Pokud by to někomu mohlo chybět, dávám sem, co dříve bylo v prvním komentáři navíc:

TODO @kikinna :
- [ ] rozpracované infografiky upravit stejně
- [ ] guidelines (crysman rád dotáhne)

GOAL:
Být koherentní a jednotní v rámci labelingu a názvů os, popisků, nadpisů a dalších prvků infografik tak, aby všude:

1. bylo **První velké**.
1. byla na konci gramaticky celých vět **tečka.**

Prošel jsem komplet všechny infografiky a nesrovnalosti hodil do TODO hned nahoře tohoto issue. Udělal jsem to zároveň komplexně a přidal i další úpravy textů, když jsem na něco narazil. Považujme to za globální jazykovo-typografickou korekturu stávajícího by crysman (neříkám, že nyní je to zcela bez chyby).

COMMENTS:
- Související: #463 , #140
- _pomlčka_ = _U+2013_ EN DASH (_CTRL+SHIFT+U+2013_) a vypadá takto: 1–3 zatímco _spojovník_ vypadá takto: 1-3
- ₂ = Unicode Character 'SUBSCRIPT TWO' (_U+2082_))
- změny jsou možné udělat i jinak, než navrhuju, ale musí být **všude koherentní** -> do guidelines
- v podstatě by se mi líbilo, kdyby součástí guidelines bylo "jazyková a typografická korektura" - a i to rád budu dělat ty korektury

cheers! #McZ

**Comment by crysman** [comment]
Zde je draft manuálu workflow a typografie k infografikám: https://docs.google.com/document/d/1JF0J4Tg_Xr6iTui2-FX2_J_Aev3NWrZnS3zly1Ct500/edit#

**Comment by crysman** [comment]
BTW, v rámci tohoto issue se taky řeší a restrukturalizuje způsob ukládání zdrojáků a práce s changelogy jednotlivých infografik

**Comment by crysman** [comment]
tak...

1) původní checkboxy vše hotovo, ou yeah!
2) chybí opravit verzování u grafik, které neměly checkbox
3) chybí doplnit všude licenci
4) @ondraspribyla má dodat revizi (scan) překlepů v rámci Atlasu - třeba pak ověřit, že ne/máme OK v rámci nyní udělaných změn - Ondráši, přidej sem checkbox na začátek úplně a podklady, díky

největší drbačka (největší díl práce) byla s přejmenováváním a reorganizací souborů a restrukturalizací a doplněním changelogs => prosím grafický tým o pečlivost při budoucím tvoření, systém už máme, a je na to guideliness (možno samozřejmě upravit dle potřeb) u jednoho .ai jsem si všiml, že viewport nebyl vhodně pojmenovaný (exportoval jem č. 11 a musel jsem ho ručně najít dle verze - tuším to byl ten phase-out)

**Comment by katkolouchova** [comment]
@crysman Wow, skvělá práce!

@kikinna Klidně ty licence můžu průběžně doplňovat, jakmile se domluvíme, kde přesně bude a přidáme ji do šablony.

**Comment by katkolouchova** [comment]
@ondraspribyla Existují v nějaké formě změny, které se dělaly v infografikách pro Atlas?

**Comment by crysman** [comment]
@ondraspribyla dodej prosím tu revizi, bez toho to tady nepůjde dodělat, díky

**Comment by ondraspribyla** [comment]
čekám až mi pošlou ai soubor.
