### ISSUE TITLE
Korektury na stránky studií

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#465]
Prechadzal som stranky studii nedavno kvoli niecomu a na vicerych z nich som videl celkom dost typografickych chyb (chyba medzera pred jednotkami, spojovniky namiesto pomlciek a podobne). Chcelo by to urobit na ne korekturu.

**Comment by mukrop** [comment]
@crysman, nevezmes si to? Celkom sa mi to pre teba hodi.

**Comment by LenkaSedlackova** [comment]
ja sa na to skúsim pozrieť v týchto dňoch

**Comment by LenkaSedlackova** [comment]
ahoj,
prebehla som dnes štúdie a urobila som v nich pár zmien, ktoré verím, že sú k dobru veci. mám vlastný branch korekturyStudii_Lenka a časom/večer (ešte to chcem radšej raz prebehnúť, ale teraz potrebujem odísť) by bolo fajn spraviť PR, ale zabudla som, ako na to :) predtým, než sa to ale mergne, by som bola rada, keby si, @mukrop , po mne skontroloval __zmenu referencií__ v "Obavy mladých protestujících jsou opodstatněné". samozrejme budem rada, ak sa pozrieš aj na ostatné zmeny, ale toto je taká najväčšia vec, ktorá by mohla ovplyvňovať funkciu. 

tiež som menila nejaké CO2 na CO<sub>2</sub> v hlavičkách štúdií, čo dúfam, že tiež nespraví nejaký prúser.

inak fakt obdivujem všetkých, ktorí vedia rozoznať pomlčku a spojovník bez toho, aby ich videli vedľa seba :))) som pomlčky pomenila na "&ndash;" z "-" (a vice versa) a imho nenastala žiadna vizuálna zmena :D

P.S. - prípadne môžeme nechať môj branch otvorený a ja sa v stredu počas klimatonu pozriem ešte na ostatné texty (je v nich dosť typografických prešľapov) a mergneme to potom?

**Comment by mukrop** [comment]
Ahoj. Mrkol som na to a je to dobra praca, presne tie veci, ktore mi tam bili do oci (chybajuce medzery pred jednotkami, chybajuce ciarky v texte a pod.). Dik!

Zmenu referencii som vratil spat, pretoze takto to generuje automaticky aj prekliky oboma smermi (a navyse to tvoje prerobenie rozbijalo build, kedze hranata zatvorka je specialny znak).

Na zaver poznamka k pomlckam – techniocky je to jedno, ci tam vlozit HTML entitu (tj. `&ndash;`) alebo priamo Unicode znak (tj. '–'). Ale aby sme to mali jednotne, pouzivame v projekte prave ten Unicode znak. Retaze `&ndash;` som teda nahradil Unicode pomlckami v celom projekte.
