### ISSUE TITLE
Systém na sledování změn u jednotlivých grafik / datasetů

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#467]
Čím více budou naše materiály použité na permanentních vnějších zdrojích (wikipedia, umimecesky.cz, atd.), tím větší chaos bude ve verzích a tím menší budeme mít přehled a kontrolu nad tím, jestli někde nevisí naše grafika se zásadní obsahovou chybou.

Co takhle mít možnost (a dost ji lidem tlačit) sledovat změny u jednotlivých grafik / datasetů? Tedy někde v sekci Ke stažení mít info o sledování této grafiky, malé políčko na emailovou adresu a tlačítko na odběr změn této grafiky. Ideálně pak uživatel, který naši grafiku někde zveřejní se zaregistruje pro odběr změn.

Člověku by pak přišel potvrzovací mail, že odebírá změny na této grafice (s instrukcemi, jak to zrušit), ideálně by se odebírání agregovalo, tedy by člověku vždy při každé změně přišel kompletní seznam grafik, které sleduje.

Museli bychom mít strukturovaný changelog pro grafiky / datasety, takže by rozesílání mailů bylo automatické po PR, který by přidal nějakou položku do changelogu. Nejlépe i s obrázkem před / po změně.

Jsem si vědom, že to je celé technicky dost složité (a úplně to nezapadá do konceptu statických stránek), ale třeba by se to dalo nějak technicky elegantně vymyslet, aby s tím bylo málo práce. 

Pokud to nebude rezonovat, jsem v pohodě to přesunout do wiki jako nice-to-have :)

**Comment by mukrop** [comment]
Changelogy pre infografiky aj datasety su v plane v rozumne blizkej buducnosti. To, co navrhujes znie rozumne, ale technologicky uz je to dost narocne (vzhladom na aktualny setup) a vaham, ci by to ludia naozaj pouzivali.

Use case: Ked ako wikipedista nahravas obrazky alebo ako novinar preberas niekolko grafik, naozaj chces mat o vsetkych takto detailny prehlad? Z mojho pohladu nie, pretoze obrazkov do novin/na wikipediu davas kvantum a zahlcovalo by to...
(Ale to je len osobna uvaha, mozno to ludia maju inak – len vzhladom na technicku narocnost diskutujem, ci to naozaj bude tak pouzivane.)

**Comment by jankrcal** [comment]
Dobrá úvaha, asi je to overkill.

Druhá (snazší) možnost by to bylo zapojit do standardního newsletteru, tedy:
 - v sekci "Ke stažení" u každé infografiky propagovat newsletter s tímto use casem,
 - mít newslettery rozdělené na osobní část (o projektu, co děláme, o čem přemýšlíme) a na technickou část, která by se nějak (polo)automaticky generovala z changelogů grafik a datasetů.

Toto by mohlo pro nadšené šiřitele našich grafik fungovat podobně dobře. Současně by nám to snížilo overhead ohledně kompilace newsletteru.

**Comment by ondraspribyla** [comment]
Po diskusi s Martinem, kdy jsme řešili use casy a možné uživatele, jsme došli k tomu, že ZATÍM by to skoro nikdo nevyužíval (asi jen wikipedisti) - novináři poté co vydají článek změny chtít sledovat nebudou, a lidi co píšou nějakou publikaci asi taky ne... Možná za rok zjistíme, že to chceme, nyní ale zavírám
