### ISSUE TITLE
Přidat zmínku o starších ice core CO2 datech do doprovodných textů

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#473]
V mezičase se objevil nový výzkum se staršími ice core daty:
paper: https://www.nature.com/articles/s41586-019-1692-3
data: https://www.usap-dc.org/view/dataset/601202

EDIT:
Data jsou hodně řídká, tedy se nedají zobrazit, proto next action:
 - [ ] Přidat do doprovodného textu a do textu k datové sadě koncentrací co2 větu jako
"koncentrace CO2 z dávnější minulosti zkoumal článek XX v Nature a i data z roku YY se pohybovaly v rozmezí 170 - 280ppm."

**Comment by ondraspribyla** [comment]
@jankrcal , @mukrop uměli byste stáhnout ten původní článek z nature? Případně data v nějakém formátu, který jde otevřít (ani po 8 minutách strávených proklikáváním té datové stránky jsem tam nic  nenašel, co bych uměl otevřit...)

**Comment by mukrop** [comment]
@ondraspribyla: Clanok mas na Klimaton gDrive. Data mi pridu bezne, zascrolluj na tej stranke dole a pod nadpisom "data files" mas obycajne CSV.

**Comment by ondraspribyla** [comment]
jsem trouba, csv jsem prehledl a doklikal se kamsi uplne jinam... za clanek
dekuju.

**Comment by ondraspribyla** [comment]
Čtu si článek. Je fajn. ale do grafiky ho předělávat nebudeme. Ale docela bych stál o zmínku v textu ke grafice koncentrace CO2 za 800kYr (a možná i v textu k datové sadě)...
Něco jako jedna věta: koncentrace CO2 z dávnější minulosti zkoumal článek XX v nature a i data z roku YY se pohybovaly v rozmezí 170 - 280ppm.

**Comment by jankrcal** [comment]
Taky koukám na článek a souhlasím, to ani podle mě nejde rozumně zpracovat do grafiky na naší úrovni přístupnosti :)

Souhlasím se zmínkou v doprovodném textu / textech. Mám si to přiřadit nebo to chceš, Ondráši, na někoho delegovat?

**Comment by ondraspribyla** [comment]
closing via #611
