### ISSUE TITLE
Ve Firefoxu nefunguje dobře dropdown zdrojových dat

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#474]
U některých infografik (a brzy i datasetů) máme více zdrojů dat, což zobrazujeme dropdownem. Ve Firefoxu (Mac OS, 74.0.1) ne zcela dobře funguje. 

Otevři takovou stránku, např. https://faktaoklimatu.cz/infografiky/emise-cr-detail a klikni na dropdown "Zdrojová data":
 1) zobrazené menu se zarovnává vzhledem k předchozímu buttonu (Naše zpracovaná data) a ne vzhledem k tomuto buttonu (Zdrojová data)
 2) když přejíždím myší přes položky v menu, tak mizí (a už se ani neobjeví, když odjedu myší pryč).

V Chrome mi to oboje funguje dobře.

**Comment by jankrcal** [comment]
@mukrop Nezkoumal jsem to do detailu, přijde mi to dobře delegovatelné na klimaton.

**Comment by mgrabovsky** [comment]
Nezkoumal jsem to do hloubky, ale tipl bych si, že by oba problémy mohly být bugy v [Popperu](https://popper.js.org/), který Bootstrap používá pro vytváření dropdownů. Ani po aktualizaci na nejnovější Bootstrap 4.4.1 (jQuery 3.4.1, Popper 1.16.0) se situace nemění. Nejnovější Popper je už na 2.3.3, ale Bootstrap jej nepodporuje (zkoušel jsem drop-in).

Na okraj: Zdá se, že problém s mizením způsobuje CSS property `transform`. Když na prvku zruším `transform` a `will-change`, na přejíždění myšítkem reaguje tak, jak má. To mě vede k domněnce, že by se mohlo jednat i o bug ve Fiefoxu. (Zkoušel jsem i poslední Nightly 77.0a1 2020-04-17.)

Žádný rychly workaround mě teď nenapadá.
