### ISSUE TITLE
Keeling + Upgrade datové sady o  koncentrace O2

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#476]
Sripps měří také úbytek O2 v atmosféře v důsledku spalování: http://scrippso2.ucsd.edu/
Mě by se tento úbytek O2 hodně hodil do grafu ke keelingově křivce. 

@jankrcal> Co si myslíš o upgradu datové sady o řadu obsahující koncentrac O2 (isotopové stopy bych tam le už nedával...)
![CO2 vs O2 concentration](https://user-images.githubusercontent.com/17317136/79274139-660bb100-7ea4-11ea-9d8e-d53b570cb3b0.png)

**Comment by jankrcal** [comment]
Není problém, můžu zpracovat. Mají tam vícero stanic [1], sedí mi tam přidat jenom Mauna Loa, protože Keelingovu křivku máme právě pro Mauna Loa.

Co myslíš?

[1] http://scrippso2.ucsd.edu/osub2sub-data2268.html

**Comment by ondraspribyla** [comment]
Jo, souhlas, jenom Mauna Loa... díky...

**Comment by ondraspribyla** [comment]
Určitě bude stačit přidat pouze Mauna Loa, jiné netřeba.

**Comment by jankrcal** [comment]
Ondráši, draft tabulky zde:
https://docs.google.com/spreadsheets/d/1DYrIsmgy_S6IIWGtsk55Jor6zSDrf6-qT8Og9n7oDoU/edit#gid=246840615

Co mi není jasné, jak to budeme zobrazovat v jednom grafu, když ty jednotky (per meg) jsou úplně jiné než ppm?
Viz http://scrippso2.ucsd.edu/units-and-terms.html

Nebo něco zjevného nevidím?

**Comment by jankrcal** [comment]
Dataset je za mě dodělaný
https://docs.google.com/spreadsheets/d/1DYrIsmgy_S6IIWGtsk55Jor6zSDrf6-qT8Og9n7oDoU/edit#gid=979818322

Ondráši, postaráš se o dotažení PR nebo se mám angažovat?

**Comment by ondraspribyla** [comment]
O dotažení se postsram

Dne po 20. 7. 2020 21:55 uživatel jankrcal <notifications@github.com>
napsal:

**Comment by ondraspribyla** [comment]
closin via #594
