### ISSUE TITLE
Drobné vylepšení stránek datových sad

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#477]
Vo vetve `datove sady` (vid #475) urobit nasledovne:
* [x] [lenka + crysman] Precitat vsetky nove texty a urobit korekturu (cestina, typografia)
* [x] [crysman] konzistence: "Náš dataset" -> "Naše tabulka s daty" ([detaily](https://github.com/faktaoklimatu/web/issues/477#issuecomment-615204235))
* [x] [crysman] potřebujeme typografické howto, narážíme na to, že nevíme, které typo věci upravuje autofiltr, a které je třeba dělat ručně. Zde je na to [starší nedodělané issue](https://github.com/faktaoklimatu/web/issues/234) a tu je ten [návod/howto](https://docs.google.com/document/d/1wVQv4w93Qg_ma6HNFn2Zs3iYQqlo6MKnQiwMHsF2pvA/edit#).
* [x] [jena] Opravit sazbu izotopů 12C, 13C a 14C na superscipty. (viz.notation https://en.wikipedia.org/wiki/Isotope )
* [x]  [jena] `emise-svet`: Chcelo by to pridat odkaz do slovnika na CO2eq a antropogenne sklenikove plyny.
* [x]  [jena] `emise-svet`: Chcelo by to mozno pridat do slovniku zmienovany Global Carbon Atlas a ISO 3166-1.
* [x]  [protivinsky] `emise-svet`: Nerozumiem poslednej vete sekcie Geograficka data. Chapem, ze existuju dve rozdelenia do regionov (svetova banka a Wikimedia), my mame tretie?
* [x]  [Jena] `emise-eu`: Tiez niekde doplnit odkaz do slovnicka (minimalne na CO2eq).
* [x] [Jena] Doplnit aktualitu, ze mame stranky datovych sad (datovat ju kludne k 2020-04-17).
* [x] [Ondras] Doplnit zmínku o jednotkách v datových sadách (Ondráš konzultoval s Kvítkem - ppm resp. micromol/mol u koncentrací, tuny CO2 eq u emisí)
* [x] [Ondras] Vyjasnit formulaci koeficientu "Global Warming potential" a přidat odkaz na GWP wiki

**Comment by crysman** [comment]
toto mě pobavilo:
![image](https://user-images.githubusercontent.com/5269350/79565318-c5d6a780-80b0-11ea-97d6-64b60eb73728.png)

![image](https://user-images.githubusercontent.com/5269350/79565348-d555f080-80b0-11ea-9425-86b7765f6b95.png)

**Comment by crysman** [comment]
### Předně:
WOW! Kus práce!

### Druhak:
#### nelíbí se mi sekvence

**Naše datasety -> Náš dataset -> Náš dataset**. Jakože ... jako userovi mi jde hlavou "_a už to tam fakt bude?_" - nějak takto: ![image](https://user-images.githubusercontent.com/5269350/79566226-84df9280-80b2-11ea-9a3e-e9ae4010ed3a.png)

Zde jak to vypadá:
![image](https://user-images.githubusercontent.com/5269350/79566117-4ba72280-80b2-11ea-83e4-68ca371b9785.png)
-> 
![image](https://user-images.githubusercontent.com/5269350/79566143-5661b780-80b2-11ea-98ab-2b46ed4a3078.png)

#### Návrh řešení:
namísto "Náš dataset" dát toto: 
![image](https://user-images.githubusercontent.com/5269350/79566325-a93b6f00-80b2-11ea-9f8f-f8b0c9a9953e.png)

což bude konzistentní se zbytkem infografik.

Přidávám jako checkbox do ToDo nahoře.

**Comment by crysman** [comment]
Hele, to co zvládnu, mám zrovna zapracovat a udělat?

**Comment by mukrop** [comment]
> Hele, to co zvládnu, mám zrovna zapracovat a udělat?

Podla mna mozes veci, ktore tam boli predpisane od nas, zapracovat hned, tie uz sme diskutovali viaceri. Ine vyraznejsie upravy by som chcel, aby boli s niekym konzultovane (Ondras/Jena/ja/...) primarne kvoli tomu, aby to videlo viac ludi.

K uprave textu tlacitka: Za mna asi OK, ale chcel by som pocut nazor @jankrcal, on tie texty upravoval a ma lepsi big picture ako ja.

**Comment by jankrcal** [comment]
Souhlasím s crysmanovým návrhem. Sám jsem přesně nad tím přemýšlel, ale nějak jsem neměl jasnou preferenci, tak jsem to nechal.

Budu rád, když něco rovnou uděláš, crysmane.

Jen pro kontext, Ondráš měl myslím představu, že některé z těch úkolů by se daly delegovat jako dobré starter-bugs pro lidi na dnešním klimatonu, aby se seznámili s technickým workflow. Tak když něco takového vhodného necháš, může se to večer hodit.

**Comment by crysman** [comment]
@LenkaSedlackova typografie a psaní textů [draft návodu zde](https://docs.google.com/document/d/1wVQv4w93Qg_ma6HNFn2Zs3iYQqlo6MKnQiwMHsF2pvA/edit#).

**Comment by crysman** [comment]
vše hotovo, zavírám
