### ISSUE TITLE
Uvítací informační dokument pro nové lidi v projektu

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web#479]
Cílem je pomoci orientaci nováčkům v projektu - lidem, kteří by chtěli dlouhodoběji pomoci (nad rámec jednoho klimathonu), ale zatím neví jak, jaké nástroje se používají, co se děje a na koho se případně obracet s prosbou o pomoc.

**Comment by setcz** [comment]
Návrh struktury takového uvítacího dokumentu - komentáře vítány! https://docs.google.com/document/d/1gsfxbehPULw192wop1o2jxUdkCILn1G1_tJDywZL-OE/edit#

**Comment by mukrop** [comment]
Dobry napad aj draft, dik :-).
Ako som pisal do jedneho komentara, asi by som to radsej dal ako subor Contributing.md do repa (a postupne tam vytvorit aj dalsie prirucky). Tam to teda bude verejny dokument, ale podla mna to nevadi.

**Comment by setcz** [comment]
Za mě finální první verze uvítání - https://docs.google.com/document/d/1Gj8boWLjmDtWckT7ILz_NgT121EDID6g9jDCLwV_sSg/edit

Aby byla užitečná, je třeba ji zaslat každému, kdo chce pracovat nad rámec jednoho klimathonu - nevím, jestli proto máte zaužívaný název, skupina lidí mezi "nárazový host" a "core týmem". Tedy například stojí za to jej poslat každému, kdo dostane přístup do Google disku či na GIT.

Za mě je to teď ve stavu, kdy je možné issue takto zavřít. 

Nicméně podněty na další možné kroky:
-  pokud již nyní existují takoví lidé, kteří by mohli být zmateni, stojí za to jim to poslat i nyní - podnět pro @ondraspribyla 
- pokud chceš tu stránku @mukrop chceš předělat i do GITu, prosím
- @crysman rozjel "profily osobností" v pracovní verzi - https://docs.google.com/document/d/1gsfxbehPULw192wop1o2jxUdkCILn1G1_tJDywZL-OE/edit - pokud se dokončí, je možné přidat i do finální verze

**Comment by ondraspribyla** [comment]
OK, díky za dotažení a vyčištění, výsledek se mi líbí, je přehlednej.
Plánuju poslat na klimaton-all mail, ve kterém bude pár poznámek o tom, co
jsme udělali (datové sady + drafty)
a přihodil bych tam i tento tůj dokument - aby i ti, kteří jsou u projektu
déla (ať už jsou zmateni nebo ne) si mohli přečíst přehled.

...a z toho, že není zmíněna googlegroupa CORE chápu, že jste se rozhodli
ji tam neuvádět. (Za mě Ok.)

Další vylepšování klidně může být (neformální poznámky ke každému z CORE se
mi líbí) ale podle mě to je nice to have, stačí to v další verzi.

**Comment by ondraspribyla** [comment]
Issue mi přijde hotové - proto zavírám. Další práci přesuňme buď do upgradovacího Issue, nebo do práce na #351.
