### ISSUE TITLE
Sjednotit GWP

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#482]
vypadá to, že v datových sadách pro EU a pro SVET používáme jiné hodnoty GWP. jednou citujeme že GWP pro methan je 34 a podruhé že je 28...
Odpovídá to hodnotám "with feedbacks" a "without feedbacks"  v https://en.wikipedia.org/wiki/Global_warming_potential#Values

**Comment by ondraspribyla** [comment]
ješte je to potřeba sjednotit se slovníčkem, kde máme GWP taky...

**Comment by jankrcal** [comment]
V roce 2016 byla platná metodika podle čtvrté hodnotící zprávy, proto EEA používá tyto koeficienty (25 pro metan)
Pro Emise Svět Tom použil koeficienty podle 5. hodnotící zprávy (28 pro metan).

V textu datasetu emise EU to vysvětluju, proč oni používají starší koeficienty.
Nevidím jiné řešení než v emise svět za rok 2015 přebrat koeficienty ze 4. zprávy, protože EEA nepředěláme :)

Kde vidíš hodnotu 34?

**Comment by ondraspribyla** [comment]
Ok, vidím, že je to vysvětleno precizně. Měl jsem dojem, že jsem někde viděl i tu 34, ale to bylo asi na wiki... každopádně díky za upgrade slovníčkového hesla a podrobné vysvětelní k datasetu EU. Issue zavírám.
