### ISSUE TITLE
Licence CC-BY-4.0 do infografik

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#485]
Momentálně je při použití našich infografik vyžadované odkazovat na nás včetně explicitního uvedení licence v tomto odkazu. Nebylo by vhodnější dát malý symbol licence (viz https://creativecommons.org/about/downloads ) přímo do infografik (například k verzi?), pak by již nebylo třeba tuto licenci znovu uvádět v odkazu. Většina čtenářů zkratce CC-BY-4.0 stejně nerozumí a je pro ně matoucí.

**Comment by mukrop** [comment]
Nie je pravda, ze po uvedeni obrazku by nebolo treba uz odkazovat licenciu. Viz pravidla pouzitia CC [na strankach CC](https://creativecommons.org/use-remix/attribution/) alebo [na ceskych strankach](https://www.creativecommons.cz/pro-uzivatele/nabyvani-licence/).

Vzdy musis totiz uviest celu licenciu (tj. celu licencnu zmluvu, nie len typ), ale ak tam zahrnies odkaz, tak je to dostatocne.

Plus osobne mi pride, ze tie CC licencne obrazky su dost skarede :D (vzhladom na nase uhladene grafiky v cistom designe).

**Comment by mukrop** [comment]
@protivinsky, vaham s kym s timu toto konzultovat. Nejake tipy?

**Comment by setcz** [comment]
Ten podnět vznikl, když jsme v pátek na klimathonu řešili doporučení na stránku jak pracovat s našimi materiály a jak je používat. Ona totiž licence vyžaduje uvedení jejího jména u každého použití díla, zároveň ale nutit (třeba) média do toho, aby ke každému obrázku psali CC BY 4.0 (což pro 99% populace je zcela kryptická sekvence znaků) je trochu nešťastné. A stejně to spíš asi nebudou dělat hádám. Tak jsme mysleli, že by se to vyřešilo právě přidáím CC BY do obrázků.

Třeba Our World in Data to tak taky dělají - nevyžadují v textu u obrázku napsat CC BY 4.0, místo toho to mají přímo v obrázku/interaktivní infografice - https://ourworldindata.org/how-to-use-our-world-in-data (v interaktivní infografice to mají prokliknutelné, v neinteraktivních samozřejmě ne)

**Comment by mukrop** [comment]
Suhlasim s tym, ze "CC BY 4.0" je krypricke pre vacsinu populacie (ale pozor, nasa cielovka/citatelia su podla mna _biased_ a licenciu bude poznat ovela vacsia cast z nich, ako pri pohlade na celu populaciu). A prave preto, ze je to krypticke, mi pride vhodne, aby novinari uvadzali tento text vzdy ako preklik na text licencie (ako vyzaduje sama licencia). Ten popis licencie [po prekliku](https://creativecommons.org/licenses/by/4.0/deed.cs) je podla mna krasne pochopitelny. A ak to budeme davat do obrazkov, tak ten preklik tam nebude.
(Navyse mi pride, ze novinari, vzdelavacie organizacie a neziskovky by mohli pouzivat licencie spravne a podla mna je zasluzne ich to ucit, ale to je osobny nazor na trochu nesuvisiacu temu.)

Co sa tyka estetickeho hladiska, tak riesenie Our World in Data (text CC BY 4.0) je pre mna o dost predstavitelnejsie, ako original symboly od CC (ktore povodne navrhoval @protivinsky).

Pragmaticky, co sa pouzitia tyka, mne (osobne) nebude zasadne vadit ani to, ked nas obazok pouziju bez explicitneho uvedenia licencie, nazvu a linkov (akoze "len preberu obrazok"), primarne preto, ze odkaz na faktaoklimatu.cz tam mame. Ale moj navrh stale je ako _default_ po nich chciet spravne pouzitie licencie (a kludne im s tym pomoct – preto je ten licencny popup taky nazorny).

**Comment by mukrop** [comment]
Zaver: Do vsetkych infografik doplnit strucny text licencie, tj. "CC BY 4.0". Pravdepodobne vlavo dole vedla licencie.

**Comment by mukrop** [comment]
@kikinna: Priradujem teba, aby si o tom vedela. Predpokladam, ze sa to upravi, ked sa zmeni system verzovania infografik.

**Comment by mukrop** [comment]
Hotovo.
