### ISSUE TITLE
Global Risks Report - infografika

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web#492]
Odložení myšlenky z rozhovoru s Ondrášem (a před tím byl podnět od Elišky) - udělat infografiku mapující vnímání světových rizika vycházející z tohoto reportu - http://reports.weforum.org/global-risks-report-2020/

Kontext - je to výstup dotazování několika set expertů, jak vnímají světová rizika. Rizika spojená se změnou klimatu jsou tam silně zastoupena.

Limitace: není to analýza "skutečného rizika", je to spíše analýza "vnímaného rizika".

**Comment by ondraspribyla** [comment]
ukazuje se že máme jiné priority. Přehazují do Knowledge base. Closing.
