### ISSUE TITLE
Udělat prototyp(y) nového typu infografiky: myšenkové mapy souvislostí

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#496]
Z hovoru s Ondrášem: chceme zkusit udělat další typ obsahu na web: myšlenkové mapy fyzikálních i jiných souvislostí k danému problému. Tedy rozkreslit graficky, jaké jevy spolu souvisí, ovlivňují se, kde je kauzalita.

Z programátorského hlediska je to infografika, která buď nemá zdrojová data nebo má podobný nedatový zdrojový sheet jako např. body zlomu.

V doprovodném textu jsou zadefinované jednotlivé pojmy a vysvětlené souvislosti. 

Garant, že se to stane: Jeňa
Garant obsahu: Ondráš
Garant grafiky: ??

První tři myšlenky na takové myšlenkové mapy:

- [ ] Fyzika skleníkového efektu
- [ ] Změna klimatu není jen oteplování
- [ ] Proč je (v ČR) sucho?

**Comment by jankrcal** [comment]
Ondráši, mohl bys mi prosím poslat (nebo sem nějak nahrát) svoje materiály k prvním dvou mapám?

**Comment by ondraspribyla** [comment]
Text který jsem posílal na Aktuálne.cz může být dobrý zárodek. Je v něm i "mapa souvislostí". Ta se dá udělat i trochu zjednodušeněji, když se oteplování vzduchu a vody scucne do jednoho... https://docs.google.com/document/d/1Uzk_MoOFQy6tEWU_6LCndmbyYhqx-We_h349VYpke-Y/edit?usp=sharing

**Comment by jankrcal** [comment]
Tři náčrtky jako první verze:
 - kauzalita v klimatickém systému: https://app.mural.co/t/zengarden9550/m/zengarden9550/1586792258148/89cdd9a7768d797717aaefd78a1e6e643998b922
 - sucho: https://app.mural.co/t/zengarden9550/m/zengarden9550/1585601355120/6188fa9f7f70ada4aa003203a7452b48704440ce
 - mitigace / adaptace: https://app.mural.co/t/zengarden9550/m/zengarden9550/1588345643363/486955322cc88a8b59a2ed2caebffe958231ea17

**Comment by ondraspribyla** [comment]
Navrhuju zavřít takto obecné issue (jedno schéma jsme už udělali a plán na další mám) a řešit to v jednotlivých issues... 
@jankrcal souhlasíš? 

O.

**Comment by jankrcal** [comment]
Ano, souhlasím.
