### ISSUE TITLE
EMBER do studií

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#511]
https://ember-climate.org/project/global-power-2020/

...již rozpracováno

**Comment by protivinsky** [comment]
Předběžná verze: https://docs.google.com/document/d/1vliojLUR1pSUbxXNAtm9gvql9-71RsH4I-A7rkCfBqU/edit#

@ondraspribyla - kdybys našel chvilku (nebo někdo jiný) to aspoň letmo pročíst, zdali to dává smysl, budu rád. Závěry jsem dal zhruba jak jsme to diskutovali telefonicky; pro hlavní část jsou použil nakonec rozdělení podle regionů, dávalo mi největší smysl. Občas jsem si nebyl jistý s přesnou českou terminologií - například pro IPCC 1.5 zprávu nebo jestli existuje obdoba termínu "energetický mix" zahrnující pouze elektřinu. Pokud bys chtěl ještě více zdůraznit ten loňský pokles ve využívání uhlí v EU o 24 %, můžeme to tam ještě někde zopakovat.

**Comment by ondraspribyla** [comment]
Pročetl jsem a jsem spokojen. Kromě jedné opravy, kterou jsem udělal přímo,
mám pouze návrhy na drobná vylepšení v jasnosti formulací + navrhuj, že
bychom udělali pro regiony (+ČR pro srovnání?) v textu tabulku, ve které by
byla spotřeba na obyvatele, emisní intenzita na kWh a případně podíl uhlí a
plynu... Co ty na to?

O.

**Comment by jankrcal** [comment]
Kouknul jsem na to, přijde mi to skvělý.

Současně přemýšlím, že je tam dost málo materiálu o Evropě, kde výrazné padání výroby z uhlí je přece jen bližší kontextu českého phase-outu. Tak by mi přišlo pěkný (pokud bude čas a síla) zpracovat i něco z https://ember-climate.org/project/power-2019/.

Ať už jako doplňkové informace ke grafice k phase-outu nebo jako druhou grafiku k phase-outu a nebo jako další studii...

Co myslíte?

**Comment by protivinsky** [comment]
@ondraspribyla - jen stručný komentář k naší diskuzi o elektřině vs celkové energii. MacKay má v knize tento graf. Spotřeba energie na osobu pro ČR zhruba 140 kWh / den (ano, z fyzikálního pohledu příšerná jednotka, ale lidé samotným wattům nerozumí); krát 365 znamená přibližně 50 000 kWh ročně. Pro USA je to 250 kWh / den, tedy cca 90 000 kWh za rok. Porovnání se spotřebou elektřiny na základě Emberu tedy dává podíl elektřiny jako 14% celkové energie v obou zemích (a jeho rozklad na jednotlivé "spotřebiče" energie tomu také nahrává). Z našeho pohledu má samozřejmě větší smysl podíl na emisích, toto je spíše pro doplnění.

![image](https://user-images.githubusercontent.com/9573993/82086339-4e635a80-96e6-11ea-9d01-4b35437be5c6.png)

A níže je jeho rozklad na jednotlivé "spotřebiče" energie (se součtem 195 kWh / den):

![image](https://user-images.githubusercontent.com/9573993/82086399-60dd9400-96e6-11ea-87ec-2fc5ed8da7e4.png)

**Comment by ondraspribyla** [comment]
To je divný, přece jsme se jednoduchým dělením dopočítali v USA na 12661
kWh /osobu /rok - jasně, není v tom rozlišené osobní spotřeba vs průmysl,
(a třrba ztráty v přenosové síti)
tak nerozumím, proč mu vychází 90 000 kWh/osobu na rok. Jinak samozřejmě
grafík je hezkej

**Comment by protivinsky** [comment]
Těch 12 661 kWh / osoba a rok je elektřina; nicméně toto zpravidla nezahrnuje dopravu (osobní auta ani leteckou), vytápění, energii spojenou s produkcí potravin (opět často benzín, nikoli elektřina), doprava zboží, které si kupuješ...

Čili v součtu všech spotřebovaných energií mu to dává 90 000 kWh. Otázkou je, jakým způsobem přesně je to počítáno - například účinnost spalovacích motorů v autech je velmi nízká, takže nevím, zdali je uvažována energie spáleného benzínu nebo energie skutečně potřebná k jízdě auta (čili jestli po elektrifikaci dopravy bude potřeba srovnatelné množství elektřiny nebo výrazně nižší). Pro nás je samozřejmě nejvíce relevantní pohled prostřednictvím uvolněných emisí, nicméně toto srovnání mi také přijde zajímavé.

**Comment by ondraspribyla** [comment]
Jasně... tedy 90 000 kWh není jen elektřina...
