### ISSUE TITLE
Názvy studií - k diskusi

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#512]
Chtěl bych přehodnotit, jak prezentujeme názvy studií... Když si představím, že mluvíme na tiskovce o studii ENERGYNAUTICS, tak bych chtěl, aby byla jasněji dohledatelná na našich stránkách a nemusel jsem vystětlovat, že jde o "Česká energetika bez uhlí".

Stejně tak EMBER: Global electricity Review 2020 by mi dávalo smysl prezentovat pod tímto názvem a nesnažil bych se jej překládat.

Chci slyšet názory a ideálně rozhodnout na dnešním hackatonu

**Comment by mukrop** [comment]
Rozumiem tvojej argumentacii, par postrehov:

**EMBER: Global electricity Review 2020**: Pride mi klucove nechat klucove slovo EMBER (pretoze podla neho to asi budete referencovat). Zaroven nahodne anglicke casti (obzvlast v nazvoch stranok) sa mi uplne nepacia. (Preco je to anglicky? Je aj ta stranka anglicky?) V tomto pripade by som zvazoval "EMBER: Globalni zprava o elektrine 2020".

**Česká energetika bez uhlí**: Pride mi zavadzajuce, ze ju volate "studie Energynautics". Energynautics je firma, ktora ju vypracovala (a ma mozno kopu dalsich studii). Pripodobnil by som to "studii CzechGlobu" alebo "zprave Ministerstva zivotneho prostredi" – to nepouzijes, lebo vobec nie je jasne, ktora sprava to je. Bohuzial pojem "Česká energetika bez uhlí" nie pramo nazov, pretoze ten je [extra dlhy](http://glopolis.org/wp-content/uploads/Infolist-sit-bez-uhli.pdf), ale aj tak mi pride vhodnejsie naucit sa hovorit "zprava o utlumu uhelnych elektraren (od firmy Energynautics)" – je to presnejsie aj vypovednejsie.

_That being said_, navrhujem **drobnu graficku zmenu**: V boxoch studii na titulnej stranke aj na samotnych strankach studii pod nazov zaradit vytvarajucu instituciu mensim sedym pismom. Pomoze to prehladnosti.

**Comment by jankrcal** [comment]
Ta studie Ember taky nemá EMBER v názvu. To je jen název organizace, která ji vydává.

Proto mi přijde, že to může být:
 - EMBER: Globální zpráva o elektřině 2020
 - Energynautics: Česká energetika bez uhlí

Ale je pro mě i fajn mít instituci níže, jak píšeš. Tedy:

Globální zpráva o elektřině 2020
EMBER

Česká energetika bez uhlí
Energynautics

**Comment by mukrop** [comment]
Aha, to som netusil. To by mozno bolo lepsie volat tu spravu inak ako "EMBER sprava".

Graficky som dost za to, aby to bolo pod sebou, uz teraz narazame na to, ze nazvy studii su prilis dlhe.
