### ISSUE TITLE
Grafika: Energetika, podíl zdrojů

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web#519]
Garant obsahu: @ondraspribyla 
Garant grafiky: @kikinna 

Pravděpodobně budeme rozpracovávat alespoň dvě grafiky zaměřené na podíl zdrojů ve výrobě energie. 

- [ ] @ondraspribyla Nadpis + podnadpis
- [ ] @ondraspribyla Rozmyslet, jestli chceš doplnit někde popisky ke grafům doplňující kontext či poskytující nějaké pozorování
- [x] @kikinna Dohodnout se s Katkou na navazující grafice (pokud bude chtít)
- [ ] Doplnit slug a správně zdroj
- [x] Zkontroluj, jestli se grafika vygeneruje správně (časové osy) s naší konverzí -- používám blend mode "multiply"
- [ ] Je ok, že měníme barevné schéma?

https://docs.google.com/spreadsheets/d/16qxVbcaxwXi0hTHXeyTQpwTLSyD40SGr-mWtFlTh2jk/edit?usp=sharing

Aktuální stav: 
![Energetika podil zdroju-10](https://user-images.githubusercontent.com/11555522/81424917-f2815a80-9156-11ea-9e35-bbe22da6e22a.png)

**Comment by ondraspribyla** [comment]
@kikinna Díky za nahození.

1. snadné korekce:

   - TWh se píše s velkým T. (Pro kontext předpon: Tera Watt hodina = 10^12
   Wh ; násobné předpony jsou  kilo-Mega-Giga-Tera , pouze kilo se jako
   predpona píše s malým k )
   - Datová řada končí rokem 2019, nikoliv 2018

2. Visuálně mi chybí x-ové i y-ové osy. U grafů bez os je moje oko
nespokojené a zmatené... vyznačení jako u prvního grafu, které by bylo u
všech grafů, by mi pomohlo.
3. Kdykoliv se uvádí procenta (tedy setiny z celku) musí být naprosto
jednoznačné, co je ten celek. Z tohoto pohledu je graf dost problematický -
u USA a EU jsou celek výroby roku 2018 a 2011. U všech ostatních je celek
výroba roku 2019. Jednoznačnost celku komplikuje i jiná konvence: když se
mluví o nárůstu poptácky po elektřině (např v případě Číny) uvádí se jako
celek počáteční, nikoliv koncový stav... Celé tohle matení ohledně procent
by se vyřešilo, kdybychom u grafů měli osy a uváděli je v absolutní
hodnotě. Odpadlo by i to číslo nahoře.... (tohle je asi na diskusi po
telefonu)

O.

**Comment by kikinna** [comment]
@ondraspribyla Hh, long story short, vnímám úplně stejné námitky, které popisuješ v bodě 3 a vyšly najevo až když jsem to dala do grafu. (Bod dva je pak závislý na vyřešení bodu tři)
Bod jedna opravím.

(Sranda, že v teorii je ten návrh jednoduchej a jakmile to nasypeš na konkrétní data, tak se to rozpadá, hh)

**Comment by katkolouchova** [comment]
Ahoj, s Kristi jsme se domluvily, že se podívám na hodnoty per capita. Rozumím tomu správně, že produkce na hlavu nedává smysl, když se její část může exportovat?
Pak bych chtěla poprosit, jestli byste mi někdo mohl pomoct upřesnit rozdíl mezi poptávkou a spotřebou elektřiny. Co je revelantnější pro zobrazení na hlavu? Dívala jsem se, že v Ember reportu zobrazují právě poptávku na osobu a její vývoj v čase.

**Comment by jankrcal** [comment]
Přidávám Oldu, který snadno může mít fundovanější odpověď na Tvoji otázku, Katko.

Mně přijde, že to používají jako synonymum. V EMBER datasetu vidím jen "Demand" s jednotkou TWh. Ty vidíš někde data pro spotřebu?

**Comment by SklenarOldrich** [comment]
V daném kontextu (Ember) je poptávka (demand) zaměnitelná se spotřebou (consumption).

V praxi se ve statistikách uvádí pouze spotřeba (lze ji zpětně změřit = "tvrdá hodnota", na rozdíl od poptávky, která je závislá mj. na ceně a může se od reálné výroby/spotřeby výrazně lišit).

Část výroby se může opravdu exportovat, ale v rámci daných bloků to budou spíše zanedbatelné hodnoty (propojení existují především rámci těchto bloků). Za mě tedy hodnoty per capita smysl dávají.

**Comment by katkolouchova** [comment]
Nene, Jeňo, máš pravdu, že v Ember datasetu jsou data pouze pro poptávku.
Díky za objasnění, byla jsem z toho zmatená, protože jsem někde četla, že poptávka se uvádí např. v kW, zatímco spotřeba v kWh. Ale teď chápu, že v daném kontextu to zaměňují a budu s tím pracovat jako se spotřebou. Díky!

**Comment by kikinna** [comment]
@ondraspribyla Update grafiky. 
Vím to a zkouším tě vědomě --  jestli překousneš to, že jsou roky jen u spodních grafů, hh. Moje motivace? Pod každým grafem to přidává zbytečně šumu, je pak třeba přidat víc bílého prostoru respektive zmenšit grafiky a zároveň informace tří let je dostatečně jasná, čitelná a několikrát zmíněná (i podnadpis) podle mě (a taky Kačky -- pomáhala mi se nad tím zamýšlet) pro to, aby byla jen ve spodní části všech grafů. 

Jinak jsem přidala procenta ke každému regionu předávající info o tom, kolik procent celosvětové výroby tvoří daný region. Je to takhle ok?

**Comment by ondraspribyla** [comment]
@kikinna vlastně dobrý, ale chtěl bych to otestovat s
nějkýma živejma lidma... nejdřív jsem si vůbec nevšiml, že tam ta y-ova osa
není. Grafy jsou asi skutečně čitelné i bez ní...
Ale já tedˇvím, co v nich hledám, takže nejsem dobrej na zpětnou vazbu.
Navíc mám trochu strach, že bez osy y natolik porušujeme "vědecké"
standardy, že tento graf nikdo nebude chtít použít v odborných praceh. Do
novin to rozhodně nevadí...
Chci to ještě zítra vyzkoušet, ale asi tomu dám zelenou - je to mimo
standard, ale dobrý.

Bude pak potřeba doladit formulační detaily... (jako například jestli
"zbytek světa"neoznačit jinak, nebo jestli se drbat s přesnějším vyjádřením
"Vývoj výroby elektřiny podle jednotlivých zdrojů mezi lety")

**Comment by kikinna** [comment]
@ondraspribyla Hh, ano, bylo by vhodnější to testovat s živými lidmi :D 
Super, tak dej pak vědět, co z testování zjistíš.
Ad texty, ty mi nachystáš ty nebo mám poprosit někoho jiného? )

**Comment by jankrcal** [comment]
Náhodný komentáře jednoho živýho člověka:

1) Esteticky jsem z toho u vytržení :) Větší označení os mi nechybí.

2) Vadí mi nejasná hierarchie: celý svět je jeden z šesti boxíků. Chápu, jak to vzniklo, ale nevím, jak to opravit, ale stál bych o to, aby boxík celého světa byl nějak vizuálně výraznější oproti zbytku.

3) Přijde mi, že může mást to, že všechny boxy jsou vizuálně stejně velké, přestože ve výrobě elektřiny nejsou. Sice je to tam pěkně označený, ale stejně to trochu zavádí. 
Současně nejde použít realistický měřítko, protože celý svět je prostě moc velký oproti zbytku. Co třeba takto?
 - Dát celý svět do pravého sloupce od zdola až nahorů (tedy omezit titulkový text na levé dva sloupce), 
 - Do levého sloupce dát EU, USA, Indii, do prostředního sloupce dát Čínu a zbytek světa
 - Těch 5 částí světa v ose y naškálovat úměrně jejich velikosti (což by v tomto rozložení mělo ty levé dva sloupce přiměřeně zaplnit).
 - Toto škálování nebude přesně úměrný škálování celého světa (svět bude o něco menší, než by měl být), ale to mi přijde, že už srozumitelnost nenarušuje)
 - Celý by to trochu omezilo čitelnost, obzvlášť Indie by utrpěla, otázka, jestli se nedá rozdělit Indie+Zbytek světa na nějaké jiné dva logické a rovnoměrnější kusy?

Bod 3 je dost invazivní a čekám, žes s něčím takovým už experimentovala, tak klidně ignoruj :)

**Comment by kikinna** [comment]
@jankrcal Jéni, díky moc za komentář! Je užitečnej ))) (A taky jsem ráda, že se ti to líbí))
Máš pravdu, že jsem s tím už experimentovala, vlastně s něčím dost podobným (celej svět zabírající jeden celý sloupec) a musím říct, že se mi líbí, jak nad tím přemýšlíš. :) Nicméně, ať jsem se snažila sebevíc, tak furt něco nefungovalo. Přjde mi, že tato grafika je odsouzena k tomu, že tam vždy zůstane něco, co jemně nefunguje :(
Ale hodně se mi líbí nápad možná ještě nějak jinak odlišit ten svět (protože to by snad fungovat mohlo?). To jsem i původně chtěla a v tom všem testování na to zapomněla, hh.

Ještě jsem přemýšlela, že jsem chtěla právě ukázat třeba na jedné ose / stacked baru poměry jednotlivých regionů, což by mohlo pomoci si vizuálně uvědomit ten kontext, ale to taky nefungovalo (hlavně není prostor).

Což je potom další velká výhrada -> zvětšení grafu světa vede ke zmenšení všech ostatních a snižuje se trošku čitelnost.

**Comment by ondraspribyla** [comment]
Navrhuju korekce po testování:

1. Přepsat nadpis a podnadpis
Nadpis: Výroba elektřiny ve světě, 2000 - 2019
Podnadpis: Vývoj množství vyrobené elektřiny podle zdrojů. Hodnoty jsou
uváděné v TWh
(současný podnadpis mate tím, že poutá pozornost k sekundárním údajům, jako
třeba "relativní podíl")

2. Doplnit "ticks" na x-ovou osu ke všem grafům
(Problém = byly sice hned jasné koncové hodnoty (protože je to popsáno u
prního grafu pro svět), ale nebyl jasný význam "čáry, která je skoro
uprostřed" (tedy vyznačení roku 2010), čáře byl nesprávně přisuzován význam)
Navrhuju dát "ticks"(=značky?) po jednom nebo dvou letech na osu x, pro
všechny grafy a pouze u spodní řady grafů psát k značkám hodnoty 2000 -
2010 - 2019

3. Zmínit, že % jsou za rok 2019  a možná změnit polohu údaje %
u grafu USA je potřeba změnit popisek na "podíl regionu na celosvětové
výrobě elektřiny v roce 2019"
(Problém = hodnota podílu% byla nesprávně přisuzována k roku 2010, protože
je uprostřed a je pod ní ta čára... ) - mohlo by tedy pomoct třeba dát
hodnotu do závorky vedle názvu regionu...

U žádného (ze dvou :-) testerů nebyl problém se čtením Celý svět vs části
světa.

Zábavné zjištění: překvapilo mě, že testeři si četli název grafu a
podnadpis. To já nedělám :-) První na co koukám jsou grafy, hledám osy a
jednotky a pak teprve se dívám na popis. A překvapilo mě, že jsou lidi,
kteří čtou nejdřív popis a pak teprve koukají na graf. Myslím, že by se
někdy hodilo si udělat nějaký eye tracking testování a podívat se, zda v
tom není nějaká typologie (třeba že fyzici hledají osy ale normální lidi ne)

**Comment by katkolouchova** [comment]
Níže přikládám dva výstupy z Rka, které ukazují výrobu/poptávku per capita. Vznikly spojením dat o energetice a ročních dat o populaci jednotlivých regionů a zemí EU z UN. Zatím se jedná spíš o explorační grafy, užitečné pro srovnání jednotlivých regionů/zemí. S Kristi jsme se ale shodly, že i tak by stálo za to je zpracovat na web.

Pak je otázka, jakou story chceme těmito grafikami říct? Zajímá nás hlavně vývoj v čase? Pokud message odpovídá grafikám níže, mohli bychom ji zapracovat do anotace. Pokud je ta message ještě jiná, můžeme z dat vytvořit další grafiku. Budu ráda za vaše podněty :) Případně si můžeme i společně zavolat a probrat to dohromady.

1. Grafika zobrazuje výrobu elektřiny v jednotlivých regionech per capita podle typů zdroje v porovnání se světem (= šedá čára). Místo výroby tam samozřejmě může být i poptávka/spotřeba (která mimochodem v datech vzniká součtem výroby a čistého importu).
![production_per_capita_regions](https://user-images.githubusercontent.com/49321752/81817854-8b382180-952d-11ea-9ff2-898c0c0db440.png)

2. Grafika zobrazuje poptávku (spotřebu) v jednotlivých zemích EU per capita v porovnání s celou EU (=šedá čára). S Kristi jsme přemýšlely, jestli grafy neseřadit podle hodnot, ale zase teď je rychlejší najít konkrétní zemi.
![demand_per_capita_EU](https://user-images.githubusercontent.com/49321752/81818909-e9193900-952e-11ea-9119-3717741c1d93.png)

**Comment by jankrcal** [comment]
Ad 1: to mi přijde skvělý a přijde mi, že by se to dalo zobrazit velmi podobně jako současně připravovaný graf celkových hodnot.

Ad 2: Upřímně toho v tom moc nevidím kromě toho, že:
 - chudší země se rozvíjejí a spíše zvyšují svoji spotřebu (k průměru, či lehce nad průměr)
 - bohatší země šetří a spíše snižují svoji spotřebu (k průměru či lehce pod průměr)
 - jsou tam tři neuvěřitelní outliers: 
    - Lucembursko (to je asi pochopitelný, je to  ~jedno město, města asi mají větší spotřebu než venkov, navíc do Lucemburska spousta lidí pendluje za prací, tak je to zkreslený)
    - Finsko a Švédsko: trochu jsem hledal a moc to nechápu, nejspíš mají snadný obnovitelný zdroje elektřiny (hydro, lesy), ale to má např. Rakousko taky a není 2-3x nad průměrem.

Přišlo by mi lepší udělat grafiku o méně vybraných zemích a dát ke každé zemi více informací, tedy:
 - jejich výrobu podle zdroje (podobně jako Kristi připravuje)
 - jejich spotřebu (tak jak to teď máš)
 - možná tam nenápadně přidat průměrnou spotřebu EU, to je taky zajímavý pro srovnání
Všechno to může být per capita, aspoň budeme moct použít stejnou osu y pro všechny země a bude to dobře srovnatelné.

Co myslíš, Katko?

**Comment by katkolouchova** [comment]
Ad 1: Máš na mysli nějak takto, Jeňo? Je pravda, že ten pohled per capita je zajímavý pro srovnání s ostatními regiony, takže je na první pohled hezky vidět, jak jsou třeba USA úplně někde jinde (když jsou navíc osy stejné).
![production_per_capita_regions_area](https://user-images.githubusercontent.com/49321752/81929261-06a9d980-95e7-11ea-8534-829fd3b6f0ed.png)

Ještě mě napadlo zobrazovat jednotlivé zdroje a k nim regiony. Je to trochu chaos, jak je každá osa y jiná, ale je tam vidět, jak jednotlivé zdroje rostou nebo klesají. Zkusila jsem dát i všechny osy y stejné, ale pak tam bylo vidět v podstatě jen uhlí, plyn a jádro.
![production_per_capita_variables](https://user-images.githubusercontent.com/49321752/81931382-4d4d0300-95ea-11ea-8d01-6ade18f68328.png)

Ad 2: 
- k Lucembursku – navíc je tam ze všech zemí EU zdaleka největší podíl čistých importů na osobu, což dává smysl
- ke Švédsku a Finsku – dívala jsem se do dat a Švédsko má hodně zdrojů z jádra a vodní energie, Finsko taky, ale ještě k tomu má navíc biomasu

Souhlasím, že můžeme vybrat pár zemí a pro ty zobrazit víc informací, jak navrhuješ. Podle jakého klíče bychom ty země vybrali? Určitě by tam mělo být Česko, protože to bude čtenářům nejbližší.

Jinak díky za podněty, Jeňo :) Celkově by mi možná pomohlo si k tomu zavolat a víc prodiskutovat, co přesně chceme těmito infografikami sdělit.

**Comment by jankrcal** [comment]
Wow, ten graf pro US mě sejmul.

Ano, zavolejme si. Dneska už to nedám, ale někdy zítra bych mohl. Pošlu mail, ať se nedomlouváme tady veřejně.

**Comment by kikinna** [comment]
@protivinsky Tome, mohla bych tě poprosit, jestli bys mi nekoukl taky u této grafiky na nadpis, podnadpis, legendu, popisky, zdroj a slug? :) 

![elektrina-svet-13](https://user-images.githubusercontent.com/11555522/82756617-7dab5300-9ddb-11ea-8b71-cebbf75a61fd.png)

**Comment by protivinsky** [comment]
@kikinna :
- nadpis: "Výroba elektřiny ve světových regionech" (případně i ten tvůj stávající je dobrý)
- podnadpis: "Vývoj celkové výroby elektřiny podle jednotlivých zdrojů v letech 2000–2019 celosvětově a pro hlavní regiony. Hodnoty jsou uváděné v TWh za rok."
- legenda: "Ostatní fosilní paliva", "Vítr", "Slunce", "Hydro"
- slug: elektrina-svet (elektrina-svet-celkem ?)
- zdroj: Ember (zde nejsou populační data)
- popisky ok - akorát ta procenta se předpokládám vztahují čistě k roku 2019, tuším že už se to někde řešilo. Prosím připiš alespoň na konec toho souvisejícího popisku "v roce 2019".
- použít "Ostatní státy" namísto "Zbytek světa"

Tím je to za mě ok, díky!

**Comment by protivinsky** [comment]
@kikinna Mimochodem teď se koukám že nadpis apod. navrhoval už Ondráš o několik komentářů výše, včetně těch procent a roku 2019 a ještě nějakých drobností. Nevím, jestli jsi to s ním nějak více diskutovala nebo jestli ti ten komentář unikl?

**Comment by kikinna** [comment]
Uniklo. Zapomněla jsem to a přehlídla.

**Comment by kikinna** [comment]
To mě mrzí. Nicméně, zapracovala jsem, snad. 
Jestli to bude dobrý, tak prosím dej povel k exportu )

![elektrina-svet-13-13](https://user-images.githubusercontent.com/11555522/82759308-db946680-9dec-11ea-90a4-61a6e7cf2a0b.png)

**Comment by protivinsky** [comment]
@kikinna - prosím ještě o stejné mezery v legendě (promiň, předtím to tak bylo, rozbili jsme to těmi změnami). Následně můžeš exportovat, díky.

**Comment by kikinna** [comment]
@protivinsky tady ;) https://www.dropbox.com/sh/fysjwh8zu2bwomm/AACj2ORNiwLiwAVKuRyU4Jw2a?dl=0

**Comment by protivinsky** [comment]
@kikinna děkuji - akorát toto je jediná z těch elektřinových grafik kterou jsem moc neřešil, ani k ní nepřipravil text nebo PR. nejspíš to ponechám na hackaton :)
