### ISSUE TITLE
Fix gradientu a průhlednosti v Emisních intenzitách

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web#524]
Konkrétně grafika emisních intenzit používá částečnou průhlednost na koncích hyperbol, avšak zkonvertované soubory tuto průhlednost nezachovávají a hyperboly tak jsou znatelně delší.

Za mě to není velký problém, ovšem může to ovlivnit i další grafiky v budoucnu a nevím jestli to nelze nějak snadno opravit. Konverzi dělá inkscape nebo něco jiného? Nestačilo by případně jen něco aktualizovat na nejnovější verzi? (Inkscape teď vydal verzi 1.0 po dlouhé době.)

**Comment by mukrop** [comment]
Uz sa to riesilo v minulosti, pri zachovani aktualneho stupna automatizacie (co ma podla mna prioritu) to ovela lepsie nejde. S polopriehladnostou je tradicne problem, osobne by som sa jej v grafikach vyhybal uplne.

@kikinna: Chces prerobit tu grafiku na Emisne intenzity, aby to bolo ciste? Podla toho tento issue bud zatvor, alebo prerob na upravu grafiky.

**Comment by kikinna** [comment]
Předělám.

**Comment by ondraspribyla** [comment]
closing - požadavek přepsán do #592
