### ISSUE TITLE
Vyjasnit licenci dat ČHMU

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#527]
Vid koemtar od Katky v #526.

**Comment by mukrop** [comment]
@jankrcal, in progress, but it's complicated, preberieme na spravnej rade.

**Comment by protivinsky** [comment]
Nejsem si úplně jistý, kde k tomuto chceme pokračovat diskuzi - ze 106 (https://www.zakonyprolidi.cz/cs/1999-106):

> § 3 (11) Otevřenými daty se pro účely tohoto zákona rozumí informace zveřejňované způsobem umožňujícím dálkový přístup v otevřeném a strojově čitelném formátu, jejichž způsob ani účel následného využití není omezen a které jsou evidovány v národním katalogu otevřených dat.

> § 4b (2) Povinné subjekty zveřejňují informace obsažené v jimi vedených nebo spravovaných registrech, evidencích, seznamech nebo rejstřících, které jsou na základě zákona každému přístupné a které lze využít při podnikání nebo jiné výdělečné činnosti, ke studijním nebo vědeckým účelům anebo při veřejné kontrole povinných subjektů, jako otevřená data.

Nejsem právník, ale toto skutečně zní, že s daty si mohu dělat cokoli.

**Comment by mgrabovsky** [comment]
Taky nejsem právník, proto bych to nechal na právníkovi.

Osobně si myslím, že data ČHMÚ nejsou (automaticky) otevřenými daty ve smyslu 106. Přinejmenším proto, že v NKOD všechna nejsou. A ač třeba [teploty pro Brno-Tuřany](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2Fhttps---kod.brno.cz-api-action-package_show-id-meteodata) tam jsou, poskytovatelem je Statutární město Brno, nikoliv ČHMÚ.

Navíc například data [nedávno zveřejněná](http://portal.chmi.cz/historicka-data/pocasi/denni-data/Denni-data-dle-z.-123-1998-Sb.) na základě žádosti podle zákona č. 123/1998 a soudního rozhodnutí, která jsou vlastně nadmnožinou těch, co využíváme my, mají [vlastní podmínky použití](http://portal.chmi.cz/files/portal/docs/meteo/ok/denni_data/Podminky_uziti_udaju.pdf). Mám pocit, že se i díky tomuhle ta přístupnost a licencovaní někde řešili, protože to je aktuálně právně nejasné, a myslím, že se chystá nějaká novela, co by to zevrubně ošetřila, ale už si nevzpomínám na podrobnosti.

**Comment by jankrcal** [comment]
Souhlasím, že data od ČHMU nemusí být otevřenými daty ve smyslu 106.

Tyhle podmínky užití jsou ale dost dobrý, ty jsem neviděl. Jakože to není CC BY 4.0, ale pro nás je to velmi podobné, minimálně to nezakazuje derivative work. Na práci Katky se to vztahuje. V datasetu (#526) bychom mohli jejich licenci shrnout volnými slovy (např. "zdarma k použití, vyžaduje odkázání zdroje" jak to děláme u některých vědeckých datasetů na https://faktaoklimatu.cz/datasety/koncentrace-co2), odkázat na jejich podmínky použítí a podle mě máme hotovo.

Další infografiky nevycházejí přímo z denních dat, tam to asi stojí za větší vyjasnění s právníkem.

**Comment by mukrop** [comment]
Hlavne nemaju jednotne info o pouziti, ja som nasiel podmienky pouzitia [na tejto stranke](http://portal.chmi.cz/podminky-uziti), ale tie, co posielal Matej mi unikli.

Navrhujem teda upravit info o licencii na stranke datasetu upravit podla toho, co nasiel Matej.

**Comment by katkolouchova** [comment]
Upravila jsem to, viz #526

Prosím o kontrolu, @mukrop

**Comment by mukrop** [comment]
PR je pripraveny na merge, toto zatvaram.
