### ISSUE TITLE
Zveřejnit svoje členství v organizaci

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#529]
Vaše členství v GitHub organizaci "Fakta o klimatu" je dle výchozího nastavení skryté (tj. nejste vidět na https://github.com/faktaoklimatu).

Jestli chcete, můžete své členství zveřejnit na https://github.com/orgs/faktaoklimatu/people (vedle svého jména vyberte _public_ misto _private_.)

**Comment by mukrop** [comment]
@faktaoklimatu/all: Bolo by super, keby na GitHub stránke organizácie bolo vidno ľudí, ktorí za projektom stoja. Na toje explicitne treba sa zverejniť. V prípade záujmu nájdete návod v issue #529.

**Comment by mukrop** [comment]
@ondraspribyla, @tomas-psorn, @vlckel, @protivinsky, @crysman, @palcifer, @jakub-zamouril, zvazte zverejnit svoje clenstvo v GitHub organizaci _Fakta o klimatu_. Instrukcie na https://github.com/faktaoklimatu/web/issues/529.

**Comment by ondraspribyla** [comment]
Hotovo, jsem public

**Comment by mukrop** [comment]
OK, uz to zacina byt reprezentativne. Dik vsetkym, ktory sa prestavili na public.
