### ISSUE TITLE
Vytvořit systematickou tabulku pro naše použití

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#531]
Vytvorit prehladnu tabulku, kde budeme ukladat vsetky pouzitia nasej prace ostatnymi subjektami.
* Je treba vymysliet, co chceme o jednotlivych pouzitiach ukladat.
* Ukladat minimalne: datum pouzitia, URL, kto nas pouzil (institucia, mozno aj je typ – politicka strana, neziskovka, media, ...), kto nas pouzil (meno cloveka), typ (zakladny prehlad typov treba vytvorit podla aktualneho prehladu).
* Spracovat existujuci prehlad (https://github.com/faktaoklimatu/internal/issues/15).

**Comment by kikinna** [comment]
@protivinsky Tome, na to by se skvěle hodila db v notion, co myslíš? ;)

**Comment by mukrop** [comment]
To mozno ano, ale excelova tabulka (gSheet) je na to podla mna viac nez dostatocna. Nebranim sa vo vseobecnosti prejst na Notion, ale nepaci sa mi byt rozlezeny cez X sluzieb. Aktualne aktivne pouzivame sadu od GitHubu a Google a potrebujem naozaj vidiet prinos, aby sme pridali nieco dalsie.
(Este teda okrajovo pouzivame Trello a Mural, ale tie neviem, ci vydrzia.)

**Comment by kikinna** [comment]
Neboj, vím :) V Notion bych to nedělala, pokud bychom se nerozhodli na něj přejít "komplet"

**Comment by katkolouchova** [comment]
Vytvořila jsem [prototyp tabulky](https://docs.google.com/spreadsheets/d/1yRQOyE_CO5c9uLfybrnj2Mc8lq3kZ3hvs7bDm8yLPvs/edit?usp=sharing) pro ukládání informací zejména o sdílení našich infografik jinými subjekty.

Hlavní otázka je, k čemu chceme, aby nám přehled sloužil. Zatím jsem uvažovala tak, že mi přijde fajn vidět, z jakého tématu je sdíleno nejvíce/nejméně infografik, jaký typ instituce nás nejvíc sdílí a jak se sdílení proměňuje v čase.
Kategorie témat odpovídá rozřazení infografik na webu. Co se týče typlogie institucí, vycházela jsem z existujících sdílení, nicméně granularitu lze upravit na větší/menší. Taky se některé typy mohou někdy významem někdy překrývat.
Narazila jsem na případy, kdy někdo jenom odkazoval na náš web (řekla bych, že i to je informace), proto jsem zatím vytvořila kategorii _pouze odkaz na web_, ale přemýšlela jsem i nad tím, jestli odkazy nezapisovat do zvláštního listu. Co myslíte?
A pak tu jsou akce, na kterých vystupoval přímo někdo z Fakt a logicky sdílel naše infografiky :) To bych ale do přehledu o sdílení jinými subjekty nedávala. A přemýšlím, jestli tento přehled vůbec udržovat (zatím jsem přidala list _Naše prezentace_) v tomto souboru, nebo to patří jinam.
Z prozatímních dat jsem vytvořila jednoduchý přehledový report (s limity googlesheets, kdy např. nejde graf bez mezitabulky graf seřadit o největší hodnoty po nejmenší...).

Budu ráda za zpětnou vazbu :)

**Comment by setcz** [comment]
Přijde mi to dost dobrý!

Jediné, co mi napadlo je přidat tam sloupec "Super zářez!" (může se jmenovat jinak:) ) - kde by bylo možné subjektivně označit význačné úspěchy. Aby se podle toho dalo filtrovat, když je potřeba někam dát jen pár příkladů. Ale možná to nikdo nepotřebuje.

**Comment by ondraspribyla** [comment]
Tabulka je super - navíc vidím, co všechno se dá v spreadsheetu
optimalizovat....

@setcz - celé mě to vede k přemýšlení o "Outreach týmu" - hodilo by se mít
partu, která bude pravidelně a konzistentně tweetovat, udržovat kontakty s
novináři a vůbec pečovat o to, aby se naše produkty dostávaly tam, kam
mají. Nicméně takový tým nebude fungovat skrze hackatonové sprinty, tedy
nebude jednoduché propojit Outreach a Produkci... Co si o tom myslíš/te?

**Comment by setcz** [comment]
@ondraspribyla ano souhlasím, to byla přesně hlavní myšlenka těch [myšlenek ke směřování Fakta o klimatu](https://docs.google.com/document/d/10FdU7q1qURRm0J6ovlawDf1qetyvQx2QKcNcKvI0BO4/edit#) (dostupné jen pro core), co jsem psal minulý týden

**Comment by mukrop** [comment]
@katkolouchova: Prototyp tabulky mi pride super :-).
* Suhlasim so Setom, ze stlpec "featured"/"highlighted" by mohol byt uzitocny (use-case: budem vypisovat prihlasku do sutaze a budem chciet vidiet, co sa nam vlastne podarilo).
* Suhlasim s tym, ze by som rozdelil karty na "zmienili nas" (napr. len link na nas) a "pouzili nas" (exemplarne: prebrali infografiku alebo data).
* Zapisoval by som aj nase vystupenia, tiez do samostatneho listu, ako si navrhla. Rad by som, aby sme dohladali aj historicke (poulicne akademie, Ondrasovu prednasku v Huse a na prirodovede, ...).
* Ak si spracovala cely issue z interneho repa s pouzitiami, prosim zatvor ho.
* Navrhujem napisat na klimaton-core, ze tabulka existuje a poprosit vsetkych, nech ked nieco objavia, nech to tam rovno pridaju.
* Vidim to niekedy na hackathon k pouzitiu – dohladavanie informacii tohto typu (mozno pracovna skupina na dalsom hackathone?).

**Comment by katkolouchova** [comment]
Díky moc za podněty :) V průběhu dnešního večera a zítřka je zapracuju a pak bych na klimaton-core napsala o tom, že tabulka existuje a je k dispozici pro používání.
