### ISSUE TITLE
Graf teploty přes graf koncentraci CO2

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#532]
Stretol som sa s grafom teploty vs. koncentracie CO2 v dlhsej historii a pride mi to ako celkom posobiva korelacia: https://skepticalscience.com/images/Milankovitch_Cycles_400000.gif

![Milankovitch_Cycles_400000](https://user-images.githubusercontent.com/1871676/82113757-c4a0a500-9758-11ea-9988-9624a8cf928e.gif)

Nezvazujeme pridat teplotu do grafu koncentracii CO2?

(Ma to aj svoje uskalia, viz [stranka na skeptical science](https://skepticalscience.com/co2-lags-temperature.htm).)

**Comment by ondraspribyla** [comment]
Je to trochu problematické... proto bych teplotu k CO2 nepridával. Ale rád
vysvětlím (osobně) a můžeme si povídat o dalších použitích

O.
