### ISSUE TITLE
Záměna Prahy-Ruzyně za Prahu-Libuš

### ISSUE THREAD

**Issue by katkolouchova** [faktaoklimatu/web#539]
Ahoj, předně se chci moc omluvit za svoji nepozornost. Při zjišťování vlivu tepelného ostrova města v Praze, jsem zjistila, že jsem při zpracování dat v Google Sheets zaměnila data pro Prahu-Ruzyni za Prahu-Libuš. Na webu jsou tudíž data pro Ruzyni jako Libuš.
Jako nejrychlejší fix vidím všude přepsat Libuš na Ruzyni. Jsem schopná to udělat na všech místech kromě názvu v infografice.

Ještě jednou se omlouvám.

@ondraspribyla Co myslíš?

Ke zjištění ohledně vlivu tepelného ostrova (z porovnání s Klementinem) – v Ruzyni je patrně velmi malý, v Libuši možná větší (ale nevím, jestli nehrají roli i jiné faktory), viz:
![ruzyne-klementinum](https://user-images.githubusercontent.com/49321752/82351718-3e58bd00-99fd-11ea-9df1-bd143e400a2c.png)
![libus-klementinum](https://user-images.githubusercontent.com/49321752/82351723-3f89ea00-99fd-11ea-9972-a3306b0426eb.png)

**Comment by ondraspribyla** [comment]
Já myslel, že ruzyne má krátkou datavou řadu a proto je ho nebrali...

Každopádně díky za kontrolu a nalezenou chybu. Bude potřeba opravit...

Ještě k tepelnému ostrovů: dokázal bys udělat rozdíl teplot, nejen počtu
dní?

Dne út 19. 5. 2020 18:23 uživatel katkolouchova <notifications@github.com>
napsal:

**Comment by katkolouchova** [comment]
To je tím, že jsem je při přesunu dat do google sheets zaměnila a myslela jsem si, že Libuš je Ruzyně. Skutečnost je taková, že v Ruzyni měří už od roku 61 a v Libuši od 71. Založím novou větev a a všude přepíšu Libuš na Ruzyni.

Můžu udělat i rozdíl teplot. Máš na mysli maximálních nebo průměrných?

**Comment by ondraspribyla** [comment]
Ad rozdíly teplot: beru to jako experimentování s daty... takže nevím, co
je nejlepší, můžeš zkoušet a hledat.
Zajímalo by mě třeba, jestli tepelný ostrov funguje (skoro) pořád, nebo jen
některé dny (tedy jestli je teplota v centru konstantně vyšší, nebo někdy
je, a někdy ne)
Nebo třeba jestli funguje jen ve dne / jen v noci.

Tedy líbilo by se mi, kdybychom mohli udělat odůvodněný závěr typu:*
klementinum je v letních měsících o 1°C teplejší než ruzyně, největší
rozdíl denní průměrné teploty byl 5°C a rozdíl teplot je nejvetší za úplňku*
:-))

Moc se s tím prosím netrap, není to diplomová práce :-)

O.
