### ISSUE TITLE
Bug při prohlížení v Safaricheck funkcionality v SAFARI

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#541]
Dostli jsme nahlášen nějaký bug webu v Safari ohledně scrollování a zobrazování menu na tabletu. Je potřeba to prozkoumat a případně opravit.

**Comment by ondraspribyla** [comment]
Udajně při provozu v prohlížeči  SAFARI mizi horní lišta když se scrolluje - dostal jsem to dneska nahlášený jako bug, tak jej předávám dál... @mukrop @mgrabovsky

**Comment by repli2dev** [comment]
@ondraspribyla mizí v safari na mobilu... matný dojem říká, že jsme to už řešili. Svým způsobem jsem to považoval spíš za feature, menu se vždy objeví v momentu kdy zaskroluji trochu nahoru.

**Comment by mukrop** [comment]
To je feature. Mobilove obrazovky su male, stranky s menu v hornom pruhu to maju rutinne tak, ze pri scrolle dole sa skryje, pri scrolle hore sa objavi.

**Comment by mukrop** [comment]
Androidy to maju robit (a robia) tiez.
@repli2dev, mozes mi prosim potvrdit, ze v desktopovom/tabletovom Safari je to OK?

**Comment by repli2dev** [comment]
Desktop Safari: menu se schovává jen při určité velikosti viewportu.
iPad - landscape: menu se schovává
iPad - portait: menu se **neschovává**
iPhone - landscape: menu se schovává
iPhone - portait: menu se schovává

**Comment by repli2dev** [comment]
Nicméně chyba tam je, pokud mám viewportu tak 800x600, zaskroluji dolů a pak úplně nahoru, tak se mi menu i přesto schová a víceméně ho nelze přinutit aby se objevilo.

![Snímek obrazovky 2020-05-21 v 13 59 32](https://user-images.githubusercontent.com/475549/82557079-4cc4e700-9b6b-11ea-8e24-ff9453fc3671.png)
