### ISSUE TITLE
Grafika: Vyrobená elektřina států EU na osobu

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web#542]
Garant obsahu: @protivinsky @jankrcal 
Garant grafiky: @kikinna
Datově zpracovává: @katkolouchova 

- [x] @protivinsky Tome, mohla bych tě poprosit o popisky (nadpis, podnadpis), atd.?
- [x] Kdo zpracuje průvodní text?
- [x] Fixnout osy (zatím jen od oka)
- [x] Zmenšit bílý prostor mezi řádky grafů
- [x] @katkolouchova Nahraješ prosím někam na drive dataset a odkážeš ho z tohoto issue? :) děkuji))
- [x] Vymyslet slug
- [x] Doplnit zdroj -- Ember? 
- [x] Posunout graf EU dolů.
- [x] Otestovat s Martinem, jak se přeloží Multiply blending mode

_Finální stav grafiky_
![Energetika EU-10](https://user-images.githubusercontent.com/11555522/82735431-ffd74100-9d21-11ea-89f2-8ecec90caf85.png)

**Comment by katkolouchova** [comment]
Dataset, který je výstupem zpracování dat v Rku a ze kterého šla data to grafiky najdete [zde](https://docs.google.com/spreadsheets/d/1jPxsJlA0smUap-AF4tciC1yrwiUJ-mknj660o6Dw7WA/edit?usp=sharing). Obsahuje data pro jednotlivé země EU a EU jako celek. Případně můžete využít i formát csv [electricity_population_EU_data.csv](https://drive.google.com/file/d/15OZFX6pjd7-Emb0WaAHOigGiKlmzRBhJ/view?usp=sharing).

**Comment by jankrcal** [comment]
Kristi, díky za vykopnutí, je to krásný!

Mám dost problém s tím, že tři outliers (Švédsko, Finsko, Lucembursko) kazí čitelnost pro všechny ostatní. Nemohli bychom pro tyto země alokovat víc prostoru (třeba dvojnásobný dílek na výšku nebo že by tyto tři země byly v jednom sloupci místo 4 zemí), aby ostatní grafy byly čitelné?

**Comment by protivinsky** [comment]
Tohle ti přes Kristi asi neprojde :)

Pěkná grafika, děkuji. Uznávám, že ty ostatní země pak vypadají dost malé, nicméně za mě je ok to ponechat takto. Moc mě nenapadá, jak to udělat graficky čistě, aby ty ostatní země mohly být větší. Zároveň je otázkou, proč to tak je - skutečně tyto tři země spotřebovávají více, nebo je to jen o spotřebě elektřiny oproti jiným druhům energie? Například vyšší elektrifikace vytápění / dopravy? Spíš úvaha do budoucna, rovněž něco, co je dobré vypíchnout v průvodním textu.

@kikinna texty dodám.

**Comment by jankrcal** [comment]
Ad outliers data: Švédsko má asi jen vyšší elektrifikaci (jejich celková spotřeba energie je jen cca o 10% vyšší než v Česku), Finsko má vyšší spotřebu (o 60% víc než v Česku), Lucembursko asi nemá smysl analyzovat ("městský stát", hodně pendlerů). Ostatně pokud by v grafice chyběl prostor, tak můžeme klidně Lucembursko vyhodit (navrhoval Ondráš).

Ad outliers grafika: fakt by mi přišlo škoda s tím nic neudělat. Pokud by byl problém s řazením, mohly by se taky státy seřadit podle maximální hodnoty v ose y a ne podle abecedy a třeba pracovat s jinou výškou grafu konzistentně (nejmenším státům bychom kreslili osu y jen do 500, větším do 750, ještě větším do 1000 a těm outliers do 1500).

**Comment by kikinna** [comment]
Ahojte )) Ad Finsko, Švédsko a Lucembursko. :) Je to věc, kterou vnímáme všichni, hh. )))
Zkusím se na to dneska kouknout, co se s tím dá dělat. Mám jeden dva nápady.

Setřizovat podle velikosti ještě jakštakš jde, ale vnímám tam už problém splnit úkol "Najdi Slovensko" -> prakticky máš lineární složitost hledání, což při 28 státech není optimální. :D Dám vám update. 

@protivinsky Tome, díky za texty!

**Comment by kikinna** [comment]
![Energetika EU-08](https://user-images.githubusercontent.com/11555522/82529356-238c6280-9b3b-11ea-850b-0e15e9a128d5.png)

Hm, tak co říkáte? 
Vím, že je Finsko trochu hůř čitelné, ale nejspíš je to něco, co jsem ochotná obětovat. :D (Docela jsem si s tím hrála a next step by byl změnit color coding všech grafik energetiky. Což nevím, jestli Finsko za to stojí, obzvlášť s takovou spotřebou! 😃 

@katkolouchova Katy, dávala jsem i osy pryč, klidně ti pošlu obrázek. Zatím mi to přijde takhle lepší (jakoby mi chybělo se něčeho uchytit), ale musím na to kouknout s čistou hlavou. :)

**Comment by jankrcal** [comment]
Za mě mnohem lepší (i když je to trochu punk), díky!

Přidávám na zvážení, jestli nedat ke všem grafíkům čárkovanou osu 15 000 a jestli neprotáhnout šedou až k té ose. Tak by programově byl název státu uvnitř jeho grafu a nebylo by to pro ty tři outliers tak překvapivý.

Ještě je tam něco divně, protože v prvním draftu se všechny země vlezou do 1500 (sic), teď ty outliers nad 15 000 (sic) dost vylézají. Ty jednotky jsou každopádně nějak divně, když průměr EU má být okolo 6000 kWh / osobu a rok.

**Comment by protivinsky** [comment]
Za mě punk dobrý! A dobrý postřeh od Jéni, ty jednotky jsou teď nějaké zvláštní a vůči čárkovaným linkám posunuté oproti předchozímu grafu.

**Comment by kikinna** [comment]
Ten průměr by měl sedět, koukala jsem na to. Průměr je 6100-6200.
Jinak na předchozích grafikách byly osy jen od oka - spíš šlo o testování vizuálu a až dneska jsem to přidala tak, aby to odpovídalo ;) Ale dobrý oko. 
Přesto to můžu ještě doublechecknout ty osy jestli sedí.

Ad protáhnout obdelníčky je to zajímavý nápad a taky jsem to zvažovala. Prvně jsem ti chtěla napsat, že to nefungovalo, ale vlastně to bylo vy jiné etapě, takže je super, že to znovu otvíráš, protože teď je to podle mě dost lepší a funguje to. (Teda FI, LU a SE stále vylézaj, ale to nevadí)
Takhle je to za vás ok?
![Energetika EU-10](https://user-images.githubusercontent.com/11555522/82537752-d44e2e00-9b4a-11ea-8642-13566e7a5cb9.png)

(Jinak tam zbývaj nějaký drobnosti uklidit a upravit.)

**Comment by kikinna** [comment]
Je skvělý, že na to takhle koukáte. :) Je to hodně nápomocný, protože jakmile začnu řešit detaily jako kde maj být osy, jaké jsou barvy, jak se mi to šrafuje, tak přestávám vidět ten overall pohled. Tak si moc cením, že na to koukáte a zrovna dáváte zpětnou vazbu 💙

**Comment by katkolouchova** [comment]
K těm osám – myslím, že spíš předtím byly špatně. Protože předtím ta úplně vrchní osa neměla být 15 000, ale spíš ke 20. Když kouknete do dat, uvidíte, že to teď sedí :)
Jinak za mě byla první varianta o něco lépe čitelná a přišlo mi snadnější jednotlivé země na první pohled porovnat, když tam bylo víc "čistého" místa. Ale rozumím argumentu s outliers.
K té variantě s názvy uvnitř – líbí se mi, působí to pak na mě víc jako celek. A navíc se tím trochu řeší i to, že se mi nelíbilo, že třeba u Lucemburska byla čára pro spotřebu úplně mimo.
Jinak mi Kristi klidně pošli tu variantu bez os. Já jsem to myslela tak, že by mě zajímalo, jak by to vypadalo s odděláním ticks pro roky všude kromě posledního řádku :)

**Comment by kikinna** [comment]
Jojo, přesně tu mám ready.

Jinak naprosto s tebou Kači souhlasím co se týče toho volnějšího prostoru a taky jsem to prvně chtěla vytknout, že to bude plnější a míň vzdušnější. Ale vlastně tak či tak něco nebude dokonalý (😭 hh) a tady v té variantě mi víc sedí, že máme všude stejně ty osy. Působí to kousek dotaženěji. 

Pošlu osy. (Mám je přesně jak píšeš, jen je to na starší verzi)

**Comment by protivinsky** [comment]
@kikinna Kristi, texty do grafiky:

- nadpis: ponechat tak jak je - "Výroba elektřiny na osobu ve státech EU"
- podnadpis: "Vývoj spotřeby elektřiny na osobu a její výroby podle zdrojů v letech 2000–2019 pro státy Evropské unie a Velkou Británii. Hodnoty jsou uváděné v kWh." (bez těch hodnot v kWh se asi obejdeme, předpokládám, že se spíš nevydáme; případně i Velká Británie se dá vynechat; akorát ty jednotky potom musíme napsat někam jinam, aby to bylo jasné)
- slug: ponechat tak jak je - "elektrina-na-osobu-eu"
- zdroj: "Ember: Coal to Clean Energy Policy" (případně pokud chceš, můžeš to udělat podobným stylem jako je ta NASA - sice Ember není zkratka, ale to nejspíš nevadí)

Vytvořím k tomu rovnou WiP PR a začnu tam připravovat průvodní text.

**Comment by protivinsky** [comment]
@kikinna Evropská unie nám to trochu komplikuje - při zobrazení na stránce je uříznutá:

![image](https://user-images.githubusercontent.com/9573993/82733762-1bd0e780-9d0e-11ea-8a9f-e3c68c3f6334.png)

**Comment by kikinna** [comment]
@protivinsky Hh, to komplikuje. Jednak ji musím trochu posunout dolů a druhak si myslím, že zrovna takovéto uříznutí není nijak kritické pro účely náhledu, co myslíš? ;)

Děkuji za texty, nahodím později ))

**Comment by kikinna** [comment]
@protivinsky Jinak legenda je v pořádku? Je to korektní termín "ostatní fosilní paliva" (spadá pod to i ten plyn?)

Jinak teda tady je [PDF ](https://www.dropbox.com/sh/kc5xqrbowhw5phc/AAAKvIqntcjXfAaO_PUDt5X4a?dl=0)
Prosím, zkusíš to uploadnout a mohl by jsi mi potom poslat, jak vypadá to PDF / PNG? 
Používám tam tentokrát spešl blending modes (pro osy v grafech - rok 2010 + ty čárkované), tak bych ráda věděla, jestli to bude fungovat v překladu. ))

**Comment by kikinna** [comment]
@protivinsky Vidíš, ty k tomu vlastně píšeš i ten průvodní text? ))

**Comment by kikinna** [comment]
@protivinsky Snad tě až moc často netaguju 😄

**Comment by protivinsky** [comment]
@kikinna díky za úpravy a export:
- konvertované png a svg jsem ti nahrál do Infografiky\06 Energetika\03 Energetika EU - podil zdroju\Export v1.0 2020-05-23\assets
- "ostatní fosilní paliva" jsou určitě v pořádku; trochu jsem přemýšlel nad jádrem, jestli by nebylo lepší "jaderné elektrárny", ale zas by to bylo jediné se slovem elektrárny mezi zdroji, tak to nechme takto.
- zdroj Ember - trochu mně tam rozčilují ty dvě dvojtečky - nenahradíme tu druhou raději pomlčkou?
- uříznutá Evropská unie - souhlasím, že její oříznutí na náhledu nevadí; nicméně po tom posunutí už je to trochu rušivé, čili bych ji klidně nechal nahoře, kde byla předtím. Má smysl u ní mít tu x-ovou osu? Přijde mi divné, že u ní je a u ostatních států s výjimkou úplně spodních není.

![image](https://user-images.githubusercontent.com/9573993/82735864-e97ab680-9d1c-11ea-9d38-313cd0cff9e4.png)

**Comment by kikinna** [comment]
Hh, taky mě ty dvojtečky štvou ))
Evropská unie je teď naprd. Tak ji kousíček posunu, ale chtěla jsem mít stejné rozestupy. A tím pádem tam i nechám víc ty osy (jsou tam zamýšlené zároveň trochu jako legenda -> spíš si těch let všimne člověk prvně tam. 
Tak přeexportuji a pošlu ))

**Comment by ondraspribyla** [comment]
Vidím jen jednu "chybu" - hodnoty jsou v kWh na osobu. Nebo kWh per capita.
(A ještě přesněji kWh/osobu/rok)

Vleze se tam přesnější vyjádření jednotek? O zdůraznění, že jde o údaj na
osobu bych docela stal.

Dne so 23. 5. 2020 18:51 uživatel kikinna <notifications@github.com> napsal:

**Comment by protivinsky** [comment]
Dobrý postřeh - @kikinna Kristi změn prosím i ty jednotky. Mimochodem, toto už jsme také splnili, ne? Nebo s tím byl nějaký problém?
- [ ] Otestovat s Martinem, jak se přeloží Multiply blending mode

Krom toho jsem pushnul i draft průvodního textu. A nevím, jaký je plán ohledně datasetu.

**Comment by jankrcal** [comment]
Ad zdroj (a dvojtečky): není zdrojem dat spíše EMBER - The Global Electricity Review 2020?

Ohledně datasetu si zavolám s Ondrášem a dám vědět. Za sebe bych udělal jeden velký Google sheet k EMBER. Moc bych se s tím necrcal, protože to stejně výhledově chceme nějak jinak (git, csv, python, jupyter, ...)

**Comment by protivinsky** [comment]
@jankrcal díky za dataset. Ohledně zdrojů v infografice rozhodně nemáme žádnou jednotnou konvenci:
- někdy používáme pouze název organizace:
  - Evropská agentura pro životní prostředí
  - Mezinárodní měnový fond
  - Společné výzkumné středisko Evropské komise a Světová banka
- někdy namísto toho jen zkratku, případně kombinaci zkratky a překladu či doplnění:
  - ČHMÚ
  - **NASA** Goddard Institute for Space Studies
  - NOAA – Národní úřad pro oceán a atmosféru Ministerstva obchodu Spojených států amerických
- občas doplňujeme i konkrétní zdroj:
  - Zpráva IPCC
  - Světová banka, State and Trends of Carbon Pricing 2019 *(zde byla grafika kompletně převzata)*
  - **ERÚ** Roční zpráva o provozu ES ČR

Osobně si myslím, že na tomto příliš nesejde. Tu frázi "Coal to Clean Energy Policy" má Ember i v logu, tak to beru že to používá skoro jako součást názvu a chtěl jsem, aby to nebylo příliš krátké. Což doplnění názvu studie splňuje také, je mi jedno co z toho zvolíme.

**Comment by kikinna** [comment]
@jankrcal @protivinsky Grafiku mám upravenou, tak až se rozhodnete jak se zdrojem, tak mi dejte vědět, fixnu to a udělám export.

Ad konvence ke zdrojům. Mohli bychom to přidat na seznam věcí, které zrevidovat, protože když jsme ještě neměly žádné grafiky, tak jsme moc netušili, co vše budeme mít za zdroje a jak to řešit. Teď už je to jasnější ;)

**Comment by protivinsky** [comment]
@kikinna podnadpis - navrhuji takto: **Vývoj výroby elektřiny na osobu podle zdrojů** a spotřeby v letech 2000–2019 pro státy EU a Velkou Británii. Hodnoty jsou uváděné v **kWh na osobu za rok.**
(klidně si vytučni něco jiného jestli chceš; chtěl bych se vyhnout dvěma "na" na konci a upřesnit, že jen výroba je podle zdrojů).

@katkolouchova Katko, odkud jsi prosím převzala data o populaci? Došlo mi, že by bylo dobré uvést i tento zdroj.

**Comment by katkolouchova** [comment]
@protivinsky Tome, data o populaci jsem brala z UN odsud https://population.un.org/wpp/Download/Standard/Population/. Konkrétně se jedná o soubor Total Population - Both Sexes.

**Comment by jankrcal** [comment]
Jo, zdroj dat je za mě dobrej, jak je. Nevěděl jsem, že to je jejich podnázev. Časem můžeme vyjasnit konvence, ale za mě je to teď nedůležitý detail.

Ad zdroj populace, přišlo by mi dobrý používat stejný zdroj jako na grafikách svět na osobu. Katko, použila jsi stejný zdroj i tam?

**Comment by katkolouchova** [comment]
@jankrcal Jéňo, použila jsem jiný zdroj, protože WB ještě nemá data za rok 2019. Ale uznávám, že by bylo ideálnější mít všude stejný zdroj.

**Comment by jankrcal** [comment]
To, že se odchylujeme od grafik emisí je za mě ok.
Mě zajímalo, jestli máš stejný zdroj populace zde a v #543. Chápu to správně, že ano?

**Comment by protivinsky** [comment]
@jankrcal svět na osobu je myšleno #543 ? @katkolouchova jak tato grafika, tak #543 potřebují populaci včetně 2019, takže dává smysl je mít obě založené na UN populaci, ne? Nebo mluvíte ještě o něčem jiném?

@kikinna dejme zdroj dat: "Ember a Organizace spojených národů"
Společně s podnadpisem je to za mě vše a můžeme exportovat: **Vývoj výroby elektřiny na osobu podle zdrojů** a spotřeby v letech 2000–2019 pro státy EU a Velkou Británii. Hodnoty jsou uváděné v **kWh na osobu za rok**.

**Comment by protivinsky** [comment]
...jestli by na toto nebyl praktičtější slack :)

**Comment by katkolouchova** [comment]
Ano, obě grafiky vycházejí samozřejmě ze stejných dat o populaci :)
Původně jsem to pochopila tak, že se Jéňa ptá na srovnání s daty o populaci u grafik emisí.

**Comment by protivinsky** [comment]
@katkolouchova Ok, díky za potvrzení. Katko, ještě ze zvědavosti, jak jsi napojovala oba dva datasety?

Mimochodem, u populačních dat máme odlišný zdroj u phase outu #166 , který vychází z Eurostatu. Narazil jsem na to, že v té grafice je výroba elektřiny z uhlí na osobu velmi mírně odlišná oproti Ember + UN. Spíš pro informaci, za mě nemá smysl tyto detaily příliš řešit.

**Comment by jankrcal** [comment]
Tome, tyhle datasety sjednocuju do jednoho, takže odlišnost zmizí.

**Comment by protivinsky** [comment]
A jako populaci tedy použijeme UN? (Eurostat se mi nechce načíst, ale předpokládám, že má data pouze pro EU či Evropu.)

Zajímá mě to kvůli průvodním textům ke grafikám, chtěl jsem tam použít například tu výrobu elektřiny z uhlí na osobu v ČR podle phase-outové grafiky. Nicméně pokud se to tam mírně změní kvůli tomu sjednocení, pak prostě budu všude vycházet z Ember + UN. Což stejně dává smysl, protože to jsou zdroje ke grafikám; a následně budeme konzistentní i s phase-out.

**Comment by jankrcal** [comment]
Ano, jako populaci použijeme UN.

**Comment by jankrcal** [comment]
@protivinsky, GSheet pro všechny grafiky postavené nad EMBER je zde:
https://docs.google.com/spreadsheets/d/1SQSnRSfTQ5HVxVJvwj4igfl22hyblYVjDo_INceKy4I/edit#gid=979818322

Prosím o zběžnou kontrolu, než to dáš do PR, už mi z toho hrabe :)

**Comment by protivinsky** [comment]
@jankrcal díky za dataset! Zběžně jsem to proklikal (a trochu zkontroloval vůči mým datům), vypadá to dobře. Můžeme ho učinit veřejně přístupný? Díky.

**Comment by katkolouchova** [comment]
@protivinsky Tome, je to napojené přes rok a název země. Vzhledem k tomu, že v datech Emberu není kód země, musela jsem relevantní země v datasetu s populací přejmenovat tak, aby odpovídaly názvům v Emberu (konkrétně šlo o USA a Česko). Napojení populace pro ostatní země mimo Čínu, Indii, USA a země EU jsem neřešila. Populaci pro zbytek světa jsem řešila tak, že jsem od světové populace odečetla populaci Číny, Indie, USA a EU. Stačí ti to takto?
@jankrcal Jeňo, budeme do datasetu přidávat i skript, který spojuje data o populaci s Ember? Nebo myslíš, že to teď není potřeba a budeme to řešit, až s případně novým způsobem sdílení skriptů pro zpracování dat?

**Comment by jankrcal** [comment]
@protivinsky Tome, díky, sdílení jsem nastavil.

@katkolouchova Propojení jsem v GSheetu udělal úplně stejně. Skript tam takto (podle mě) není potřeba. Budeme to řešit až s novým způsobem zveřejňování datasetů (což myslím přijde brzo, protože s těma Google sheets je to na takto velké datasety fakt voser ;)). Mimochodem, kdybys taky viděla v tom sheetu nějakou nesrovnalost, dej mi prosím vědět!

**Comment by katkolouchova** [comment]
@jankrcal Koukám na to a opravdu tě obdivuju, žes to takhle dal v google sheetu dohromady! :) Pokud na něco narazím, dám vědět :)

**Comment by kikinna** [comment]
Pardon, zapomněla jsem přidat odkaz na export. Tak [tady](https://www.dropbox.com/sh/exo6qm0uypy81d7/AAD3B1KHJWKYy4RlzTypFt3Va?dl=0)
