### ISSUE TITLE
Grafika: Vyrobená elektřina na osobu podle zdrojů (regiony)

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web#543]
Garant obsahu: @protivinsky @jankrcal
Garant grafiky: @kikinna
Datově zpracovává: @katkolouchova

- [ ] @protivinsky Tome, chtělo by se ti mi i k této grafice doplnit popisky, prosím? (nadpis, podnadpis, slug)
  - Nadpis: Výroba elektřiny na osobu ve světových regionech
  - Podnadpis: Vývoj výroby elektřiny na osobu podle jednotlivých zdrojů v letech 2000–2019 celosvětově a pro hlavní regiony, včetně jejich podílu na globální výrobě elektřiny. Hodnoty jsou uváděné v kWh na osobu za rok.
  - Slug: elektrina-na-osobu-svet
  - Zdroj: Ember a Organizace spojených národů
- [ ] Kdo zpracuje průvodní text?
- [ ] Doplnit osy

_Aktuální stav grafiky_
![04 Energetika na osobu - svet - podil zdroju-01](https://user-images.githubusercontent.com/11555522/82454869-96053000-9ab2-11ea-9b59-604e27f3856d.png)

**Comment by katkolouchova** [comment]
Dataset, který je výstupem zpracování dat v Rku a ze kterého šla data to grafiky najdete [zde](https://docs.google.com/spreadsheets/d/1YTd44h5GQCUxAJMS4PL311QrqE6_CPMhJ_ly-nlDA54/edit?usp=sharing). Obsahuje data pro jednotlivé regiony a svět. Případně můžete využít i formát csv [electricity_population_regions_data.csv](https://drive.google.com/file/d/1qmW2LZdVF_M5-1s6bbUwYA4sP6Lt6JxT/view?usp=sharing).

**Comment by kikinna** [comment]
@jankrcal @protivinsky @katkolouchova Co prosím říkáte na tu grafiku? Je to dobře nahozené? 

@katkolouchova Kači, máme tady kategorii "ostatní obnovitelné zdroje", kterou jsem v elektřině ne na osobu neměla. Čím je to daný? Přijde mi, že bychom to měli mít sjednocené. Myslíš, že bych tě mohla poprosit, jestli by jsi nekoukla do dat, které zpracovával ondráš pro #519 ?
Respektive, @jankrcal a @protivinsky, víte o tom něco?

**Comment by katkolouchova** [comment]
Kristi, ono je to asi tím, že ostatní obnovitelné zdroje mají jenom některé regiony a i v nich jsou velmi nízké (ani v těchto grafikách na osobu nejsou skoro vidět). Předpokládám, že proto je asi Ondráš do grafik ne na osobu nezařadil. Na druhou stranu předpokládám, že součástí té celkové produkce jsou, takže si myslím, že by tam být měly? Nebo je to tak zanedbatelné, že je možné je vynechat? Co myslíte? Určitě souhlasím s tím, že by to mělo být sjednocené, jak píšeš.

Ke grafice. Celkově se mi takto nahozená líbí :) Přemýšlím nad řazením jednotlivých regionů. Možná by se mi líbily USA uprostřed, aby bylo ještě rychleji vidět, jak jsou v porovnání s nimi ostatní regiony v produkci elektřiny na osobu menší.
Taky jsem musela trochu přemýšlet při čtení podílů na celosvětové produkci elektřiny. Že mi na první pohled přišlo zvláštní, že USA mají tak velkou plochu a přitom relativně nižší podíl, než mi došlo proč :D Tak si říkám, jestli tu informaci nezařadit i do podnadpisu. Tak i tak, bych určitě k popisku _podíl regionu na celosvětové výrobě elektřiny_ přidala i rok, pro který to platí.
A ještě mě napadá, že mi v tomto případě ani nechybí další osy. Osobně mi jako referenční body stačí popisky k celkové produkci a šedé boxy.

**Comment by kikinna** [comment]
@katkolouchova Děkuji moc za tak rychlou odpověď. :) 
Nahraji novější verzi (mezitím jsem totiž přidala osy, tak prosím koukni i na ně, jestli ti to přijde fajn. Prostor na ně totiž máme, tak jsem si říkala, že je spíš lepší je tam mít (i když souhlasím, že číst se to dá pěkně i bez toho)) 

Ad "ostatní obnovitelné zdroje" -- Ondráš mi teď říkal, že to jsou typicky geotermály a dohodli jsme se, že jsou tak malé, že je nebudeme zařazovat do grafiky, ale rozhodně je zmíníme do průvodního textu (@protivinsky Tome, budeš psát průvodní text? Pokud ano, prosím, nezapomeneš to zmínit?)

Ad setřízení regionů, to je pěkná úvaha. :) Já jsem vyšla z toho, co je v grafice s celkovými hodnotami a vlastně přišlo mi trošku pěknější dát prvně EU (čistě proto, že my jsme EU a taky nedávat USA tak větší důležitost, hh), ale máš pravdu, že by se dalo líp srovnávat vůči USA. Naštěstí USA má tak velké ty hodnoty na osobu, že se sami trochu staraj o to, aby se dalo ostatní vůči tomu snadno porovnat :D :D -- Nicméně, jak jsem přidala osy, tak by to mělo taky napomoci srovnání, co myslíš?

K podílu na celosvětové produkci jsem přidala rok, to je super komentář. :) Myslím taky, že je super, že to právě u toho USA neodpovídá poměrovně, jinak by to možná zavádělo si myslet, že procenta nějak odpovídají výšce. Tudíž nutíme čtenáře přemýšlet, co to znamená :D Ale nevím, jestli je to dobře. 
Nicméně, právě jsem přemýšlela, jak to pěkně znázornit (vizuálně) a přemýšlela jsem, že bych do grafiky dala dolů nějaký stacked bar, který by ukazoval podíly jednotlivých regionů na celosvětové produkci, ale nějak to nefungovalo. Přemýšlím, jestli by se to vlezlo možná vlevo. Zkusím to. 
Jinak čím myslíš, že bylo pro tebe tak těžké se v tom zorientovat, co to znamená? (Formulace poznámky nebo právě to míchání dvou témat?)

@protivinsky Tome, mohl by jsi prosím zvážit zařazení "podíl regionu na celosvětové výrobě elektřiny" do podnadpisu, jestli by to dávalo smysl?

**Comment by kikinna** [comment]
@katkolouchova Ad Podíl na celosvětové výrobě elektřiny, posílám rychlý a ošklivý prototyp. 
Daly by se tam pak přehodit ty procenta 
Co si o tom myslíte? 

![04 Energetika na osobu - svet - podil zdroju-05](https://user-images.githubusercontent.com/11555522/82737972-cc51e200-9d34-11ea-842a-1a7fb3b42d92.png)

**Comment by ondraspribyla** [comment]
Procenta v pruhu vpravo dobrý :-)

**Comment by katkolouchova** [comment]
@kikinna Kristi, díky za info s těmi ostatními obn. zdroji. Jen pak ještě prosím projdi čísla v grafice k celkové produkci, protože teď tam jsou včetně nich, tak je potřeba některá trochu upravit :)
Myslela jsem, že by USA mohly být místo Indie, ale zase mi dává smysl, aby Čína a Indie byly vedle sebe.
Osy za mě pro srovnávání fungují dobře, máš pravdu, že tam prostor je :)
Problém s orientací jsem měla určitě z míchání dvou pohledů, popisek mi naopak v orientaci pomohl. Taky jsem právě přemýšlela, že by tam mohl někde být nějaký stacked bar, který by ty podíly znázornil přehledněji, ale nenapadlo mě, jak ho tam zakomponovat. Tvůj návrh se mi, Kristi, docela líbí :) Přijde mi fajn mít ho proto, že můžeš porovnat dva pohledy a dá ti to širší kontext. Říkám si ale, že colour coding bude možná trochu oříšek :D Možná by fungovalo seřazení podle velikosti podílu a odstíny šedi?

**Comment by protivinsky** [comment]
Pruh vpravo mi přijde dobrý, @kikinna doplnění textů:

- Nadpis: Výroba elektřiny na osobu ve světových regionech
- Podnadpis: Vývoj výroby elektřiny na osobu podle jednotlivých zdrojů v letech 2000–2019 celosvětově a pro hlavní regiony. Hodnoty jsou uváděné v kWh na osobu za rok.
- Slug: elektrina-na-osobu-svet
- Zdroj: Ember – Coal to Clean Energy Policy

**Comment by protivinsky** [comment]
@kikinna a teď jsem si všiml té poznámky o podílu a doplnil jsem.

**Comment by protivinsky** [comment]
Mimochodem je nějaký plán ohledně dat? Budeme je překlápět a zpracovávat na GD?

**Comment by kikinna** [comment]
@jankrcal @protivinsky V nějaký moment vzešel dotaz, jestli se "Zbytek světa" má opravdu jmenovat zbytek světa nebo jestli máme vymyslet nějaký šikovnější název. Co si o tom myslíte?

**Comment by kikinna** [comment]
Tome, vyhodila jsem jedno slovo z podnadpisu ("jednotlivě"), aby se mi to vlezlo. 

@katkolouchova Díky moc za připomínku k úpravě dat -- to mi vůbec nedošlo ))

Já jsem podle mě teď zapracovala veškeré připomínky. Mrknete na to prosím a když to bude ok, tak můžem exportovat. :) 
(Explicitně se zeptám, co říkáte na ten stacked bar napravo? Hned říkám, že jsem zkoušela různé varianty i s šedými odstíny atd, ale pak to hodně poutalo pozornost nebo bylo moc těžký, atd.)

![elektrina-na-osobu-svet-06](https://user-images.githubusercontent.com/11555522/82756209-05439280-9dd9-11ea-81dc-9c912da068ea.png)

**Comment by mgrabovsky** [comment]
Mně se ten stacked bar docela líbí a neodvádí mou pozornost. Co mě možná trošku ruší (a už hledám fakt prkotiny) jsou ticks na y-ové ose. Zdá se mi, že je jich zbytečně moc a stačily by přírůstky po 5000 (a stávající gridlines by možná mohly i zůstat jako taková vodítka).

**Comment by protivinsky** [comment]
@kikinna podnadpis je super, díky. Drobnosti k textům:
- "Zbytek světa" můžeme nahradit "Ostatní státy"
- přejmenoval bych některé kategorie - zejména proto, že "větrný" působí divně. Použil bych "Vítr", "Slunce" a "Hydro" (abychom se vyhnuli přídavným jménům)

Stacked bar za mě fajn, je rozhodně dobré ho tam mít. Přemýšlel jsem nad tím, že je to jediný orámovaný prvek, nicméně na tom nesejde, už bychom akorát ladili přílišné detaily :)

**Comment by jankrcal** [comment]
@protivinsky @ondraspribyla Vlastně mi ještě vrtá hlavou, proč tady a v #519 dělíme svět tak, jak ho dělíme. Ono to asi vychází z rozdělení EMBERu, ale my bychom to mohli udělat jakkoliv jinak. Dokonce pro každou z těchto grafik to můžeme jinak rozdělit.

Konkrétně narážím na to, proč je Indie tak zajímavá, abychom ji vypichovali? Nebude mít podobnou dynamiku jako zbytek Asie? Nebo jinak: Nestálo by za to mít více kategorií (třeba Afrika, Jižní Amerika, Austrálie)?

Vím, že se ptám v pozdní fázi přípravy grafiky, tak mě klidně utlučte. Jen by mě zajímalo, jestli pro současné dělení máme pádné důvody.

**Comment by protivinsky** [comment]
@jankrcal souhlas, to rozdělení je trochu arbitrární, je prostě shodné s tím jak data prezentuje Ember. Vyčlenit Evropskou unii, USA a Čínu rozhodně dává smysl, neboť to prostě jsou hlavní hráči. Indie už tolik ne, maximálně z toho pohledu, že je to druhý nejlidnatější stát světa a pravděpodobně bude významná v nedaleké budoucnosti. Zároveň si ale nemyslím, že vyčleňování čehokoli dalšího by dávalo větší smysl (Afrika i Jižní Amerika jsou z pohledu výroby elektřiny celkem malé; velký hráč je pravděpodobně "zbytek Asie", ale to je zas taková sběrná kategorie míchající vyspělé státy jihovýchodní Asie, ropné státy blízkého východu a pak ty ostatní; Kanada nebo Austrálie jsou velcí ve spotřebě na osobu, ale mají celosvětově zanedbatelnou populaci... Takže pokud chceme menší množství kategorií, toto rozdělení podle Emberu není špatné a aspoň se dá srovnávat s tou jejich studií, kterou už také máme zpracovanou. Čili souhlasím s tvojí připomínkou, nicméně bych to už ponechal takto.

**Comment by kikinna** [comment]
@mgrabovsky Ty ticks je super point. Děkuju )) Já původně měla max jen 12 500, tak jsem to dělala po 2500 a od té doby, co jsem to roztáhla jsem řešila už jiný věci. Zredukuji, je to šup dup. ))

@protivinsky Díky za legendu, přesně nad tím jsem taky přemýšlela )
Ad orámování, kdyby nebylo, tak musí být barva, která je mnohem komplexnější v tom, aby zapadla do zbytku grafiky ;) 

![04 Energetika na osobu - svet - podil zdroju-02](https://user-images.githubusercontent.com/11555522/82758593-b2250c00-9de7-11ea-842a-6ef3ef8bbe51.png)

**Comment by jankrcal** [comment]
Drobnost: a nemůže být to orámování bílé a trochu tlustší? Tedy jako u samotných boxů: šedé boxy oddělené bílou barvou pozadí.

**Comment by kikinna** [comment]
Ne. :D
(Trochu by se mi chtělo poslat tu zprávu jen takhle, z rozvernosti :D)
Nicméně, vysvětlím )) 
Jednak je to fakt detail a už se mi tím nechce zaobírat (skrz moji časovou kapacitu).
Druhak. Když budou rámečky bílé, šedá musí být tmavší (skrz kvalitu tisku a projekce, aby byla čitelná, protože není sama o sobě dostatečně viditelná a rozlišitelná) a tmavší šedá začne strhávat na sebe pozornost a zase to naruší vyváženost grafiky. 

Aneb, zkoušela jsem jako jednu z mnoha variant a nepřišlo mi to lepší.

**Comment by jankrcal** [comment]
Ano. :D

Rozvernosti bych nebránil, občas stačí jen Tvoje autorita.

**Comment by kikinna** [comment]
@jankrcal Jéni, tady je [export](https://www.dropbox.com/sh/fysjwh8zu2bwomm/AACj2ORNiwLiwAVKuRyU4Jw2a?dl=0)

**Comment by protivinsky** [comment]
@kikinna díky, přidám to do PR a můžeme na review :)
