### ISSUE TITLE
Napsat průvodní texty k tématům

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#549]
* [x] [Energetika](http://localhost:4000/temata/energetika/) DRAFT
* [ ] [Energetika](http://localhost:4000/temata/energetika/) načisto
* [ ] [Ekonomika](http://localhost:4000/temata/ekonomika/)
* [ ] [Svet](http://localhost:4000/temata/svet/)
* [ ] [EU](http://localhost:4000/temata/eu/)
* [ ] [CR](http://localhost:4000/temata/cr/)

související PR: https://github.com/faktaoklimatu/web/pull/559

**Comment by crysman** [comment]
I'm on it... :zap:
