### ISSUE TITLE
Posunout nadpisy o jednu úroveň

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#550]
Stranka by nemala mat viac nadpisov H1 (u nas sa to celkom stava, napriklad na titulke).
Bolo by dobre poprehadzovat CSS styly nadpisov a posunut ich v HTML, aby H1 bol vzdy len ten prvy napis.

**Comment by mgrabovsky** [comment]
Technicky řečeno vícero nadpisů v HTML5 už není problém, pokud jsou správně zanořené uvnitř `<section>`, `<article>`, `<header>` apod. Ale tím, že se rozdělí na různé úrovně se samozřejmě nic nepokazí.

**Comment by mukrop** [comment]
Aha, to som nevedel. Vytklo mi to v poslednej dobe celkom dost nastrojov pre SEO a accessibility a je pravda, ze mat jedinecny H1 nadpis dava logiku. Trochu vsak vaham, ako to riesit, pretoze kazda stranka by mala mat jeden H1. A ked to posunieme, tak budu napr. infografiky zacinat H2.

Tj. my by sme vlastne chceli, aby nadpisy na titulnej stranke mali styl o 1 vyssie ako su (a ostatne veci mozu zostat).

**Comment by mukrop** [comment]
Pravdepodobne riesenie: Na uvidnej stranke pouzit Bootstrap display headings
https://getbootstrap.com/docs/4.0/content/typography/
