### ISSUE TITLE
update AKTUALIT

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#568]
Po velkém sprintu je potřeba přidat do aktualit: 
1. grafiky elektriny - svet, EU na osobu, svet na osobu
2. grafiku Uhelny Phase out
3. Zpravy EMBER a IRENA
4. to, že jsme měli dnes 2.6. tiskovou konferenci spolu s AMO a Danuší Nerudovou

**Comment by setcz** [comment]
5. (?) Nová stránka [Jak používat naše materiály](https://faktaoklimatu.cz/jak-pouzivat)
