### ISSUE TITLE
Průměrná roční teplota v ČR - neodpovídá na hlavní otázku

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web#572]
Nejčastější dotaz, kterým nám chodí lidi na web je "průměrná roční teplota ČR" či "průměrná teplota ČR" či podobné varianty. Zobrazujeme se na to i vysoko ve vyhledávačích. Přijdou na https://faktaoklimatu.cz/infografiky/teplota-cr

A tam se nedozví odpověď:(. 

Návrh: napsat do toho grafu a taky do textu průměrnou teplotu v 1961 a 2020 (nebo za kdy máme poslední data).

Kromě toho, jak je tam krátký popis, tak se to ukazuje ošklivě na googlu:
<img width="686" alt="Screenshot 2020-06-05 at 11 30 36" src="https://user-images.githubusercontent.com/10813593/83861055-672cc200-a720-11ea-8d41-18a3f2faed9e.png">

Fujky! Pomůže asi prodloužit popis.

Na seznamu je to lepší (a dokonce máme dvě z prvních třech pozic):
<img width="930" alt="Screenshot 2020-06-05 at 11 35 03" src="https://user-images.githubusercontent.com/10813593/83861230-9d6a4180-a720-11ea-966d-e579481b221f.png">

**Comment by ondraspribyla** [comment]
Tohle je trochu metodologický průblém: průměrná teplota se musí počítat za určité období - pro meteorology je minimální délka období 30 let... takže bychom mohli udělat průměr za 1961-1990 (vyjde 7.3°C ) a pak průměr za 1991-2020. (vyjde 8.3°C)

Dekádové průměry vyjdou postupně 7.1 - 7.3 - 7.5 - 8.0 - 8.2 - 8.9 °C

Průměrná teplota se počítá jednak průměrováním měsíců, jednak průměrováním geografickým (Liberecký kraj je typicky o pár stupňů chladnější než Jižní Morava) -- Samotný průměr tedy není vhodným reprezentantem ani časové, ani prostorové škály. 
(Proto se také ve světovém měřítku používá teplotní anomálie, a ne průměrná teplota)

Oproti tomu údaj "průměrná teplota vzrostla za 60 let o dva stupně" aniž bychom uváděli průměrnou teplotu je dobře reprezentativní - údaj dobře odpovídá oteplení pro většinu měsíců a pro většinu krajů...

Navíc, kdyby lidé chteli, mohou si průměrnou teplotu vyčíst z grafu. 

Není mi tedy jasné jak by se naše stránka v tomto dala vylepšit (krom toho, že tyto údaje můžeme uvést do textu...)

Co ty na to @setcz <

**Comment by setcz** [comment]
To je fér komentář, chápu, že průměrná teplota se mění mezi roky (a je to i vidět v grafu) - tedy můj původní komentář napsat tam průměr za jeden rok byl nerozumný, to beru zpět:). 

Zvídavá - proč na průměr za rok to musí být 30 let a na průměr za měsíc stačí 10 let? Viz https://faktaoklimatu.cz/infografiky/teplota-cr-mesice (dolů přidávám výstup ze svého hledání nějaké metodologie, kde se tváří, že 10 let by mělo docela stačit)

---

Ještě přemýšlím, co vlastně člověk chce dostat, když hledá ve vyhledávači "průměrná teplota ČR" - a podle mě nejlepší věc, co na to na českém internetu existuje je tohle - https://arcg.is/9efnb0 - jak tam jsou ty šoupací mapky, to je úplně hrozně názorný a moc se mi to líbí. 

Co na to přidat odkaz do textu pod infografiku? 

---

mimochodem, drobnost - @jankrcal: v grafu v [datasetu](https://docs.google.com/spreadsheets/d/1pNBmfQbz6QKAl9nLc5RnoLrJMFrCSxzk_KOY4Ns7xTY/edit#gid=979818322) k téhle grafice je v podnadpise napsané, že se teplota zvýšila o 1.9 stupně, ve finální grafice pak je napsáno 2.0 stupně. To by mi přišlo dobré mít konzistentní

---

Přídavek - jsem si o tom počtu let na průměrování něco hledal a v [WMO Guidelines on the Calculation of
Climate Normals](https://library.wmo.int/doc_num.php?explnum_id=4166) píšou:

>  In The Role of Climatological Normals in a Changing Climate (WMO, 2007), it was found that, for
> most mean and sum parameters (not extreme parameters or higher-order statistical properties
> such as quantiles), 10–12 years of data provided a predictive skill similar to that from a standard
> 30-year period. Furthermore, it was also found that shorter periods than 10–12 years still could
> be used effectively by combining observed data from the short-period data with spatially
> interpolated anomalies from longer-term stations in the region. While such short periods cannot
> be considered to be climatological standard normals or reference normals, they are still useful to
> many users, and in many cases, there will be benefits to calculating such averages operationally.
> Readers are referred to section 7.2 of The Role of Climatological Normals in a Changing Climate
> (WMO, 2007) for further details and potential methods.

Tady je případně ta [The Role of Climatological Normals in a Changing Climate (WMO, 2007)](https://library.wmo.int/doc_num.php?explnum_id=4546) - to jsem ale už jen proletěl.

**Comment by jankrcal** [comment]
ad drobnost: Jo, to je outdated. Prostě bych to z toho grafu smazal, protože takový duplicity prostě z principu zastarají. Z nějakýho důvodu nejsem mezi lidmi, co můžou ten list upravovat. Ondráši, mohl bys to prosím smazat? (nebo mě dát práva k úpravám)

**Comment by ondraspribyla** [comment]
V tabulce s daty jsem větu smazal, tedy nebude nutné opravovat.

**Comment by ondraspribyla** [comment]
@setcz - 30 let je platný standard WMO. Na průměr za měsíc deset let nestačí - a proto je ta naše grafika trochu problematická (Tolasz ji kritizoval už při spuštění)... z druhé strany, trendy pro měsíce jsou statisticky signifikatní snad s vyjímkou řijna... a děláme kompromis mezi "vědeckým" pojetím a názorným zobrazením změny - a pro to názorné zobrazení i ten desetiletý průměr docela stačí. 

v Tabulce opraveno. Odkaz přidán #607. Closing   

closing

**Comment by kikinna** [comment]
Zajímavý point, že neodpovíde na otázku.
Nedala by se jen přejmenovat grafika, např. na Změna průměrné roční teploty
v ČR?
