### ISSUE TITLE
aktualizace aktualit dle newsletteru 2020-06

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#574]
[v aktualitách](https://faktaoklimatu.cz/aktuality) chybí spousta věcí, je třeba to doplnit - mělo by to být poměrně snadné dle [červnového newsletteru](https://tinyletter.com/faktaoklimatu/letters/sedm-nov-ch-infografik-a-dv-studie-newsletter-faktaoklimatu-cz-2020-06).

crysman teď nemá kapacitu

@mukrop PS: povolil jsem veřejné zobrazování archivu - viz link výše, přijde mi to užitečné. Jediný zádrhel je, že to má anglický text - ale to tam má kdeco, na druhou stranu:
![image](https://user-images.githubusercontent.com/5269350/84495405-690bfd80-acab-11ea-832a-086f95887386.png)

**Comment by ondraspribyla** [comment]
closed via #608
