### ISSUE TITLE
jednotky - anglofónne krajiny vs Európa

### ISSUE THREAD

**Issue by LenkaSedlackova** [faktaoklimatu/web#576]
Ahoj, 
asi by nebolo zlé skontrolovať jednotky typu bilión, viď
https://cs.wikipedia.org/wiki/Kr%C3%A1tk%C3%A1_a_dlouh%C3%A1_%C5%A1k%C3%A1la
je bilión v texte písanom v angličtine naozaj bilión v češtine? narazila som pri tom teraz v texte IRENA výcucu a som si takmer istá, že to je aj v iných štúdiách/textoch k infografikách. mohli by sme sa dohodnúť na používaní jednej formy jednotiek (zrejme dlhej) a implementovať to všade. @crysman , zvážila by som pridanie do typografického manuálu

**Comment by mukrop** [comment]
* Pre spravu od IRENA sa to uz riesilo, vid [diskusiu v pull requeste](https://github.com/faktaoklimatu/web/pull/561#pullrequestreview-421508298).
* Do manualu pisania textov to urcite patri.
* Tj. actionable pre tento issue:
  1. Prejst vsetky texty a najst, kde sa taketo pojmy nachadzaju.
  2. Skontrolovat, ze su spravne
  3. (nezavisle na tom) doplnit do manualu k pisaniu textov.

**Comment by crysman** [comment]
https://docs.google.com/document/d/1wVQv4w93Qg_ma6HNFn2Zs3iYQqlo6MKnQiwMHsF2pvA/edit?disco=AAAAJyzz4tY

**Comment by jankrcal** [comment]
Plně souhlasím s přidáním takového pokynu do guidelines (už je hotovo).

Provedl jsem rychlou poloautomatickou kontrolu: 
 - nemáme nikde v textu prefixy "billion", "bilion", "biliard",
 - výskyty prefixu "miliard" jsou v pořádku (odkazuje ke světové populaci, počtu tun v 1 Gt),
 - výskyty prefixu "bilión" jsou taky v pořádku (odkazuje ke světovému HDP, které je cca 100 biliónů USD, a je použito ve zprávě IRENA, kde to je explicitně v pořádku).

Tímto issue zavírám.
