### ISSUE TITLE
Infografika - těžba a zásoby fosilních paliv

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web#578]
Udělat infografiku, ukazující jak se vyvíjí těžba fosilních paliv a jak jsou velké nevytěžené rezervy. A kolik CO2 se uvolní, když se to spálí a kolikrát víc je to, než můžeme spálit, abychom dodrželi různé dohody. 

Rychlá myšlenka motivovaná:

1) tímhle pár let starým článkem - https://www.theguardian.com/environment/2015/mar/10/keep-fossil-fuels-in-the-ground-to-stop-climate-change :

2) nějakou knížkou, kterou jsem četl na podzim - cituji ze svého [zápisku, co jsem psal na podzim]( https://www.facebook.com/notes/martin-k%C5%99iv%C3%A1nek/klimatick%C3%A1-zm%C4%9Bna/10156872665543090/) :

A další věc ze série “vystřelilo mi mozek z hlavy” - těžařské firmy publikují souhrn svých rezerv, tedy již zmapovaných a nalezených, ale zatím nevytěžených zdrojů, které firmy počítají, že v budoucnosti vytěží. Odvíjí se od toho i nacenění firem na akciovém trhu. V roce 2011 Londýnský think tank Carbon Tracker Initiative sečetl všechny tyto rezervy.

Kdyby se všechny nyní známé rezervy vytěžily a spálily, uvolní se 2 795 gigatun uhlíku. Zároveň podle vědeckých modelů množství uhlíku, které můžeme jako lidstvo spálit od roku 2011 do roku 2050 a stále mít 80% šanci, že oteplení nebude větší než o dva stupně Celsia, je 565 gigatun.

Tedy - fosilní firmy plánují vytěžit pětkrát více zdrojů, než si můžeme dovolit, abychom planetu přehřáli jen na středně propečeno. Pětkrát. A to ještě samozřejmě je možné, že se objeví nové, zatím neobjevené a neprozkoumaná naleziště.

V roce 2014 se akcionáři ptali firmy Exxon Mobile, jestli většina z firmou uváděných rezerv nezůstane nevytěžená, pokud vlády dodrží svůj slib na udržení oteplení pod dva stupně - a zavedou agresivní zákony a regulace. Firma odpověděla, že považuje “omezující klimatickou legislativu za velmi nepravděpodobnou a že jsou si velmi jistí, že žádná z jejich rezerv nezůstane nevytěžená.”

**Comment by jankrcal** [comment]
Tohle už je v procesu, jen trochu zaseklé, #337. 

Můžeš Sete prosím deduplikovat? (tedy přidat tam do diskuse, co tady podle svého pohledu píšeš navíc)

**Comment by setcz** [comment]
Díky za upozornění, toho jsem si nevšiml. Minimálně ten první Ondrášův příspěvek a článek v něm hovoří jen o CO2 budgetu, nikoliv o těžbě fosilních paliv. Diskuze potom to posouvá právě k fosilním palivům - a jejich těžbě a zbývajících zásobách, což je to, o co šlo mě. Tak já toto zavřu.
