### ISSUE TITLE
Typo v texte k sekci "Adaptační a mitigační opatření"

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#584]
V texte k sekcii energetika je typo, su tam _hnedouhlene_ alektrarne miesto _hnedouhelnych_.

**Comment by ondraspribyla** [comment]
Níže je text z webu k sekci energetika, Nevidím tam ani zmínku o hnědouhelných... kde je typo? @mukrop 

Sektor elektroenergetiky je celosvětově největším zdrojem emisí skleníkových plynů (v roce 2017 tvořil cca 40 % emisí CO2 a cca 25 % emisí všech skleníkových plynů  měřeno v CO2eq ). Svým dopadem výrazně přesahuje zemědělství stejně jako spalování fosilních paliv v dopravě, spalování fosilních paliv v průmyslu nebo produkci cementu. V rámci elektroenergetiky přes 70 % emisí pochází z uhlí, přes 20 % ze zemního plynu, asi 5 % tvoří deriváty ropy.

**Comment by jankrcal** [comment]
Je to na hlavní stránce jako shrnutí sekce "Adaptační a mitigační opatření". Aktualizuju název issue.

**Comment by ondraspribyla** [comment]
closing via #606
