### ISSUE TITLE
Nefunkční odkazy v doprovodném textu

### ISSUE THREAD

**Issue by mgrabovsky** [faktaoklimatu/web#585]
V sekci [Zajímavosti a komentáře](https://faktaoklimatu.cz/infografiky/emise-eu-poradi#zaj%C3%ADmavosti-a-koment%C3%A1%C5%99e-k-ro%C4%8Dn%C3%ADm-emis%C3%ADm-na-obyvatele) v doprovodném textu k infografice  _Pořadí států EU podle emisí_ vedou čtyři odkazy na smazanou tabulku <https://docs.google.com/spreadsheets/d/1ldy3l-W0HDG1cHK393_rQC5pGXIWbVw94Dh3ie4aEI8/edit>.

**Comment by jankrcal** [comment]
Good catch!

Přijde mi, že je to hodně fragilní, když odkazujeme
 - ke konkrétní tabulce
 - ke konkrétnímu listu
 - ke konkrétní buňce.
Všechno z toho se může snadno změnit.

Navrhuju ty odkazy smazat a nechat místo nich prostý text. Místo toho, někam na konec odstavce zmínit něco jako:
Všechna tato čísla jsou k dohledání v našem datasetu v sekci emisí na obyvatele.

Co myslíš? Pokud souhlasíš, Matěji, jsi schopen se toho prosím zhostit?

**Comment by mgrabovsky** [comment]
Souhlasím, že takhle konkrétní odkazování moc nepřináší a není dlouhodobě uhlídatelné, a zbavit se odkazů mi zní logicky.

V blízké době si čas asi nenajdu, tak to prozatím nechávám free-to-take případným zájemcům.
