### ISSUE TITLE
Chybějící verze infografiky

### ISSUE THREAD

**Issue by mgrabovsky** [faktaoklimatu/web#586]
V infografice [_Výroba elektřiny ve světových regionech_](https://faktaoklimatu.cz/assets/infographics/elektrina-svet_1920.png) chybí v levém dolním rohu označení verze.

**Comment by kikinna** [comment]
Matěji, wow, vůbec nechápu, jak si umíš všimnout takových detailů!

**Comment by crysman** [comment]
přemístěno do https://github.com/faktaoklimatu/web/issues/464 zde zavírám
