### ISSUE TITLE
Převod grafiky Teplotní anomálie na pre-industriál

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#587]
**Update viz níže.**
 
Kontext: Grafika https://faktaoklimatu.cz/infografiky/vyvoj-teplotni-anomalie ukazuje hodnoty TA vzhledem k referenčnímu období 1951-1980. S @jakub-zamouril  jsme zpracovali převod na refernční období 1850-1900, což je pracovní definice pre-industriálu, se kterou pracuje IPCC SR15 a vůči které udává hodnoty oteplení o 1.5°C apod...

Převodní vztah: TA[1850-1900] = TA[1951-1980] + 0.24°C 

Hodnota 0.24°C byla spočítána jako srovnání hodnot řady, kterou používáme (NASA GISS) s hodnotou oteplení, kterou pro tuto řadu udává [IPCC SR15](https://www.ipcc.ch/site/assets/uploads/sites/2/2019/06/SR15_Full_Report_Low_Res.pdf) na straně 58. Podrobná diskuse pracovní definice je na stránkách 57 a 58.

Co je potřeba udělat? 

- [ ] Zkontrolovat upravený dataset, že je srozumitelně napsaný a odpovídá našim standardům. Prosím @jankrcal . Upravený dataset zde: https://docs.google.com/spreadsheets/d/1Fyw0pN4aZECXDHzKF8PItjjqXE72TDrFvC-V4t4iKWY/edit?usp=sharing 

- [x] upravit grafiku (=posunou všechny grafy o 0.24°C nahoru a upravit osu - podle upraveného datasetu. Prosím @kikinna 

- [ ] napsat vysvětlující text k převodu a k referenčním obdobím, který bude na stránkách. Udělá @ondraspribyla ...

**Comment by jankrcal** [comment]
@ondraspribyla Dataset je srozumitelný, díky za úpravy.

Nicméně bych chtěl netriviální úpravy:
 1) Nedává mi smysl, aby grafika TA 22k let zpět a grafika TA 140 let zpět byly postavené na jiné naší tabulce. Nebude ale těžké přidat těch pár údajů navíc do tabulky od Jakuba. **Mám to udělat?**
 2) Tím pádem potřebujeme použít konzistentní převod mezi referenčními obdobími. V této tabulce používáš pro přepočet období 81-10 (a konstantu 0.66, je nějaký důvod proč jsi vzal zrovna hodnotu GISTEMPu?), Jakub používá období 86-05 a hostantu 0.63. Navrhuju přepočet sjednotit na přístupu použitém v Jakubově tabulce. Protesty?

**Comment by ondraspribyla** [comment]
Protože naše teplotní rada je od NASA GISS a označuje se GISTEMP...
Ktere konkrétní referenční období vezmeme je mi jedno... Na grafy to vliv nema, rozdíly jsou v setinách stupně a to okem není poznat. Ale v tabulce je potřeba to mít správně :-) řekněme si to v neděli?

**Comment by ondraspribyla** [comment]
@jankrcal  zpracoval dataset, ve kterém je převod uvedený. viz. https://docs.google.com/spreadsheets/d/1XDa9X1W-bEJhKYMtefvwPuz5N0l2HPyio5dR5KI9qsY/edit?usp=sharing

Poprosil jsem @katkolouchova aby se o úpravu grafiky postarala.

**Comment by katkolouchova** [comment]
@ondraspribyla Přikládám export aktualizované grafiky. Vše jsem posunula o 0,23 stupňů.
[Vyvoj teplotni anomalie_v2.0.pdf](https://github.com/faktaoklimatu/web/files/4962428/Vyvoj.teplotni.anomalie_v2.0.pdf)

**Comment by ondraspribyla** [comment]
Ještě poprosím o jednu úpravu: nechejme v podnadpisu pouze

*Svět je nyní o 1,2°C teplejší než v letech 1850-1900.*

a prosím export. Díky moc!

**Comment by ondraspribyla** [comment]
closed via #602
