### ISSUE TITLE
zakázka - překlad grafik do EN

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#598]
Kontext: pro prezentaci švýcarské centrále korporátu je třeba nachystat tyto grafiky přeložené do EN: 

- Emise v ČR
- Výroba a spotřeba elektřiny v ČR 
- Uhelný phase-out 
- výroba elektřiny na osobu ve státech EU
- srovnání emisí ČR + Německo + Švýcarsko + Dánsko + Skotsko + a Izrael ve fromátu

podkladová tabulka pro grafiku "srovnání emisí ČR + ..." je zde: https://docs.google.com/spreadsheets/d/12eeCaXEYoubz3SaE4JJaMZiLxttdjEvXtPQ-0Sfgwls/edit?usp=sharing

Grafiky v PDF poslat Ondrášovi 
+ potřebujeme trackovat čas: 
Jeňa: 1,5hod dohledávání
Ondráš: 1.5hod koordinace
Katka: **??  prosím zkus pokud možno hned odhadnout kolik hodin ti to zabere :-) Potřebuju napsat cenovou nabídku**

**Comment by ondraspribyla** [comment]
formát grafiky "srovnání emisí " viz https://faktaoklimatu.cz/infografiky/emise-vybrane-staty

**Comment by katkolouchova** [comment]
@ondraspribyla Myslím, že překlady bych mohla mít do 2 hodin a srovnání emisí pro země tak 4 až 5. Ale je to hrubý odhad, uvidím, jak to půjde :)

**Comment by jankrcal** [comment]
Klasická poučka/vtip v softwarových firmách je "odhad času vynásob dvěma a inkrementuj jednotku" :)

14 dní na to potřeba nebude, ale i tak bych byl opatrnější v odhadech a aspoň odhad třeba vynásobil dvěma (nakonec, já jsem nad dohledáváním a přípravou podkladů strávil 2:15).

**Comment by katkolouchova** [comment]
@ondraspribyla Ondráši, chtějí i emise ČR detailně nebo stačí podle sektorů?

**Comment by ondraspribyla** [comment]
...detailně - chtělo by to ukázat na jednotlivé hnědouhlené elektrárny

**Comment by katkolouchova** [comment]
@ondraspribyla Ondráši, za mě mám téměř hotovo. Chystám se odstranit verzi infografiky, která podle mě v tomto kontextu nemá význam a přemýšlím nad tím, zda ponechat odkaz na náš web?

Co se týče korektury, přečte si to po mně Matěj. Mám pak požádat ještě někoho dalšího, nebo to zkoukneš sám, jestli se ti to zdá v pořádku?

**Comment by ondraspribyla** [comment]
Klidně zkoukni sám... Odkaz asi taky není třeba.

Kolik ti to zabralo?

O.

Dne st 5. 8. 2020 19:14 uživatel katkolouchova <notifications@github.com>
napsal:

**Comment by katkolouchova** [comment]
@ondraspribyla Řekla bych, že cca 7 hodin. Překlady šly rychle, ale taky jsem měnila desetinné čárky za tečky atp. :) Nejvíc času mi zabralo znovu vytvořit srovnání emisí. Jinak koukám, že tady nezmiňuješ UK, ale v datasetu je, tak jsem ji tam taky dala.

Všechny infografiky najdeš [tady](https://www.dropbox.com/sh/xlv9oazj84bi677/AACyZs06W68rcyN8UHL2tHj-a?dl=0).

**Comment by ondraspribyla** [comment]
Ahoj Katko, koukal jsem na výstupy, myslím, že je to v podstatě finalní podoba. Posílal jsem je "zákazníkovi" abych si s ním checknul, že odpovídají účelu, pro který je potřebuje. Pokud se ozve s nějakou prosbou na změnu, dám vědět. 
Issue uzavřu jakmile budu mít finální převzetí grafik od zákzníka.

**Comment by ondraspribyla** [comment]
Hotovo, odesláno.
Closing.
