### ISSUE TITLE
Časová osa historie klimatologie

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#599]
Podklady zde: https://docs.google.com/document/d/1BlxyQRhu-QsRzxKvZEbPO5naNDcF_cSxRHZtKzI-PJ0/edit?usp=sharing

Grafika vzniká primárně pro Atlas grafik o klimatické změně, ale nejspíš to dáme i na web
Smyslem je podpořit text o výzkumech a citlivosti klimatu, hlavní sdělení textu je:
1. O klimatické změně způsobené rostoucími koncentracemi CO2 víme už 124 let
2. Už 124let víme, že zdvojnásobení koncentrací CO2 způsoví oteplení o 3°C

**Comment by katkolouchova** [comment]
Ahoj všem, sdílím první návrh vizualizace časové osy klimatologického výzkumu, který navazuje na podklady výše.

Trochu bojuju s množstvím informací a jejich přehledností. Snažila jsem se něco trochu editovat, ale pořád jich je hodně. Taky jsem musela zvolit malou velikost fontu, aby se tam všechno přehledně vešlo, ale přijde mi, že na menší obrazovce už to může být obtížněji čitelné. V jakém formátu Atlas bude?

Obecně by mě zajímalo, jestli je to pro vás v něčem přehlednější než prostý výčet událostí v [dokumentu s podklady](https://docs.google.com/document/d/1BlxyQRhu-QsRzxKvZEbPO5naNDcF_cSxRHZtKzI-PJ0/edit).

Podle mě je z toho dobře vidět, že informace o změně klimatu máme dlouho a že výzkum probíhá, ale čtení jednotlivých událostí a jejich spojení v plynoucí příběh grafika tolik neumožňuje -- k tomu se mi líbí text v podkladech. Pokud to bude primárně sloužit jako doprovodná grafika k textu, asi to nevadí.

@kikinna, @ondraspribyla a kdokoliv další

![Historie klimatologie](https://user-images.githubusercontent.com/49321752/89772131-cda7d500-db01-11ea-9f5b-91b3d348c471.png)

**Comment by ondraspribyla** [comment]
@katkolouchova Díky moc za draft!

**Výsledek testování s Adamem:** funguje to. Je to zajímavý, čte se to dobře, zobrazení neruší a hlavně: vytváří to v jeho hlavě další otázky, které by si rád vyhledal. Tedy **jako rámec to funguje, pojďme dolaďovat.**

- Ocenil bych, kdyby události v letech 2018 a 2020 měly trochu více místa a text nebyl tak smáčklý. Dala by se celá osa trochu posunout a přeškálovat? 
- Vysvětlivku vlevo dole bych dal klidně do rámečku a přeformuloval: “Citlivost klimatu” udává o kolik °C se planeta oteplí po zdvojnásobení koncentrací skleníkových plynů. Nejlepší současné odhady citlivosti klimatu jsou v rozmezí 2,6 °C - 4,1 °C, s očekávanou střední hodnotou 3 °C.
- ... pak bychom mohli přeformulovat i Charneyho zprávu: "...dochází k závěru, že citlivost klimatu je v rozmezí 1.5 - 4.5°C se střední hodnotou 3°C.
- zkoušel jsem ještě další zkrácení textu, ale moc to nešlo, takže bych asi zůstával u formulací, které jsou v grafice. 
- kdyby se tam dalo dát přistání na měsíci, udělalo by mi to radost :-)) ale to je naprosto nice to have...

**Comment by kikinna** [comment]
Grafické věci konzultuji přímo s Káťou, jen tady zareaguju na citlivost
tématu. -- Souhlas, že by měla být v boxíčku, nebo nějak odlišená. Ale
vlastně nechápu, proč tam je. Jako čtenář a laik nevidím návaznost na
historii klimatického výzkumu a nijak si to nespojím se zbytkem grafiky.
Tak, jak je teď napsaná, bych řekla, že tam nepatří. Pokud patří (promiň
Ondráši, že nemám odbornost), protože termín citlivost tématu je důležitý,
pak bych ji přeformulovala, něco ala "Celý výzkum se točí kolem hledání
odpovědi na to, ..., což se popisuje pojmem "citlivost tématu".... " --
jakoby vysvětlit, proč je to relevantní a pak teprve vysvětlit samotný
termín.

Jinak předpokládám, že se to ještě neřešilo, ale bacha na typo věci typu
jednoslabičná předložka na konci řádku.

**Comment by katkolouchova** [comment]
Kristi, jak už jsem ti psala, citlivost klimatu jsem tam dala proto, že se ten termín objevuje v popiskách, tak by někomu nemuselo být hned jasné, co znamená. Líbí se mi tvůj návrh na přeformulování a přinesení důvodů, proč je termín a jeho otázka relevantní -- myslím, že by to mohlo i lépe uvést celou grafiku.

**Comment by ondraspribyla** [comment]
Kristy, píšeš "citlivost tématu" ale kde o "citlivost klimatu". (Už podruhé
- poprvé se to objevilo vysazené v tom štafetovém PDF) je to klávesnicí?

Ano, je to ústřední pojem, má tam být vysvětlen a celý text v atlase je
prakticky o historii zpřesňování tohoto údaje.
Provazuje koncentrace skleníkových plynů a oteplení planety...

Nerozumím, co ti přijde v tom textiku divné, tedy buď to zkus naformulovat
líp, nebo si k tomu pojdme zavolat..

O.

Dne út 11. 8. 2020 9:28 uživatel kikinna <notifications@github.com> napsal:

**Comment by ondraspribyla** [comment]
@kristy ...už mi došlo co by znamenala ta "uvozující věta"... (dlouhé
vedení). podívám se na to s Ondrou Pechníkem.

O.

**Comment by kikinna** [comment]
Ok, super.
Ad "citlivost tématu" - fakt netuším, jak se to stalo a to hnedka dvakrát.
Asi divný myšlenkový pochody :D
Vím, že to je citlivost klimatu :D Pardon :D

**Comment by katkolouchova** [comment]
@ondraspribyla [Zde ](https://www.dropbox.com/s/1sa9rr2v0481vuc/Historie%20v%C3%BDzkumu%20sklen%C3%ADkov%C3%A9ho%20efektu.pdf?dl=0)je aktuální export. Kdybys měl ještě nějaké připomínky, dej mi prosím vědět.

**Comment by katkolouchova** [comment]
@ondraspribyla Nahrála jsem tam verzi s prodlouženou osou :)

**Comment by ondraspribyla** [comment]
Hotovo. Closing. Nové issue na překlopení této grafiky na Web otevřu.
