### ISSUE TITLE
Sepsat system prace

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#60]
Sepsat kratky dokument o systeme prace (kde a co kedy najst/zapisat). Nic extra dlhe, ale aby bolo nieco, na co sa da odkazat, ked sa novy clovek bude chciet pridat.
Format: Markdown file v repe (CONTRIBUTING.md), pridat do ignorovanych suborov, aby sa nekopiroval do webu.

**Comment by mukrop** [comment]
Poznamky do dokumentu systemu prace:
* Data sa rozpracovavaju v gDrive.
* Ak ste mimo tim, vytvarajte na zmeny pull requesty.
* Ak ste v time a mate pravo zapisu do repa, tak male zmeny typu oprava pravopisu a preklepov mozte robit rovno, velke najskor konzultujte v issues (a asi tiez cez pull request?).
* Kazdy issue by mal byt aspon v jednom z projektov.
* Ako je to s branim si issues?
* Commits and commit messages? CZ/EN?

**Comment by kikinna** [comment]
A nahrávat nové infografiky můžu taky napřímo (bez pull requestu)? 
Řekla bych, že issues přes infografiky se můžou směrovat všechny na mě a je budu kdyžtak dál rozesílat? Ať to má někdo na starosti. 
A jazyk pro commit messages fakt nevím, přirozenější by bylo anglicky (vývoj anglicky), ale zase celý web je českej. Ale stejně bych byla pro EN možná?

**Comment by mukrop** [comment]
Ty mozes nahravat priamo :-).
Vyvoj som povodne aj ja robio v anglictine, ale web je cesky, issue tracker je cesky, Ondras pise cesky,  tak som sa nedavno rozhodol, ze to asi cele dame CS+SK (uz tak vacsinou pisem commit spravy).
Rolu "rozdelovaca issues" podla mna netreba, kedze pracujeme, ked nam zostane cas. Kazdy si sam vezme, co urobi alebo to ktokolvek podla vlastneho uvazenia ponukne niekomu inemu.

**Comment by mukrop** [comment]
Bude to mat 3 sekcie: 1) IT veci, 2) graficke veci, 3) veci k spracovaniu dat. S tym suvisi, ze za kazdu sekciu je jeden zodpovedny (Martin/Kika/Ondras?).

**Comment by ondraspribyla** [comment]
? Je to ještě relevantní?
Vlastně mi přijde že systematické věci máme jen velmi málo, kromě pravidel pro merge a review ani nic? Taky máme poměrně málo opakující se práce, takže systém se zatím tvoří špatně. 

Návrh: 

- [ ] Sepišme pravidla k branch/review/merge... (nejsem to schopen ani dobře pojemnovat, takže to nechám na tobě. )
- [ ] Ukliďme GIT a Drive - a z toho možná vzniknou nějaké jasnější guidelines??

**Comment by ondraspribyla** [comment]
Souvisí s #234

**Comment by ondraspribyla** [comment]
Premyslim nad tim, jake guidelines ma smysl sepisovat ted... navic se nam to porad trochu vyviji pod rukama. Prijde mi, ze by mel smysl checklist pro tvorbu a finalizaci grafiky/textu... ale mozna je to usili spojene s externalizaci tacit knowledge zbytecne velke... nakonec stejne jednotlivce zaskolujeme osobne (Katka Kolouchova), tak mi neprijde moc uzitecne psat na to delsi dokumenty...

Co ty na to, @mukrop ? Navrhuju zavrit.

**Comment by mukrop** [comment]
Suhlas, zatvaram.
