### ISSUE TITLE
Spektrum kredibility důvěryhodnost nová grafika navrh

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#600]
Námět na novou infografiku Spektrum kredibility. Velmi užitečná věc hlediska porovnávání informací a důvěryhodnosti - že bysme udělali něco podobného jako Greg. Přijde mi to užitečné jak pro koncové normální lidi tak pro novináře. Rozhodně to přispívá k čistější debatě kolem GCC.

![IMG_20200722_121416_9 u](https://user-images.githubusercontent.com/5269350/88179854-c42afb80-cc2c-11ea-9e5d-51f882a249bb.jpg)

Vím že to to patří spíš do wiki ale z mobilu to tam rozumně nedám až se někdy dostanu mimo pracovní k počítači tak si to tady po sobě uklidím a přemístím zatím můžete názorovat

**Comment by setcz** [comment]
Názoruji: Jakkoliv souzním s obrázkem samotným, nejsem si jistý, že to patří na Fakta o klimatu. Budeme to umět ozdrojovat? Staví to na nějakých datech/faktech/výzkumu? Mně to přijde spíš jako trochu "názorový kus", který pomáhá strukturovat přemýšlení, ale není snadné/možné vyargumentovat, proč je pořadí zrovna takto.

**Comment by crysman** [comment]
@setcz souhlasím, že asi není snadné to ozdrojovat/vyargumentovat - ale na druhou stranu, nedělal jsem v tomto žádnou rešerši, takže je to jen můj civilní názor

hlavní otázka je:
_je toto dostatečně zajímavá infografika v rámci plnění našich cílů a vize?_

Pokud je, technikálie řešme pozdějc, pokud není, tak holt nebude.

**Comment by setcz** [comment]
Za mě ne, protože podle mě by snižovala kredibilitu ostatních infografik/dat/projektu.

**Comment by jankrcal** [comment]
Za mě taky ne (už jen proto, že faktaoklimatu.cz jsou v nejlepším případě v "Big fuzzy middle")

**Comment by ondraspribyla** [comment]
V dlouhodobém pohledu uvažuju o tom vytvořit sérii článků/grafik o
typických argumentačních faulech a kritickém myšlení, zejména nad
klimatickýcmi daty. V podstatě výtah z knížky Cranky Uncle (doporučuju)
Je to spíše varianta vize než plán. V takové sérii by se tahle grafika
možná hodila, protže umožňuje si něco uvedomit o důvěryhodnosti... i když
pouze o vnímané důvěryhodnosti...

Tedy můj pohled je: Teď ne. Možná v 2021 (vidím, kolik máme práce a jak
pomalu postupujeme, tak nechci dávat falešnéí naděje)

O.

**Comment by mukrop** [comment]
Za mna tiez nie, argumentacne suhlasim s chalanmi vyssie.
@crysman, prehodis to na wiki a zavries prosim?

**Comment by crysman** [comment]
ok, dodáno do wiki https://github.com/faktaoklimatu/web/wiki/N%C3%A1pady-na-infografiky-a-studie#credibility-spectrum toto issue zavírám
