### ISSUE TITLE
České emise od 1990

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#601]
Cíl: udělat graf, ze kterého je vidět jak klesaly české emise od roku (že většina poklesu byla 1990-2000) a jaké příspěvky k tomu mají jednotlivé sektory (energetika je pořád stejná, doprava mírně rostl, v devadesátých letech spadl průmysl, mezi 2000-2010 poklesla spotřeba v domácnostech??) - asi to bude chtít i rešerši proč se to stalo. 

Rozpracovaný soubor je zde: https://docs.google.com/spreadsheets/d/1LI2sArKOHn_VYzwkIygBsEB9eTZiYzGknyvEpvNmNr4/edit?usp=sharing

Zároveň máme poptávku po grafice, která je ekvivalentní druhé grafice v prezentaci: 
https://docs.google.com/presentation/d/1T3mM4IYaiY0ET237F6gXJE62WOY3MH1sg-ivWInb75s/edit?usp=sharing
která v podstatě také ukazuje, jak klesaly české emise.

**Comment by jankrcal** [comment]
Ondráši, ještě mi není jasné zadání:
  - mají to být dvě různé grafiky? (jedna dělá rozpad emisí v čase podle kategorií, např. podobně, jak máme grafy elektřiny, druhá pak ukazuje pouze celkové emise v čase a protahuje to do budoucna stejně jako graf v přiložených slidech)
  - nebo si to nějak představuješ v jedné grafice?

Zadruhé mi není jasné, odkud tahat křivky, jak rychle by ČR měla snižovat emise.
 - Rozklikal jsem si ČR v http://paris-equity-check.org/multi-equity-map.html# a jsem z toho trochu zmatenej, jestli je to dost autoritativní zdroj a kterou křivku z těch 5 kritérií, jak distribuovat redukce emisí mezi země, máme brát.
 - Nebo vidíš nějakej jinej snadnej zdroj takové křivky pro ČR (podle Pařížské dohody)?

**Comment by jankrcal** [comment]
Dnes jsem se bavil s Tomem, Katkou a Matějem.

Tom teď další dva týdny (1. - 16.) nemá moc čas, Katka je pak hned další týden na dovolené (17. - 23.), tak by to pak mohlo být hektické (do 8. září). Tak jsem se domluvil s Matějem, že na to koukne a data (k historickým emisím) zpracuje, trochu vykouká, co je tam všechno zajímavého, a zkusí i trochu dohledat souvislosti. S Katkou se pak pobaví o prezentaci dat.

Katko, Matěji, navrhuji si zavolat cca za 14 dní (v tom týdnu před vaší dovolenou), abychom probrali, co máte, a další postup. Jestli potřebujete s něčím pomoct, atd.

Ondráši, připomínám svoje otázky z předchozího komentáře. Prosím o odpověď, tuhle část práce jsem zatím nemohl moc vysvětlit, protože mi to samotnému není jasné.

**Comment by ondraspribyla** [comment]
Díky za posouvání :-) 
Vyjasnení zadání: rozdělil jsem issue na dvě - v tomto nechávám pouze vytvoření grafiky, která zobrazuje emise ČR 1990-2020 podle sektorů - viz rozpracovaný dokument v úvodním komentáři tohoto issue. 
Nové issue #613 bude odpověď na otázku jak moc by měla ČR snížit emise... a to bude chtít pár hodin studia :-)

Zároveň nabídka pro Katku a Matěje: v pondělí cca 17:00 - 20:00 máme s Oldou setkání a malý pracovní sprint v Nazemi. Jestli máte čas, tak se můžete přidat, myslím, že odpovědi na spoustu otázek, které se týkají emisí bude prostě v Oldově hlavě a bude se stačit zeptat.

**Comment by jankrcal** [comment]
Aktualizace pro Katku a Matěje: přímé využití této infografiky na zmiňované akci 8. září je nejisté. I tak je to za mě důležitá grafika, kterou na FoK určitě chceme mít a rád bych ji do 8. září měl. Jen jsem chtěl nastavit přesnější očekávání.

**Comment by mgrabovsky** [comment]
@ondraspribyla Díky za nabídku, nakonec nám to ale ani jednomu nevyjde. Kdybych potřeboval s něčím poradit, dám vědět.

**Comment by ondraspribyla** [comment]
Zápis z rozhovou s Oldou: 

- Emise z výroby elektřiny se víceméně nezměnily od roku 1990, i přesto, že byl spuštěn Temelín
- Emise CRF1A1 ze spalování v průmyslových procesech klesla na začátku devadesátých let hlavně v souvislosti s ukončováním energeticky náročných provozu, zejm. těžkého průmyslu.
- Emise z domácností a komerčního sektoru se snížily v devadesátých letech díky plynofikaci a zvyšující se energetické efektivitě budov
- Emise ze Zemědělství - pokles souvisí s poklesem počtu chovaných zvířat a nižšími dávkami průmyslových hnojiv. 
- Fugitiv emissions klesají - jde důsledek poklesu těžby černého uhlí. 
- Emise z dopravy rostou dlohodobě, je vidět krize roku 2008

Graf bude dobré mít asi dvojítý: jeden na celkové emise, energetiku a spalování v průmyslu a druhý na další "menší" procesy, které v poměru k energetice a spalování v průmyslu zanikají.

**Comment by mgrabovsky** [comment]
@ondraspribyla @SklenarOldrich Stáhl jsem si nejnovější data Eurostatu z roku 2018 a trochu jsem se v nich probíral (+ jsem aktualizoval sdílenou tabulku). Díval jsem se jen na ty obecnější kategorie, jak jsou uvedené v tabulce a jak je máme v jiných infografikách (energetika, doprava atd.).

K vašim pozorováním nemám co dodat; až na jednu pozoruhodnost jsem žádné nové vzorce neobjevil. K tomu mám jednu drobnost k datům a hrst otázek ke kategorizaci.

1. Pozoruhodnost: Emise z LULUCF od roku 2014 setrvale rostly k nule a v roce 2018 se dokonce překlopily do kladných. LULUCF chápu dost primitivně a intuitivně, takže se mi těžko vysvětluje, jak mohou být najednou kladné a ještě k tomu o tolik.

   Při bližším pohledu tvoří dominantní složku podkategorie _„Forest land“_, konkrétně _„Unconverted forest land“_:

   ![Land Use, Land Use Change and Forestry](https://user-images.githubusercontent.com/134321/89552756-de5c0080-d80c-11ea-8343-94912146df64.png)

2. Při aktualizaci tabulky jsem si všiml, že některá čísla se v nových datech drobně liší – většina je stejná, někdy se liší o 5 %, výjimečně o 10 % (hrubým odhadem; systematicky jsem se tím nezabýval). Předpokládám, že jde o nějaké aktualizace výpočtů a přepočtů.

3. Většina kategorií v nynější tabulce kopíruje ty z dřívějších infografik ([donut ČR](https://faktaoklimatu.cz/infografiky/emise-cr-detail) a [kytičky EU](https://faktaoklimatu.cz/infografiky/emise-vybrane-staty)), ale některé nezapadají na 100%. Chtěl bych si tedy vyjasnit, co kam zařadit:

   1. Odpovídá kategorie „domácnosti a instituce“ z dřívějších infografik součtu sektorů CRF1A4A a CRF1A4B (_Fuel combustion in commercial and institutional sector [+] households_)? (V CRF1A4A je i komerční sektor.)
   2. Odpovídá „spalování v průmyslu“ sektoru CRF1A2 (_Fuel combustion in manufacturing industries and construction_)? (Je tam průmysl i stavebnictví.)
   3. Co s kategoriemi úniků (CRF1B) a LULUCF (CRF4)?
   4. Navíc jsou tu dva vcelku nezanedbatelné sektory, které nejsou započítány nikde jinde, pokud se dobře dívám: CRF1A4C (_Fuel combustion in agriculture, forestry and fishing_) a CRF1D3 (_Biomass_). Co s nimi? (Intuitivně bych první zařadil asi do zemědělství a druhý do energetiky, ale chci mít jistotu.)

**Comment by SklenarOldrich** [comment]
Ahoj Matěji a díky za info! Rychlá zpětná vazba k bodu č. 1 - podle mě to
souvisí s kůrovcovou kalamitou. Srovnej prosím data pro LULUCF s grafem na
straně 6 v tomto pdf dokumentu:
https://www.csas.cz/content/dam/cz/csas/www_csas_cz/dokumenty/analyzy/Lesnictv%C3%AD%20v%20%C4%8CR_2019_01_public.pdf

čt 6. 8. 2020 v 18:20 odesílatel Matěj G. <notifications@github.com> napsal:

**Comment by katkolouchova** [comment]
Ahoj všem, přikládám rozpracovanou infografiku:

![vyvoj-emisi-cr-05](https://user-images.githubusercontent.com/49321752/90987255-d2509c80-e589-11ea-8f8a-8170ed0da8de.png)

S Matějem jsme nad tím přemýšleli tak, že chceme zobrazit jak přehled vývoje objemu emisí od roku 1990 v kontextu celku, tak jejich detailní průběh v jednotlivých sektorech. Pro první část jsme použili area chart, ve kterém je dobře vidět, že celkový objem emisí klesl a jak velké jsou jednotlivé sektory v kontextu celku. Detailní průběh pak ukazují grafy s jednotlivými sektory (tzv. small multiples). Aby mezi sebou byly jednotlivé sektory rychle porovnatelné, zobrazujeme data jako relativní změnu oproti roku 1990 (vidíme, jaké sektory oproti r. 1990 výrazně klesly/vyrostly a jaké se moc nezměnily –⁠ což potvrzuje Ondrášovi poznatky výše). Kdybychom zvolili absolutní hodnoty a chtěli pro porovnatelnost nechat stejné osy y, nebyl by dobře vidět průběh u malých sektorů.

Kromě obecného dojmu, bych ráda znala váš názor na:
- Anotace –⁠ přidali byste k jednolitlivým sektorům další vysvětlivky (např. ty, co psal Ondráš)? Otázka je, jestli už by to pak nebylo příliš zahlcené.
- Legenda – přijde vám intuitivní využít jako legendu grafy jednotlivých sektorů? 
- Barvy –⁠ aktuálně odpovídají barvám sektorů v koláčových grafech, abychom drželi stejné kódování napříč grafikami, ale možná zde působí příliš výrazně?

Taky prosím o kontrolu a případnou reformulaci nadpisu, podnadpisu a slugu.

Díky!

**Comment by jankrcal** [comment]
Super, díky za skvělou práci!

Obecný dojem: 
 - Nepůsobí to na mě vizuálně vyváženě: Ten levý graf působí dost slisovaně. Vpravo dole zůstává jeden slot na malý graf volný. 
   - Nedaly by se zmáčknout do dvou sloupců po 4? Třeba je roztáhnout až nahorů přes podtitul grafiky a smazat malé nadpisy, ono je to vcelku zřejmé, že to je podle sektorů? 
   - Nebo to dát na šířku všech 8 grafíků do jedné řady dole? 
   - Nebo to dát do jedné řady nahoře a trochu to zjednodušit, aby to vypadalo jako legenda rozšířená o maličkou trendline?
 - Nejsem si jistý relativní škálou u line grafů, protože pak člověk nedokáže porovnat důležitost jednotlivých změn. Nedalo by se to uvést jako delta absolutní škály? (nevidím od oka, jaký je tam rozsah).

Moje připomínky:
 - Podnadpis bych osobně spíš zaměřil na ten těžký průmysl v 90s a na to, že celkové emise od roku 2000 spíše stagnují. Takto to na mě působí, že máme pifku na energetiku.
 - Bez legendy - ani jsem si toho nevšiml. Ale po Tvé otázce mi to intuitivní nepřijde, nějak mi v tom area chart intuitivně něco chybí (legenda).
 - Anotace bych spíš nechal do doprovodného textu.
 - Barvy - konzistence super, v line chartech mi to přijde ideal, ten area chart mi přijde vskutku moc výrazný. Nějak bych to utlumil, ale, jak konkrétně, na to nemám názor.
 - Pokud zůstaneme u procentuální škály, osy y u line chartů bych přeznačil na 0% - 150%, přijde mi, že je intuitivnější začínat na 100% než začínat na 0%.

**Comment by jankrcal** [comment]
Promiň, toto jsem nějak zasklil.

> @ondraspribyla @SklenarOldrich Stáhl jsem si nejnovější data Eurostatu z roku 2018 a trochu jsem se v nich probíral (+ jsem aktualizoval sdílenou tabulku). Díval jsem se jen na ty obecnější kategorie, jak jsou uvedené v tabulce a jak je máme v jiných infografikách (energetika, doprava atd.).
> 
> K vašim pozorováním nemám co dodat; až na jednu pozoruhodnost jsem žádné nové vzorce neobjevil. K tomu mám jednu drobnost k datům a hrst otázek ke kategorizaci.
> 
> 1. Pozoruhodnost: Emise z LULUCF od roku 2014 setrvale rostly k nule a v roce 2018 se dokonce překlopily do kladných. LULUCF chápu dost primitivně a intuitivně, takže se mi těžko vysvětluje, jak mohou být najednou kladné a ještě k tomu o tolik.
>    Při bližším pohledu tvoří dominantní složku podkategorie _„Forest land“_, konkrétně _„Unconverted forest land“_:
>    ![Land Use, Land Use Change and Forestry](https://user-images.githubusercontent.com/134321/89556892-4fea7d80-d812-11ea-8a23-ed56f4d60e19.png)

Tady je na zvážení, jestli LULUCF vůbec zobrazovat. Všechny naše další grafiky LULUCF nezobrazují a chtělo by to být konzistentní. Sloučení se zemědělstvím je pro ČR docela elegantní řešení, ale nejsem si jistý, že u vybraných zemí EU to všude vyjde pozitivně. Ta LULUCF je pro ČR docela náhodná složka (kůrovcové kalamity), která moc nevypovídá o emisních trendech, tak si dokážu představit to úplně zazdít.

> 2. Při aktualizaci tabulky jsem si všiml, že některá čísla se v nových datech drobně liší – většina je stejná, někdy se liší o 5 %, výjimečně o 10 % (hrubým odhadem; systematicky jsem se tím nezabýval). Předpokládám, že jde o nějaké aktualizace výpočtů a přepočtů.
> 3. Většina kategorií v nynější tabulce kopíruje ty z dřívějších infografik ([donut ČR](https://faktaoklimatu.cz/infografiky/emise-cr-detail) a [kytičky EU](https://faktaoklimatu.cz/infografiky/emise-vybrane-staty)), ale některé nezapadají na 100%. Chtěl bych si tedy vyjasnit, co kam zařadit:
>    
>    1. Odpovídá kategorie „domácnosti a instituce“ z dřívějších infografik součtu sektorů CRF1A4A a CRF1A4B (_Fuel combustion in commercial and institutional sector [+] households_)? (V CRF1A4A je i komerční sektor.)

Ne, v ostatních grafikách je to sektor CRF1A4 tedy tam spadá i CRF1A4C. To je za mě taková hraniční nepřesnost. Krása zemědělství je v tom, že to jsou všechno jiný procesy, než spalování fosilních paliv. Možná přeznačit na "Další spalování (domácnosti, instituce, zemědělství)"?

>    2. Odpovídá „spalování v průmyslu“ sektoru CRF1A2 (_Fuel combustion in manufacturing industries and construction_)? (Je tam průmysl i stavebnictví.)

Ano. Ty štítky holt musí být co nejúdernější, vysvětlují se v doprovodném textu.

>    3. Co s kategoriemi úniků (CRF1B) a LULUCF (CRF4)?

Úniky jsou zajímavé, tedy konkrétně, že jich bylo na začátku 90s tolik. V koláčové grafice to máme označeno jako "Jiné" (spolu s pár dalšími zbytky). Asi bych zůstal u stejné terminologie a okomentoval to v doprovodném textu.

>    4. Navíc jsou tu dva vcelku nezanedbatelné sektory, které nejsou započítány nikde jinde, pokud se dobře dívám: CRF1A4C (_Fuel combustion in agriculture, forestry and fishing_) a CRF1D3 (_Biomass_). Co s nimi? (Intuitivně bych první zařadil asi do zemědělství a druhý do energetiky, ale chci mít jistotu.)

Biomass je memo item (typicky se nezapočítává do grand total), tak bych to nezobrazoval. Nejsem si jistý, jak se to počítá (v kombinaci s LULUCF), když spalování biomasy je v principu součástí carbon-neutral cyklu.

Jinak kódy pro jednotlivé kategorie najdeš zde (B.4, kódy EUROSTAT)
https://docs.google.com/spreadsheets/d/1y52VXoiW7OmzT1sm1UQeT0XhZTuKge1962A4pjFmqzg/edit#gid=0

**Comment by katkolouchova** [comment]
@jankrcal Jeňo, díky moc za zpětnou vazbu. S rozložením si zkusím pohrát, díky za nápady.

Co se týče relativní škály, přijde mi, že tam právě hezky vynikne průběh, který je pak porovnatelný mezi sektory. Chápu potřebu vědět, o jak velké změny se jedná, ale k tomu podle mě dobře pro referenci slouží právě ten area chart. V něm vidíš, v jakých absolutních hodnotách se jednotlivé sektory pohybují. Bojím se, že kdybychom dali absolutní hodnoty i do line chartů, mohlo by být těžší porovnání sektorů mezi sebou, protože by každý graf měl jinou osu (musel by mít, pokud chceme, aby byl vidět průběh i u malých sektorů).

**Comment by ondraspribyla** [comment]
Pojďme jít nyní cestou graf absolutních + relativní poklesy/nárůsty. Něco
to ukazuje dobře, něco ne - možná není možné do jednoho grafu dostat
všechno.

Určitě nesmime míchat LULCF a zemědělství. Obecně: nezobrazujeme pohlcování
ale jen emise (stejně jako v ostatních grafech)

Graficky by to chtělo vyladit ale yslim že jsme na dobré cestě :-)

Dne po 24. 8. 2020 17:08 uživatel katkolouchova <notifications@github.com>
napsal:

**Comment by mgrabovsky** [comment]
@jankrcal @ondraspribyla Super, díky za vyjasnění dat. LULUCF tedy vypustím, „domácnosti a instituce“ přepočítám a popisek změníme na „Spalování v domácnostech, institucích, zemědělství“ (jak navrhuješ [Jeńa] v #631), zbytek dáme pod „Jiné“.

**Comment by katkolouchova** [comment]
Po konzultaci s Kristi přikládám aktuální verzi :) Dejte vědět, co na ni říkáte, díky!
![vyvoj-emisi-cr-12](https://user-images.githubusercontent.com/49321752/91199696-84a97080-e6fe-11ea-8d17-330a3a290451.png)

**Comment by jankrcal** [comment]
Wow, to je dost dobrý! Obzvlášť se mi líbí výsledné číslo v čárových grafech a vynechání -100%, takhle to řeší mé všechny předchozí výhrady.

Jediné, co mě k tomu napadá, je že ten area chart mi pořád přijde na šířku trochu slisovaný. Nedalo by se to vysvětlení s 51 Mt v roce 2018 přesunout jinam a graf ještě trochu roztáhnout?

Trochu jiné téma, přijde mi to náročné na doprovodný text, konkrétně na interpretaci, proč která oblast kdy stoupala a klesala, @mgrabovsky jsi schopný něco v tomto směru nastřelit, nebo bys byl rád, kdyby se toho zhostil někdo jiný?

**Comment by mgrabovsky** [comment]
@jankrcal Nejméně do 20. září teď nebudu mít mnoho času, takže bych to raději přenechal jiným zájemcům.

**Comment by kikinna** [comment]
Mně osobně to "slisování nevadí", hlavně proto, že posun/úprava poznámky
vedle grafů způsobí imho jen minimální zmenšení vzhledem k tomu, že mezi
dvěmi částmi infografiky chce nechat tak či tak nějaký negativní prostor

**Comment by kikinna** [comment]
Když už, tak bych přemýšlela nad snížením grafu o kousek. Ale nevím, jestli
je to moc nutný

**Comment by katkolouchova** [comment]
Mně osobně taky moc slisovaný nepřijde a celkové rozložení objektů mi přijde i po několika dnech fajn :)
@jankrcal Jak to vypadá s použitím grafiky na kulatém stolu 8. září? Abych věděla, jestli se budou případně v příštích dnech řešit nějaké úpravy.

**Comment by SklenarOldrich** [comment]
@katkolouchova, @jankrcal Dovolím si reagovat za Jeňu - grafika vypadá opravdu dobře, nicméně na kulatém stolu bych primárně použil stávající [koláč](https://faktaoklimatu.cz/infografiky/emise-cr-detail), jakožto výchozí bod pro další snižování, abychom zbytečně nezabředli do diskuze o tom co bylo v minulosti...

**Comment by jankrcal** [comment]
Rozhodně vytiskneme a vezmeme s sebou :)

Jinak na dotažení doprovodného textu teď do úterka nebudu mít kapacitu, budu se snažit se na to vrhnout, až bude kulatý stůl z krku.

**Comment by ondraspribyla** [comment]
Kromě vytištěných materiálů tohle můžete použít v prezentaci pro ukázání
českého kontextu. (a taky ukázání, že jako FoK docela víme o čem mluvíme a
máme data ke kdečemu :-)

**Comment by katkolouchova** [comment]
Export grafiky [zde](https://www.dropbox.com/s/necb05p2kx8iosi/2020-09-07%20vyvoj-emisi-cr.pdf?dl=0).
