### ISSUE TITLE
Trend růstu teploty vybraných míst

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web#62]
Potřeba vytvořit podkladová data pro infografiku znázorňující vybraná místa na světě a vývoj jejich průměrných ročních teplot + dodat zdůvodnění, proč jsou jednotlivé místa vybrány.

**Comment by ondraspribyla** [comment]
Jde o trendy růstu. Nejlépe z https://data.giss.nasa.gov/gistemp/

**Comment by ondraspribyla** [comment]
https://climexp.knmi.nl/selectstation.cgi?id=someone@somewhere

https://data.giss.nasa.gov/gistemp/station_data_v4_globe/

**Comment by ondraspribyla** [comment]
presunuto do wiki
