### ISSUE TITLE
Grafika: Schématická mapa klimatické změny

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web#627]
Grafika do brožury. 
Má jít i na web? -- Jak jinak. Akorát @mukrop, aktuálně grafika zasahuje do prostoru ořezu. Tak přemýšlím, co s tím. Jestli nevadí, tak do brožury bych to nechala takhle, ale popravdě ani nevím, jak to potom upravit :D 
![image](https://user-images.githubusercontent.com/11555522/90138242-013f6500-dd77-11ea-9ea9-58e5389f2579.png)

![schema-klimaticke-zmeny-05](https://user-images.githubusercontent.com/11555522/90138077-bcb3c980-dd76-11ea-9205-d8f9b0b03b74.png)

**Comment by mukrop** [comment]
Chceme aj na web. Chapem, vidim tri cesty, usporaduvam podla toho, ako dobra moznost mi to pride:
1. Poposuvat bramboryaj siplky tak, aby sa uzavrela diera medzi zaplavami a migracemi, modry nadpis by sa teda dostal imo orez.
2. Presunut modry nadpis doprostred, do diery medzi migracemi a zaplavami (ma vyrazne iny styl, mozno by mohol fungovat aj tam).
3. Dat do atlasu inu verziu ako na web (toto mi pride velmi problematicke na dlhodobu udrzatelnost a chcel by som sa tomu vyhnut).

**Comment by ondraspribyla** [comment]
Grafiku na web určitě chceme :-)
...atlas je trochu jiný formát a už nyní budeme dávat mírně jiné verze bodů
zlomu. Tedy zásadním způsobem mi třetí varianta nevadí.

**Comment by kikinna** [comment]
Pokud byste se nezlobili, fakt bych teď hlasovala za variantu 3 a do
budoucna to dodělala.
Tu grafiku už jsem doladila a byť se to nezdá, tak to není vůbec snadný
vyvážit a pak musím předělat všechny čáry a šipečky jednu po jedné otáčet.
Upřímně na to teď nemám kapacitu. (pardon)

**Comment by mukrop** [comment]
OK, za mna v pohode. Na web teda dame inu verziu. Beriem za uzatvorene.
