### ISSUE TITLE
Předělat sekce úvodní stránky

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#628]
Zaciname mat mnoho obsahu, Mierne prerobena titulna strana vyzera, ze by mohla chciet nasledovne:
* Zjednotit rozmer blokov pre studie, aby boli rovnake ako infografiky.
* Zobrazovat data, studie a datasety v sekciach spolu.
* V kazdej sekcii asi zobrazovat najviac 2 riadky veci s odkazom na prehlad celej sekcie.
* Na vrchu stranky mozno sekciu "Nove" (1 riadok), kde budu posledne prirastky (pre vracajucich sa navstevnikov).

**Comment by jankrcal** [comment]
Souhlas se vsim. 

Nadhazuju alternativu k poslednimu bodu:
  - u novych prirustku zarucit, ze se zobrazi ve sve kategorii (tedy maji prednost) a pridat jim nejaky badge "nove".
Vyhoda tohoto je, ze to nerozbije deleni do kategorii. (Drobna) nevyhoda je, ze clovek musi proskrolovat stranku, aby nasel vse nove.
