### ISSUE TITLE
Trend oteplování - mapka světa

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web#63]
Dodat podkladová data + texty pro rozdíl mezi průměrnou roční teplotou na pevnině a v oceánech.

Garant grafiky: @kikinna 
Garant obsahu: @ondraspribyla 

**Úkoly:** 
- [x] Převést mapku z rastru do vektoru
- [ ] Vymyslet nadpis a podnadpis
- [ ] Dotáhnout grafické detaily (především okraj mapy)
- [ ] Chceme vytáhnout nějaké info / popisky k mapičce? Například nějaká zajímavá místa s výrazným oteplením?
- [ ] Doplnit popis legendy
- [ ] Je zdroj dobře? (Goddart institute?) 
- [ ] Můžeš být garantem obsahu? @ondraspribyla 
- [ ] Vytvořit průvodní text
- [ ] Vyresit korektne citace
**Otestovat:**
- [ ] Jak čtenář vnímá legendu?

_Aktuálně rozpracovaná grafika_
![Mapa nárustu teploty v letech 1961-2018 v1 0-03-03-03-03-03-03-03-03-03](https://user-images.githubusercontent.com/11555522/75326507-08cb8a00-587b-11ea-8e8c-3419bcf46b76.png)

**Comment by ondraspribyla** [comment]
https://data.giss.nasa.gov/gistemp/maps/index_v4.html
Parametry: TREND + ANNUAL + 1961-2018 +1200km
Tuhle mapu bychom měli zobrazit

**Comment by ondraspribyla** [comment]
Souvisí s #62

**Comment by kikinna** [comment]
Tak jsem zvektorizovala mapku. (Trošku náročnější než jsem čekala, ale pro příště už budu vědět, haha)

![world temp map-01](https://user-images.githubusercontent.com/11555522/70193248-d50b1900-16fe-11ea-99bf-15bf529702a0.png)

**Comment by kikinna** [comment]
@ondraspribyla Prosím, koukneš na to, co je třeba doplnit (koukni do vrchního komentáře)? :)

**Comment by ondraspribyla** [comment]
![Temp-Trend-polar orthographic coord](https://user-images.githubusercontent.com/17317136/73927801-56835100-48d2-11ea-849a-df7143c1a7eb.png)

**Comment by ondraspribyla** [comment]
When referencing the GISTEMP data, please cite both this website as well our most recent scholarly publication about the analysis. In citing the webcite, be sure to include the date of access.

GISTEMP Team, 2019: GISS Surface Temperature Analysis (GISTEMP). NASA Goddard Institute for Space Studies. Dataset accessed 20YY-MM-DD at data.giss.nasa.gov/gistemp/.
Lenssen, N., G. Schmidt, J. Hansen, M. Menne,A. Persin,R. Ruedy, and D. Zyss, 2019: Improvements in the GISTEMP uncertainty model. J. Geophys. Res. Atmos., 124, no. 12, 6307-6326, doi:10.1029/2018JD029522.

**Comment by kikinna** [comment]
@ondraspribyla Stačí to referencovat v textu nebo by to mělo být i v grafice?

**Comment by ondraspribyla** [comment]
@kikinna tak jsem strávil další dvě hodiny dohledáváním trendů jednotlivých stanic a výsledek je na nic. 
Aspon se to rýmuje.
Tedy pojdme vydat grafiku bez popisu, a zrusme spicberky... jedine co je tedy potreba dodelat jsou okraje mapky, tak aby z ni nevytekaly kontinenty...

**Comment by kikinna** [comment]
@ondraspribyla Haha, oceňuji rým )) 
Pak budu ráda, když mi povíš, jaktože výsledek byl na nic.
Dotáhnu.

**Comment by ondraspribyla** [comment]
Špicberky / Jiřího Země:
Weddellovo moře:
San Francisco:
St Petěrburg:
Sydney:
Buenos Aires:

**Comment by Keramadohal** [comment]
Btw, už je tam i rok 2019:
![NASA_GISStemp_v4_global map_1961-2019](https://user-images.githubusercontent.com/41745152/74554149-26365500-4f59-11ea-8c8e-28368761a31b.png)

**Comment by kikinna** [comment]
@ondraspribyla @Keramadohal  Ještě tě poprosím, dodáte mi podnapis, jak jsme se bavili a popisek k tomu Weddellovi moři (a zemi Františka Josefa)? Vím, že jsi mi napsal do závorky "absolutní maximum", ovšem to není moc lidskou řečí do grafiky. Chtělo by to něco víc jak jsme se bavili "jediná oblast, která se od roku 1961 ochladila" a "nejvyšší změna teploty na zemi" třeba. Co myslíš?

**Comment by kikinna** [comment]
@ondraspribyla Prosím koukni do prvního komentáře issue, je tam aktualizovaná verze grafiky. 
Jen se ujišťuji, že hodnoty za jednotlivá místa, která jsi mi výše vypsal, jsou opravdu změny do roku 2019 ne 2018, viď?
A prosím koukni na legendu šipeček, jestli ji chceš přepsat.

**Comment by kikinna** [comment]
@ondraspribyla Tom Pšorn má dobrou připomínku, že mu tam chybí Praha nebo něco místního.
Asi jsem hodně za, je důležitý pro nás mít referenční bod, který si dokážeme představit. Jsi s tím ok a pokud jo, mohl bys mi prosím dohledat její hodnotu?

**Comment by ondraspribyla** [comment]
1. Trendy jsou pro 1961 - 2019
https://docs.google.com/spreadsheets/d/1sPyUN8g6_9QNOeClsFgIpq98zwSs6kRydjxpLOIFfCQ/edit?usp=sharing
2. Česká republika vychází 2.2°C  (a nechci ji zobrazit právě proto, že bych musel vysvětelovat detaily metodiky NASA a rozdíl od ČHMÚ) - prosím, nechme tuto verzi bez ČR a já to zkusím během jara vyjasnit s Michalem Žákem... ok? 
3. stál bych ale o zobrazení té Země Fr Josefa - protože extrém 4.9°C je o stupeň více, než špicberky
Pošleš prosím PDF?

**Comment by kikinna** [comment]
Ad 2, okej. Budu ráda, když se to dořeší (vlastně to podpořil i Milan Vítek), ale proteď to můžeme nechat takhle.
Ad 3. Nahradím tedy špicberky za zemi fr josefa a pošlu ti pdf, ju? Očekávej třeba během zítra odpoledne. Do to doby se k tomu bohužel nedostanu.
Jak je na tom doplňující text?

**Comment by kikinna** [comment]
Ještě se chci zeptat, jestli chceš upravit nějak popisek legendy nebo je to ok.

**Comment by kikinna** [comment]
@ondraspribyla V horním postu je aktualizovaná grafika. Barvy v tisku mám otestované, takže jsme ok. Jinak dostala jsem feedback, že popisek "nedostatečná data" otevírá spíše otázek, proč nedostatečná. Vím, že jsi říkal, že ty data tam nějak jsou, tak jsem přemýšlela, jestli by dávalo smysl to nahradit třeba slovíčkem "neúplná data". To je asi deseti vteřinová změna. 
Pokud by to zamyšlení z tvé strany mělo být netriviální, tak řešit nemusíme. 
Dej vědět a hned na to posílám PDF.

**Comment by kikinna** [comment]
@ondraspribyla Finální PDF tu https://www.dropbox.com/sh/1j7ox2drnut9sou/AAD-5Lw_M9HRo2eeECHJtc9Da?dl=0

**Comment by kikinna** [comment]
@ondraspribyla Máme špatnej slug -- ten už máme u "Vývoje světové teplotní anomálie".
Může být třeba "mapa-zmeny-teploty"? Nebo?

**Comment by ondraspribyla** [comment]
Jo mapa-zmeny-teploty je ok

Dne čt 27. 2. 2020 9:32 uživatel kikinna <notifications@github.com> napsal:

**Comment by kikinna** [comment]
Opraveno, soubor ve složce přepsán.

**Comment by ondraspribyla** [comment]
Hotovo via #393
