### ISSUE TITLE
Aktualizovat grafiky emise ČR pro data z roku 2018

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web#631]
Aktualizovaná grafika s detailním koláčem je potřeba co nejdřív ze dvou důvodů:
 - bude se dávat do brožury (deadline zítra, ale v praxi půjde podstrčit i později)
 - použije se v prezentaci na kulatém stole (8. září).

Když už se bude aktualizovat jedna, tak by bylo fajn aktualizovat i tu druhou (hrubější koláč).

Zpracoval jsem dataset:
https://docs.google.com/spreadsheets/d/17HOhx8aSDhWUY_dAE2f21GcBT510t5dd9LsXuFEMs_M/edit#gid=0

Zbývá:
- [ ] (??) Aktualizovat grafiky
- [ ] (Jeňa) Udělat PR, aktualizovat texty, kde bude třeba.

**Comment by jankrcal** [comment]
Kristi, myslíš, že by sis na to našla čas?

(Přidávám Ondráše a Oldu, FYI)

**Comment by kikinna** [comment]
@jankrcal Ahoj Jéni, ano ano, grafy předělám )) 
Začala jsem, ale jsem trošku zmatená -> když kreslím ten detailní koláč, tak mi nelícuje graf oblastí s grafem podoblastí procentama (viz obrázek) -- prvně jsem myslela, že to je jen tím, jak se grafy vykreslují, ale hned oblast "jiné" má v tom detailním grafu cca o procento míň (2,4 %) než v tom rozkladu na základní oblasti (3,3 %) a součty jsou taky rozdílné (99,1 % v detailním a 100 % v souhrném). 

Než budu pokračovat, mohl by jsi na to prosím mrknout a případně dorovnat nebo mi dát info, jak to má být? Děkuji )) 
![image](https://user-images.githubusercontent.com/11555522/91006879-e375c980-e5da-11ea-9fe1-1b5f9e1ec8a0.png)

**Comment by jankrcal** [comment]
Promiň, v detailním rozdělení byla chyba ve výpočtu položky "Ostatní", opraveno.
Ta chyba byla i v předchozí verzi dat, nějak to tam nevadilo :)

**Comment by kikinna** [comment]
Hm, hm, zajímavé :D Jakože něco mi tam nelícovalo, ale myslím, že to byly
tak malé věci, že jsem to považovala za grafický bug.
Jinak aspoň plníme další cíl vizualizace -- vizualizace jako cesta k
hledání chyb v datech ))

**Comment by kikinna** [comment]
Přemýšlím nad grafikou na osobu. 
Co tam chcete za hodnoty? (Všechny v tunách CO2eq a s/bez procent?) A chcete detailní pohled nebo jen ty hlavní sektory. Aktuálně: 

![image](https://user-images.githubusercontent.com/11555522/91044322-5f8d0300-e615-11ea-8db9-23c15e207cd8.png)

**Comment by jankrcal** [comment]
Co potřebuje Atlas nebo @SklenarOldrich do prezentace, to nemám rozmyšleno.

Já bych chtěl stejné grafy, jaké máme na webu, tedy spíš procenta než absolutní čísla a také verzi s detailním pohledem.

Ještě přidávám ke zvážení bod z diskuze z #601: "Domácnost a instituce" je trochu zavádějící zjednodušení, protože:
  1) jde o __spalování__ v domácnostech a institucích (typicky plynové / uhelné kotle, vaření plynem, atd.),
  2) v té kategorii je i "CRF1A4C - Fuel combustion in agriculture, forestry and fishing"
Co třeba pojmenovat to "Spalování v domácnostech, institucích, zemědělství". 

Je to neohrabanější, ale použitá zkratka je už pro mě příliš vzdálená realitě. Prosím @ondraspribyla o vyjádření.

**Comment by SklenarOldrich** [comment]
Za mě bych grafiku/přepočet na osobu tímto způsobem neřešil. 

U [mezinárodního srovnání](https://faktaoklimatu.cz/infografiky/emise-vybrane-staty) to smysl má, samostatně nikoli - informace o tom, jaké jsou emise z průmyslových procesů na osobu není příliš vypovídající. Současně  v přehledu chybí např. emise spojené s dovozem masa/mléka/spotřebního zboží, které v těchto statistikách nefigurují. Chci tím říct že pokud by se uvedená data měla vztáhnout na průměrnou spotřebu jednotlivce (k čemuž by taková grafika vyloženě vybízela) vznikl by tím poněkud zkreslený obraz...

**Comment by SklenarOldrich** [comment]
> Ještě přidávám ke zvážení bod z diskuze z #601: "Domácnost a instituce" je trochu zavádějící zjednodušení, protože:
> 
> 1. jde o **spalování** v domácnostech a institucích (typicky plynové / uhelné kotle, vaření plynem, atd.), 
> 2. v té kategorii je i "CRF1A4C - Fuel combustion in agriculture, forestry and fishing"
> 
> Co třeba pojmenovat to "Spalování v domácnostech, institucích, zemědělství". Je to neohrabanější, ale použitá zkratka je už pro mě příliš vzdálená realitě. Prosím @ondraspribyla o vyjádření.

**Pokud jde opravdu pouze o spalování, tak Tvůj návrh dává smysl.**

**Comment by SklenarOldrich** [comment]
> Za přepočítáváním emisí ze sektorů na obyvatele si stojím - i když vím, že je to zjednodušení. V dané cílovce si nikdo celkové emise nepředstaví, emise na osobu začínají byt představitelné. Asi dává smysl doplnit mezi komentáře o zjednodušeních tohle zjednodušení + důvod proč je to víceméně ok.

OK, v tom případě prosím do popisu doplnit poznámku o emisích, které nejsou zahrnuty v této statistice, tj emisích spojených se zahraničním obchodem. @ondraspribyla doplníš Ty, nebo to mám udělat já (jaký je v tom případě deadline?)

**Comment by kikinna** [comment]
Ahojte, posílám složku s exporty grafik. @ondraspribyla Prosím mrkni, jestli je vše, jak má být. 

https://www.dropbox.com/sh/poo7m35iu067opn/AACe9735y6tSIlF1DrbRFJdWa?dl=0

**Comment by ondraspribyla** [comment]
Našel jsem chybu (až po koukání za vizualizace - čimž se potvrzuje, že jedním z účelů vizualizací je hledání chyb)
"Jiná doprava" má být stejně malá a zanedbatelná, jako v grafu za rok 2016.

V datech za rok 2016 nejsou uvedeny light duty trucks, zatímco v datech za rok 2018 jsou uvedeny zvlášť, ale nebyly započítány. 

Opravu v datech jsem udělal (@jankrcal  zkontrolueš prosím korektnost?), grafy ale bude nutné opravit.

**Comment by kikinna** [comment]
Ok, akorát to už neopravím dnes.
Ondráši, dej mi prosím soft a hard deadline skrz atlas, ať si to
rozplánuji.

**Comment by kikinna** [comment]
Upravené grafiky tady: 
https://www.dropbox.com/sh/4fi7pkljx3wj73f/AACXpL_p3DvnjX7WyfIl_4Jwa?dl=0

**Comment by ondraspribyla** [comment]
U datasetu za rok 2018 se stále zobrazuje náhled za rok 2016. Je potřeba doplnit/změnit tento obrázek.

**Comment by jankrcal** [comment]
Tady vše hotovo.
