### ISSUE TITLE
Rozcestník pro energetické scénáře ČR

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#636]
Zárodek zde:  
https://docs.google.com/spreadsheets/d/1r_XON_uOnnM4FzdzeCpWwv-qjSgJqIooBtyHuXCWs1A/edit?usp=sharing

Idea: 
pokud někdo hledá data o tom, jak moc může ČR snížit emise změnou energetického mixu, nic moc nenajde... existuje řada zpracovaných studií, které je ale těžké najít. Záměrem je udělat přehledovou "rozcestníkovou" stránku, kde by energetické scénáře byly v tabulce s linky a případně by k nim byly další komentáře a údaje.

**Comment by mukrop** [comment]
Hotovo?
