### ISSUE TITLE
vizualizace energetických scénářů

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#660]
Rozpracoval Olda - viz přílohy
[Cesta k dekarbonizaci české energetiky 02.docx](https://github.com/faktaoklimatu/web/files/5325988/Cesta.k.dekarbonizaci.ceske.energetiky.02.docx)
[Energetické scénáře ČR.xlsx](https://github.com/faktaoklimatu/web/files/5325989/Energeticke.scenare.CR.xlsx)

**Comment by mukrop** [comment]
Tiez hotovo?
