### ISSUE TITLE
Analytika: Přidat event na proklikávání tabů na titulce

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#664]
Aby sme vedeli, kolko navstevnikov klika na "pre ucitelov" a "pre novinarov".

**Comment by mgrabovsky** [comment]
Když už jsme u toho, hodilo by se sledovat i prokliky na datasety z infografik, prokliky na sdílecí modál a prokliky na související materiály (to hlavně). (Pokud už to někde je, nenašel jsem to.)

**Comment by mukrop** [comment]
To vsetko by tam uz malo byt. V GA to vidis ako actions. (Je to tam dohodene cez Google Tag Manager, takze v kode to nevidis.)

**Comment by mukrop** [comment]
Done.
