### ISSUE TITLE
Zrušit email scientistsforfuture

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#669]
Upravit stranku https://faktaoklimatu.cz/studie/2019_science-vyjadreni-vedcu
* [x] Opravit zobbrazovanie boxov.
* [x] Preformulovat text, aby sa info k podpisom posielalo na adresu info@faktaoklimatu.cz.
* [x] Zrusit adresu scientistsforfuure@faktaoklimatu (@mukrop).

**Comment by mukrop** [comment]
Sekciu s moznostou pridat podpis som stiahol celu.

**Comment by ondraspribyla** [comment]
ok.
