### ISSUE TITLE
Odkaz na stránku "O nás" nefunguje

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web#684]
Třeba na této stránce https://faktaoklimatu.cz/jak-pouzivat (nevím jestli ještě někde jinde) je odkaz na stránku "O nás" která vede na https://faktaoklimatu.cz/#creators , která však otevře jen homepage Fakta o klimatu.

**Comment by setcz** [comment]
Jako úplnej hacker jsem to zkusil opravit v tady tom pull requestu - jen nevím, jak udělat, aby se to doopravdy opravilo, to asi musí schválit ještě nějakej větší hacker - https://github.com/faktaoklimatu/web/pull/685

**Comment by mukrop** [comment]
Este vacsi hacker uz to schvalil :-P. Teraz treba pockat, kym zbehne CI (test build), potom to mergnem do produkcnej verzie. (CI je v poslednej dobe pomale, takze to moze byt aj niekolko hodin.)

Akurat ked som videl tu notifikaciu na otvorene issue, tak som si povedal, ze to je dost mala vec, ze by si to mohol rovno skusit aj opravit, tak ma potesilo, ze sa tak aj stalo :-).
