### ISSUE TITLE
Možnost odkazovat na rozbalovací sekce a sekce akordeonu

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web#712]
Navrhuju:

1. nějak zlepšit čitelnost a atraktivnost rozbalovacích sekcí, viz https://faktaoklimatu.slack.com/archives/C01C6UQBS2X/p1606812157002100 - aktuálně jsem navrhl preview následného textu s fade-outem (netestováno, jen návrh)
2. aby byla každá sekce bookmark, tj. aby se na to dalo odkazovat
u nadpisů to máme: ![image](https://user-images.githubusercontent.com/5269350/101898973-54061d80-3bad-11eb-9216-b4cbc284561d.png) - hodí se nejen pro newslettery, ale taky twitter, a prostě odkazování na konkrétní věci - teď u [Atlasu](https://faktaoklimatu.cz/atlas) např. bych rád odkázal na "metodiku", ale nemůžu

**Comment by mukrop** [comment]
Cau. Dik za tip, uz sme pridavali automaticke otvaranie ked sa linkuje na nieco v zabalenej sekcii, ale toto je tiez dobra poznamka. Urcita suhlasim. Mrkne sa na to @mgrabovsky?

Upravil som nazov, aby bol vystiznejsi. Mateja som zrusil z assignees, prosim priradzuj ostatnych len ak o tom vedia a dohodli ste sa. Priradeny = vie o tom, zobral si to na starost, urobi to (inak priradenost straca velku cast vyznamu a robi trochu chaos). Zmienit niekoho v issue, ze by si to mohli chciet vziat je samozrejme naopak vhodne! :-)

**Comment by mgrabovsky** [comment]
Druhý bod řeším v #713.

Prvním bodem si nejsem zcela jistý, ale můžeme ho nechat jako myšlenku do zálohy. Případně ho zkusím implementovat v aktuálně probíhajícím redesignu stránek infografik.
