### ISSUE TITLE
Bug: horní lišta na Apple

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web#715]
Na applovském tabletu horní lišta zajíždí velmi rychle, takže je nepoužitelná pro navigaci a stránky se stávají obtížně browsovatelné

**Comment by repli2dev** [comment]
Ověřeno, i na iPhone

**Comment by mukrop** [comment]
Nemam Apple, nemozem odskusat. Mozem poprosit detailnejsi popis problemu,
pripadne navrh riesenia?

Ona pri scrollovani dole zachadza pomerne rychlo, ale zase sa objavuje pri
scrollovani hore (standardne spravanie na weboch, tj. zamer).

Takze asi prosim o popis rozdielu spravania Apple/non-Apple.

**Comment by repli2dev** [comment]
Pri ipadu na landscape v pruhu menu nic neni, aby se neco ukazalo musim pretahnout stranku jeste vic dolu a dokud budu drzet menu uvidim.
![757C413D-4210-4A09-A7F8-21265D702257](https://user-images.githubusercontent.com/475549/103402102-ed40a800-4b4b-11eb-9105-4d20e04a73ba.jpeg)

**Comment by repli2dev** [comment]
Důvodem je, že podmínka

```
if (prevScrollpos > currentScrollPos) {
```

skončí při úplném naskrolování navrch jako `false`, protože `prevScrollpos` je `0`, stejně jako `currentScrollPos`.

**Comment by mukrop** [comment]
Aha, zaujimave. A takto je to hned po nacitani, alebo az po prvom
odscrollovani?
Na Androide sa k tomuto stavu nedostanes, lebo aj sebemensie scrollovanie
smerom hore vzdy zobrazi menu. To sa na Apple nedeje nikde?

**Comment by repli2dev** [comment]
Je to po prvním scrollu a jen když je stránka úplně nahoře.

**Comment by mukrop** [comment]
Na faktaoklimatu.cz je nasadena nova verzia, ktora to mozno uz opravuje. Mozte to prosim vyskusat @ondraspribyla alebo @repli2dev ?

**Comment by repli2dev** [comment]
Za mě retest v desktopovém i mobilním Safari OK

**Comment by mukrop** [comment]
OK, tak to beriem za vyriesene.
