### ISSUE TITLE
Chybný export do SVG

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web#727]
Infografika [Vývoj emisí v ČR v letech 1990–2018](https://faktaoklimatu.cz/infografiky/emise-cr-vyvoj) ma v SVG len vlozenu bitmapu namiesto vektorovych dat. Odskusal som nahodne niekolko dalsich grafik a vsetky ostatny vyzeraju v poriadku.
Je to tak na webe (deploy cache) aj pri lokalnom zostaveni z cisteho projektu. Zdrojove PDF ale vyzera v poriadku.

@katkolouchova alebo @kikinna, mozte mi prosim overit, ze to jedno PDF nie je exportovane nejako inak?

**Comment by katkolouchova** [comment]
@mukrop Martine, tento export jsem určitě dělala já, ale bohužel si nevzpomínám, jestli jsem ho udělala v něčem jinak. Je možné, že ano, ale jistá si nejsem :/
Každopádně by to snad mohl opravit ten nový PR na aktualizaci grafik, který dnes dofinalizuju?

**Comment by mukrop** [comment]
Mohol, nechame to teda na kontrolu po prijati toho velkeho updatu.

>
