### ISSUE TITLE
U většiny grafik se nevygenerovala nová verze

### ISSUE THREAD

**Issue by katkolouchova** [faktaoklimatu/web#728]
@mukrop Martine, všimla jsem si, že po mergi nedošlo k aktualizaci grafik z prvního commitu v PR #725. Např. Body zlomu, které byly součástí pozdějšího commitu, jsou v pořádku, ale např. [emise-cr-detail](https://faktaoklimatu.cz/infografiky/emise-cr-detail) nikoliv (a všechny ostatní grafiky z toho commitu).

**Comment by mukrop** [comment]
Vyriesene. Ak by si narazila este na nejaky problem, tak sa ozvi, alebo ten issue znova otvor.

**Comment by katkolouchova** [comment]
Bezva, díky :)
